### ISSUE TITLE
"All votes are in" is closing the topic after email invited participants have voted

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1000]
**What is the user story?**

User selected "All votes are in" when created a voting. He shared voting via email invitation with few people and through the link with wider audience. Our system closed voting after he and few other people who were invited via email link had voted and those who entered via link, could not vote any longer. 

This was very confusing, because admin user didn´t know what he did wrong. He discovered then that he can change the voting deadline and he did it. But somehow our system closed the voting earlier again (I guessed that someone or himself voted over and our system counted again in all participants who were invited via email link and closed the voting). 

**Which feature needs to be updated and how?**

I don´t have very good idea how to solve it. Maybe we´ll write better explanatory text to the place where User can choose to opt in the "All votes are in"? Because this situation occurred for the reason that User couln´t understand what this option does...  

**Additional information.**
Would nee your help in brainstorming possible solutions @ilmartyrk @loorm

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/94
