### ISSUE TITLE
Upgrade AngularJS to Angular

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#1005]
Angular JS LTS has officially ended as of January 2022. This means that there will be no further security fixes etc. As we are also planning to update our FE design I believe the most efficient way would be to migrate from Angular JS to Angular. I have done research and testing on it and found a really good step by step course on how to migrate from Angular JS to Angular. 

https://www.youtube.com/watch?v=qeQljCLpR04&list=PL-TLnxxt_AVE9dec6IU-0DSx6Oy5hsTCu&index=1&ab_channel=jawache

**Comment by anettlinno** [comment]
Triage 66. Decided to update Angular during the summer (July?) when the workload is smaller. Estimated updated time 2 weeks (transition version). Sending it To Do.

**Comment by ilmartyrk** [comment]
- [x] Update Angular JS version and packages
- [x] Fix code where necessary
- [x] Update directives to components
- [x] Fix factories and services
- [x] Update controllers to components

**Comment by ilmartyrk** [comment]
Issues related to angular https://github.com/citizenos/citizenos-fe/issues/163, https://github.com/citizenos/citizenos-fe/issues/343, https://github.com/citizenos/citizenos-fe/issues/593

**Comment by ilmartyrk** [comment]
Done and in live, renamed citizenos-fe to [citizenos-fe-old](https://github.com/citizenos/citizenos-fe-old) and will soon archive the project after updating readme and confirming crowdin setup finalizations
