### ISSUE TITLE
Topic mentions feature issues

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#1006]
Topic mentions feature has been fire and forget solutions. It currently loads 20 items from Twitter API and that is it. There is also a bug that for each item a default icon is used from initial html. 
- [x] Replace the default icon
- [ ] see if there is a way to add load more button or use different external API-s for more mentions from other platforms than Twitter

**Comment by anettlinno** [comment]
Triage 66. Fixing the icon issue.  

Sending this issue to investigation, to figure out what is new in Facebook and Insta regarding pulling social mentions to our platform. Some places have Twitter mentions in beautiful "box" with pictures and headers etc. 
Investigation time 1 hour. Sending it to development.

**Comment by ilmartyrk** [comment]
As we use twitter we could use their public embed API that has no rate limit, but this is meant to display certain user profiles. Still it could make sense for some organizations etc. to display their own feed. https://developer.twitter.com/en/docs/twitter-for-websites/timelines/guides/oembed-api

**Comment by anettlinno** [comment]
One of the main reasons for using social mentions by our Users is that they want to bring all the discussions from different social media channels into one place. That would be the main value of this feature. Currently it´s more like "nice to have" feature :) 

Re: `but this is meant to display certain user profiles`
Is this in any way incompatible with our users data storage principles @kativellak?

**Comment by ilmartyrk** [comment]
fixed the default icon issue as  it was simple fix

**Comment by BeccaMelhuish** [comment]
Just adding this finding from @ssin1901 re the loading of the first 20 hashtag results FYI: 

![image](https://user-images.githubusercontent.com/61320526/175936240-126176d6-0019-454c-98a8-02979f621852.png)

**Comment by ssin1901** [comment]
For more context, I recreated this issue with the hashtag DeliberativeDemocracy
<img width="1162" alt="Screenshot 2022-06-27 at 16 38 27" src="https://user-images.githubusercontent.com/72747107/175955534-1d4ef449-8c41-4e00-9cfc-5d9fe790669b.png">

It is not very clear how hashtags are pulled (up till which date)

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/74
