### ISSUE TITLE
Activity feed: alignment issue

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#1007]
**What is the problem?**
When the event data exceeds 3 rows, alignment of the 4+ rows slips to the left:

<img width="775" alt="Screenshot 2022-05-27 at 22 49 06" src="https://user-images.githubusercontent.com/34126353/170780609-a35091eb-2b22-4733-8ae2-3738bda90d38.png">

<img width="766" alt="Screenshot 2022-05-27 at 22 49 43" src="https://user-images.githubusercontent.com/34126353/170780629-ff3784e7-6281-4a2e-a9c3-b2a8813184d7.png">

**Why is this a problem?**
Looks buggy and unprofessional.

**Possible solution.**
Align all rows to the same level - preferably to the right from the avatar.

**Comment by anettlinno** [comment]
Triage #67. Quick fix. Estimated dev. time 10 minutes. Sending to development.

**Comment by anettlinno** [comment]
Tested. Still looks the same for in the test environment but in product all looks beautiful @ilmartyrk 

Test environment: 
<img width="451" alt="Test" src="https://user-images.githubusercontent.com/45175679/174558273-d57f9cf0-238a-4c69-b256-3133d2c66812.png">

Platform: 
<img width="448" alt="Test2" src="https://user-images.githubusercontent.com/45175679/174558477-52540595-30e9-458d-81b5-c4bbda88f514.png">
