### ISSUE TITLE
Activity feed: event is missing a topic name

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#1008]
**What is the problem?**
We have an AF message about user leaving a reaction to an argument, but nowhere in sight is the name of the topic, where the argument itself resides.

<img width="776" alt="Screenshot 2022-05-27 at 22 54 49" src="https://user-images.githubusercontent.com/34126353/170781389-a3dbd509-4c36-4d46-a67e-2d399b24ac4f.png">

**Why is this a problem?**
The message is useless without a topic name, as it doesn't tell the user necessary information about what this notification is about.

**Possible solution.**
Please add topic name to the notification text.

**Comment by anettlinno** [comment]
Second topic name bug:

<img width="446" alt="Activity feed" src="https://user-images.githubusercontent.com/45175679/171352169-03988228-91fd-45fd-a398-96c1ed51146b.png">

**Comment by anettlinno** [comment]
Triage 67. Needs some changes in original text and @oksks help is needed with copy. Ilmar will check if topic´s name is missing from any other place. 

Fast fix, est. dev. time 10 minutes. Sending it to development.

**Comment by ilmartyrk** [comment]
@oksks what would be the suitable text? We have 12 strings that probably need this update. Do these look OK?
```
 "ACTIVITY_USER_CREATE_COMMENTVOTE_COMMENT_UP": "User <em>{{userName}}</em> has left a reaction <em>{{reaction}}</em> on an argument in topic: <em>{{topicTitle}}</em> ",
    "ACTIVITY_USER_CREATE_COMMENTVOTE_COMMENT_UP_ACTIVITYGROUP": "User <em>{{userName}}</em> and <em>{{groupCount}}</em> others have left a reaction <em>{{reaction}}</em> on an argument in topic: <em>{{topicTitle}}</em>",
    "ACTIVITY_USER_CREATE_COMMENTVOTE_COMMENT_UP_USERACTIVITYGROUP": "User <em>{{userName}}</em> has left <em>{{groupCount}}</em> reactions <em>{{reaction}}</em> on an argument in topic: <em>{{topicTitle}}</em>"
```

**Comment by oksks** [comment]
@ilmartyrk these look fine! :) logical and translatable.
