### ISSUE TITLE
Cannot delegate vote

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1012]
**What is the problem?**
When delegating my vote to another User, I need to choose an option as well, because the system doesn´t allow me to submit my vote without doing that. "Submit your vote" button is inactive.
<img width="508" alt="Sumbit vote" src="https://user-images.githubusercontent.com/45175679/171361945-2378fc03-a052-47ae-8eb0-c6e22b7acd38.png"> 

**Why is this a problem?**
If I have to choose an option, then I can vote for myself and I don´t need to delegate it. 

**Possible solution.**
Please let the system to press the "Submit your vote" button after I have chosen to whom I want to delegate my vote.

**Comment by anettlinno** [comment]
Triage 67. User´s main confusion came when two options (option "Yes" and option "Delegate your vote") were active at the same time. To make it clearer, we decided to do following:

- Remove the button "Submit your vote" when vote is delegated. After vote is delegated, User should receive message "Your vote is successfully delegated to" (maybe change the text below?)
- Let´s not give a User an opportunity to use vote delegation AND vote casting options at the same time. 

<img width="521" alt="Vote delegation" src="https://user-images.githubusercontent.com/45175679/173558529-c7224095-eaaa-4bc9-96c0-74a03d24e46e.png">
 
After User has delegated vote, our system should not allow to click on voting options and voting options are left gray. IF User is trying to click on the voting options, pop-up window with message "You need to revoke your delegation before submitting your vote" appears. @oksks we need your copy-magic here :) 

- As discussed with Ilmar, this message could appear in the box above of the voting options: 
<img width="521" alt="Vote is registered" src="https://user-images.githubusercontent.com/45175679/173559215-aac2047b-a2cc-4c63-93ed-9e7221cd2423.png">

Estimated dev. time 2 hours. 
QA and UX testing in test environment. 
Sending to development.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/75
