### ISSUE TITLE
Replace capital letters with lower case

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1017]
**What is the user story?**
In some places, we use capital letters on our platform that can create shouty/aggressive vibe and are not commonly used in plain text.

![image (14)](https://user-images.githubusercontent.com/45175679/172617599-29bd4fb0-129b-422a-a490-e930c95804f6.png)

**Which feature needs to be updated and how?**
Replace all capital letter which are in the plain text with lower case.

**Additional information.**
N/A

**Comment by anettlinno** [comment]
Triage 47. Quick fix, estimated dev. time 30 min. Sending to development.

**Comment by anettlinno** [comment]
Tested. Text is still in capital letters @ilmartyrk  :) 
<img width="353" alt="Capital" src="https://user-images.githubusercontent.com/45175679/174559013-25fc033e-f6c1-4273-9b34-e7f70788ed29.png">

**Comment by ilmartyrk** [comment]
@anettlinno, fixed in translations, soon should be updated by @oksks and then it is fixed everywhere

**Comment by anettlinno** [comment]
Oh, yes, of course! Thanks @ilmartyrk :))

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @anettlinno @oksks By the way I found a few more places still with capital letters

I'm less sure that the buttons and headings should be lower case, but the explanatory sentences definitely in all cases should be :) 

![image](https://user-images.githubusercontent.com/61320526/185418430-9b99a0f8-b8ba-45d9-b2ad-a1235c12f7ec.png)

![image](https://user-images.githubusercontent.com/61320526/185418504-56a89139-3b7f-469f-a403-021121753344.png)

![image](https://user-images.githubusercontent.com/61320526/185418675-f4ccaf6f-6d5c-4b21-baa3-ec7cbda39f1d.png)

**Comment by BeccaMelhuish** [comment]
P.S @ilmartyrk @anettlinno I do feel like in the case where there is a whole sentence like this in the button, it's a bit too shouty/panicky. Like something might explode if you chose the wrong button - feels a bit stressful... So I'd suggest making buttons lower case too, personally!

(The heavy use of red and triangle exclamation mark doesn't help with the vibe either - it's very much yelling "Danger! Danger!" But that's probably a separate conversation..) 

![image](https://user-images.githubusercontent.com/61320526/185610068-128a2e1a-0d23-4145-aafc-3e589485f8dc.png)

**Comment by anettlinno** [comment]
Agree with @BeccaMelhuish. Capital letters are rather intense and IMO we could change them all (both explanatory texts and button texts) to lower case letters. 

I also noticed that the font size is quite small and it´s hard to read the text. Would make the text bigger. AND as you can see from the picture, then some button texts are in lower case :) We should keep the consistency here :) 

<img width="953" alt="Letters" src="https://user-images.githubusercontent.com/45175679/190621941-d27bda97-2855-484b-baef-29c55614251c.png">

**Comment by anettlinno** [comment]
Triage 72. @oksks these changes needs to be made in translation files. Let´s keep all text in lower case letters (with first letter being capital letter).
Sending it To do.

**Comment by oksks** [comment]
Am a bit surprised changing the English texts has been assigned to me :D But I've scanned through the whole UI code and changed all (applicable) occurrences of uppercase to lowercase. I'll of course take care of translations, too. :)

Lmk if anything else is needed.
