### ISSUE TITLE
UX issues: Manage Participants / Invite users

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1018]
As discussed recently with @anettlinno, I noticed a UX problem with the Manage Participants feature, which is that you can't invite participants from within the "Manage Participants" window, which would (I believe, and fairly certainly) be what most users would expect. (Myself, even once I'd noticed that it wasn't possible, I kept going back to "Manage Participants" to invite people as it seems the most intuitive). 

So my suggestion is that the "Invite users" function be incorporated within "Manage participants". (No need for a separate menu link either). And (as one user suggested in our HC user tests) the share topic function could potentially also be included within the same window - so everything related to managing participants is all in one place. Though this latter one I'm less sure about from an intuitive UX perspective. 

![image](https://user-images.githubusercontent.com/61320526/172847422-ad11d4e4-c51a-4adc-8832-f944a0ccaae5.png)
 
There's also some differences in wording here - we "invite **users**" but "manage **participants**" - should be the same for both I think?

**Comment by anettlinno** [comment]
Manage participants/ invite users is incorporated in the UX/UI redesign but there are some UX flaws in the new version that came out from user tests and needs to be fixed. After we have working solution, we could  already change it in our current version. WDT @ilmartyrk ? :)

<img width="487" alt="Share Invite" src="https://user-images.githubusercontent.com/45175679/177497754-b13d8d0c-5cae-482a-aefa-2478328ee55f.png">

**Comment by anettlinno** [comment]
Triage 69. It requires AngularJS updates. We could develop the code part now, but it would be too expensive to have the designs and updates on our current version as it requires Kevin´s input and Ilmar´s development time. Redesign version also need some updates (came out from user tests).

Sending it to In prep and once we have working version for the redesign then we can start developing the code part.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/42
