### ISSUE TITLE
BUG: Localisation - Report argument modal - use term "arguments" instead of "comments"

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#102]
**Overview**

Citizen OS has "arguments", not "comments", thus proper term should be used system wide.

![image](https://user-images.githubusercontent.com/7405383/47802219-796e9f00-dd38-11e8-8e5a-2249e695927a.png)

**TODO**

- [x] Fix source strings to contain the term "argument" instead of "comment"

**Comment by ilmartyrk** [comment]
@tiblu was this intended to be simply translations/source fix or should we go deep and update Model names, API endpoints etc. ? I ask this because we cannot completely update _comments_ -> _arguments_ as some keys are auto generated by endpoints or Model names.

**Comment by tiblu** [comment]
Lets do the localisation fix, I think the model one is not worth it at this
point.
