### ISSUE TITLE
User should be notified if an ID card reader is not plugged in when they click on “Authenticate with ID card” 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-old#1032]
**What is the user story?**

Users who click on Log in with ID-Card/Mobiil-ID and click on the Authenticate with ID-card button should be notified that the e-ID card reader needs to be plugged into the device, in order for the authentication to occur. 

![Citizen OS - an e-decisionmaking platform for communities 6](https://user-images.githubusercontent.com/72747107/174802799-f269c507-f532-4fb9-be69-311cab0b4765.png)

+ add screenshot / screencast when applicable

**Which feature needs to be updated and how?**

If a user who has no e-ID card reader plugged in user clicks on the “Authenticate with e-ID card button” they should receive such as “Failed to read ID-card certificate. Please ensure that an ID-card reader is connected to the device.”

**Additional information.**
We should encourage users either via the platform or the Help Centre to read up on how e-ID cards are used in Estonia. https://www.id.ee/en/rubriik/card-reader/ 

Otherwise, it may become confusing for users.

**Comment by anettlinno** [comment]
Important update, let´s add an error message after clicking "Authenticate with ID-card" if User hasn´t connected ID card with ID-reader
@ilmartyrk does RIA have the automated failure messages that we could use? 
@BeccaMelhuish I´m thinking that maybe we should also link "[Failed log in and sign in](https://www.id.ee/en/article/failed-to-log-in-or-sign-in-e-services-with-an-id-card/)" ID helpline page on the Help Center? WDT?

**Comment by anettlinno** [comment]
Triage 69. Needs some investigation. Takes approximately 30 minutes.

**Comment by BeccaMelhuish** [comment]
Yes great idea @anettlinno, will add this link "[Failed log in and sign in](https://www.id.ee/en/article/failed-to-log-in-or-sign-in-e-services-with-an-id-card/)" :)

**Comment by ilmartyrk** [comment]
After some research found that we could possibly use `hwcrypto.getCertificate()` method to detect if Id card reader is installed or card is inserted correctly. If it fails then we can display users an error message that we couldn't read their ID-Card

**Comment by anettlinno** [comment]
> After some research found that we could possibly use `hwcrypto.getCertificate()` method to detect if Id card reader is installed or card is inserted correctly. If it fails then we can display users an error message that we couldn't read their ID-Card

Sound good, @ilmartyrk! What would be your time estimation for that? :)

**Comment by ilmartyrk** [comment]
I estimate 30 minutes, I actually found that we already have error message for that and it has been fully translated
