### ISSUE TITLE
Action confirmation and error messages are difficult to notice

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1048]
**What is the user story?**
Confirmation and error messages appear in narrow band in the top corner of the page and they are difficult to notice, because our platform is colorful, these messages often merge into the page. Users often miss those and they don´t see the confirmation or error messages they need to see.
![Messages](https://user-images.githubusercontent.com/45175679/176703879-5392ab40-d273-4c6c-9a9c-f61aa1715b2c.png)

**Which feature needs to be updated and how?**
We should display action confirmation messages and error messages in bigger font and make it more visible for Users. As this is UX issue then we would need @kevincrepin´s help here :) 

**Additional information.**
N/A

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/63
