### ISSUE TITLE
Register account information does not fit into the box in mobile view

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1049]
**What is the problem?**
In mobile view "Register account" information box is too small for the text and it looks broken. 

![mobile view](https://user-images.githubusercontent.com/45175679/176706951-219f9051-5502-4bf0-a80b-12a8ec118ec7.jpg)

**Why is this a problem?**
User cannot read the whole text. 
I´m also thinking that maybe we should change the text. Current text is: "_Register a free account now to get access to Citizen OS: the platform for asynchronous meetings & citizen participation_". For my taste "asynchronous meetings" is one specific user case and "citizen participation" again is too vague. My proposals are: 

1. EITHER remove the "_the platform for asynchronous meetings & citizen participation_" part at all and leave only "_Register a free account now to get access to Citizen OS_"
2. OR leave only "_Register a free account now to get access to Citizen OS: the platform for citizen participation_" (but then again some might use it for their organization or team or friends group... 

@oksks your thoughts are welcome here :)

**Possible solution.**
Let´s decide, what text we leave there and then fix the box size.

**Comment by oksks** [comment]
@anettlinno I agree with the shortening of the text! :) But I'd change the "free account" part, as it doesn't really explain that the usage of the platform is free. Maybe smth like this would work:
_"Create an account to get free unlimited access to Citizen OS platform"_

**Comment by anettlinno** [comment]
> @anettlinno I agree with the shortening of the text! :) But I'd change the "free account" part, as it doesn't really explain that the usage of the platform is free. Maybe smth like this would work: _"Create an account to get free unlimited access to Citizen OS platform"_

Sounds good to me :)

**Comment by anettlinno** [comment]
Triage 70. Quick fix, est. dev. time 10 min. Sending to development.
