### ISSUE TITLE
FE: Vote creation - no error messages displayed when custom vote option does not pass validation

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#105]
**Overview**

When creating a new custom vote for a Topic and entering invalid data (>100 chars etc) into vote option fields there are no error messages.

**NOTES:**

* Probably requires API to return an error per field. If so, please create a API task also.

**TODO:**

- [x] Show field error message for the invalid option using the Citizen OS field error style
![image](https://user-images.githubusercontent.com/7405383/47808110-577c1900-dd46-11e8-9bf8-42b2283757f6.png)
- [x] Localisation of the error

![image](https://user-images.githubusercontent.com/7405383/47807881-cf960f00-dd45-11e8-950e-0031b8f42592.png)

**Comment by tiblu** [comment]
**DONE**

* API: limit changed from 100 to 200.
* FE: Generic error messages to fields until API starts returning more specific ones to pinpoint violating field.

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
