### ISSUE TITLE
Community moderation feature

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1053]
As discussed with @ilmartyrk [on Slack](https://citizen-os.slack.com/archives/C02E7TF8JUF/p1657735514045179), the community moderation feature we announced in [this article](https://citizenos.com/news/a-new-approach-for-maximum-transparency) doesn't actually exist.. (Am a bit baffled how this article happened, but there you go!) 

So am just creating an issue to bring it back onto the agenda, if it's still something we want to explore :) 

@anettlinno @ssin1901 tagging you for your info.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/93
