### ISSUE TITLE
Log in issues

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1054]
Maybe this is already on the list of login problems to solve, but in case not there's quite a problem here: 

- When I am logged in to my COS account that is linked to my gmail email address, then click on an email invitation which has been sent to my citizen os email address, it shows this screen:

![image](https://user-images.githubusercontent.com/61320526/179193024-b356e1be-bf17-41f1-ad68-9fcd73c5d6c8.png)

- All very well, up to there, but then when I click "log in", this is what happens (the pop up disappears and I'm taken to logged out home screen view, with the cursor flashing in the "search" box): 

![image](https://user-images.githubusercontent.com/61320526/179193143-b0da129a-b368-4daf-962c-ccd595e9e339.png)

- So I click "log in" and log in with my COS email address:

![image](https://user-images.githubusercontent.com/61320526/179193359-22bee6c0-6ea3-47a9-9147-1509a1e49d03.png)

- And this is what happens, I get taken to the logged in home screen, not to the topic I was trying to join:

![image](https://user-images.githubusercontent.com/61320526/179193494-6f3cde67-69a7-4db3-a6c8-303aa24e66ca.png)

- So I have to go back to the invite email, and click the "join topic" button again. (Which not everyone would think to do..). Then it does actually take me into the topic. 

@ilmartyrk @anettlinno @ssin1901

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/92
