### ISSUE TITLE
User invitation modal window disappears if you click outside the modal box 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-old#1055]
**What is the problem?**
When a user receives an invite to a topic and clicks outside the modal box (despite the existence of a close button) the modal window disappears. Issue has been recreated in IPad Chrome and Mac OS Safari.

<img width="1342" alt="Modalerror" src="https://user-images.githubusercontent.com/72747107/179397994-0678ff7b-6127-4171-88bf-212d8c3e8080.png">

+ add screenshot / screencast whenever possible

**Why is this a problem?**
Describe, how this bug stops a user from performing a desired activity.
User has now lost the invitation, and has to locate the invitation from their email again.

**Possible solution.**
Modal window should neither close when the user clicks out of the modal area nor have an x button at all. The reason being that the user arrived to this point by clicking a link from their email. If they accidentally close the modal they will be totally lost.

**Comment by anettlinno** [comment]
Triage 70. Important issue. Quick fix. Est. dev. time 5 min. Sending to development.
