### ISSUE TITLE
Moderation notifications

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1059]
Not sure if this is a bug or it's just not set up to happen, but when I was testing the moderation features in order to write them up for the HC, I found that there is no notification once the admin has actually taken action to moderate (or not) the flagged content. 

There is a notification which the original author of the comment receives when someone has reported their comment, but I was expecting there would be some notifications when the admin has moderated it. I.e. telling the original author what they did about the post and why, and also telling the person who reported it the same thing.

Should this happen? Or if not, would it be worth making it happen? (In my opinion this would make a lot of sense). 

@ilmartyrk @anettlinno @ssin1901

**Comment by anettlinno** [comment]
Triage 71. We´ll take topic´s email text and adjust it according to the argument. After the reported argument has been moderated, our system will send out email to 1) other moderators 2) user, who reported the argument 3) user, who wrote the argument. 

Est. dev. time 30 minutes. Sending to development.

**Comment by ilmartyrk** [comment]
Replace "This argument has been deleted by user {{usersFullName}} (moderator)" -> with "This argument has been moderated by user {{usersFullName}} (moderator)"

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/78
