### ISSUE TITLE
Error when trying to report a comment 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1060]
I got this error message when trying to report a comment. I tried it a couple of times and got the same thing:

![image](https://user-images.githubusercontent.com/61320526/179928151-5f921ba4-6f37-48aa-9e77-5958bbae0627.png)

**Comment by BeccaMelhuish** [comment]
A bit more info: 

The test above was trying to report a comment left by my University email linked account, by my COS email linked account. 

I logged out and then tried again reporting a comment left by my Gmail linked account (the admin of this topic in case that's relevant) using my COS email linked account and it worked fine. 

I then logged out again and tried a repeat of the same above (uni email comment, reported by COS email) and it worked fine. 

I guess it could have just been internet issues (mine here is a little dodgy), though you'd expect a different kind of error message?

**Comment by anettlinno** [comment]
Could not replicate. Reporting an argument by another email account works fine for me. @ssin1901 maybe you want to test it too?

**Comment by anettlinno** [comment]
Triage 70. We use this error message for Error 500 (for server error) and crypto error (for ID-card) and probably this was Error 500 and appeared because of the internet issues or something else. @ssin1901 could not replicate it either.

Closing the issue.
