### ISSUE TITLE
Bug: Moderating while logged into the wrong account

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1061]
I found an odd bug when testing the moderation feature for the HC texts. The end result of the action is the same (as I'll explain below), but could cause user confusion nonetheless. (Though to be honest, I imagine it's pretty unlikely that this situation would arise in real life, I just discovered it because I was logging in and out of the same topic playing different "roles" within a discussion for the purposes of working out the texts..) 

Essentially the bug is that: if you follow the ’moderate this argument’ link in an email notification while you are logged into a different account to the one in which you are topic admin, it still takes you to the moderation pop up and allows you to moderate the comment while logged into the wrong account.

Here's the step by step:

- I only have admin rights for this topic in my Gmail linked COS account: 

![image](https://user-images.githubusercontent.com/61320526/180176841-6ee279eb-952d-4c14-bfff-1cbf878ad6cc.png)

- So the email notification is sent to my Gmail. And while I was still logged into COS with my university email linked COS account, I clicked on the "moderate this argument" link. 

![image](https://user-images.githubusercontent.com/61320526/180177144-761df630-201c-4bf8-8bc8-e8b7c477db0e.png)

- It opens the moderation window while still keeping me logged into my university email linked COS account:

![image](https://user-images.githubusercontent.com/61320526/180177591-daad291b-3c45-4a9d-947f-11ae4ca3ffae.png)

![image](https://user-images.githubusercontent.com/61320526/180177627-132b6961-d0b8-4606-9002-84e88c73d592.png)

- I am able to moderate the argument despite being logged into the wrong account (no error message appears and the comment gets deleted/hidden), but the moderation action still appears as though it was done by the correct account: 

![image](https://user-images.githubusercontent.com/61320526/180178059-b9644ff9-f46a-4fbd-bf4d-a5023711cb37.png)

@ilmartyrk @anettlinno @ssin1901

**Comment by anettlinno** [comment]
Triage 70. Moderators should login with the email address in which they receive the moderation email (same pop-us as login has).  

In public topic moderation we have a list with moderators who will receive the email for the topic moderation. This is easy as these moderators are in our database and system can recognize them easily. 

With private topics admin users receive topic moderation reports and they should be logged in for moderating. IF any admin user (who has received report email) has lost her admin permission (rights are being changed) should not have the right to moderate the report. 

We have the designs but would need copy from @oksks 

Est. dev. time 2 days. Sending to development.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/77
