### ISSUE TITLE
UX improvements for moderation feature

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1062]
When testing the moderation feature in order to write up the HC texts, I came across a number of UX issues, some much more serious than others, so I'll split them out as such.. 

**More serious issues:**

(1) **When a user has already deleted an argument, the moderation pop up still appears as if the argument is still there.** As both the original author and the moderator receive notifications at the same time, it is quite feasible that by the time the moderator comes to moderate the argument, the original author has already logged in and deleted it. I discovered that if they have, the window that appears when the moderator clicks "Moderate this argument" in their notification email looks as if the argument is still there. 

See the screenshot below, this is what appeared when I clicked on the window as moderator, after having deleted the argument (from my other account). The error message saying that the content has been deleted only appears after they have taken action to moderate it. 

I can imagine this could cause a great deal of frustration to users, as moderating offensive arguments can be quite stressful especially if it's a delicate subject with a fine line between freedom of speech and causing offense. I.e. the moderators thinks long and hard what is the right thing to do, calls a colleague to get a second opinion, calls the person who reported it too, then writes a carefully worded explanation of why they are deleting it, only to find that the argument had already been hidden anyway! :-/ 

![image](https://user-images.githubusercontent.com/61320526/180180888-b4bc4c2e-dc98-4635-bb28-b38cbaa8ffc3.png)

(2) Same as above, but when the original author has already edited the comment. In this case, the moderation window that appears shows the edited version of the argument, but doesn't indicate that the comment has been edited. So they are going to think that someone has reported the argument in its edited form, when in fact they reported it in its original form. Again they are only notified that the argument has been edited after having tried to moderate it. Which could cause a lot of confusion, frustration, misunderstandings etc.  

![image](https://user-images.githubusercontent.com/61320526/180181796-b50f693e-1d58-4b29-bd22-f64310fcc6d2.png)

![image](https://user-images.githubusercontent.com/61320526/180181917-745c5095-4597-451c-abbb-d77c1fbfc589.png)

(3) There doesn't seem to be any way for the moderator to (transparently) explain their reasons if they decide to not take action on a report. For example, someone reports an argument as racist. The moderator disagrees as they don't think it is racist, and therefore clicks "No" or closes the window. Currently (as far as I can tell) in this case there is no visible trace that the argument was ever reported, why it was reported, that the moderator chose not to moderate it, or why they did not. (Which seems very non-transparent to me, the moderator should have to justify their choice either way and this should be visible somewhere, in my opinion). 

**Medium serious issues:**

(1) The wording here doesn't really make sense in the context. As you're not changing your mind, just deciding not to moderate it. And it's also not clear what action they are taking, as "moderate" isn't very specific. So I'd suggest, "No, don't hide this", "Yes, do hide this". With the text above saying "Are you sure you want to hide this argument? You cannot undo this action."

![image](https://user-images.githubusercontent.com/61320526/180186970-67f76974-b61e-43de-acc6-f6a505590645.png)

(2) There is no "Other (please specify)" option, but there should be I think? 

![image](https://user-images.githubusercontent.com/61320526/180188170-0b766d56-3159-4b1c-a9d3-2c48b58669d7.png)

**Less serious issues:**

(1) There's some quite dodgy looking formatting here: 
![image](https://user-images.githubusercontent.com/61320526/180188514-47cb451c-63e1-4771-965b-fa852fbe38e9.png)

(2) Seems odd that you can report your own argument:

![image](https://user-images.githubusercontent.com/61320526/180188611-5855c126-fd0b-425e-9bdf-01eb6daf0e1e.png)

(3) This should say "Hide argument" or similar once it is open. (Standard practice - "View" then "hide") 

![image](https://user-images.githubusercontent.com/61320526/180188731-94c1aa6c-8386-442b-ae4b-65706586e0db.png)

(4) Wondering if "the community" is the right word here:

![image](https://user-images.githubusercontent.com/61320526/180188983-368ddc25-8983-4a9c-9216-b0f3dc8468e5.png)

@ilmartyrk @anettlinno @ssin1901

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/40
