### ISSUE TITLE
Filtering topics by "Most recent" 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1063]
I know I've suggested this before but wanted to try again now we have more of a UX focus :) (I'm sure this is something to be included in the redesign, but still worth making such improvements sooner in my opinion). 

For me as a user I would find it highly useful to be able to filter (or sort) my topics by those I have most recently been active in. I often struggle to find a topic if I can't remember the exact wording of the title, but usually they are ones that I have been invited to or active in recently. 

I would suggest either a filter (easier presumably as it already exists) or sort function for both "Most recently joined" and "Most recently active in" here: 
 
![image](https://user-images.githubusercontent.com/61320526/180190949-26e42e2d-ed49-4404-b853-bdef6a3ddee8.png)

And I'd also again suggest adding the standard filter icon next to the "Show all my topics". (Ideally actually changing that to "Filter my topics" (and moving the default selected show all my topics down) as it would be a whole lot clearer what that little box does then :)  

@ilmartyrk @anettlinno @ssin1901

**Comment by anettlinno** [comment]
Triage 69. 

1. We agreed that changing the drop down text to "filter my topics" and adding filtering icon would make it better in UX wise. We should have the icon design (Ilmar will check).

2. Defining what is "Most recently active"? It is User´s recent activity (any activity), also the interactions where user only reads or opens the topic, as well as joining, editing, voting it etc.
Showing **all** recent activities under the topic list is data heavy for our system and that´s why we should limit it to 10 and phrase it as "10 most recently active topics". 
If User wants to see the joined topics, one can see it in Activity feed or under the 10 recently activity topic list (if joined recently). We should try to keep the filters list short and to the point :)  @BeccaMelhuish if you have any strong reason why you want to see most recently joined topics, then please let know (Y).

Approx. dev time 14 hours. Sending to development.

**Comment by BeccaMelhuish** [comment]
@anettlinno just wondering what happened with this one - did it get decided against in the end? Would be really helpful to users I think :)

**Comment by anettlinno** [comment]
> @anettlinno just wondering what happened with this one - did it get decided against in the end? Would be really helpful to users I think :)

It´s in pipeline, @BeccaMelhuish and waiting for the development :)

**Comment by BeccaMelhuish** [comment]
@anettlinno Ah OK great, thank you!

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/76
