### ISSUE TITLE
Clarifying who is speaking in discussions (& highlighting replies)

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1064]
Just wanted to move this conversation below from the [COS topic](https://test.app.citizenos.com/en/topics/b40650d6-9936-4168-bd10-aa83d235edf9?argumentsPage=1) (not sure if that link works for others?) onto Github so that it could potentially be resolved. I always get very confused about who is speaking as I automatically assume it is the large blue name, not the tiny grey one. And it seems @oksks also finds this. I feel like as discussions is one of the main features of the platform it would be a good thing to try and fix asap (i.e. not to wait for the redesign. There are some other discussion related points in the screenshot too, but I feel like this one highlighted is really an important one.. 

![image](https://user-images.githubusercontent.com/61320526/180193490-e74984ed-4170-4d87-9bad-06947e1fbc14.png)

I'll also just add again that I find the replies get really lost in discussions as they are so tiny and hidden. I know this is again something for the redesign, but I feel like it should be quite easy to make a "quick fix" for now - i.e. make the replies bigger and bolder, perhaps in the COS blue (same as buttons)? This would very quickly make a big difference I feel. 

Made a very quick mockup of these here so you can see what I mean: 

![image](https://user-images.githubusercontent.com/61320526/180197301-c1b0872a-26cb-4b1e-b720-eef572fcfba7.png)

@ilmartyrk @anettlinno @ssin1901

**Comment by oksks** [comment]
I support wholehandedly - it always takes me quite a moment to understand who's replied to whom, which is annoying.

**Comment by anettlinno** [comment]
I totally agree that it´s difficult to understand who is replying to whom. 

In our new, redesign version it looks like that (which is quite good, I think, as replies are different color but it is not clear how the UX is when the answers go deeper than two levels): 
<img width="431" alt="Replies" src="https://user-images.githubusercontent.com/45175679/181481454-ed1ecfdb-09cb-42d3-892a-bee6f285c8fe.png">

FB has solved this problem with lines and alignment, which is also easy to follow (especially if replies goes deeper than 2 levels). 

![FB](https://user-images.githubusercontent.com/45175679/181490477-ce670359-dde0-47fc-bc64-36b3aa588423.jpg)

So, we could improve these with changing replies color and/or alignment and/or lines. How to best do it in our current platform with minimum effort is a question :) 
@BeccaMelhuish @ilmartyrk @ssin1901?

I vote for the highlighted "Show replies" -- makes it more visible :)

**Comment by ilmartyrk** [comment]
I would like to add that when you click on the  @username reference in replies it highlights the argument or reply that this reply is meant to

**Comment by BeccaMelhuish** [comment]
@anettlinno one thought for a "quick fix" re making it more obvious who is speaking, could be to make the name of the person speaking (highlighted yellow) bolder and perhaps also a little bigger, and then to start the comment on the same line as the @username (like Facebook does) so it is like the continuation of the sentence, not a heading for it. I.e. "Anett, I think you are right here" or "Sara, I disagree" etc. 

![image](https://user-images.githubusercontent.com/61320526/181769872-3eeae45a-f19b-4779-88e7-5b876ea1df3d.png)

It would be great to also use alignment to show which comments are being replied to (again like Facebook does) but I guess this is more of a big change, less of a quick fix..

**Comment by anettlinno** [comment]
Triage 70. Great ideas! Let´s change and try how these three changes would work: 

- "Show replies" in bold and colored into blue
- Author of the reply in bold
- Person to whom reply is being written would move to the same line with reply

Est. dev. time 1 hour. Sending to development.

**Comment by ssin1901** [comment]
@ilmartyrk this seems to be resolved. 
<img width="413" alt="Screenshot 2022-10-05 at 15 16 44" src="https://user-images.githubusercontent.com/72747107/194058345-52ca09b4-7637-45c2-b675-626704a1296c.png">
