### ISSUE TITLE
Something is broken with headings?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1065]
@ilmartyrk Seems like something is broken with the topic headings at the moment (at least for this particular topic) as this is what it looks like in the topic in edit mode

![image](https://user-images.githubusercontent.com/61320526/180396274-1d53986d-5024-4bd3-9fa7-06dc0a5b40bf.png)

But this in view mode and in the dashboard: 

![image](https://user-images.githubusercontent.com/61320526/180396495-4d24786b-8226-4ebe-ae64-a6b7388817e3.png)

![image](https://user-images.githubusercontent.com/61320526/180396566-755d119e-cb4a-412d-818d-4419e907b9d5.png)

**Comment by BeccaMelhuish** [comment]
Another example here, this one is called "Let's Discuss Together", but showing like below.  

![image](https://user-images.githubusercontent.com/61320526/183083791-e6f57b13-b8a2-4106-a64d-d42b56214336.png)

![image](https://user-images.githubusercontent.com/61320526/183085940-d45a0316-1d1b-4f6b-9ea3-13a032cdbe9e.png)

This is how it looks in the topic itself in edit mode:

![image](https://user-images.githubusercontent.com/61320526/183086053-5adb417a-e237-4137-90de-dd89b98daefb.png)

But in view mode, like this: 

![image](https://user-images.githubusercontent.com/61320526/183086125-7985f35f-2ca7-47c4-8779-70755338c505.png)

**Comment by anettlinno** [comment]
Triage 70. Ilmar has noticed an error in synchronizing and our system should refresh changes more often. 
Sending to investigation, approx. time 30 minutes.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish is it happening in our live or test environment?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk live..

**Comment by ssin1901** [comment]
@ilmartyrk the issue occurs intermittently in our live environment and I could not yet identify a pattern. It seems to be cache related.

**Comment by anettlinno** [comment]
Closing the issue as it´s been fixed.
