### ISSUE TITLE
UX suggestion for Group rights confusion

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1068]
Unless I'm missing something I feel like the using word "read" for the group rights that aren't "admin" might confuse things a bit. As the group rights don't (I think?) actually determine whether the user can read topics or not, it only determines whether they have access to the group management settings or not - i.e. to change the name, invite users etc.? 

So perhaps it would be less confusing if it was "admin" and "group member" (or just "member") or something else like this? 

![image](https://user-images.githubusercontent.com/61320526/181512026-f21450e2-1aee-418b-a98c-ea4fb8b60a43.png)

@ilmartyrk @anettlinno @ssin1901

**Comment by anettlinno** [comment]
Triage 70. Good ideas and @oksks your input would be appreciated as well. 

Group rights: 
- **Admin** is the one who can change the group´s settings etc
- **Read** to **Member** as this is the one who has access to the content of this group (topics, users)

We were also thinking that we could change topic rights copy as well, as currently these are rather technical descriptions, but we could change them more User centric. Some ideas:

- **Read** to **Participant** as this person can read the topic, participate in discussion and vote (we preferred "discussion" but this is not a noun and we need a noun. All good ideas are appreciated!)
- **Edit** to **Co-creator** as this person can co-create, edit and change the topic content
- **Admin** can change the topic´s setting

Regarding the "none" rights. As we don´t have any waterproof user cases for that and Ilmar checked that there is only one user (outside our organization) who was using "none" rights in a topic, we decided to remove "none" option under the topic rights. In #1066 is the longer discussion about this. 

AND if we change user rights to user roles, then we should also change this on the platform. We propose to change the **rights** to **roles**. 

@oksks @ssin1901 @BeccaMelhuish your ideas are welcome!

Sending to In Prep for further discussion.

**Comment by oksks** [comment]
I agree with Group rights' change:
- Admin - full access to make changes to a group
- Member - access to a group without any editing rights

Topic rights-wise, i feel like this division would be most logical/self-explanatory to internet users and cover our needs:
- Admin
- Editor
- Participant

**Comment by BeccaMelhuish** [comment]
Big thumbs up to what @oksks suggested from me :)

**Comment by anettlinno** [comment]
Triage 71. Removing "none" under the topic rights, changing "rights" to "roles" and new roles as @oksks and @BeccaMelhuish suggested. 
Est. dev. time 10 minutes. Sending to development.
