### ISSUE TITLE
 Registration and initial login flow is too long

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1070]
**What is the user story?**
New User who receives an email invitation is forced to create an account with email and password and does not have an opportunity to use social login, if one has Gmail account or Facebook account that is merged with the same email. 
This discussion started in issue #773 

Step 1: 
<img width="357" alt="Creating account_step1" src="https://user-images.githubusercontent.com/45175679/181575786-73f0823f-89be-4803-944f-85213a46a759.png">

Step 2: 
<img width="358" alt="Creating account_step2" src="https://user-images.githubusercontent.com/45175679/181576010-2eb6f2a5-d87a-474e-bdfc-c4a1383ad404.png">

**Which feature needs to be updated and how?**
In step 1 User could have an opportunity to choose if User wants to create an account with email & password OR login with social account (Create account OR login with Gmail or Facebook). This would make the account creation and login time much shorter for new users. We would still need to follow all the security steps of course (like sending confirmation email). 
@ilmartyrk do you think that would be doable? :) 

**Additional information.**
N/A

**Comment by anettlinno** [comment]
Triage 71. The main issue is that account creation process is very long. Probably this issue will be solved, if login process gets more user friendly and for that we´ll do following:

1. When User starts registering account, add checkbox to signup form to confirm that User agrees with the terms of Use (@kativellak please confirm, if this is OK). 
2. "Verify your email" message should be more visible for users (currently it appears in blue ribbon in top of the page). 
3. When User clicks on "Verify my email", automatically log user in and display message "Your email is confirmed and account is activated -- welcome to Citizen OS!" (@oksks and @BeccaMelhuish your copy ideas are welcome :) ).

Est. dev. time 6 hours. Sending to development.

**Comment by BeccaMelhuish** [comment]
@anettlinno @oksks Maybe just: "Your email has been verified! Welcome to the Citizen OS platform."

**Comment by ssin1901** [comment]
@ilmartyrk I need some more information about this issue. At present, the situation is that in both the testing and the main environment users who are invited to a topic have no option but to register with email and password. The social login is treated as a separate account and there is no option to link the two accounts.

**Comment by ssin1901** [comment]
@ilmartyrk @anettlinno @BeccaMelhuish I got this option in the test environment for an **existing account**

<img width="1142" alt="Screenshot 2022-10-05 at 12 43 11" src="https://user-images.githubusercontent.com/72747107/194031794-7672e2bc-4051-47e2-a334-5d07a587b0e0.png">

and this for a **new account**
<img width="1389" alt="Screenshot 2022-10-05 at 12 33 54" src="https://user-images.githubusercontent.com/72747107/194032212-0ec46552-edef-418d-8788-faa3fc4919fb.png">

**Comment by ilmartyrk** [comment]
Change issue title:
New user is forced to create password account and cannot create social account  -> 
Registration and initial login flow is too long

**Comment by anettlinno** [comment]
Triage 73. Agreed that we don´t implement this: 
"Verify your email" message should be more visible for users (currently it appears in blue ribbon in top of the page) 
as if we do it, we need to change all notification messages in whole platform. 

Sara tested, flow works nicely. 

Closing the topic.

**Comment by KatiVellak** [comment]
@anettlinno @ilmartyrk 
when User starts registering account, we should add mandatory checkbox to signup form for the User to confirm that User agrees with our Terms of Use. The Terms of Use should be linked to the confirmation text.

**Comment by ssin1901** [comment]
@ilmartyrk I wrote to you in product channel. This issue is ongoing and needs to be resolved quite urgently.

**Comment by ssin1901** [comment]
Incidentally, I feel our login/registration flow is quite okay. The issue seems to be with merging the accounts.

**Comment by anettlinno** [comment]
Closing the issue as the Terms of Use toggle works nicely.
