### ISSUE TITLE
Clarity of "must log in with same email address" message

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1072]
I feel like this message used to be clearer than it is now? Like actually saying the email address that you have to log in with, in the message itself. 

In any case, I feel like it could be this, to be clearer, with the bold font heading, then the regular font explanation: 

**You must log in with rebecca.melhuish@sciencespo.fr to access this.** 

Topics and groups can only be accessed via a Citizen OS account that is registered to the same email address as one to which the invitation was sent.  

![image](https://user-images.githubusercontent.com/61320526/183086486-b76b1c11-5c0c-4222-8b22-38e4cdbec71c.png)

@anettlinno @ilmartyrk @ssin1901

**Comment by anettlinno** [comment]
Triage 71. Our tone of voice is friendly and supportive and I wouldn't use the language where we say to our users that they "must" do anything. Current text says everything and therefore we don´t see the need to change that. 
Closing this issue.

**Comment by BeccaMelhuish** [comment]
@anettlinno The problem here for me is not so much that the sentence itself doesn't say what it should, but that in my opinion must users are pretty unlikely to read it, or get their heads around it if they do. It's a very long sentence (and all in bold which makes readability more difficult), and if you just skim your eyes quickly over it which most people are likely to do, then you may well not grasp what it's trying to say.

It's a good point re the tone of voice though, but that's easily rectifiable. For example, "To access this topic, please log in using rebecca.melhuish@sciencespo.fr" does the same job. 

That way people could instantly understand what they need to do, rather than trying to get their heads around the long sentence and then work out what that means for them in practice. And then go back to their email to check which email address it was sent to. Etc. 

Would make it all much smoother and more likely to be a successful login if the email was provided, in my opinion. And I'm sure I remember that it used to be like that previously?

**Comment by anettlinno** [comment]
Thank you for the explanation, @BeccaMelhuish Let´s change that to: "To access this topic, please log in using bbb@bbb.com" 

I also remember that we previously had this...

**Comment by anettlinno** [comment]
Triage 72. 
Est. time 15 minutes. Sending To do.

**Comment by ssin1901** [comment]
Works fine in the test environment. Text changed.

<img width="1440" alt="Screenshot 2022-11-27 at 20 42 10" src="https://user-images.githubusercontent.com/72747107/204153689-eac995fe-4791-4d1d-97d6-59964cd57b32.png">
