### ISSUE TITLE
Back button not working correctly (?) 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1073]
When I click "back" on the platform, often it pulls up a pop-up that I was previously in and closed. 

This always surprises me - I feel like it's not usually how back buttons work (i.e. they ignore pop-ups)? 

For example, I'm here and click back: 

![image](https://user-images.githubusercontent.com/61320526/183105797-c83032b8-0d78-406a-a66f-8ca9461470e1.png)

And then I get this, when I was expecting to go back to the dashboard (which was the last page I was on before the one above):

![image](https://user-images.githubusercontent.com/61320526/183105994-620ec3dd-80d1-45ef-ab5b-357cbd7c260c.png)
 
@ilmartyrk @anettlinno @ssin1901

**Comment by anettlinno** [comment]
Triage 70. This is developed like that in purpose and we don´t see a need to change it. 
Closing this issue.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish Opening the popup also changes the url so users could possibly share the link to the view if needed
