### ISSUE TITLE
Feedback form for app.citizenos.com

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-old#1074]
**What is the user story?**
A feedback form for users who would like to help us to improve our platform. The feedback form should appear under the Attachments section of Create a Topic and be visible to all users. 
<img width="1161" alt="Screenshot 2022-08-07 at 19 49 28" src="https://user-images.githubusercontent.com/72747107/183302054-7fc63aee-942e-4441-8c10-1b3950cc96d2.png">

+ add screenshot / screencast when applicable

**What is the requested feature?**

A feedback form with two steps.

**Step 1: The form**
The feedback form should comprise 1-3  questions, a text area and a submit button. The 1-3 questions should be editable by the lead from Citizen OS (details to be discussed privately).

The feedback form should include a text area as the answers should be open-ended.

**Step 2: Confirmation and message to Citizen OS supporters**
Once the users have submitted their answers, they should receive a confirmation message. The confirmation message should be editable by the lead from Citizen OS (details to be discussed privately).

**Additional information.**
This article may be useful regarding the interface (https://saberfeedback.com/feedback-button)

**Comment by anettlinno** [comment]
@kevincrepin we would need your help here please :) 

What Sara proposed is one option. We also discussed another option, which is to reuse of the bottom ribbon (something we  used a while ago when Arvamusfestival started their own life). But maybe there are more options and looking forward your ideas :)

**Comment by anettlinno** [comment]
PING @kevincrepin  :))

**Comment by kevincrepin** [comment]
Sorry, will have a look tomorrow!

**Comment by kevincrepin** [comment]
I would suggest the following: https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?page-id=3512%3A40125&node-id=3512%3A40126&viewport=554%2C449%2C1&scaling=min-zoom&starting-point-node-id=3512%3A40126

Instead of having the form immediately visible on the right side, which would add a lot of info there, I would rather have a call-to-action which would open a dialog window. It keeps the focus more at the task at hand.

**Comment by anettlinno** [comment]
Thanks a lot, @kevincrepin! I think we can go with that if @ssin1901 also agrees :) 

(Box corners are rounder then the others, but I´m sure Ilmar can fix that).

**Comment by oksks** [comment]
@ssin1901 asked for design feedback in the product chat, so here be my 2 cents ))
 
Tbh, I'm not a fan of it - the grey background colour seems off in comparison with the rest of the page; the style overall seems different from the current app style, the coloured stripe underneath seems unnecessary and provides a weird optical illusion of the box being wonky :D 
To sum it up, it looks to me like one of those ad banners on news pages. 🙈

**Comment by anettlinno** [comment]
Triage 72. @kevincrepin the Feedback box doesn´t match with the rest of the design as Oks pointed out, so maybe it is possible to make it match with the rest of the platform. Thank you!

**Comment by kevincrepin** [comment]
Good point. I was already/still in the new style mode, but admittedly in the current platform it doesn't suit very well.

Made an update: https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?page-id=3512%3A40125&node-id=3512%3A40126&viewport=402%2C316%2C1&scaling=min-zoom&starting-point-node-id=3512%3A40126

**Comment by anettlinno** [comment]
Triage 73. Thanks @kevincrepin! Let´s implement this but only with white talk bubble (without thumbs up and down in it). 
Est. dev. time 2 hours. 
Sending to development.

**Comment by ssin1901** [comment]
@ilmartyrk @kevincrepin as Anett mentioned, our team agreed that we should have only a white talk bubble without icons 

<img width="1390" alt="Screenshot 2022-10-20 at 16 59 29" src="https://user-images.githubusercontent.com/72747107/196969770-486d3f94-5fe2-4656-9035-0741a21b9e98.png">

I also wanted to add that I think that this button should also say "Submit" not "Submit Feedback"

<img width="1396" alt="Screenshot 2022-10-20 at 16 58 07" src="https://user-images.githubusercontent.com/72747107/196969458-981f8d0e-4a19-4d45-8e9e-ab81b209c27e.png">

**Comment by kevincrepin** [comment]
@ssin1901 updated!

**Comment by ssin1901** [comment]
Hey @ilmartyrk @kevincrepin here are some final updates from me and @BeccaMelhuish 

1. This should say Share your Citizen OS story not We appreciate your feedback 
<img width="1390" alt="131E5A33-D86E-440B-864E-72B2BFC422E3" src="https://user-images.githubusercontent.com/72747107/204000098-bf429e5f-fb0a-478b-9c79-dcdce782dbe0.png">

2. The form text should have the following questions and text input
<img width="1396" alt="DBC23AC8-BD47-4A4E-AFC6-FA9937FB22BF" src="https://user-images.githubusercontent.com/72747107/204000451-30dc58d1-7158-4ce8-8de9-6a303b2011bf.png">

1. How does your organisation create impact?
- Text Field 

2. How do you use Citizen OS? 
- Text Field

**Comment by kevincrepin** [comment]
Updated! https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?page-id=3512%3A40125&node-id=3512%3A40126&viewport=326%2C289%2C0.97&scaling=min-zoom&starting-point-node-id=3512%3A40126

**Comment by BeccaMelhuish** [comment]
@ssin1901 what about the bit where we ask them to get in touch for an interview? :)

**Comment by ssin1901** [comment]
@ilmartyrk @kevincrepin so sorry but could we replace this text [screenshot attached] with 

"Thank you so much for sharing your story! We would love to get in touch with you for a short interview. In case you are interested, please contact Sara Sinha (sara@citizenos.com)".

<img width="1407" alt="Screenshot 2022-12-07 at 11 34 24" src="https://user-images.githubusercontent.com/72747107/206153028-9492fdcc-6ac0-464f-917c-777f768fb1ac.png">

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish update this in testing

**Comment by ssin1901** [comment]
Hey @ilmartyrk sorry for the delay. After some deliberation, here are my proposed changed @BeccaMelhuish @anettlinno 

Replace this button text with Help Us Improve 

<img width="1402" alt="Screenshot 2023-01-06 at 16 14 30" src="https://user-images.githubusercontent.com/72747107/211029951-ce2f00aa-4f70-461e-acae-0ddee1821d6e.png">

Replace the fields in this block with 

[text] We are so happy to have you as a Citizen OS user! If you would like to help us to keep our product free and able to meet a variety of users needs, we would appreciate if you could fill out this short survey. Please be **mindful about what you share with us**

For more information about how we process your data please see https://citizenos.com/legal/privacy/

[field]
Name

[field]
Email address

[field]
Organisation name

[text area]
How do you use Citizen OS?

[checkbox] I would like to be contacted by a representative from Citizen OS 

[button] Cancel [button] Submit

<img width="1400" alt="Screenshot 2023-01-06 at 16 18 39" src="https://user-images.githubusercontent.com/72747107/211038419-b6574850-2608-4c96-8ec6-86d44df9349a.png">

Replace this text with Thanks for Sharing. The rest can remain as it is.

<img width="1298" alt="Screenshot 2023-01-06 at 17 04 31" src="https://user-images.githubusercontent.com/72747107/211039105-6b6eff0f-b2a5-4ab6-8147-fa96585e50de.png">

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish @anettlinno is this final or just proposal?

**Comment by ssin1901** [comment]
@ilmartyrk just a proposal, sorry about the confusion. I wrote to Anett that we (the three of us) can discuss it next week with all the other issues.

**Comment by anettlinno** [comment]
Triage 79. @ssin1901 we have the designs and everything. Please just share the exact copy and then we can finalize the feedback form. I don´t think there is much to discuss as from the technical perspective we have everything we need.

**Comment by BeccaMelhuish** [comment]
Hey @ssin1901 some thoughts from me, sorry for the delay! 

- I think we could go for "Help us improve" but maybe we can try out some different options and see which gets more clicks? "Share your Citizen OS story" was what we agreed before for example (was there some arguments against it?). I don't know which of these would get more clicks, but they are quite different, so would be interesting to test. I think we could also try some other options, such as "Can we connect?" or "Help us understand you". (My hunch is that "Can we connect?" might get the most clicks, as it's quite intriguing. They'd be wondering what it means and curious to see who's asking them to connect and in what way). 

- I feel like if we do have something that sounds like a user feedback button (i.e. "Help us improve") then we need to also give them an opportunity to give feedback. (I.e if something is bugging them and they click there expecting to give user feedback then they're going to be even more annoyed that the button doesn't do what they expected, I imagine). Ideally this would be on the first page to avoid confusion, but it would get in the way a bit of the main message so I'm suggesting it on the second. Tbh though if we get user feedback (i.e. specific UX issues/requests for help) through this button it's not such a bad thing. We can just filter them out and deal with them as we would if it came through the HC. 
 
- In your suggestion above we've got us saying we'll contact them on the first page, and us asking them to contact us on the second page, which is confusing and also as discussed at the monthly meeting it's very unlikely anyone will do the latter. 

Here would be my suggested amendments, taking into account the above and also trying to make it more friendly and engaging :) 

**First page:**

Heading: We'd love to know you better

[text] Hi there! We're really excited to get to know our users, and find out what you use our platform for. Happy to share? It will help us evaluate our impact and make our platform better suit your needs. 

[field]
Name

[field]
Email address

[field]
Group/Organisation

[text area]
What do you use Citizen OS for?

Could we contact you to find out more? (We'll keep it brief, we promise).
[checkbox] Yes, I am happy to be contacted by a representative of Citizen OS.

P.S! Always be mindful of what data you share. For more information about how we process your data [please see here](https://citizenos.com/legal/privacy/). 

[button] Cancel [button] Submit

**Second page:** 

Heading: Thank you for sharing! 

Thank you so much for sharing with us. If you agreed to chat more, we'll be in touch soon! For any queries or feedback in future, please submit a Help Request or User Feedback via our Help Centre.

**Comment by ssin1901** [comment]
@ilmartyrk 

First page:

Heading: We'd love to know you better

[text] Hi there! We're really excited to get to know our users, and find out what you use our platform for. Happy to share? It will help us evaluate our impact and make our platform better suit your needs.

[field]
Name

[field]
Email address

[field]
Group/Organisation

[text area]
What do you use Citizen OS for?

Could we contact you to find out more? (We'll keep it brief, we promise).
[checkbox] Yes, I am happy to be contacted by a representative of Citizen OS.

Please be aware that by continuing to submit your response Citizen OS shall collect and process your personal data for the purposes of being able to provide its services in accordance with the relevant and applicable legislative acts related to the protection of personal data, including GDPR. 

For more information, please read our Privacy Policy at https://citizenos.com/legal/privacy/

P.S! Always be mindful of what data you share. 

[button] Cancel [button] Submit

Second page:

Heading: Thank you for sharing!

Thank you so much for sharing with us. If you agreed to chat more, we'll be in touch soon! For any queries or feedback in future, please submit a Help Request or User Feedback via our Help Centre.

**Comment by BeccaMelhuish** [comment]
Hey @ssin1901 you've got some text in there about DDA by the way :) 

That paragraph feels a bit heavy in contrast to the rest, but if you do feel it's necessary (rather than just the reminder to be mindful and the link to the privacy policy, which I feel like from what Kati said in the meeting is enough), then I would edit it to this to the following, in this order:

P.S! Always be mindful of what data you share.

By submitting your response Citizen OS will collect and process your personal data for the purposes of understanding user needs and contacting consenting users, in accordance with the relevant and applicable legislative acts related to the protection of personal data, including GDPR. 

For more information, please read our Privacy Policy at https://citizenos.com/legal/privacy/

**Comment by BeccaMelhuish** [comment]
So just to clarify @ssin1901 and @ilmartyrk, this below would be the full text :) 

**First page:**

Heading: We'd love to know you better

[text] Hi there! We're really excited to get to know our users, and find out what you use our platform for. Happy to share? It will help us evaluate our impact and make our platform better suit your needs.

[field]
Name

[field]
Email address

[field]
Group/Organisation

[text area]
What do you use Citizen OS for?

Could we contact you to find out more? (We'll keep it brief, we promise).
[checkbox] Yes, I am happy to be contacted by a representative of Citizen OS.

P.S! Always be mindful of what data you share.

By submitting your response, Citizen OS will collect and process your personal data for the purposes of understanding user needs and contacting consenting users, in accordance with the relevant and applicable legislative acts related to the protection of personal data, including GDPR.

For more information, please read our Privacy Policy at https://citizenos.com/legal/privacy/

[button] Cancel [button] Submit

**Second page:**

Heading: Thank you for sharing!

Thank you so much for sharing with us. If you agreed to chat more, we'll be in touch soon! For any queries or feedback in future, please submit a Help Request or User Feedback via our Help Centre.

**Comment by ssin1901** [comment]
@ilmartyrk please use the text suggested by Becca for the moment.

**Comment by BeccaMelhuish** [comment]
And just to check @ssin1901 are we going with "Help us improve" for the button? (I think it's OK, but I suggested some other options above too).

**Comment by BeccaMelhuish** [comment]
@ilmartyrk OK I can confirm it was just decided (in Marketing Meeting) that we will go with "Help us improve" for the button and see how it goes :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 updated the form in testing

**Comment by ssin1901** [comment]
Hey @ilmartyrk couple of enhancements if possible? First can begin What do you use Citizen OS for as a new section? (screenshot below)
<img width="1307" alt="Screenshot 2023-01-26 at 13 36 50" src="https://user-images.githubusercontent.com/72747107/214826278-9b891dbf-120d-4e10-ae60-03782b8b87f3.png">/

Second of all, can we fix the alignment? It is breaking at certain points (screenshot below)
<img width="1104" alt="Screenshot 2023-01-26 at 13 36 59" src="https://user-images.githubusercontent.com/72747107/214826636-e3eee87c-b2fd-4cc3-af68-5b8cfbff4e5a.png">

**Comment by ilmartyrk** [comment]
@ssin1901 I've changed the button texts as suggested, (I initially got them wrong, had used the Help us improve instead of submit), this also fixed the allignment

**Comment by BeccaMelhuish** [comment]
Thank you @ilmartyrk!

One aesthetic/readability thing - could we have a little gap between the heading and the intro text? :) 

![image](https://user-images.githubusercontent.com/61320526/218986679-b4504e39-b6d8-4573-87d0-56a2d4130b8b.png)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 Made some enhancements to style, added the gap between title and description. also made description text a little smaller, also made bottom texts a little smaller as I remember from MM.

**Comment by oksks** [comment]
Hey guys, could you pls let me know if the texts are final & locked now - good to know when I may start with translations :)

**Comment by ssin1901** [comment]
@oksks waiting for some input about shortening the text.

**Comment by ssin1901** [comment]
@ilmartyrk till we get a response from Kati can we make the compliance text "By submitting your response...." smaller.

**Comment by ssin1901** [comment]
@oksks so far I guess text remains the same, so can go ahead with translations.

**Comment by ilmartyrk** [comment]
@ssin1901 @anettlinno @BeccaMelhuish @oksks closing this issue as it is now released in live, For any changes, updates lets open a new issue(s) as this thread is already way too long.

**Comment by ssin1901** [comment]
@ilmartyrk currently nobody is using the feedback form. Can we reopen this issue?

I also had the following ideas @MeelikaH @oksks @BeccaMelhuish @anettlinno 

1. Replace "Help Us Improve" with "Share Impact Story" OR "Your Story" 

<img width="339" alt="Screenshot 2023-06-01 at 11 23 55" src="https://github.com/citizenos/citizenos-fe-old/assets/72747107/650d3e5f-a1b4-43ab-951a-5174facc8170">

2. Dunno anything about the design but maybe something like this? https://www.istockphoto.com/vector/share-your-story-flat-line-design-gm908171294-250195393

3. I propose the following changes to the form 
3.1 Be clear and precise – what do we want them to do and how?
3.2 Replace email address with "email address or social media handle". Why? we should be more modern and not limit our users to just email.
3.3 Instead of group or organisation we should have an impact category dropdown. Why? Less work for the users. Also group/organisation is confusing for people who create impact in a community. Group/organisation indicates formal affiliation.
3.4 I would rather the users who want to share their stories meet with us in person. It would be more valuable to the individuals or organisations as well. 

Also the form is way too long in my opinion. Suggested changes in the screenshot below.

<img width="608" alt="Screenshot 2023-06-01 at 11 28 17" src="https://github.com/citizenos/citizenos-fe-old/assets/72747107/680dad62-8aed-44ad-8d3c-c3afa99a882c">

**Comment by ilmartyrk** [comment]
@ssin1901 lets open a new issue we can refer to this, but it will be cleaner discussion and easier to follow as this thread here is already really long
