### ISSUE TITLE
Own reaction in Activity feed

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1079]
**What is the problem?**
User´s own reaction is shown in the Activity feed. 
<img width="558" alt="Activity" src="https://user-images.githubusercontent.com/45175679/188580545-bbea524e-8b2b-45ab-98fd-ca21090a8c41.png">

**Why is this a problem?**
I think we agreed in Notifications system that we do not show own reactions :) IMHO it´s not necessary and it creates more buzz in Activity feed...

**Possible solution.**
I would suggest to remove own reactions from Activity feed.

**Comment by anettlinno** [comment]
Triage 72. Currently it is possible to filter out "My activities" and "Activities related to User" which are pretty much the same (needs some investigation). 

There is also inconsistency in presenting User´s own actions in Activity feed. Sometimes our system sais that "You set up...", "You removed..." etc and sometimes "User Anett Linno has updated..." We should be consistent in our language (IMO "You set up..." is more personal and stands out from other actions. 

<img width="414" alt="Activityfeed123" src="https://user-images.githubusercontent.com/45175679/191209929-5904e07b-a06e-456f-9cc9-fea5aec5a65a.png">

Decided at the Triage meeting that we will update Activity Feed in UX/UI redesign as there are some upcoming changes planned in Activity Feed feature. Sending back to In Prep.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/38
