### ISSUE TITLE
UX: `/my/topics` & `/my/groups` - Topic/Group list should be an independently scrolling block

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#108]
![image](https://user-images.githubusercontent.com/7405383/48060058-891c3680-e1c3-11e8-9870-d5fa004d16c9.png)

**Comment by ilmartyrk** [comment]
Might still be relevant, adding this to prioritization

**Comment by anettlinno** [comment]
Triage 51. Still relevant issue as the topic/group General Info will disappear from the screen after scrolling down to find topic/group. Making topic/group list as an independent scrolling block and adding scroll bar to the right side of the topics/groups list.
Est. dev. time 2 hours. Sending to development.

**Comment by KatiVellak** [comment]
Good improvement, no legal impact.

**Comment by ilmartyrk** [comment]
@anettlinno this is quite difficult to implement, as it will be changed with UX/UI update I'll close this issue and put effort into other issues
