### ISSUE TITLE
BUG: Argument body text structured into 2 columns

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#1081]
**What is the problem?**
Oddly, argument body text is now structured into columns for some reason.

<img width="813" alt="Screenshot 2022-09-16 at 12 05 06" src="https://user-images.githubusercontent.com/34126353/190601266-356b0f91-391b-4e6e-85e6-f603f1bdbf85.png">

Topic in question: [link](https://app.citizenos.com/et/topics/d43b0899-9fa5-40fa-a173-26adb67152e2?argumentsPage=1)

**Why is this a problem?**
Text should flow in one column

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/79
