### ISSUE TITLE
Email invitation to the topic in a group doesn´t say a word about the group

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1098]
**What is the user story?**
When User receives an invitation email to the topic that is in a group, it does not come out from the invitation that this topic belongs to certain group. This test topic was added to COS Team group:

<img width="557" alt="Grupi kutse" src="https://user-images.githubusercontent.com/45175679/197729259-224f46f2-0c8d-431c-acb2-a4b26524700d.png">

**Which feature needs to be updatd and how?**
Some groups and discussions in a group have higher priorities to me as a User and therefore I would like to know in invitation email, in which group the topic was added.

**Additional information.**
N/A

**Comment by anettlinno** [comment]
Triage 74. @kevincrepin we would like to redesign the black header (with COS logo) and replace it with our new redesign UI. 
@oksks we would like to add in addition to the topic name also the information about which group this topic belongs to. Any good ideas where to add it and how to phrase it? :)

**Comment by oksks** [comment]
I would like to resolve this via design + copy - like have a prominent, coloured stripe up top, which has the group name and logo (if available), and then text underneath saying:

---

Hi **Anett Linno!**

User **Ilmar Türk** from group **"Some Group Name"** is inviting you to join a discussion:
**Topic name**

---

I probably wouldn't add "Citizen OS" to the above sentence, as it is pretty clear from the email design anyway and doesn't add value - wdyt? The design change should apply to all group-related emails, though.

**Comment by ilmartyrk** [comment]
@oksks sounds good, just to add context, adding topics to groups means that members of group automatically are members of topics, in case it is important to know for translating. Really like the idea of adding group name and logo to e-mail.

**Comment by kevincrepin** [comment]
I will take this opportunity to also think about other operational email and marketing email templates.

**Comment by kevincrepin** [comment]
Will share these already and will add more operational mails as we figure them out, because there can be a lot. Anyways it's using a similar template: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?node-id=748%3A79962

**Comment by anettlinno** [comment]
Sending it to UX/UI redesign.

**Comment by anettlinno** [comment]
Triage 76. This will be fixed with the issue https://github.com/citizenos/citizenos-api/issues/239

**Comment by anettlinno** [comment]
> Will share these already and will add more operational mails as we figure them out, because there can be a lot. Anyways it's using a similar template: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?node-id=748%3A79962

How beautiful! :))

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/91
