### ISSUE TITLE
Why does an Editor have the ability to see and add input in follow up and only receives an error after submitting data?

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-old#1109]
**What is the user story?**
A user who has been assigned Editor rights is still able to to add input in follow up but when they click post an update they receive this error

<img width="1440" alt="Screenshot 2022-11-27 at 00 32 25" src="https://user-images.githubusercontent.com/72747107/204111309-6cf48db4-5c5b-4328-99e0-63e978b60c6e.png">

**Which feature needs to be updated and how?**
Only admins should see these input fields (in my opinion)

**Comment by anettlinno** [comment]
Triage 76. Follow-up posts should only be posted by Admin users and this window should be hidden for editing and reading rights Users. 
Est. dev. time 15 min. Sending it to do.

**Comment by ilmartyrk** [comment]
FIXed in angular update
