### ISSUE TITLE
Updating front page: public groups and public topics

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1112]
**What is the user story?**
Very soon we are ready to launch public groups feature and therefore we need to update our current front page (dashboard) UI. We could use the simpler version of redesign (but something that fits with our current design) so that in top of the page would be public groups: 

<img width="532" alt="Public groups" src="https://user-images.githubusercontent.com/45175679/204550787-10df6e47-2fc4-487b-8b1e-fae2c74e1ed7.png">

And below public topics: 

<img width="532" alt="Public topics" src="https://user-images.githubusercontent.com/45175679/204550837-cf96a9c1-d10d-4d7a-956f-fee61af26d7a.png">

**Which feature needs to be updated and how?**
@kevincrepin would need beautiful design for the dashboard from you :) 

**Additional information.**
We want to loose the "boxes" on the front page and show public groups instead.

**Comment by kevincrepin** [comment]
Proposal: https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?page-id=3518%3A40968&node-id=4464%3A41226&viewport=891%2C1190%2C0.25&scaling=scale-down&starting-point-node-id=3518%3A40969

**Comment by anettlinno** [comment]
Thanks, @kevincrepin! Looks good to me! :) 
Prioritizing and sending it To Do. Est. dev. time 2 hours.

**Comment by anettlinno** [comment]
@ilmartyrk texts are broken: 

<img width="818" alt="Broken" src="https://user-images.githubusercontent.com/45175679/209100898-14cf12bc-388e-4ace-87ab-ff5e5e05bb7b.png">

**Comment by anettlinno** [comment]
Additionally groups alignment is on left side, topics alignment fits to the screen.
