### ISSUE TITLE
Redesign: UI main styles, icons, illustrations

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1113]
**What is the user story?**
Implement UX/UI redesign main styles, icons, illustrations and everything related.

**What is the requested feature?**
Implement new design in: 

- [ ] colors
- [ ] icons
- [ ] buttons
- [ ] illustrations
- [ ] pop-up modals
- [ ] check-boxes
- [ ] input fields
- [ ] forms
- [ ] pagination

**Additional information.**
Prototypes: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&node-id=29%3A13982&viewport=329%2C326%2C0.02&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/82
