### ISSUE TITLE
Redesign: language selector

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1114]
**What is the user story?**
Implement redesigned language selector feature:

<img width="412" alt="Language selector" src="https://user-images.githubusercontent.com/45175679/204562764-8c406377-3669-4fa9-92ec-c981afe26fa4.png">

**What is the requested feature?**
"Help us to translate" directs users to "Get involved" page: https://citizenos.com/get-involved/

**Additional information.**
N/A

**Comment by oksks** [comment]
And we should link to /get-involved/help-us-translate/ in the future, when the page has been created. I'll create the content & layout for it - please assign this issue to me, when the initial request above has been implemented.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/83
