### ISSUE TITLE
Redesign: implement log-in / sign-up / password change modals

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1115]
**What is the user story?**
Implement redesigned log-in, sign-up and password change modals

<img width="616" alt="Login" src="https://user-images.githubusercontent.com/45175679/204566354-667b925b-d20a-4c68-a7d9-c83045842a19.png">

**What is the requested feature?**

- [ ] Log-in modal
- [ ] Sign-up modal
- [ ] Reset password modal

**Additional information.**
N/A

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/84
