### ISSUE TITLE
Redesign: User profile

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1116]
**What is the user story?**
Implement redesigned User profile Account details page: 

<img width="527" alt="Profile" src="https://user-images.githubusercontent.com/45175679/204572177-de6890ab-3fa9-4ca3-8ae7-41849377bfd4.png">

And Notifications page: 

<img width="528" alt="Profile2" src="https://user-images.githubusercontent.com/45175679/204572620-bcf0b966-4587-44be-9edd-9d78a6728528.png">

**Which feature needs to be updated and how?**

**Additional information.**
N/A

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/85
