### ISSUE TITLE
Redesign: notification messages

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1117]
**What is the user story?**
Implement product´s internal notification messages (both success and error messages).

<img width="254" alt="Notmessage" src="https://user-images.githubusercontent.com/45175679/204577459-ee872ebf-6bdf-4873-b23d-1c3f325443c5.png">

**Which feature needs to be updated and how?**

**Additional information.**

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/86
