### ISSUE TITLE
Redesign: search

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1118]
**What is the user story?**
Implement redesigned search feature

<img width="136" alt="Global search" src="https://user-images.githubusercontent.com/45175679/204578586-7c494f11-90f6-462b-b60b-4f856064f6cd.png">

**Which feature needs to be updated and how?**
User is able to search by keywords among all public topic, public groups, categories and tags and user´s private topic, groups etc: 

<img width="137" alt="Global search2" src="https://user-images.githubusercontent.com/45175679/204579346-1f1727aa-5724-4193-b638-471e1c6bad0c.png">

I would recommend to change the "Global Search" to just "Search". Additionally in explanatory text would explain better that User sees both public topics, groups etc and one´s own topics, groups etc (those that s/he has initiated or where s/he is participating)

**Additional information.**
N/A

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/87
