### ISSUE TITLE
Redesign: activity feed design update

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1119]
**What is the user story?**
 In first iteration, implement activity feed design updates (and actions inside the feed during the fifth iteration).

<img width="136" alt="activityy" src="https://user-images.githubusercontent.com/45175679/204597931-5bc3d5d6-e508-4ddf-a8cb-01e5c235f20d.png">

**Which feature needs to be updated and how?**
Activity feed design only.

**Additional information.**
Related topic (for the second iteration) is #1079

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/81
