### ISSUE TITLE
[Error] Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by MK0010** [citizenos/citizenos-fe-old#1122]
Hi, 

I am trying to deploy citizenOS locally on macOS. I can run Etherpad, and the API and access the API's docs on port 3002, I can verify that the API is connected to the Etherpad and can access the database. 
I can see the frontend activity in the API's console, however I have an issue when interacting with the frontend. 
I use both API and frontend over http (port 3000 and 3002), and I verified that `baseUrl` and `connect-src` point to the correct port. 
When connecting the frontend displays the error "Network issues, please check your internet connection." and the browsers console returns as error:
```
[Error] Refused to load https://js.live.net/v7.2/OneDrive.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Did not parse stylesheet at 'http://localhost:3000/config/styles/local.css?v=d41d8cd98f00b204e9800998ecf8427e' because non CSS MIME types are not allowed in strict mode.
[Error] Refused to load https://js.live.net/v7.2/OneDrive.js because it does not appear in the script-src directive of the Content Security Policy.
[Debug] citizenos.factory.cosHttpApiUnauthorizedInterceptor (citizenos-fe.bundle.js, line 35885)
[Debug] citizenos.factory.cosHttpApiErrorInterceptor (citizenos-fe.bundle.js, line 35885)
[Debug] $urlRouterProvider.otherwise – "Language detected before status" – "en" (citizenos-fe.bundle.js, line 35885)
[Error] Unrecognized Content-Security-Policy directive 'script-src-elem'. (x2)

[Debug] AppCtrl.$translateChangeSuccess – "en" (citizenos-fe.bundle.js, line 35885)
[Error] Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.
[Error] XMLHttpRequest cannot load http://dev.api.citizenos.com:3002/api/auth/status due to access control checks.
[Debug] sAuth.err – Object (citizenos-fe.bundle.js, line 35885)
Object
[Debug] $urlRouterProvider.otherwise – "Matched state" – Object (citizenos-fe.bundle.js, line 35885)
Object
[Debug] Resolve language – "en" (citizenos-fe.bundle.js, line 35885)
```
How can I solve `[Error] Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.`? Thanks in advance for your help.

**Comment by ilmartyrk** [comment]
Hello, this is because CORS in the citizenos-api project is not configured to allow access from localhost. This part of the configuration can be found in here https://github.com/citizenos/citizenos-api/blob/master/config/default.json#L58.
