### ISSUE TITLE
Add picture size info under the public group actions

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1128]
**What is the user story?**
As a user who is creating a public group, I want to upload a photo, but I don´t know what size is recommended. Currently my photo looks like that (I tried different sizes but current pic is 11KB):
<img width="397" alt="publicg" src="https://user-images.githubusercontent.com/45175679/206428857-4c5dbd24-bbdf-420a-a423-07c8e8ea8d35.png">

**Which feature needs to be updated and how?**
Please add picture size information as an explanatory text or change the picture field so that it would not narrow it from it´s original size.

**Additional information.**
N/A

**Comment by anettlinno** [comment]
Same picture format in all "Public groups" view:

<img width="181" alt="Pic format" src="https://user-images.githubusercontent.com/45175679/206435636-d5ff2683-b6fb-4170-8031-81e3a4b04622.png">

**Comment by anettlinno** [comment]
Cannot see the updates, @ilmartyrk and picture is still the same (I closed and reopened all tabs). Should I wait longer? :)

**Comment by ilmartyrk** [comment]
@anettlinno now it has reached live, github auto-closes issue if the ID is mentioned in commit message as FIX

**Comment by anettlinno** [comment]
Thanks, @ilmartyrk ! Now it works nicely! :)
