### ISSUE TITLE
Empty public group

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1130]
**What is the problem?**
When clicking on the public group (without joining the group) User sees that the group is empty and that there are no topics in:
<img width="832" alt="Empty" src="https://user-images.githubusercontent.com/45175679/206433392-bc639c62-862c-4382-b05d-6b0f916e5e79.png">

**Why is this a problem?**
As a User, I would like to see which topics are being discussed in this group, before joining it. If I don´t see any discussions in the group, then I don´t join it, because I think there is no discussion going on.

**Possible solution.**
We should show all the topics in a public group. And for participation (adding arguments and for voting) User should join the group.

**Comment by ilmartyrk** [comment]
@anettlinno I believe there are no topics in this group at the moment, that is why this text is displayed

**Comment by anettlinno** [comment]
There are, @ilmartyrk :)

**Comment by anettlinno** [comment]
Ahh, just tested and here´s what happened. 

If I clicked on the "Public groups" (in left menu) and on the certain group when **I was logged out,** I saw the topics in public group.
Now, when **I logged in** and clicked on the public group (in left menu) and on the certain topic, I got this message that there are no topics yet.

Please check @ilmartyrk :)

**Comment by ilmartyrk** [comment]
@anettlinno can you please explain a little more, I can not replicate this issue. You clicked on "public groups" link in the left menu, then it redirected to the list of public groups and then when you clicked on a title of a topic it displayed no topics yet?

**Comment by anettlinno** [comment]
@ilmartyrk when I´m logged out, then I see the topics in the public groups: 

Step 1: 

<img width="843" alt="Logged out" src="https://user-images.githubusercontent.com/45175679/207002488-44a9faec-000b-4ae7-949d-1fc000b2e88e.png">

Step 2: 

<img width="936" alt="loggedout2" src="https://user-images.githubusercontent.com/45175679/207002676-6ac715a7-604d-4927-935f-76e8f8fdf4e5.png">

Now, with non-existing User who will login first time with Gmail account (as a new User), this is what I see when following exactly the same steps as above: 

Step 1: 

<img width="846" alt="Publicgroups" src="https://user-images.githubusercontent.com/45175679/207003345-6ba8765a-44dd-4d2c-913f-397cb9844125.png">

Step 2: 

<img width="936" alt="Loggein" src="https://user-images.githubusercontent.com/45175679/207003170-ed2d34e7-c885-47de-81e1-48674f733006.png">

**Comment by ilmartyrk** [comment]
@anettlinno fixed, it was a query bug for logged in users who were not members of the group
