### ISSUE TITLE
Leaving a public group is made tooo easy :) 

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1131]
**What is the user story?**
In my "Public groups" dashboard I have an opportunity either to "Join" the group or "leave" a group. It almost seems that we want people to leave the groups because it´s made so easy for them :)

<img width="818" alt="Leave group" src="https://user-images.githubusercontent.com/45175679/206477154-f4d9be05-70ab-4d4f-9745-c9999f5d7911.png">

**Which feature needs to be updated and how?**
 I would leave "Join group" button as it is, but if a User is already a member of a group, I would show them their member status only (button could be gray and renamed to "Member")

**Additional information.**
N/A

**Comment by BeccaMelhuish** [comment]
I just created a new issue but think it is someone related to this one: https://github.com/citizenos/citizenos-fe/issues/1132

**Comment by anettlinno** [comment]
@BeccaMelhuish do you have any recommendations to what to name the button if User has already joined? :)

**Comment by BeccaMelhuish** [comment]
@anettlinno I'd suggest "View group" perhaps? :)

**Comment by anettlinno** [comment]
> @anettlinno I'd suggest "View group" perhaps? :)

Ahh, @BeccaMelhuish! That´s a good one! :)

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish fixed
