### ISSUE TITLE
Public groups hover cursor not working correctly

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1132]
When you hover over a group in the "Public groups" homepage, the cursor doesn't (at least for me) turn into a "hand" hover like it usually would when something is clickable. It remains either a normal cursor or a text cursor. Which makes is seem like you can't click on the box to view the group. It therefore seems (unless you try clicking anyway, which I did in the end) like the only part you can click is on "Leave/Join group". I nearly clicked on "Leave group" by mistake as a result :) 

![image](https://user-images.githubusercontent.com/61320526/206491036-13eefa52-e381-4b7d-9cd4-5f67514fe5b6.png)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed
