### ISSUE TITLE
Public groups topic list, user list and topic rights not displaying correctly

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1133]
I spotted a few things not displaying/working correctly when looking at the COS public group:

(1) When you click on the grey bar "Topic list" nothing happens, it doesn't open and you have to click on the plus to open it. (Whereas when you click on the "Users list" bar, it does open. (I think this often also happens for me in private groups and in topics - or at least sometimes it does, if not always. I can check this if you like). 

(2) One of the topics has "participant participant" showing as my user rights - see below. 

(3) The user list is only showing 3 of the 5 users - see below. 

![image](https://user-images.githubusercontent.com/61320526/206493313-7bbcfdd6-1d37-4118-af1f-e6e334619e94.png)

**Comment by anettlinno** [comment]
As you are are member of the group and not owner, then there shouln´t be "Remove from group" column either. This should only be visible for admin users.

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish fixed

**Comment by anettlinno** [comment]
@ilmartyrk User list info is still showing less users than there are (5 out of 8):

<img width="945" alt="Userlist" src="https://user-images.githubusercontent.com/45175679/207061024-57d32106-65f5-4b91-82bb-54410ed754f8.png">

**Comment by ilmartyrk** [comment]
fixed
