### ISSUE TITLE
Change users to members

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1134]
**What is the user story?**
I would suggest to rename people who belong to group (both in public and private groups) from "Users" to "Members" and use it consistently throughout the platform. We use the same copy in redesigned version as well.

According to the Merriam-Webster dictionary member (noun) is **one of the individuals composing a group** and **a part of a whole**

**Which feature needs to be updated and how?**
Please let´s change here: 

<img width="185" alt="members" src="https://user-images.githubusercontent.com/45175679/206490453-0b07e191-ed9f-4164-b0cc-8f25e7b415eb.png">

And here: 

<img width="573" alt="members2" src="https://user-images.githubusercontent.com/45175679/206492201-18f69b10-c1f3-40a7-8fe4-39d877799cef.png">

And here: 

<img width="828" alt="members3" src="https://user-images.githubusercontent.com/45175679/206494704-ccca520a-2b6d-4f35-a317-88e835eb9240.png">

**Additional information.**
N/A

**Comment by anettlinno** [comment]
On the third picture please also change the "Invite users via their name..." to "Invite members via their name..."

**Comment by ilmartyrk** [comment]
@anettlinno fixed
