### ISSUE TITLE
Unable to change public group roles

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1135]
**What is the problem?**
As an admin user I wanted to some group members admin rights, but got this error message: 

<img width="921" alt="Group rights" src="https://user-images.githubusercontent.com/45175679/206497966-8d2f1a57-9a14-43d4-86a9-41a1940501e3.png">

**Why is this a problem?**
Unable to change members rights in public group. 

**Possible solution.**
Please fix the problem.

**Comment by ilmartyrk** [comment]
@anettlinno fixed
