### ISSUE TITLE
Unhide settings in public group actions

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1136]
**What is the user story?**
As a public group admin I am unable to find where to add members into the group, because they are hidden under the "Settings"
<img width="136" alt="Settings" src="https://user-images.githubusercontent.com/45175679/206509567-1b24b03f-8bad-41fa-b0ff-cf3fe66c4fa3.png">

**Which feature needs to be updated and how?**
IMO we could bring "Invite users" and "Share group" in drop-down menu so that when clicking on the "Group actions" then admin user will see the drop-down menu:

- Settings (where one can change group name, intro text etc)
- Add topics (IF we decide to keep it: https://github.com/citizenos/citizenos-fe/issues/1129) 
- Invite
- Share
- Leave
- Delete

**Additional information.**
"Leave group" is currently in two places -- in the drop down menu of "Settings" and under the "Actions". I think under the "Actions" we could take it out :)

<img width="331" alt="leave group111" src="https://user-images.githubusercontent.com/45175679/206511413-a8b7bae5-992b-4309-8afa-4dd38cc85131.png">

**Comment by ilmartyrk** [comment]
removed leave group, other things need some thinking

**Comment by anettlinno** [comment]
As frightened, then the current "Group actions" --> "Settings" --> and add topic / invite / share do not work, because Users do not find those actions there. 

We should either bring it to the drop-down menu as suggested above or follow suggestions from the user test:

- User did not find where to invite people in group (in public group view, see below). He tried to click on the members icon next to Group actions and as this was not responsive, he went back to My groups and found "Invite" from My Groups General Information dashboard.  He suggested either to make the icon responsive or add separate button "Invite and share". 

<img width="837" alt="Inviteshare" src="https://user-images.githubusercontent.com/45175679/206672731-d165f10c-c246-42c9-b9f6-10005e5eaa84.png">

- User didn´t understand that for adding a topic this topic must exist and that he needs to create it before he can add it. He said that some guide or explanatory text would be helpful OR there could be big fat button on the public group view (look above) where he could either add or create topic. 

@kevincrepin your magic is very much needed :)

**Comment by anettlinno** [comment]
One more thing. Add topic and Group actions should be seen only to admin users but "Add and invite" could be there for all the group members. 
@ilmartyrk your thoughts are very much welcome :)

**Comment by kevincrepin** [comment]
I updated the prototype: https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?page-id=3518%3A40968&node-id=3518%3A40969&viewport=695%2C441%2C0.5&scaling=min-zoom&starting-point-node-id=3518%3A40969

**Comment by anettlinno** [comment]
Thanks a lot, @kevincrepin!

I have few comments: 

- I would move the topics number into the brackets behind the "Topics" tab and number of group members behind the "Members" tab because IMO it would make it more clean and there it´s clearly understandable, what these numbers show

<img width="622" alt="invite share" src="https://user-images.githubusercontent.com/45175679/207124523-5fd18ff0-30d5-4d46-84e4-12d501bd7db2.png">

- In Admin User view we need to also add "Create topic", because currently it is not understandable for Users that under the "Add topics" they can only add already created topics. Especially new Users does not understand the flow and we don´t mention this anywhere :) This came clearly out from the user test as well and I see that there are two ways how to solve this: 

1. We bring back the "Create new topic" tab in "Add topic" as it was in previous verison
2. We add there somewhere "Create topic" button close to the "Add topic" button

<img width="705" alt="Add topic" src="https://user-images.githubusercontent.com/45175679/207126093-6e7c18f8-9321-4d09-949e-9e381c06a22f.png">

**Comment by kevincrepin** [comment]
Did the updates. What if we have dropdown menu under "add topics" from which you can choose either create new topic or add existing topic. You can try it out in the prototype.

**Comment by anettlinno** [comment]
> Did the updates. What if we have dropdown menu under "add topics" from which you can choose either create new topic or add existing topic. You can try it out in the prototype.

Thanks, @kevincrepin! That looks really good! (Y)

**Comment by anettlinno** [comment]
Triage 77. High priority. Sending to To DO. 
Est.dev. time 3 hours.

**Comment by anettlinno** [comment]
Some bugs and ideas: 

- "Add topics" button opens _Group settings_ window
<img width="225" alt="Add" src="https://user-images.githubusercontent.com/45175679/208383052-a24cec86-18d3-4701-be4a-1e0469ce4952.png">

- After clicking on "Create topic" button, User can read _Add new topic to group_ -- it is confusing as I clicked on Create but now it says Add. Let´s change that. I feel that there should also be little explanatory text which explains that If a User will create a new topic in group, then after creating "Create topic" button, all group members can read the topic. 
<img width="840" alt="Create" src="https://user-images.githubusercontent.com/45175679/208383918-ac8d46d2-71b5-4a30-9608-75eeaeb7870f.png">

- After clicking "Add exciting topic" User can read "Add topic to group" but let´s add please "Add existing topic to group" and again there could be explanatory text which says that User can add only public topics in group. If the topic does not show up then most probably it is private topic and it needs to be changed to public. 
<img width="837" alt="Addtopic" src="https://user-images.githubusercontent.com/45175679/208384737-af39fc52-f47f-4202-9e93-6ab7d2e1c119.png">

@oksks @BeccaMelhuish could you please help with the copy :)

**Comment by anettlinno** [comment]
Triage 80. 

When adding new topic to public group, User has to refresh the page before seeing the topic. Please reload the topic list after User clicks on "Add topic". 

When User clicks on "Remove topic" icon same thing happens that the page is not reloading and User should refresh the page. 

Estimated dev.time 15 min. Sending to do.

**Comment by ilmartyrk** [comment]
Fixed in angular update

**Comment by BeccaMelhuish** [comment]
@anettlinno Sorry I missed the request for help with copy for this, do you still need it? And if so which bit, I got a little lost? Perhaps you can write something and I can proofread? :)

**Comment by anettlinno** [comment]
@BeccaMelhuish I think we´re all good with that right now :) Thanks!

**Comment by ilmartyrk** [comment]
fixed with angular update https://github.com/citizenos/citizenos-fe-old/issues/1005
