### ISSUE TITLE
EP: Timeline - cannot see change history for a big document - https://app.citizenos.com/en/topics/7abdd244-d45b-40d3-997c-a6290d4e972c

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#114]
**Overview**

There is no changes visible when scrolling in the timeline view of https://app.citizenos.com/en/topics/7abdd244-d45b-40d3-997c-a6290d4e972c

Tho its Etherpad issue, it's this projects task to find out what the issue is.

**TODO**

- [ ] Find out why EP does not show history for https://app.citizenos.com/en/topics/7abdd244-d45b-40d3-997c-a6290d4e972c
- [ ] Fix and make a pull request to EP project (https://github.com/ether/etherpad-lite)

**Comment by ilmartyrk** [comment]
This issue still exists

**Comment by KatiVellak** [comment]
Technical issue, no legal comment.

**Comment by ilmartyrk** [comment]
Triage 51, needs investigation to create proper issue in Etherpad project. As this probably needs quite a lot of time to fix will not invest time to fix this issue for now.

Est. investigation time 1 hour.

**Comment by tiblu** [comment]
### Investigation notes

* When using timeslider view buttons to navigate (playback, back, forward), the changes ARE displayed  
![image](https://user-images.githubusercontent.com/7405383/153201734-fcc6bd39-6fcc-41a9-98b7-4c3104a06b6c.png)
* ALSO, after using the buttons, timeslider suddenly starts working - you can use the slider to slide back and forward.
* When using timeslider slider element BEFORE using the timeslider navigation buttons, changes ARE NOT displayed instantly BUT delayed without any indicator in the UI
    * EP starts loading all the changesets in a sequence via WS and will not change the UI before all changesets are loaded thus delay may be significant. ![image](https://user-images.githubusercontent.com/7405383/153203512-e932f3c5-abaf-4e27-a9da-87529d43522e.png)


### Related issues

* https://github.com/ether/etherpad-lite/issues/5012#issuecomment-916405707 - User notices same behavior - the content of the pad lags behind for timeslider.

**Comment by tiblu** [comment]
In conclusion - its not broken, but there is a delay for loading the changes.
Investigation time over, created an issue for Etherpad - https://github.com/ether/etherpad-lite/issues/5408.
