### ISSUE TITLE
Public group invite is not working properly

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1140]
**What is the problem?**
Group admin wanted to invite me in public topic, but received following error message: 

<img width="958" alt="Email" src="https://user-images.githubusercontent.com/45175679/206663797-36307f39-f978-4e55-9afb-98fed488cd17.png">

**Why is this a problem?**
We checked that I was not in the group nor was the invitation previously sent. User invited me to the topic that was created, but the topic wasn´t in the group at that time. 

Additionally, it would be nice if error message would be more precise in what happened. 

- IF the user is already invited in group, error message should say that "invite was not sent, because this person (or email) is already invited in this group"
-  IF email address is invalid, error message should say that "invalid email address, please enter correct one"

**Possible solution.**
Please investigate why User could not add me in public group

**Comment by ilmartyrk** [comment]
@anettlinno is the issue in inviting to group or topic? I could not replicate the issue

**Comment by anettlinno** [comment]
> @anettlinno is the issue in inviting to group or topic? I could not replicate the issue

Issue was with inviting in group. Most probably User had connection issues (as seen in user test), but is there anything we can do with that? I mean to prevent these kinds of issues for Users with poor internet connection?

**Comment by ilmartyrk** [comment]
I believe it is not an issue with connection, rather it seemed to be:
1) Server side issue as heroku had some weird errors during that timeperiod
2) Browser related (Safari)

I suggest we close this issue and if issues reoccur we open a new issue

**Comment by anettlinno** [comment]
Thanks for investigating this issue @ilmartyrk 
Let´s close the issue.
