### ISSUE TITLE
Shouldn't this Log In feature in Public Groups trigger some sort of action?

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-old#1142]
**What is the problem?**
When the user clicks on Public Groups and selects this topic https://app.citizenos.com/en/topics/5309ffb9-b43d-4412-a3d5-5ddc61c167a9 they are prompted to log in (see screenshot) but the link doesn't do anything 

<img width="1438" alt="Screenshot 2022-12-11 at 19 19 00" src="https://user-images.githubusercontent.com/72747107/206918625-aa743acc-8dab-4b43-9f8b-7c5ca23e447f.png">

+ add screenshot / screencast whenever possible
Looks like a broken link

**Possible solution.**
The link should direct them to the login page or even better open the modal login window

**Comment by anettlinno** [comment]
Triage 77. Already in work, translations merge issues. 
Done by the end of Triage meeting :)
