### ISSUE TITLE
UI - remove duplicate code that's generated due to liberal use of @import

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#115]
**Overview**

* The misuse of SCSS `@import` generates duplicate code in the CSS bundle.
* Also it will mess up CSS inheritance by importing duplicate code in the middle of things.

**References**

* SCSS - https://sass-lang.com/

**TODO**

- [x] Remove excessive use of `@import`
- [ ] Standardize the whole SCSS usage, right now it's homebrew

**Comment by loorm** [comment]
Triage 14 - talked about this. Needs to be done. @tiblu - do you have an estimated time?

**Comment by loorm** [comment]
Triage 15: Time estimate 5 days due to heavy cost of testing (needs CSS rewrites). This would go away, if we were to have a major front end redesign.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by ilmartyrk** [comment]
replace @import with @use https://sass-lang.com/guide#topic-5 and also removed @import of other scss files that created duplicates in final css. Everything seems to look as it should including mobile, tablet and print views.
