### ISSUE TITLE
Issues with topic list in a group

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1150]
**What is the problem?**

1. First, I would like to search topic in group but it´s not working properly. I do not get any results or message that topic is not found.

![Search](https://user-images.githubusercontent.com/45175679/208700672-cef066ef-606b-4ee8-904c-d68fbbfafda2.png)

2. Secondly, search bar is named as "filter" and IMHO we should change that to search, because when clicking on "filter" then search bar is opening and not filters.

3. Third, roles design is strange it looks like it´s broken: 

![Filter](https://user-images.githubusercontent.com/45175679/208702134-972e6767-be97-46b0-8b12-c41750c7ac2f.png)

4. Forth, "Remove from group" is not aligned correctly and trash icons are missing behind the topics where I´m an admin

**Why is this a problem?**
Inconvenient user experience as search is not working and topic list looks broken. Please fix it :) 

**Possible solution.**
N/A

**Comment by ilmartyrk** [comment]
Fixed all the issues except 3. as not sure what would be the best solution, I could possibly make all items dropdowns. but some would be disabled, but at the same time, when user has only topics where he/she cannot change permissions, there is just a bunch of disabled dropdowns that also looks a little broken, I suggest not to put much effort into solving this in our current design

**Comment by anettlinno** [comment]
Triage 78. Will not fix the third, roles designs issue as it´s going to change with redesign anyway. Closing this issue.
