### ISSUE TITLE
Commenting feature is not working properly

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1151]
**What is the problem?**
I answered on the comment that was left in the document and my text looks messy.

<img width="519" alt="Comments" src="https://user-images.githubusercontent.com/45175679/209099619-0c612769-1dda-44fb-aab2-fc002ab62df9.png">

**Why is this a problem?**
Text is not readable.

**Possible solution.**
Please fix the problem.

**Comment by ilmartyrk** [comment]
Triage 78. issue is in ep_inline_comments plugin, est. dev time 1h

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/64
