### ISSUE TITLE
Open link in new tab

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1166]
**What is the user story?**
When clicking on a link inside the topic, a new link will open in the same window. For user experience perspective it would be better if link would open in new tab.

**Which feature needs to be updated and how?**
Please open link in new tab.

**Additional information.**
N/A

**Comment by ilmartyrk** [comment]
Triage 78. Estimated dev time 2 hours. Check if issue can be fixed with plugin update or add fix to API Etherpad sync code.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/66
