### ISSUE TITLE
Remove "Change all" rights when inviting one person or group to a topic

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1169]
**What is the user story?**
As a User I wanted to add a topic to a group. I clicked on "Share topic" on the right menu and chose "Invite". After inserting group´s name, I have two options for changing group rights: 1) Change all 2) Groups 

![Topic to group](https://user-images.githubusercontent.com/45175679/210351511-c4e10123-c02f-472f-9c37-1deccf156577.png)

When entering only one group or person then the "Change all" is redundant. 

**Which feature needs to be updated and how?**
"Change all" option could appear only when User invites more than one group or one person. It would also explain what the "Change all" means -- _Change the topic rights of all invited groups and users_ (and drop-down menu)

**Additional information.**
N/A

**Comment by ilmartyrk** [comment]
Triage 78. Update this behavior during angular upgrade.

**Comment by ilmartyrk** [comment]
FIX-ed with [angular update](https://github.com/citizenos/citizenos-fe-old/issues/1005)
