### ISSUE TITLE
Participants search is not responding

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1176]
**What is the problem?**
I wanted to search participants under the "Manage participants", but I didn´t get any response after inserting participants name on the search bar.
<img width="385" alt="Search part" src="https://user-images.githubusercontent.com/45175679/210995803-332196de-cac1-4d44-b2ba-b1a9924fe3cb.png">

**Why is this a problem?**
If I have a list with 500 participants and I need to find certain participant, I want to use search option for finding the participant. Currently I should do it through the pagination which is very inconvenient. 

**Possible solution.**
Please fix the search problem.

**Comment by anettlinno** [comment]
Triage 79. Same issue appears also in "My topics" view. Est. fix time 15 min. Sending it to Do to.

**Comment by ilmartyrk** [comment]
Fixed

**Comment by ssin1901** [comment]
Tested and working now @ilmartyrk @anettlinno
