### ISSUE TITLE
BUG: No clear way to close an inline comment

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#1179]
**What is the problem?**
I've opened an inline comment, and there's no clear way to close it - there's no "X" in the corner, and it doesn't close when I click outside of it, which are the main 2 ways to usually close any pop-up.

<img width="862" alt="Screenshot 2023-01-13 at 12 26 03" src="https://user-images.githubusercontent.com/34126353/212298197-eb2933dd-279f-49be-99f8-89dd5a76d0c8.png">

**Why is this a problem?**
I'm stuck with unable to close the pop-up. Bad UX :)

**Possible solution.**
Please add "X" to close the pop-up.
If possible, also allow to close it by clicking outside of it.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/80
