### ISSUE TITLE
UX: User profile - cannot update User info without creating/inserting a password

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#118]
**Overview**

In User profile, you cannot change any info without entering a password. 
The problem is that not everyone has a password - Google, FB authentication.

https://trello-attachments.s3.amazonaws.com/54f6dc9eb07f7a437bef6770/59bbd8488b6782d59fa46ed0/1c969194231cf6ef77996c4e8fb06cc8/image.png

**TODO**

- [x] Profile modification (avatar, name, company, email) without asking for a password.
- [x] Separate password creation/modification section.

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-fe/pull/124
