### ISSUE TITLE
Inviting users to groups doesn't work on IPad or Mac

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#1180]
User invites to group are missing id/e-mail in invite body on IPad/Mac

**Comment by anettlinno** [comment]
Triage 79. Possible fix already in live,  needs double-testing. Sending it to Testing @ssin1901.

**Comment by ssin1901** [comment]
@ilmartyrk tested this and it now works. Also invite users works for topics.

**Comment by ssin1901** [comment]
@ilmartyrk Tested and working now.
