### ISSUE TITLE
Alignment looks wrong when user clicks on the public topic

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-old#1184]
**What is the problem?**
The alignment for the public topics category labels does not look correct in MacOS Safari or Chrome.

<img width="1305" alt="Screenshot 2023-01-17 at 00 23 18" src="https://user-images.githubusercontent.com/72747107/212774316-26bbca38-22fa-421f-ab3f-5dfd5045e794.png">

**Why is this a problem?**
It is not visually pleasing and looks like a bug. It is also distracting for the user.

**Possible solution.**
Alignment should look consistent (all items centre or all left aligned)

**Comment by anettlinno** [comment]
Triage 79. Quick fix, est. fix time 5 min. Sending it To do.

**Comment by ilmartyrk** [comment]
Fixed

**Comment by ssin1901** [comment]
Tested
