### ISSUE TITLE
BUG: Edit Topic (Etherpad) - iOS "no cookies" if cookie settings are "Allow cookies from websites I visit" which seems to be iOS default

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#119]
**Overview**

When entering Topic edit mode in iOS, Etherpad shows "no cookies" error, that is if cookie settings are "Allow cookies from websites I visit" which seems to be iOS default.

**TODO**

- [ ] Find out the root cause and fix it. IF an Etherpad issue, PR a fix.

**Comment by ilmartyrk** [comment]
Closing as we haven't had any feedback of this happening. Re-open If happens again.
