### ISSUE TITLE
Public groups invite login very broken

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1190]
I followed a public groups login invite and it didn't work at all. (May be for other kinds of login too though, didn't check). 

First there was no email address where there is meant to be:
![image](https://user-images.githubusercontent.com/61320526/213398318-bca8f6fb-9048-4f09-aca2-1398ac68765d.png)
(Though actually this prob isn't relevant to public groups and should be removed entirely?) 

And then when I clicked "Log in" the popups disappeared totally and went to the dashboard. (No login pop-up, have to click Login to try again).

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I tried to test it by leaving the group and then following the link again to see what happened. I got a "Invite has now been deleted" message so wasn't able to test, but I ended up on this page as a result, and it seems the buttons don't work - nothing happens when I click on them.. 

![image](https://user-images.githubusercontent.com/61320526/213549549-839ab336-ede7-4487-b393-3a4ff4a23316.png)

Also is this maybe just the dashboard but not as it should be? Not sure how it happened.. When I clicked COS logo to go to dashboard home I did then get the dashboard as it should look..

**Comment by BeccaMelhuish** [comment]
P.S. I tried clicking the join link again and got the same again - seems it's what happens when an invite has been deleted (or you've joined then left then tried to join again in my case!) 

![image](https://user-images.githubusercontent.com/61320526/213550321-b901f554-2184-4ec5-8ad9-0375fb9012b5.png)

**Comment by BeccaMelhuish** [comment]
Also sorry I think my heading was incorrect! I believe it was a private group not public group I was trying to join. Though this makes me think, @anettlinno, should we say in the email invite whether it is a private or public topic/group, as this may affect whether they want to join it or not..

**Comment by ilmartyrk** [comment]
@BeccaMelhuish fixed the deleted invite issue

**Comment by anettlinno** [comment]
Triage 80. @ssin1901 please test.

**Comment by ssin1901** [comment]
@ilmartyrk here are the steps I followed on MacOS Google Chrome and here is the error (opening an issue describing the same after testing with Windows)

1. Step 1:  Sent invitation to user (works perfectly) 
2. Step 2: User receives email (works perfectly) - **screenshot for reference**
<img width="1074" alt="Screenshot 2023-02-06 at 14 54 12" src="https://user-images.githubusercontent.com/72747107/216977893-66b40432-ecc5-4155-98fb-4f3fc6f531f1.png">


3. Step 3: User receives confirmation message on COS platform (works perfectly) - **screenshot for reference**
<img width="1440" alt="Screenshot 2023-02-06 at 14 54 27" src="https://user-images.githubusercontent.com/72747107/216977567-dc62fec8-9b1d-47cf-a53b-ad5fe0446af4.png">

4. Step 4: User clicks on confirmation message (bug) - **screenshot for reference** <img width="1251" alt="Screenshot 2023-02-06 at 14 54 41" src="https://user-images.githubusercontent.com/72747107/216977596-0a187700-6e43-475c-ab3f-bef82bfc837e.png">

<img width="1440" alt="Screenshot 2023-02-06 at 15 00 26" src="https://user-images.githubusercontent.com/72747107/216977942-f3e2453d-7a73-4544-b461-007b509ae42a.png">

**Comment by ssin1901** [comment]
@ilmartyrk let me know if I need to provide more information about the use case.

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish I tested this feature and while the bug is fixed and the user receives the correct invite (screenshot attached)

<img width="1084" alt="Screenshot 2023-05-08 at 18 18 06" src="https://user-images.githubusercontent.com/72747107/236863209-4672c386-ba30-4541-8796-848323863add.png">

 the user does not get added to the public group (screenshot attached).
 
<img width="1251" alt="Screenshot 2023-05-08 at 18 18 14" src="https://user-images.githubusercontent.com/72747107/236863533-fc03de6f-5f4e-4e8d-9fd1-7a7a92fcaad7.png">

**Comment by ilmartyrk** [comment]
@ssin1901 Moved new issue to https://github.com/citizenos/citizenos-fe-old/issues/1246
