### ISSUE TITLE
Save button is missing

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1196]
**What is the problem?**
When managing participants and changing roles then I am not able to save the changes as the "Save" button is missing. 
![Save](https://user-images.githubusercontent.com/45175679/214063903-e0cd7f85-4507-47f8-8c4e-ca0269b590d2.png)

**Why is this a problem?**
As a user, I don´t know if my changes are being saved after I close this window. I need to press the "Save" button for the confirmation.

**Possible solution.**
Please add "Save" button.

**Comment by anettlinno** [comment]
Triage 80.
Adding "Save" button to confirm the changes. Button itself doesn´t do actually anything else than closing the window, but for keeping the UX same everywhere, we´ll add the button. 
Sending it TO DO. Est.dev.time 10 minutes.

**Comment by ilmartyrk** [comment]
FIXed with [angular update](https://github.com/citizenos/citizenos-fe-old/issues/1005)
