### ISSUE TITLE
When E-ID card reader is not detected mobile ID doesn't work either

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-old#1197]
**What is the problem?**
When the user clicks on Login with E-ID/Mobile ID and there is no E-ID card reader plugged in then the user does not have the option to use Mobile ID either even though there is no error message indicating that the mobile ID is invalid. See screenshot 
<img width="1440" alt="Screenshot 2023-01-23 at 16 44 32" src="https://user-images.githubusercontent.com/72747107/214069367-0ff615ee-39f5-4a42-bd72-bd9d7e9cfacc.png">

+ add screenshot / screencast whenever possible

**Why is this a problem?**
User cannot use mobile ID either
This is helpful for prioritizing the bugfix.

**Possible solution.**
User should be able to login with mobile ID regardless of what is happening with E-ID

**Comment by anettlinno** [comment]
Triage 80.
Could not replicate the issue. @ssin1901 from the screenshot we can see that the "Authenticate with Mobile-ID" button is active. Please add more details. 
Moving to In Prep.

**Comment by ilmartyrk** [comment]
@ssin1901 please check if still valid, if not then we can close this

**Comment by ssin1901** [comment]
@ilmartyrk resolved. Mobile ID and E-ID can be used at the same time.
