### ISSUE TITLE
UX: Joining topic via link changes the permission for people who are being invited with higher rights then "participant"

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1198]
**What is the user story?**
I created a topic and added it to the group where I gave all the participants "editor" rights. I also shared this topic in Slack and called people to join the topic via link. People who joined via the link had "participant" rights and they could not edit the topic content. Now I have to manually check if more people have joined via link and change their permissions. Most of our Users might not know that they have to change the rights when participants joins with the link. 

**Which feature needs to be updated and how?**
When topic is added into a group with higher rights than "participant" then our system should change topic link rights as well, because from the user experience perspective, we cannot assume that Users know that the link rights are different then the rights that are given to all participants in the group (or invited via email). 
When participant joins the topic via link, then our system should already recognizes the rights that have been given to him/her by the admin User when adding topic into the group or inviting people via email?

**Additional information.**
N/A

**Comment by anettlinno** [comment]
Triage 80. User case needs more details, when exactly what happens and possible solution how to solve this issue. 
Sending to InPrep.

**Comment by ilmartyrk** [comment]
When user has been added through group they get groups permissions, after clicking on join link user gets direct permissions that are taken from the join link permissions level. These permissions override the initial group permissions like if group had edit permissions and invite link is to participate, user will have downgraded permissions from edit to participate. If user has been given direct permissions they will always override permissions coming from groups

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/37
