### ISSUE TITLE
Vote/Topic - adding and modifying vote deadline

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#120]
**Overview**

There is no method to extend vote deadline in the UI.

**TODO**

- [x] Enable adding and modifying vote deadline in the Topic settings after the vote has been created.

![image](https://user-images.githubusercontent.com/7405383/48136110-82ff8600-e2a7-11e8-81da-de1a9f39c8c1.png)

**Comment by loorm** [comment]
Enhancement tested and confirmed working.

@ilmartyrk - I did not have a topic, that would be in voting with a deadline, where I would have only view rights. Hence, I could not test, if this new feature plays ball with our rights system. Does it?

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
