### ISSUE TITLE
Critical issue - Login via email invitation not working

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-old#1208]
**What is the problem?**
1. When the user goes to their email and clicks on the invitation they are directed to login (attached below).

<img width="1439" alt="Screenshot 2023-02-07 at 14 52 21" src="https://user-images.githubusercontent.com/72747107/217257886-9f53703c-7667-4a9d-a3ae-1097874bc616.png">

2. Instead of seeing all the login options they come to this page and cannot login with their accounts.

<img width="1439" alt="Screenshot 2023-02-07 at 14 52 33" src="https://user-images.githubusercontent.com/72747107/217257919-d4a81a8d-bd2e-4071-b274-c9e8bad71cb1.png">

+ add screenshot / screencast whenever possible

**Why is this a problem?**
Users cannot access topics they have been invited to.

**Possible solution.**
Users should be presented with all the login options that are present in the main login feature.

**Comment by ilmartyrk** [comment]
@ssin1901 can you please describe your flow a little more as I am not able to replicate this issue

**Comment by ssin1901** [comment]
@ilmartyrk if I receive an invite to join a group and click on Join Group from my email (even if the invitation was recent) I am directed to "please login using ____" (email that the invitation was sent to) but when I click on login I get that menu with no login options, only No account and Login button. Then when I click Log in, I get a message "Bad request*". 
<img width="1437" alt="Screenshot 2023-02-07 at 18 23 17" src="https://user-images.githubusercontent.com/72747107/217302941-50f7f31b-541b-423e-bcc6-0cbb213b322e.png">

And this issue occurs across Windows Microsoft Edge, Mac Safari and Chrome.

**Comment by ilmartyrk** [comment]
@ssin1901 I still can't replicate it, can you forward the invite email? And also could you make a video about what happens

**Comment by ssin1901** [comment]
@ilmartyrk sent the email! Also when I tested it with another account it had only two sign-in methods (I guess which I had previously used)
<img width="1398" alt="Screenshot 2023-02-07 at 22 08 47" src="https://user-images.githubusercontent.com/72747107/217354667-9e6c65cb-4693-4659-ba6f-0edc3e065aca.png">

**Comment by ssin1901** [comment]
@ilmartyrk I will also test from the perspective of a first-time user (who is creating an account for the first time)
