### ISSUE TITLE
BUG: users list is messy

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1209]
**What is the problem?**
Users list pages are messy: 
<img width="599" alt="List" src="https://user-images.githubusercontent.com/45175679/217474445-cd2e5a52-0e56-4567-8bac-5ec23282a4a7.png">

**Why is this a problem?**
Currently user can see those who have accepted the invitation above and those whose invitations are pending below, but it´s confusing for the users as you can see page pagination on both cases.

**Possible solution.**
Please only leave one users list.

**Comment by ilmartyrk** [comment]
@anettlinno what do you suggest? Should we remove invites from that view, create another tab for invites or merge them together with other users? I guess most clear would be to create a separate tab for invites that way the functionality will basically stay the same

**Comment by anettlinno** [comment]
@ilmartyrk I would suggest that we just add pending invites to the end of the list (last pages in pagination). WDYT?

**Comment by ilmartyrk** [comment]
@anettlinno I understand the idea, but from UX perspective, when you have a lot of users and also a lot of invites and you wish to browse through invites only this would be quite annoying to try and determine where the members end and invites start, also technically it is a little more difficult because invites and members come from different API endpoints.

**Comment by anettlinno** [comment]
I understand @ilmartyrk. But the separate tab solution -- where this tab would be? 
Here?
<img width="228" alt="Tab" src="https://user-images.githubusercontent.com/45175679/217495477-5344fe33-44ff-43af-8f9f-2bd4e4a2637a.png">

Do we need design for that?

**Comment by ilmartyrk** [comment]
@anettlinno it would look like the existing ones, for topics list and members list, activities etc.

**Comment by anettlinno** [comment]
OK, @ilmartyrk . So there would be three "ribbons": 
1) Topic list
2) Members list
3) Pending invites list (or something like that)

Yes? :) If so, then I think it could work nicely :)

**Comment by anettlinno** [comment]
Triage 81. Easy development. Est. dev. time 15 min. 
Sending to To Do.

**Comment by ilmartyrk** [comment]
FIXed in [angular update](https://github.com/citizenos/citizenos-fe-old/issues/1005)
