### ISSUE TITLE
BUG: Vote singing with ID-card does not work on Edge 14.14393 (Windows 10)

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#121]
**Problem**

The problem is that there is no IE Edge support for ESTID.

**What giants do?**

* Eesti.ee - shows a button to open the whole page in regular Internet Explorer
* Swedbank - Shows "not supported" message - "You are using Microsoft Edge internet browser. You can log in, but can’t confirm payments or sign agreements with ID-card, because Microsoft Edge browser doesn’t support estonian ID-card yet. Please use Internet Explorer or Mozilla Firefox if logging in with ID-card."

**What we do?**

* I think we should follow the Swedbank path, but not sure if we should show the message on the page header or only in sign-in/sign-vote dialog?

**TODO**

- [x] Research if EDGE support has been added.
- [x] IF NOT, show "not supported" message. Message has to reflect that it's not a Citizen OS issue but ID-card support issue.

**Comment by ilmartyrk** [comment]
This issue can now be closed https://www.id.ee/?id=37347
