### ISSUE TITLE
Why does our Registration page Terms and Conditions have an On/Off Toggle button?

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-old#1210]
**What is the user story?**

On our platform a new user who clicks on sign up for a new account (https://app.citizenos.com/en/account/signup) is presented with this page (screenshot attached) which as a Terms and Conditions sections with a Toggle button (on and off).

I think that it is not standard to have a Terms and Conditions button like that (https://termly.io/resources/articles/agree-to-terms-and-conditions-checkbox/). Usually it is a checkbox. 

<img width="1440" alt="Screenshot 2023-02-07 at 18 26 44" src="https://user-images.githubusercontent.com/72747107/217305008-e832306d-ff7c-4ef7-8e5e-977b9e00e89c.png">

**Which feature needs to be updated and how?**
Using a checkbox with a proper label  (https://termly.io/resources/articles/agree-to-terms-and-conditions-checkbox/) over here https://app.citizenos.com/en/account/signup.

**Additional information.**
Something you want to add, that didn't fit one of the boxes above.

**Comment by anettlinno** [comment]
Triage 81. This is not very high priority issue, as it doesn´t affect platform usage. 
We have checkbox designs in our redesign project and we will make the changes with redesign. 
Closing the issue with no further action.
