### ISSUE TITLE
UX: "human readable"/"machine readable" confusion

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1216]
Was checking for the HC whether we still have this "human/ computer readable" explanation, and I see that we still do.. I believe we're all in agreement now that this will be highly confusing to the average user? And I remember Kevin giving the same opinion in one of the redesign meetings. 

So shall we change it, to make it clearer? It's not really my role to do so, but wanted to bring it up as it bugs me :D 

Also, I noticed that for the topic I was testing it on it made no sense at all, as there are not even any options to choose, you just click "download".. I assume that for topics where there was e-ID voting then options appear below and the text would make more sense. But it should be different text (or no text in fact) for topics where there is no choice of format?   

![image](https://user-images.githubusercontent.com/61320526/220119803-7d4258c4-f8b0-40aa-becd-a62af4b779b6.png)

@ilmartyrk @anettlinno @ssin1901

**Comment by anettlinno** [comment]
Triage 82. Thanks, @BeccaMelhuish for bringing this topic up again! 
We could hide this text when User has used social log-in for voting so that there would only be test that "Voting is closed" and "Download voting results". 
Approximate dev.time 10 min. Sending to development.

**Comment by BeccaMelhuish** [comment]
@anettlinno will we still be keeping the "human readable" and "machine readable" explanations for when the vote was using e-ID then? I feel like it could use a re-think to be put in more user-friendly language.. (Not got suggestions off the top of my head, but sure we can do better!)
