### ISSUE TITLE
Can we prevent the "force reconnect" issue when topic editing?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1218]
@ilmartyrk We have often found in our Marketing Meetings that the "Force Reconnect" pop-up that appears when you stop typing in a topic for a while and then go back to start typing in again can be quite frustrating. You have to realise what's happened, stop typing, scroll up to the top where the button is and click it, then come back down to where you were and type again. And often repeat the process several times as it happens again and again. 

For me, this happens very frequently. For @anettlinno it doesn't happen (at all, I believe you said?). For @ssin1901 it does also happen, and she has also found it to be annoying. I noticed it happened to Meelika too in one of our recent meetings.  

Is there a way to prevent this from happening? :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno  I am afraid not as this comes from Etherpad and needs a lot of effort to make some kind of a fix. Even issue tracking is probably quite difficult given that it works for some and not for others. Anyway we will be moving away from Etherpad with our UX/UI updated so  I am going to close this issue.
