### ISSUE TITLE
UX: Dashboard (my/topics & my/groups) - filter Topics by status, favs (once implemented)

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#122]
**Overview**

Dashboard (my/topics & my/groups) - filter Topics by status, favs (once implemented)

![image](https://user-images.githubusercontent.com/7405383/48140826-42593a00-e2b2-11e8-9528-e79add94cb2a.png)

**TODO**

- [x] Add a possibility to filter Topics on the dashboard by status and favs (once implemented)

**Comment by ilmartyrk** [comment]
Solved by https://github.com/citizenos/citizenos-fe/commit/e7204fceac8be13c51d18b4ee88a82dc5b152f30
