### ISSUE TITLE
BUG: Image preview in News section not displaying correctly (EST)

### ISSUE THREAD

**Issue by MeelikaH** [citizenos/citizenos-fe-old#1229]
**What is the problem?**
On the news page (in EST version, Uudised), the latest news does not display the thumbnail image. https://citizenos.com/et/uudised/
+ add screenshot / screencast whenever possible
![Screenshot 2023-03-01 at 13 10 39](https://user-images.githubusercontent.com/126671955/222123232-961e329d-7e1b-46f3-ac6f-121ff89b28e3.png)

**Why is this a problem?**
Visually this looks out of place with a gray area displayed instead of the image.
This is helpful for prioritizing the bugfix.

**Possible solution.**
Check the image settings.
 @oksks

**Comment by ilmartyrk** [comment]
@MeelikaH this seems to be under a wrong project, I created a new issue in https://github.com/citizenos/citizenos-web/issues/405 and will close this
