### ISSUE TITLE
BUG: Platform doesn't open from website multilingual page

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#1231]
**What is the problem?**
Trying to open the Finnish-language platform URL by clicking the top-right "Käytä alustaa" black button on the Finnish frontpage of the website (https://citizenos.com/fi/), the platform page opens black with only a Help Center button in the bottom-right corner:

<img width="1440" alt="Screenshot 2023-03-07 at 16 09 31" src="https://user-images.githubusercontent.com/34126353/223446529-3081920f-9122-46d9-8091-a98de21f435f.png">

Same behaviour in Chrome and Safari.

**Comment by oksks** [comment]
@Ilmar - nevermind, we'll drop the Finnish language from the website, so no redirection fix needed.

**Comment by ilmartyrk** [comment]
@oksks thank you for update on Finnish language, but actually the issue was that the page should not be blank and should at least display 404 so fixed that as it was a little legacy bug in code

**Comment by ilmar** [comment]
@oksks please stop mentioning me, I have nothing to do with this project. Thank you! :)
