### ISSUE TITLE
Let´s Do It Indonesia page

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#131]
**Overview**
Please create page for LDI Indonesia which is similar to the Keep It Clean Plan https://app.citizenos.com/et/keepitcleanplan 

**TODO** 
- [x] Please add LDI Indonesia box on the Home page. 
    * Owner: Let´s Do It Indonesia. 
    * Header of the box: "10 island project oleh Let´s Do It Indonesia" (in English: "10 island project by Let´s Do It Indonesia"). 
    * Category: 10 island project. 
    * Logo: Let´s Do It Indonesia logo (find it from https://drive.google.com/drive/u/1/folders/1bhJyquk94NCxSCB3-XEYM99lNjQQ1AEb).
    * Box color: #bed73d 
    * Text: 10 island project bersifat terbuka bagi seluruh pihak, baik masyarakat, organisasi, dan pemerintah di Indonesia dengan tujuan menampung ide untuk mengimplementasikan rencana lingkungan yang berkelanjutan dalam Keep It Clean plan di Indonesia 

- [x] Users should be able to choose the category "10 island project"

![image](https://user-images.githubusercontent.com/7405383/49450815-7c045e80-f7e6-11e8-8684-dc6fc036072a.png)

**Comment by anettlinno** [comment]
Thanks, @tiblu! Yes, I think it´s ready to pass for @kevincrepin and I´ll send him logo via Slack (Y)

**Comment by kevincrepin** [comment]
On Invision: https://projects.invisionapp.com/d/main#/console/9829159/332797153/preview

**Comment by anettlinno** [comment]
@kevincrepin Thank you! Unfortunately I cannot see it in InVisionApp, as it says I need permission, but Ilmar promised to give me the access :) 

@ilmartyrk, design is ready now and so are the translations. Kindly ask you to do the integration on our web page. Thank you in advance.

**Comment by kevincrepin** [comment]
@anettlinno just invited you ;)

**Comment by anettlinno** [comment]
> @anettlinno just invited you ;)

Hmm... It still says I don´t have access :P

**Comment by tiblu** [comment]
@kevincrepin @anettlinno This design looks good to me. Added screenshot of it to the issue description.

**Comment by tiblu** [comment]
![image](https://user-images.githubusercontent.com/7405383/49450791-7149c980-f7e6-11e8-8edf-a8ad34ac7e6f.png)

**Comment by tiblu** [comment]
@anettlinno @ilmartyrk Is this done and can be closed?

**Comment by ilmartyrk** [comment]
@tiblu @anettlinno closed

**Comment by anettlinno** [comment]
@ilmartyrk @tiblu Thank you!! :)
