### ISSUE TITLE
Partner/client box colours to come from a predefined selection?

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#153]
So far, COS app's grid view has been cohesive and pleasant to the eye in the use of colour scheme.
Recently, we have onboarded some partners who have wished to use their specific colours for the client box, which looks very "off" in the cohesive app design's colour scheme.

To illustrate:
![screenshot 2019-01-07 at 11 58 58](https://user-images.githubusercontent.com/34126353/50769205-ec8e1780-128b-11e9-8b52-34dff189b987.png)

**Comment by loorm** [comment]
Colourful boxes at the top are hard-coded right now. We're not sure if we want to keep the public topics boxed view in the long run and even if we do, we don't want to keep hard-coding boxes indefinitely. Will move to the bottom of SPDP for now.

**Comment by loorm** [comment]
Merging this into our public groups user story. Closing this issue.
