### ISSUE TITLE
BUG: App's English locale should be en-GB to have a correct date format

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#154]
Currently, if app's language is set to English, the date format looks like mm/dd/yyyy. (08/31/2018)

Since we currently only have one default English and most of our EN-speaking users come from non-US territories, I propose to set current English locale to en-GB for the date format to be displayed as dd/mm/yyyy. (31/08/2018)

![screenshot 2019-01-07 at 15 09 13](https://user-images.githubusercontent.com/34126353/50770260-58be4a80-128f-11e9-9b9e-974a8b5eea06.png)

**Comment by ilmartyrk** [comment]
Seems still relevant

**Comment by anettlinno** [comment]
Triage 51. Relevant change, successfully replicated. As discussed in Triage meeting then changing the en-US date format to en-GB format is more user friendly in our region. Currently the language switch works nicely with changing the date format.  

Est. dev. time 1 hour. Sending to development.

**Comment by KatiVellak** [comment]
No legal impact, relevant change though.

**Comment by tiblu** [comment]
I propose a soluton that looks at the operating system locale list and uses the first `en-XXX` locale for date formatting.
That is - IF the chosen language is `en`, check into `window.navigator.languages` (if it even exists - IE....), find first `en-` locale and use that for date formatting (set as Moment's locale).  IF no `en-XXX` is found, then fall back to `en-GB`.

**Comment by tiblu** [comment]
### Done

Implementation notes:

* We take the most precise locale that the browser returns in `window.navigator.languages`.
    * NOTE: What browser returns, depends on your browser settings which MAY be set on install looking at the OS languages OR can be set manually on install. For Chrome you can modify your language settings by going "Settings->Advanced->Languages". (chrome://settings/languages). 
![image](https://user-images.githubusercontent.com/7405383/143479915-0d975b43-e915-4dda-bbf5-cc255dc0d106.png) 
* IF nothing is found, we fall back to the language code. For ex: `en`, `pt`.
* IF we have fallen to `en`, we set locale to `en-GB`.
* Solution works for all languages, that is - if you select `pt` but your browser list also has `pt-BR`, we will use the `pt-BR` for date formatting.
