### ISSUE TITLE
BUG/FEATURE: Configuration setting to hide/show promoted content and categories - Keep It Clean, Eesti Jazzi Arengusuunad

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#156]
**Overview**

Citizen OS helps out some organizations to get their discussions more traction on the Home page. These include Keep It Clean Plan, 10 island project, Eesti Jazzi Arengusuunad tiles and custom categories on the Home page.

These are all fine on https://app.citizenos.com site, but should not affect other installions.

![image](https://user-images.githubusercontent.com/7405383/50773131-95db0a80-1298-11e9-9814-2fe617598a0d.png)

**TODO:**

* Configuration to hide/show all Home page promotion tiles and related custom categories. Key: `features.showPromotionTiles`. Default: `false`. 
* Configuration to hide/show Citizen OS tutorial tile. Key: `features.showTutorialTile`. Default: `true`.
* Change Citizen OS live configuration to show the promotions and tutorial.

**Comment by ilmartyrk** [comment]
Still relevant.

**Comment by anettlinno** [comment]
Triage 51. Closing the topic as the UX/UI redesign includes public groups creation and the issue with these "boxes" on the landing page will be irrelevant after that change.
