### ISSUE TITLE
voting deadline expiry not accurately reflected

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#160]
When voting has a deadline and the deadline is expired, a user who navigates to voting tab does not understand, what the status is, because:
- no message anywhere about "voting closed" (see attached image)
- coloured status timeline at the top of the page indicates ongoing voting
- deadline in the top right corner does not say "voting" deadline, but "signing" deadline and it is difficult to notice

Why is this a problem: as evidenced by the image, situation right now is very confusing. All signs indicate, that voting should be ongoing, yet a vote cannot be cast. Most frustrating for the user.

**Possible solution:** relabel the date in the top right corner correctly and once expired, make it red and well visible. Also, possibly say "voting deadline expired" in red on top of the voting results.

![unclear ux](https://user-images.githubusercontent.com/22661743/50970921-6c65ed00-14eb-11e9-962e-0060ea1c5386.JPG)

**Comment by kevincrepin** [comment]
Shouldn't there be also the box to download the ddoc? In design we have a title there stating the voting has ended.
Also in the timeline it states "current status: voting has ended" and "0 days left" with the deadline still visible.

![screenshot 2019-01-10 at 15 38 45](https://user-images.githubusercontent.com/26792281/50971974-15ade280-14ee-11e9-8256-8f9675036b0a.png)

**Comment by loorm** [comment]
Adding a screenshot to illustrate the problem. 
![screenshot-app citizenos com-2018 06 11-11-51-57](https://user-images.githubusercontent.com/22661743/55436091-0fd31500-55a4-11e9-8eb5-f57c667e3c4a.png)

**Comment by loorm** [comment]
A duplicate of #502. Closing.
