### ISSUE TITLE
BUG: activity feed loses track of topic

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#161]
Description: under certain conditions, activity feed no longer indicates topic title, even though title existed

Why is this a problem: this makes it difficult to track changes to topics later on or possibly raises suspicions of censoring certain activity feed entries.

Possible solution: track topic id ad2b2254-4cca-4e86-b154-258d4118f702 and find out, why activity feed lost track of topic title and previous rights status.

![capture_2](https://user-images.githubusercontent.com/22661743/50973257-1bf18e00-14f1-11e9-8e59-d7f25d9ad17c.JPG)

**Comment by loorm** [comment]
Just ran into it again.
![Capture](https://user-images.githubusercontent.com/22661743/55878265-c0dd3f00-5ba4-11e9-96f2-08d85a73fd24.JPG)

**Comment by ilmartyrk** [comment]
Closing as this issue seems to be fixed. This was related to including topic info in certain activities that initially only included topic id.
