### ISSUE TITLE
suggest similar public topics when a new public topic is being created

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#162]
**Problem**
When a topic becomes hot in society, it is likely, that multiple people will want to create a public topic in Citizen OS about it. However, it makes more sense, if they all contribute to the same public topic, instead of creating double entries.

**Why is this a problem?**
It may not be, however, in an ideal world, people's efforts would be pooled to achieve a diverse discussion and the best possible decision.

**Possible solution**
When you start entering a topic title, compare the words to other topic titles and if the per centage of similarity exceeds a certain threshold, display possible existing topic(s) about the same problem.

**Comment by loorm** [comment]
@ilmartyrk Could we do this, even in principle. Topic titles and content are entered in Etherpad. Is there any way that we can monitor in real time what the user is typing in Etherpad, compare it to topic titles of other public topics and suggest existing public topics in real time.

BTW, we would need to do this for all topics (private and public), because topics are private by default.  Users only make them public later, when there is already content to display.

Also, this might not be limited to analysing the title only, but might take into account keywords found in topic text, too.

Alternatives:
- when a user is viewing a topic, display a list of related Citizen OS topics (this does not need to be real time) somewhere in UI
- Only do the analysis and suggest similar topics, once a topic is being made public.  This would take away the real time monitoring and processing load.

**Comment by loorm** [comment]
Ping @ilmartyrk.

**Comment by ilmartyrk** [comment]
@loorm I think we could possibly add this feature. Easiest way would be to link this to our current search endpoint. BUT this would probably need an update too as it currently is searching for exact matches.  @kevincrepin @anettlinno this seems relevant in the UI/UX refresh process too.

**Comment by anettlinno** [comment]
@ilmartyrk @loorm I also think that solving this with (better) search on the public topics page would give a user an opportunity to search similar topics (but she has to be aware of this feature and as came out from the user tests and UX meeting then search is not being used as expected by the users). 

Currently it works nicely with even only one keyword: 
<img width="469" alt="Search" src="https://user-images.githubusercontent.com/45175679/139651210-cc17a7aa-171d-40fb-accd-848905b05c8d.png">

I personally wouldn´t support that our system would provide existing public topics while the user is typing the topic title for following reasons: 
- This is very specific user case when one wants to initiate public topic on the issue that is already in discussion. If I think about our main users today, then mostly our platform is being used for private discussions. For these users showing published topics is not relevant but makes the user experience more messy I believe;
- I also see the issue of topic´s accuracy -- if I´m being suggested topics with similar keywords but the content or angle is totally different, I am overwhelmed with information and might loose focus on my own topic.

**Comment by loorm** [comment]
I think linking to search endpoint, like @ilmartyrk suggested, makes sense. However, I would not trust users to go searching for similar topics on their own. Most people will neglect to do that. Our system would neet to auto-recommend similar topics, just like you get recommendations when purchasing books on Amazon or listening to songs on Spotify. 

The purpose of doing this is to get around one of the main problems of social media - liberals gather in one group to have their discussions, conservatives gather in another to have their discussion, often about the very same topics, but there's no meaningful interaction and thus, there's less agreement and understanding in society.

To some extent, separate groups of people discussing the same topic should be "forced" to engage with each other, to combine the discussions. Now, I mean the word "force" in the softest possible meaning, by making people aware, that there are other similar topics and by suggesting cooperative discussion.

The same thing is true not only in society at large, but in organisations, too. People who hold opposing beliefs and opinions tend to cluster tugether and reinforce their own thinking, not engaging the arguments of the other side. Debate is productive, opinion bubbles are not.

I still think this is a valuable and relevant feature for a cooperative decision-making paltform.

**Comment by anettlinno** [comment]
Thanks for the explanation, @loorm, I have no doubt about the importance of this feature but I misunderstood the implementation part. If our system would provide similar topic recommendations proactively let´s say in the right side of the topic or below (as Amazon does), then this would make sense and makes it really valuable.

BUT only with public topics, right? :)

**Comment by loorm** [comment]
> Thanks for the explanation, @loorm, I have no doubt about the importance of this feature but I misunderstood the implementation part. If our system would provide similar topic recommendations proactively let´s say in the right side of the topic or below (as Amazon does), then this would make sense and makes it really valuable.
> 
> BUT only with public topics, right? :)

It should only suggest public topics. However, the suggestions should always be there for both public and private topics, because all topics are created as private topics by default. Example: when I want to make a topic about school closures due to the pandemic, I create a new topic. Right now, this topic is private. I invite a few like-minded people and we start putting the topic content together. The topic is still private. At some point we feel like we have enough sustance to make it public. If I only get suggestions then, when I already have my own content ready, I'm still going to publish my separate topic. However, when I create a new topic, enter the title "Do not close schools due to covid pandemic" and then get a list of similar topics, then there's a real chance, that I will not create my own additional topic, but will instead go and participate in one of the existing topics.

- suggestions visible near public and private topics

- only public topics are suggested

**Comment by anettlinno** [comment]
@kevincrepin I think that the user case is pretty clear now and with Margo´s explanations doable. Could we add this to our UX/UI redesign project or do you think we could do this separately?

**Comment by kevincrepin** [comment]
I would like to hear from @ilmartyrk what are the possibilities within Etherpad for this, considering the title of the topic is created within the Etherpad "textfield". It would be easier if the title is a separate input, I think. Something also to reconsider during the redesign.... We've seen some weird behaviour/issues with the Etherpad title section.

**Comment by ilmartyrk** [comment]
@kevincrepin @anettlinno @loorm 
 I would actually exclude Etherpad from this equation. We sync topic content from Etherpad to our own database where we have title and content separated. This would allow us to use this title based searching part. Anyway as some time has passed and we also have Ronald who is enthusiast and has a lot of ideas on creating search algorithms and AI integrations we could possibly use his input on creating this searching feature.

**Comment by ilmartyrk** [comment]
Moving to https://github.com/citizenos/citizenos-fe/issues/35
