### ISSUE TITLE
UX: open the most current tab first

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#163]
Problem: when opening a topic that is in voting or in follow-up, the system nevertheless displays "View" tab first. It does display a notification for the relevant status, for instance: "This topic is being voted on, editing is no longer possible!"

Why is this a problem: it requires the user to look for the tabs and make an extra click

**Possible solution:** open the most current tab first. Then, if the user navigates away from that to the "View" tab, display the notification.

**Comment by ilmartyrk** [comment]
From navigation perspective, this probably needs fix for "public topics" view as it already works in the my topics view. To always load the correct tab, we would probably have to implement a new url param for reading view. This could help us always navigate to most recent tab and also would still let the view tab switch-ing to work

**Comment by KatiVellak** [comment]
No legal impact.

**Comment by anettlinno** [comment]
Triage 51. Successfully replicated. Public topics should direct to the phase where the topic currently is (this only works when the topic is in "voting" phase"). Redirecting "follow-up" and "closed" topics to the "follow-up" tab. 

When user enters via link and the topic´s status has changed in the meanwhile then it should direct to the current (changed) tab.

Est. dev. time is 4 hours. Sending to development.

**Comment by anettlinno** [comment]
Triage 76. This will change with the redesign project and should be fixed with Angular update. 
Sending to redesign.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/89
