### ISSUE TITLE
Make sharing topics on social media easier

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#166]
**What is the problem?**
Social media sharing results in a suboptimal share experience (see screenshot). Only info about our platform is displayed, not information about the actual shared content.

**Why is this a problem?**
Because few people are in the habit of regularly visiting our main page, but many people regularly engage with social media. So we should give much more visibility to our users' content.

**Possible solution** 
When sharing, the preview includes at least the title and possibly first lines of the content of the topic.

![share_cos](https://user-images.githubusercontent.com/22661743/51040762-021f7c00-15c1-11e9-9837-fafb6e5af20b.JPG)
![share_raa](https://user-images.githubusercontent.com/22661743/51040775-08155d00-15c1-11e9-841e-17e2336766d0.JPG)

**Comment by loorm** [comment]
linked to #420

**Comment by liinaguiter** [comment]
Re: possible solution: social media share button is nice to have, but not necessary or urgent.

When sharing the link on social media, the title has to show. This should be changed ASAP. Remove COS logo as well please. No need for our logo. 

Better, if we have a few sentences of the topic in the preview as well. 

Bonus, if we can display an image that is in the topic. = )

**Comment by tiblu** [comment]
> Possible solution: use some standard social media share button tool or library (like https://www.sharethis.com/), that displays a single share button next to the topic, but then enables a choice between at least FB/LinkedIn/Twitter sharing. When sharing, the preview includes at least the title and possibly first lines of the content of the topic.

@KatiVellak what do you think?

**Comment by tiblu** [comment]
![image](https://user-images.githubusercontent.com/7405383/82825290-a4d55380-9eb3-11ea-99d9-e99ca3ab04a5.png)

**Comment by loorm** [comment]
@kativellak "We had a talk with Kati, she said that share "widgets" are legally complicated. Don't remember exactly what, but I would take Katis input on this before we do it." This was by @tiblu

**Comment by loorm** [comment]
Two different issues bundled up as one. I'm separating the "social media share BUTTON" issue into a separate issue. Leaving only the part about showing topic content in shares.

**Comment by loorm** [comment]
There was a separate proposal in Slack by @anettlinno, that if the topic has an image, this image should be used in the preview instead of our logo. When there are no images, our logo looks beautiful.

**Comment by tiblu** [comment]
Interesting, FB share preview tester picks up image from the content, others like Slack and Skype don't.

* Slack - 
![image](https://user-images.githubusercontent.com/7405383/82894317-14524e00-9f5b-11ea-938c-b2e83cee5211.png)
* Facebook - 
![image](https://user-images.githubusercontent.com/7405383/82894698-aa867400-9f5b-11ea-897c-e5f59f441fed.png)
* Skype - 
![image](https://user-images.githubusercontent.com/7405383/82894796-d570c800-9f5b-11ea-9a6d-bd0ca7a5a709.png)

**Comment by tiblu** [comment]
Done!
The preview image is the first one found in the topic, BUT I've seen SOMETIMES Facebook override it and take some other image from topic.

* Facebook - 
![image](https://user-images.githubusercontent.com/7405383/82899645-005f1a00-9f64-11ea-821c-715733fe17b0.png)
* Skype - 
![image](https://user-images.githubusercontent.com/7405383/82899609-f3dac180-9f63-11ea-9660-9a9d4b8b32b7.png)
* Slack -
![image](https://user-images.githubusercontent.com/7405383/82899731-22f13300-9f64-11ea-83a2-8770330dacdc.png)
