### ISSUE TITLE
Help text needs to move from being a topic to being a sub-page in the web app

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#167]
Problem: web app help texts right now are a separate topic in the Citizen OS system. This makes them non-translatable using CrowdIn and they do not move with the system, when a partner installs a separate instance.

Why is this a problem: changes to help texts cannot be tracked over different languages and they become out of sync. Partners who install an instance can have altogether missing help texts. Languages used in the app may not have help in corresponding languages. In all cases, user is left without adequate support.

**Possible solution:** move help text from topic content to a separate sub-page within the app. Then it a) moves with the app and b) goes into CrowdIn and becomes translatable.

**Comment by oksks** [comment]
@kevincrepin 
Hi! :) Could you pls help us with a solid UX for this issue? @tiblu would like to implement it.

Here's the current Help (EN): https://app.citizenos.com/en/topics/c6b6d06a-e8cf-4297-9654-8c1cf01b133b?argumentsPage=1
It's accessible from the "Help" button in the left-hand toolbar in the app, as well as from the first topic block on the frontpage.

Thanks!

**Comment by kevincrepin** [comment]
@oksks Putting it on my todo!

**Comment by kevincrepin** [comment]
@oksks @loorm @tiblu 

I suggest as a "quick" solution like this: https://projects.invisionapp.com/d/main#/console/9829159/352173492/preview

We divide the content into the chapters via a menu, so it's not one long document in which you have to go find what you're looking for. Let's also have a place for the demo video to be accessible, because that one explains it visually whereas otherwise it's just text.

When we go into our next UX improvement sprint, I think we need to consider smart tooltips, first time onboarding, etc.

**Comment by oksks** [comment]
@kevincrepin Love it! Thanks :) Demo video placement adds an especially awesome touch imho - totally makes sense in there. I wonder if search could change into Help-specific search, when user is visiting the Help page?
 
Agree, let's take this subject into the next UX discussion. We should keep in mind, that the FAQ's will also need to live someplace similar, but this layout looks like a great fit for them as well.

WDYT guys?

**Comment by loorm** [comment]
@tiblu @ilmartyrk How big is this in terms of development? Do you think this is a good approach?

**Comment by oksks** [comment]
@tiblu @ilmartyrk is the ball in your court with this ticket? 
We can consider moving Help and FAQ's out of the app and into the web, too. That would mean the user has to leave the app to get help - but that's usually how it's done on the Interwebz.

I'd love to get this sorted out before I hand over to the new localization person.

**Comment by loorm** [comment]
Assigning to Triage.

**Comment by tiblu** [comment]
Pro of having it in the app is that the help is in sync with version deployed. That is, if there is a self-hosted instance, that help will apply to the version installed. IF we link to Citizsen OS site, that MAY have newer version of what the on-premise has.
Con is that it takes developer resource to maintain and deploy. As developers we would not like to deal with content editing and releases related to new help text. One possibility is create the content by CS team in an other system and on build we would generate docs and bundle with release.

**Comment by loorm** [comment]
Triage 22. This needs to be decided in the larger context of Citizen OS Customer Support. Whether to have help in app (requires dev hours to maintain form) or out of app (on website or in a separate environment). Sending back to in preparation.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Triage 42. We are fixing these issues on a larger scale with the new Help Center. This was a temporary fix, which is no longer needed. Closing issue.
