### ISSUE TITLE
UPDATE: add RFC 3161 asice container format support

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#173]
Problem: signed votes can be downloaded in Estonian-specific bdoc container format RFC 2560. 

Why is this a problem? This container format is difficult to use internationally for Citizen OS users outside Estonia, who need secure voting.

**Possible solution:** create support for RFC 3161 .asice container format with an international timestamp along with national guidelines https://www.id.ee/?id=37026

**Comment by ilmartyrk** [comment]
Closing this as it is fixed with moving to our own container creating.
