### ISSUE TITLE
README: Improve contribution section to include non-code related contributions

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#176]
**Overview**

Citizen OS aims to be more than just an app, we aim to be a community beyond coding.
There are many other areas we are interested in outside coding, thus  there are many other ways to contribute.

**Related to**

* https://github.com/citizenos/citizenos-api/issues/98

**TODO**

- [ ] Describe all more ways to contribute in the contributions section.
- [ ] Move contribution section up in the README.md

**Comment by ilmartyrk** [comment]
Still relevant, needs wider input

**Comment by anettlinno** [comment]
Triage 52. Linked on the web site https://citizenos.com/get-involved/ and updating content. Closing the issue.
