### ISSUE TITLE
ETHERPAD: Display warning when "title" exceeds determined limit

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#177]
**Overview**

@moll rightfully pointed out (https://github.com/citizenos/citizenos-api/issues/2) that the `title` limit is too strict and there is no warning to the customer. So we decided to make the limit configurable and warn the user about truncation.

**TODO**

- [x] Display warning (alert dialog) when Topic title exceeds configured limit.
- [x] Bonus: Discuss with @kevincrepin, what would be better way to inform User about such restriction while he/she types in the EP.

**Comment by kevincrepin** [comment]
Suggestion in attach.

Idea is to not block the user, but just give them a warning and visually also indicate where the title goes "over the line".

![desktop hd](https://user-images.githubusercontent.com/26792281/52210337-729f7d00-288f-11e9-9354-94e9e29f5195.png)

**Comment by ilmartyrk** [comment]
@kevincrepin can you please add it to invision too?

**Comment by kevincrepin** [comment]
Added it here: https://projects.invisionapp.com/d/main#/console/9829159/345728780/preview

the icon should be exportable as well
