### ISSUE TITLE
REQUEST: Add timer to user session

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#180]
Request was made to add session timer, like banks do. To log users out or extend session to void situations when user forgets to log out from public computer, thus enabling others to access their accounts.

**Comment by ilmartyrk** [comment]
Seems still relevant. We'll need more input to decide if and how to implement

**Comment by anettlinno** [comment]
Triage 52. Discussed and decided that there is only small amount of users who use our platform on public computers. AND hopefully their digital literacy is good enough to log out from all their accounts after finishing their sessions. 

Our system auto saves topics in editing mode but does not save when writing arguments. When user is writing an argument and goes to search for evidence from other pages for example, she might loose already written argument if our system logs her out after her session time ends. 

At this moment we will not add timer to user session but this issue will be closed for the future discussion.
