### ISSUE TITLE
Increase attachment limit and indicate the limit visually

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#181]
Problem: number of topic attachments is currently set at 5, but this is not obvious to the user.

Why is this a problem? User plans the topic and attachments, but may then run into our limit and feel frustrated, that they were not told about the limit beforehand.

Possible solution: increase number of attachments per topic from 5 to 10. And indicate this clearly on the attachments box, as shown in the image (in red).
![attachments](https://user-images.githubusercontent.com/22661743/51921974-eefa1200-23f0-11e9-87ad-89353f17d654.JPG)

**Comment by ilmartyrk** [comment]
We had hard-coded limit for 5 attachments both on API and FE side. As it was not programmed  to display error on if limit is exceeded on FE-side, I removed the limit check and after that only API side checks for limit and sends error if limit is exceeded. But I will add informative variable to FE side, that is by default same as on API side, that displays how many attachments are allowed.
