### ISSUE TITLE
BUG: Rewiew + fix the use of "comment" vs "argument"

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#185]
In the old days, arguments were named "comments". Since then, we've decided to split and separate the two, both ideologically and hierarchically: 
- Argument is the pro or con statement you can leave under a topic
- Comment is a reply you can leave to the argument, placed lower in the hierarchy.

However, in the FE, app still talks about comments, while it may probably still have arguments in mind.
Please review and fix "comment" => "argument" where applicable and necessary.

**Comment by ilmartyrk** [comment]
This seems to be fixed as I didn't see any use of comment in our source en.json file
