### ISSUE TITLE
BUG: Topic view gets unresponsive or slow when topic has lot of arguments

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#188]
When topic has lot of arguments page responsiveness falls drastically even turning unresponsive in IE

**Comment by tiblu** [comment]
Reading:

* https://bytes.babbel.com/en/articles/2017-03-17-angular-performance.html

**Comment by ilmartyrk** [comment]
Main reason why topic view is slow, is that there are too many watchers.
Just a fact: for 100 arguments + 100 replies, there are ~7000 watchers. ~2000 of these are created by `cos-disabled` directive. But even replacing it with native `ngDisabled` only halves that amount

For debuging used : https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk

One way to get watchers count down is to hide replies and add show replies link if replies exist

**Comment by ilmartyrk** [comment]
@kevincrepin, need your help. Seems that we need to add pagination to topic arguments, as after trying to optimize it for better performance, it still gets way too slow if argument count gets near 100 or over that

**Comment by kevincrepin** [comment]
@ilmartyrk Something like this?
![screenshot 2019-02-18 at 10 16 27](https://user-images.githubusercontent.com/26792281/52936884-480cf400-3366-11e9-974d-ab32383c0a32.png)

**Comment by kevincrepin** [comment]
I also adjusted the comment box a bit, so it separates better form the thread and the pagination.

**Comment by ilmartyrk** [comment]
Thank you, @kevincrepin, looks really good! Can you please add it to invision too

**Comment by tiblu** [comment]
@kevincrepin @ilmartyrk I gues we should use the same style for the Home page pagination as well? Right now we have "Load more" button there. WDYT?

**Comment by ilmartyrk** [comment]
@tiblu @kevincrepin we probably should as currently there are over 300 public topics in our system and allready at ~120 topics the angular watchers count goes over 2000. I can optimize it, but that just pushes the problem furthers. Also with pagination user can go through past topics and if we add a page query param to the URL, he/she can proceed on the page that was last viewed.

**Comment by ilmartyrk** [comment]
Added pagination and optimized watchers https://github.com/citizenos/citizenos-fe/commit/8e5b4c52ed2e6ff54fe4c0322583068df151cac0
