### ISSUE TITLE
UX: Incorrect placeholder text in search box

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#190]
**Problem:** search box on top of the page (in My Topics view, for example), has the following placeholder text: "Search topics, users, groups..."

**Why is this a problem?** Because it's partially false information. In fact, the search algorithm covers topics and groups, but not users. One can't search for users. 

**Possible solution:** a) just fix the string and remove the word "users". Alternatively, include users in the search algorithm.

![user_search](https://user-images.githubusercontent.com/22661743/52768648-bdab5400-3036-11e9-803b-ef2fc1c6895c.JPG)

**Comment by ilmartyrk** [comment]
Still relevant. @seppviljar this seems like an easy fix

**Comment by seppviljar** [comment]
Should be live already
