### ISSUE TITLE
UX: no error message for expired invite link

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#191]
**Problem:** when user follows an invite link, which has expired (a new invite link has been created by topic admin), then no error message is displayed. User is taken to opening public topics page of app.

**Why is this a problem?** User is confused. They follow a link, but nothing happens. They go check My Topics, but there's nothing there.  They don't know, what the problem is.

**Possible solution:** detect, when an expired link has been followed and create an error message, which basically says, that "The link you followed is no longer valid. Please ask topic administrator for a current link to join the topic."

**Comment by ilmartyrk** [comment]
Still relevant.

**Comment by anettlinno** [comment]
Topic 52. Very important issue, successfully replicated. Applies only for join links. Show user error message as Margo proposed above: "The link you followed is no longer valid. Please ask topic administrator for a current link to join the topic." 
Using generic design.

Est. dev. time 1 hour.

**Comment by anettlinno** [comment]
Tested. Got error message after the link was renewed.
