### ISSUE TITLE
UX: confusing UX when inviting users to join a topic

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#193]
**Problem:** when inviting users to join a topic, there are several different instructions for the user to follow. One says "Click", the other says "Press enter". Some are clickable, others are not. If you start entering text in the input field and at some point press enter, a user is added to the invite list. If you do exactly the same thing, except instead of pressing enter, you try to click the upper "Press enter to add" link with a mouse, the dropdown disappears and nothing happpens. See attached image.

**Why is this a problem?** It's confusing for the user. Not clear, how new users can be invited.

**Possible solution:** unify the experience. Either remove the upper "Press enter to add" text at all. Or then leave them both, unify the text and make both clickable. 

![add_user](https://user-images.githubusercontent.com/22661743/52771993-129f9800-3040-11e9-8ab2-868c45147a65.JPG)

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-fe/commit/85ae1c479a9e37e555da8915669fecd39d6e145f
