### ISSUE TITLE
UX: topic editing toolbar tip texts are unhelpful or confusing (esp. with footnotes button)

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#194]
**Problem:** when editing a topic, a toolbar is displayed. All buttons, when hovering a mouse cursor over them, display a tooltip text. But in some cases, the tooltip text just says "Toolbar (Alt F9)". 

**Why is this a problem?** This is very confusing in case of footnotes, for example. The button "FN" is not self-explanatory. Clicking it opens an unlabeled dialog box. And the tooltip just says "Toolbar". Very hard to understand, what the button is for. Look at the attached gif screen recording.

**Possible solution:** a) assign correct tooltip texts to buttons and b) add some explanatory placeholder or title information to the footnote dialog box. Also, consider not making topic text disappear, when entering footnotes.

![20190214_101910](https://user-images.githubusercontent.com/22661743/52773116-dc174c80-3042-11e9-92bd-45d96eec5157.gif)

**Comment by ilmartyrk** [comment]
Closing as this has been fixed
