### ISSUE TITLE
UX: missing max file size information in error message dialog when uploading photos

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#195]
**Problem:** when trying to insert files larger than 5(?) MB, topic window displays an error message in a dialog, that says the file is too large.  It does not say, however, what is the max file size.

**Why is this a problem?** User does not know, how much does the image need to be optimized to be able to insert it. Must make several attempts. Frustrating.

**Possible solution:** just include max file size information in the error message dialog.

![too large](https://user-images.githubusercontent.com/22661743/52773627-23520d00-3044-11e9-9c4e-74aa11c664c2.jpg)

**Comment by ilmartyrk** [comment]
Still relevant

**Comment by ilmartyrk** [comment]
Related to https://github.com/citizenos/ep_image_upload/issues/59

**Comment by ilmartyrk** [comment]
Will need to update the translation string to include max file size inside the message, also should be solved together with citizenos/ep_image_upload#59, estimated dev time 1h

**Comment by anettlinno** [comment]
Triage 53. Est. dev. time 1 hour. Sending to development.

**Comment by ilmartyrk** [comment]
FIXED with https://github.com/citizenos/ep_image_upload/commit/fff92727e7609001bd07af3668c1f3cdc1aedc9a

**Comment by anettlinno** [comment]
Tested. Error message appears. BUT before the picture is uploaded, the User will see the image below: 

<img width="940" alt="Broken" src="https://user-images.githubusercontent.com/45175679/154684459-18eed083-e81c-4671-8024-c18d76ecc9d4.png">

It looks like something is broken @ilmartyrk
