### ISSUE TITLE
UX: inconsistent terminology in topic timeline review

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#196]
**Problem:** use of terms in Etherpad Lite does not conform to terminology in Citizen OS. See image.

**Why is this a problem?** User is confused and does not know the meaning of the button(s).

**Possible solution:** unify use of terms in EP Lite and COS. Decapitalise name of month in Estonian. Add full stop behind the number of date etc.

And ... what's a "klade", anyway? :)
![kladele](https://user-images.githubusercontent.com/22661743/52774071-2b5e7c80-3045-11e9-9d2b-43ca6fcffd55.jpg)

**Comment by ilmartyrk** [comment]
Still relevant

**Comment by ilmartyrk** [comment]
This seems to be a bug related to ep_translations plugin. We have updated translations inside etherpad_translations project, but seems that they are not overriding the original translations in timeline view.

**Comment by anettlinno** [comment]
Triage 53. Est. dev. time 6 hours. Sending to development.

**Comment by ilmartyrk** [comment]
Fixed with https://github.com/citizenos/ep_translations/commit/1af6b1562b5f480c2f0daa78c844704ecd7fec50, translations were loaded separately in timeline view, added the functionality to there too
