### ISSUE TITLE
FEATURE: opportunity to hyperlink word(s) inside the text

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#200]
**Problem**: Inside the topic text it is currently not possible to hyperlink words. Links has to be copied inside the text. When highlighting the word(s), we can leave comment, but missing the hyperlinking word(s) opportunity.

**Why is it a problem**: Texts with copied URL-s are getting long and visually messy. 

**Possible solution**: To add hyperlink opportunity on the Tool Bar.

**Comment by ilmartyrk** [comment]
Closing as it is a duplicate of https://github.com/citizenos/citizenos-fe/issues/110
