### ISSUE TITLE
UX: "Press enter to add" clickable 

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#201]
**Problem**: When inserting people to group or inviting them to join the topic (settings - invite), then "Press enter to add" could be clickable. 

**Why is it a problem**: User experience show that people want to click on "Press enter to add" to insert people

**Comment by ilmartyrk** [comment]
@anettlinno this link acutally is clickable, could you add some data what happened, when it didn't work etc.

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-fe/commit/85ae1c479a9e37e555da8915669fecd39d6e145f Seems same issue as https://github.com/citizenos/citizenos-fe/issues/193
