### ISSUE TITLE
BUG?: Vote results not hidden during voting to owner of topic

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#202]
As the owner of the topic, I can see the current vote results. Not what individuals have voted for, but how many votes per choice. Is this a bug? 

The screenshot is taken before the voting deadline, I could also see the results yesterday.
![screenshot 2019-02-27 at 13 13 42](https://user-images.githubusercontent.com/34899902/53486683-1399e600-3a92-11e9-9d3a-8c6ffb8aaab2.png)

**Comment by oksks** [comment]
Certainly a bug IMHO, as the topic admin can go and tinker with the results by making sure your preferred option gets the most votes by the deadline - even 1 vote matters, so it's a huge deal.

**Comment by ilmartyrk** [comment]
Closing as this is fixed
