### ISSUE TITLE
BUG: Etherpad - crash - "Max call stack size exceeded"

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#205]
**Overview**

Etherpad crashes:
```
05 Mar 2019 12:36:27.808331 <158>1 2019-03-05T12:36:27.016318+00:00 host heroku router - at=info method=POST path="/socket.io/?EIO=3&transport=polling&t=MbDslAQ&sid=tSQWVCFdBR6x6YdHAAAs" host=p.citizenos.com request_id=9d311d0e-1ce1-4ba8-a1a0-83ef83a60cd6 fwd="xxxxxxxx" dyno=web.1 connect=0ms service=3ms status=200 bytes=270 protocol=https
05 Mar 2019 12:36:28.208139 <190>1 2019-03-05T12:36:27.657191+00:00 host app web.1 - [32m[2019-03-05 12:36:27.656] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:28.757139 <190>1 2019-03-05T12:36:28.435269+00:00 host app web.1 - [32m[2019-03-05 12:36:28.435] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:30.003139 <190>1 2019-03-05T12:36:29.352567+00:00 host app web.1 - [32m[2019-03-05 12:36:29.352] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:30.523139 <190>1 2019-03-05T12:36:30.205955+00:00 host app web.1 - [32m[2019-03-05 12:36:30.205] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:31.551139 <190>1 2019-03-05T12:36:30.894610+00:00 host app web.1 - [32m[2019-03-05 12:36:30.894] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:32.245139 <190>1 2019-03-05T12:36:31.616000+00:00 host app web.1 - [32m[2019-03-05 12:36:31.615] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:32.955139 <190>1 2019-03-05T12:36:32.320587+00:00 host app web.1 - [32m[2019-03-05 12:36:32.320] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:33.641139 <190>1 2019-03-05T12:36:33.008015+00:00 host app web.1 - [32m[2019-03-05 12:36:33.007] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:34.412139 <190>1 2019-03-05T12:36:33.729780+00:00 host app web.1 - [32m[2019-03-05 12:36:33.729] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:35.079139 <190>1 2019-03-05T12:36:34.444641+00:00 host app web.1 - [32m[2019-03-05 12:36:34.444] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:35.470139 <190>1 2019-03-05T12:36:35.149351+00:00 host app web.1 - [32m[2019-03-05 12:36:35.149] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:36.481139 <190>1 2019-03-05T12:36:35.841832+00:00 host app web.1 - [32m[2019-03-05 12:36:35.841] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:37.195139 <190>1 2019-03-05T12:36:36.554081+00:00 host app web.1 - [32m[2019-03-05 12:36:36.553] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:37.985139 <190>1 2019-03-05T12:36:37.305757+00:00 host app web.1 - [32m[2019-03-05 12:36:37.305] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:38.688139 <190>1 2019-03-05T12:36:38.021917+00:00 host app web.1 - [32m[2019-03-05 12:36:38.021] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:39.118139 <190>1 2019-03-05T12:36:38.800006+00:00 host app web.1 - [32m[2019-03-05 12:36:38.799] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:39.859139 <190>1 2019-03-05T12:36:39.535145+00:00 host app web.1 - [32m[2019-03-05 12:36:39.534] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:40.984139 <190>1 2019-03-05T12:36:40.333263+00:00 host app web.1 - [32m[2019-03-05 12:36:40.332] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:41.818139 <190>1 2019-03-05T12:36:41.162873+00:00 host app web.1 - [32m[2019-03-05 12:36:41.162] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:42.716139 <190>1 2019-03-05T12:36:42.057165+00:00 host app web.1 - [32m[2019-03-05 12:36:42.057] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:43.595139 <190>1 2019-03-05T12:36:42.913444+00:00 host app web.1 - [32m[2019-03-05 12:36:42.913] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:44.476139 <190>1 2019-03-05T12:36:43.814277+00:00 host app web.1 - [32m[2019-03-05 12:36:43.814] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:45.394139 <190>1 2019-03-05T12:36:44.733391+00:00 host app web.1 - [32m[2019-03-05 12:36:44.733] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:46.128139 <190>1 2019-03-05T12:36:45.467294+00:00 host app web.1 - [32m[2019-03-05 12:36:45.467] [INFO] ueberDB - [39mgarbage collected 500 values
05 Mar 2019 12:36:47.276133 <190>1 2019-03-05T12:36:46.820238+00:00 host app web.1 - [32m[2019-03-05 12:36:46.820] [INFO] console - [39mdb sucessfully closed.
05 Mar 2019 12:36:47.317156 <190>1 2019-03-05T12:36:46.566256+00:00 host app web.1 - [31m[2019-03-05 12:36:46.566] [ERROR] console - [39mRangeError: Maximum call stack size exceeded
05 Mar 2019 12:36:47.33292 <134>1 2019-03-05T12:36:46.891112+00:00 host heroku web.1 - State changed from up to crashed
05 Mar 2019 12:36:47.346327 <158>1 2019-03-05T12:36:46.835277+00:00 host heroku router - at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=a3Zhd8MTfwtVk1x-AAAr" host=p.citizenos.com request_id=f022c1f6-ed5b-46ad-ba4a-aad397da6ebc fwd="xxxxxxxx" dyno=web.1 connect=1ms service=380892ms status=101 bytes=175 protocol=https
05 Mar 2019 12:36:47.39388 <190>1 2019-03-05T12:36:46.566267+00:00 host app web.1 - at Array.toString (native)
05 Mar 2019 12:36:47.393146 <190>1 2019-03-05T12:36:46.566269+00:00 host app web.1 - at AttributePool.putAttrib (/app/etherpad-lite/src/static/js/AttributePool.js:38:13)
05 Mar 2019 12:36:47.393118 <190>1 2019-03-05T12:36:46.566270+00:00 host app web.1 - at /app/etherpad-lite/src/static/js/Changeset.js:1530:26
05 Mar 2019 12:36:47.39397 <190>1 2019-03-05T12:36:46.566272+00:00 host app web.1 - at RegExp.[Symbol.replace] (native)
05 Mar 2019 12:36:47.39397 <190>1 2019-03-05T12:36:46.566273+00:00 host app web.1 - at RegExp.[Symbol.replace] (native)
05 Mar 2019 12:36:47.39388 <190>1 2019-03-05T12:36:46.566275+00:00 host app web.1 - at String.replace (native)
05 Mar 2019 12:36:47.393152 <190>1 2019-03-05T12:36:46.566276+00:00 host app web.1 - at Object.exports.moveOpsToNewPool (/app/etherpad-lite/src/static/js/Changeset.js:1526:21)
05 Mar 2019 12:36:47.393150 <190>1 2019-03-05T12:36:46.566277+00:00 host app web.1 - at Object.exports.prepareForWire (/app/etherpad-lite/src/static/js/Changeset.js:1693:23)
05 Mar 2019 12:36:47.393129 <190>1 2019-03-05T12:36:46.566279+00:00 host app web.1 - at /app/etherpad-lite/src/node/handler/PadMessageHandler.js:1240:37
05 Mar 2019 12:36:47.393136 <190>1 2019-03-05T12:36:46.566280+00:00 host app web.1 - at iterate (/app/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
05 Mar 2019 12:36:47.393126 <190>1 2019-03-05T12:36:46.566282+00:00 host app web.1 - at /app/etherpad-lite/src/node_modules/async/lib/async.js:160:25
05 Mar 2019 12:36:47.393129 <190>1 2019-03-05T12:36:46.566283+00:00 host app web.1 - at /app/etherpad-lite/src/node/handler/PadMessageHandler.js:1251:13
05 Mar 2019 12:36:47.393136 <190>1 2019-03-05T12:36:46.566285+00:00 host app web.1 - at iterate (/app/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
05 Mar 2019 12:36:47.393126 <190>1 2019-03-05T12:36:46.566286+00:00 host app web.1 - at /app/etherpad-lite/src/node_modules/async/lib/async.js:160:25
05 Mar 2019 12:36:47.393129 <190>1 2019-03-05T12:36:46.566287+00:00 host app web.1 - at /app/etherpad-lite/src/node/handler/PadMessageHandler.js:1251:13
05 Mar 2019 12:36:47.393136 <190>1 2019-03-05T12:36:46.566289+00:00 host app web.1 - at iterate (/app/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
05 Mar 2019 12:36:47.393131 <190>1 2019-03-05T12:36:46.566378+00:00 host app web.1 - [32m[2019-03-05 12:36:46.566] [INFO] console - [39mgraceful shutdown...
05 Mar 2019 12:36:47.41598 <134>1 2019-03-05T12:36:46.978969+00:00 host heroku web.1 - State changed from crashed to starting
05 Mar 2019 12:36:47.52088 <45>1 2019-03-05T12:36:46.874984+00:00 host heroku web.1 - Process exited with status 0
```

**Comment by tiblu** [comment]
Might be related to:

* https://github.com/ether/etherpad-lite/issues/3430
* https://github.com/ether/etherpad-lite/issues/1889 - increased stack_size
* https://github.com/ether/etherpad-lite/issues/1567 - traces the issue to message spam by the server
* https://github.com/ether/etherpad-lite/issues/800 - traces the issue to message spam by the server
* https://github.com/ether/etherpad-lite/issues/1567 - traces the issue to message spam by the server

**Comment by ilmartyrk** [comment]
Some notes: `https://github.com/citizenos/etherpad-lite/blob/master/src/static/js/pad.js#L279` - if server is under load eg. one large pad is polling with timeline revision requests. There is a race conditions here. If now a new pad connects to server or switches between timeline/edit views pad.collabClient might not be set when code reaches  `https://github.com/citizenos/etherpad-lite/blob/master/src/static/js/pad.js#L213`

**Comment by ilmartyrk** [comment]
`https://github.com/citizenos/etherpad-lite/blob/master/src/node/handler/PadMessageHandler.js#L1226` Here is the part of code that caused _"Max call stack size exceeded"_ Error. What happens is that there must be at least two users connected to same pad. While one pad is inactive and for some reason not syncing eg. offline or slow internet connection. Other pad is generating new revisions. And when at one point inactive pad manages to connect to server the `revisionsNeeded` value might be so big that it falls into _"Max call stack size exceeded". `--stack_size (default size of stack region v8 is allowed to use (in kBytes))
      type: int  default: 984`

This is hard to replicate, but one way to try is open a pad in edit mode, switch tabs, open another editor, add images in `base64` or copy paste large chunks of data. Also decreasing node call stack size using `--stack_size=` could help

**Comment by ilmartyrk** [comment]
Timeline crashes when there is large number of revisions. It happens https://github.com/citizenos/etherpad-lite/blob/master/src/static/js/Changeset.js#L602 and error happens when `lines` doesn't have value on position `idx` and so function returns _`undefined`_. So that causes error in here https://github.com/citizenos/etherpad-lite/blob/master/src/static/js/Changeset.js#L1945 for trying to get `substring` of _`undefined`_

**Comment by sid-comunicacio** [comment]
Hi Ilmar, we have similar problems with etherpad crashing randomly when some user that wasn't in one big/large pad connects.

[2019-03-07 08:51:24.822] [INFO] access - [ENTER] Pad "AL_DIA_2019": Client L0Lhk58aZe8qtUERAACu with IP "XXX.XXX.XXX.XXX" entered the pad
[2019-03-07 08:51:24.828] [INFO] ueberDB - Flushed 1 values
[2019-03-07 08:51:24.992] [ERROR] console - RangeError: Maximum call stack size exceeded
    at exports.database.get (/home/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:137:42)
    at exports.database.getSub (/home/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:350:8)
    at exports.channels.doOperation [as operatorFunction] (/home/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:143:18)
    at exports.channels.emit (/home/etherpad-lite/src/node_modules/channels/channels.js:49:11)
    at exports.database.getSub (/home/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:82:17)
    at Pad.getRevisionDate (/home/etherpad-lite/src/node/db/Pad.js:147:6)
    at /home/etherpad-lite/src/node/handler/PadMessageHandler.js:1213:19
    at iterate (/home/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at /home/etherpad-lite/src/node_modules/async/lib/async.js:160:25
    at Object.callback (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:1217:17)
    at /home/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:149:17
    at /home/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:378:7
    at exports.database.get (/home/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:144:5)
    at exports.database.getSub (/home/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:350:8)
    at exports.channels.doOperation [as operatorFunction] (/home/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:143:18)
    at exports.channels.emit (/home/etherpad-lite/src/node_modules/channels/channels.js:49:11)
    at exports.database.getSub (/home/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:82:17)
    at Pad.getRevisionDate (/home/etherpad-lite/src/node/db/Pad.js:147:6)
    at /home/etherpad-lite/src/node/handler/PadMessageHandler.js:1213:19
    at iterate (/home/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at /home/etherpad-lite/src/node_modules/async/lib/async.js:160:25
    at Object.callback (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:1217:17)
[2019-03-07 08:51:24.995] [INFO] console - graceful shutdown...

[2019-03-14 11:09:39.456] [INFO] access - [ENTER] Pad "AL_DIA_2019": Client Mkxup370_FfUTkvIAABf with IP "XXX.XXX.XXX.XXX" entered the pad
[2019-03-14 11:09:39.471] [INFO] ueberDB - Flushed 1 values
[2019-03-14 11:09:39.579] [ERROR] console - RangeError: Maximum call stack size exceeded
    at exports.database.get (/home/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:142:56)
    at exports.database.getSub (/home/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:350:8)
    at exports.channels.doOperation [as operatorFunction] (/home/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:143:18)
    at exports.channels.emit (/home/etherpad-lite/src/node_modules/channels/channels.js:49:11)
    at exports.database.getSub (/home/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:82:17)
    at Pad.getRevisionAuthor (/home/etherpad-lite/src/node/db/Pad.js:143:6)
    at /home/etherpad-lite/src/node/handler/PadMessageHandler.js:1200:19
    at iterate (/home/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at /home/etherpad-lite/src/node_modules/async/lib/async.js:160:25
    at Object.callback (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:1204:17)

[2019-03-14 15:04:11.866] [INFO] access - [ENTER] Pad "AL_DIA_2019": Client lgV9tDJsBv5fris5AAAK with IP "XXX.XXX.XXX.XXX" entered the pad
[2019-03-14 15:04:11.896] [ERROR] console - RangeError: Maximum call stack size exceeded
    at iterate (/home/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/home/etherpad-lite/src/node_modules/async/lib/async.js:165:9)
    at /home/etherpad-lite/src/node/handler/PadMessageHandler.js:1198:19
    at /home/etherpad-lite/src/node_modules/async/lib/async.js:610:21
    at /home/etherpad-lite/src/node_modules/async/lib/async.js:249:17
    at iterate (/home/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at /home/etherpad-lite/src/node_modules/async/lib/async.js:160:25
    at /home/etherpad-lite/src/node_modules/async/lib/async.js:251:21
    at /home/etherpad-lite/src/node_modules/async/lib/async.js:615:34
    at /home/etherpad-lite/src/node_modules/async/lib/async.js:157:25
[2019-03-14 15:04:11.896] [INFO] console - graceful shutdown...

I hope it helps.

Miguel.

**Comment by ilmartyrk** [comment]
@sid-comunicacio thank you. Every piece of information helps and you are very kind to share all this data with us. I'll try to fix this issue as soon and fast as possible.

**Comment by tiblu** [comment]
Good reading/watching on event loop:

- https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/
- https://www.youtube.com/watch?v=P9csgxBgaZ8&list=PL_lVOJzXeE_8qUxxJBKZ4OXuw7QKvtvJe&index=2
- https://www.youtube.com/watch?v=8aGhZQkoFbQ
- https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/
- https://snyk.io/blog/nodejs-how-even-quick-async-functions-can-block-the-event-loop-starve-io/

![image](https://user-images.githubusercontent.com/7405383/55411550-81906c00-556e-11e9-8403-aef0aefdb769.png)

**Comment by tiblu** [comment]
### Some findings

- Calls to `getHTML` (https://etherpad.org/doc/v1.7.5/#index_gethtml_padid_rev) **block the whole Node.JS event loop** until finished. It's probably because `getLineHTMLForExport` hooks are called in a loop with `setImmediate` and it won't let the event loop continue until drained.
    - Proof:
    ```
    for i in {1..10000}; do echo date & curl -i -k 'https://dev.p.citizenos.com:9001/api/1/getListAllPads?apikey=APIKEY&padID=33b57bda-87b8-44a4-ab9d-32e0d26955c5' | head -n 1; sleep 1; done
    curl -i -k 'https://dev.p.citizenos.com:9001/api/1/getHTML?apikey=APIKEY&padID=33b57bda-87b8-44a4-ab9d-32e0d26955c5'
    ```
    If you run these at the same time, you can see that the calls to `getListAllPads` will start timing out as soon as `getHTML` is executed.
- Citizen OS implements sync between Etherpad and Citizen OS database by calling the `getHTML` (https://etherpad.org/doc/v1.7.5/#index_gethtml_padid_rev) and this will end up calling `getLineHTMLForExport` hooks once per line in the document. So for example we have 8 plugins that use that hook, we have 1000 lines in a document will mount to 8000 hook calls per sync. The hooks are all deferred to **check** phase by `hooks.js` `aCallAll` functions `async.map` by calling `setImmediate` in the guts. The **check** phase will not complete until the `setImmediate` "queue" is empty. STUCK.
- In general the need to see if `hooks.js` `aCallAll` implementation  is flawed or the fact that the hooks are not implemented as async is to blame.
- All and all, the matter of the fact is, the HTML export is expensive, we need to figure out to make it cheaper to make EP perform.

**NOTE:**  This is most likely not the cause of the MAX CALL STACK, but just a finding that needs to be fixed before we proceed.

**Comment by ilmartyrk** [comment]
@sid-comunicacio do you have any plugins installed? Could you possibly add a list of them?

**Comment by tiblu** [comment]
https://github.com/ether/etherpad-lite/issues/3589

**Comment by sid-comunicacio** [comment]
Hi two you.
Yes we have a lot of plugins. List:

adminpads 	Gives the ability to list and administrate all pads on admin page 	0.0.12 	
align 	Add Left/Center/Right/Justify to lines of text in a pad 	0.0.24 	
autocomp 	autocompletion 	0.0.2 	
button_link 	Adds a button to the toolbar that links out to a new window 	0.0.8 	
clear_formatting 	Clear formatting on a selection, this plugin requires the file menu 	0.0.2 	
comments_page 	Adds comments on sidebar and link it to the text. Support for Page View, requires ep_page_view 	0.0.35 	
copy_paste_select_all 	Add support to do Copy, Paste, Select All and Find and Replace, this plugin requires the file menu 	0.0.4 	
delete_empty_pads 	Delete pads which were never edited 	0.0.4 	
desktop_notifications 	Recieve chat desktop notifications 	0.0.9 	
embedmedia 	Embed media (youtube, vimeo etc) 	0.0.4 	
fileupload 	File upload 	0.0.10 	
font_color 	Apply colors to fonts 	0.0.11 	
font_family 	Add support for different Fonts 	0.2.7 	
font_size 	Add support for Font Sizes 	0.1.11 	
headings2 	Adds heading support to Etherpad Lite. Includes improved suppot for export, i18n etc. 	0.0.9 	
historicalsearch 	Search through the history of documents to find when a query/search pattern or string existed 	0.0.8 	
horizontal_line 	Horizontal line 	0.0.4 	
infopanel 	Displays an info section in pad settings exposing the software used and the current git revision. 	0.1.2 	
ldapauth 	Hooks into etherpad lite auth to provide LDAP authentication. 	0.3.0 	
line_height 	Change the line height 	0.0.4 	
list_pads 	List Pads on the Index Page 	0.0.4 	
offline_edit 	View your pad data even if you are disconnected from the Internets 	0.0.8 	
page_view 	Add support to do 'page view', with a toggle on/off option in Settings, also Page Breaks with Control Enter 	0.5.24 	
previewimages 	Image previewer, paste the URL of an image or upload an image using ep_fileupload 	0.0.9 	
small_list 	Adds a list of all pads on the index-page 	0.2.0 	
special_characters 	Insert special characters into a pad 	0.0.6 	
spellcheck 	Add support to do 'Spell checking', with a toggle on/off option in Settings 	0.0.3 	
subscript_and_superscript 	Add support for Subscript and Superscript 	0.0.3 	
table_of_contents 	View a table of contents for your pad 	0.1.15 	
tables2 	Adds tables to etherpad-lite 	0.3.0 	
timestamp 	Add a button for inserting timestamps 	0.1.4 	
xmlexport 	XML Export for Etherpad Lite 	2.1.6

And we use HUGE pads.

**Comment by tiblu** [comment]
@sid-comunicacio Thanks a lot for your input, that's a lot of plugins!

Further questions:

- What version of Etherpad are you using?
- What version of Node.JS are you running?
- Is the Etherpad app public? Can we use it as clients? 
- How huge are the pads? I guess character and line counts are sufficient.
- How many users are usually editing the same pad? Is it more like 1 or 10?
- How manu users are there overall - that is, concurrent pads open and users working on them?
- How often do you get the "MAX CALL STACK" error?

We need this info to correlate with what we are experiencing, based on this info we can try to create a test case to reliably replicate the issue. Right now, we have some hints of why this happens, but we need solid proof. To create a fix, we need a test case to replicate the error first and then the same test case will verify the fix.

**Comment by sid-comunicacio** [comment]
Yes, we know. It's possible some of them aren't necessary.

Etherpad Version: 1.7.0
NodeJs Version: 8.11.2   (until now) Now:  10.15.2
Is Etherpad app public ? No. Can we use it as clients ?  No, sorry.
How huge are the pads ? Nowadays it's like 1200 lines, 25.000 words, 150.000 characters, but we renew the pads when they grow and starts to crash. It's a binnacle. (Could be bigger, Timeslider: 
**Version 70537** Saved April 4, 2019 )
How  many users editing the same pad? Max: 7 users.
Concurrent pads: -+15.   Concurrent opened pads: 3.  Users working together at the same time in this opened pads: -+4.
How often do you get the "MAX CALL STACK" error? :  Randomly... it happens when some "sleep" user reenter to the pad.

Hope it helps.

**Comment by tiblu** [comment]
@sid-comunicacio Thanks for the detailed response, we'll look into it and figure out how to reproduce it.

**Comment by tiblu** [comment]
@sid-comunicacio 

First of all, we have not been able to reproduce the issue in our development environments. If we cannot reproduce it, we don't have a way to test if any of our changes make it better or worse.
Code review shows that there are places with big loops which can use a lot of stack in normal conditions (without infinite loop), specially in case of documents that have a lot of revisions. So, depending of the use cases, users at some point may hit the issue.

### Suggestion: Increase Node.JS stack size

Have you tried increasing the maximum stack size that can be used by Node.JS?

To do so, you have to add V8 option `--stack_size (default size of stack region v8 is allowed to use (in kBytes))` when starting Node.JS. ~1000 should be the default, so 2000 is double. You can check it from the `--v8-options`. To have a look at the full list of V8 options you can run `node --v8-options`.

For example: `node --stack_size=2000 ./etherpad-lite/node_modules/ep_etherpad-lite/node/server.js`. 

**NOTE:** If you run Etherpad with any of the `/bin/*.sh` scripts, you have to implement their functionality before you run `server.js`. The `run.sh` for example installs dependencies etc.

### Logic behind increasing the stack size

- IF the issue is caused by infinite loop, no matter how high you set the stack size, it will still appear. Then we know that it's an infinite loop issue and can check the code for possible infinite loop sources.
- IF the issue is fixed OR does not appear as often, we know that it's an issue with the code where at times a lot of stack is used even without infinite loop.

Please let us know if you have any questions or feedback. We would love to know how the server behaves with bigger stack size limit.

**Comment by tiblu** [comment]
### How to create big Pads for testing?

Etherpad comes with a testing system both for frontend and backend. Have a look - https://github.com/ether/etherpad-lite/tree/develop/tests

We use the frontend testing.

- To generate Pad with a lot of revisions:
```javascript
//  create_pad.js

describe("create big pad", function () {

    beforeEach(function (cb) {
        helper.newPad(cb);
        this.timeout(600000);
    });
    it("inserts characters", function (done) {
        var inner$ = helper.padInner$;

        var revCount = 1500;
        var i = 0;

        var addLine = function () {
            setTimeout(function () {
                var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

                //get the first text element out of the inner iframe
                var $firstTextElement = inner$("div").first();
                var letter = possible.charAt(Math.floor(Math.random() * possible.length));
                $firstTextElement.sendkeys(letter + 'xxx');
                $firstTextElement.sendkeys('{enter}');

                if (i < revCount) {
                    addLine();
                    i++;
                } else {
                    done();
                }
            }, 500); // FIXME: We could do faster if we react to the ACCEPT_COMMIT message or other callback that indicates that EP is ready to accept new revision
        };
        addLine();
        this.timeout(600000);
    });
});
```

**Comment by sid-comunicacio** [comment]
Hi, we are  testing our scenario with "--stack_size=2000".   We will report about success changes in 1 month since now. Today, we take a work break for 10 days.

OFFTOPIC: We don't know if it's a common situation that after  "stopping"  etherpad via systemclt in debian, some PADs got corrupted... and it's not possible to repair through  "npm  bin/repairPad.js 'Name_of_the_pad'".  :-/

Thanks.

> @sid-comunicacio
> 
> First of all, we have not been able to reproduce the issue in our development environments. If we cannot reproduce it, we don't have a way to test if any of our changes make it better or worse.
> Code review shows that there are places with big loops which can use a lot of stack in normal conditions (without infinite loop), specially in case of documents that have a lot of revisions. So, depending of the use cases, users at some point may hit the issue.
> ### Suggestion: Increase Node.JS stack size
> 
> Have you tried increasing the maximum stack size that can be used by Node.JS?
> 
> To do so, you have to add V8 option `--stack_size (default size of stack region v8 is allowed to use (in kBytes))` when starting Node.JS. ~1000 should be the default, so 2000 is double. You can check it from the `--v8-options`. To have a look at the full list of V8 options you can run `node --v8-options`.
> 
> For example: `node --stack_size=2000 ./etherpad-lite/node_modules/ep_etherpad-lite/node/server.js`.
> 
> **NOTE:** If you run Etherpad with any of the `/bin/*.sh` scripts, you have to implement their functionality before you run `server.js`. The `run.sh` for example installs dependencies etc.
> ### Logic behind increasing the stack size
> 
>     * IF the issue is caused by infinite loop, no matter how high you set the stack size, it will still appear. Then we know that it's an infinite loop issue and can check the code for possible infinite loop sources.
> 
>     * IF the issue is fixed OR does not appear as often, we know that it's an issue with the code where at times a lot of stack is used even without infinite loop.
> 
> 
> Please let us know if you have any questions or feedback. We would love to know how the server behaves with bigger stack size limit.

**Comment by sid-comunicacio** [comment]
Thanks for the code. We will use it.

> ```js
> //  create_pad.js
> 
> describe("create big pad", function () {
> 
>     beforeEach(function (cb) {
>         helper.newPad(cb);
>         this.timeout(600000);
>     });
>     it("inserts characters", function (done) {
>         var inner$ = helper.padInner$;
> 
>         var revCount = 1500;
>         var i = 0;
> 
>         var addLine = function () {
>             setTimeout(function () {
>                 var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
> 
>                 //get the first text element out of the inner iframe
>                 var $firstTextElement = inner$("div").first();
>                 var letter = possible.charAt(Math.floor(Math.random() * possible.length));
>                 $firstTextElement.sendkeys(letter + 'xxx');
>                 $firstTextElement.sendkeys('{enter}');
> 
>                 if (i < revCount) {
>                     addLine();
>                     i++;
>                 } else {
>                     done();
>                 }
>             }, 500); // FIXME: We could do faster if we react to the ACCEPT_COMMIT message or other callback that indicates that EP is ready to accept new revision
>         };
>         addLine();
>         this.timeout(600000);
>     });
> });
> ```

**Comment by tiblu** [comment]
We've put fair amount of time into this and are fair amount smarter on how JS and Etherpad work.
BUT, we don't have the issues in our live environment, so we will close this issue for now and move on to next tasks in current "sprint" (https://github.com/orgs/citizenos/projects/4).
Feel free to report back and reopen if need be, we sure are interested in contributing to the Etherpad project.

**Comment by tiblu** [comment]
@sid-comunicacio Hi! Any news on the "Max call stack" issue? How's it holding on after the suggested changes?

> OFFTOPIC: We don't know if it's a common situation that after "stopping" etherpad via systemclt in debian, some PADs got corrupted... and it's not possible to repair through "npm bin/repairPad.js 'Name_of_the_pad'". :-/

Sorry, I don't have experience with that.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
