### ISSUE TITLE
ETHERPAD: Features to add to the  Etherpad text editor

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#206]
**Overview**

Proposal of new features to add to the editor so that the quality of the documents is better and it's more enjoyable to work with the documents.

**FEEL FREE TO ADD YOUR IDEAS IN THE COMMENTS!**

**TODO**

- [ ] Text highlight/background color - good to mark out some sections of text. Right now you can use inline comment to mark out a section. 
- [ ] Linking to a another section of the text - it would be nice to create links in text that reference another part of the text in the same document. 
     - When link is clicked, it scrolls the document to the part of the text.
     - When the link is hovered AND we have room on the screen, show preview of the text.

**Comment by ilmartyrk** [comment]
@anettlinno @kevincrepin this should probably be considered in UI/UX refresh or be closed and separated into different issues or project

**Comment by kevincrepin** [comment]
hmmm I like the anchors quite a lot. Could maybe be fleshed out more to give users the opportunity to work with a sort of table of contents...

So basically we'll keep in mind that we can actually do a lot and let's discuss during that time then what seems feasible.

**Comment by anettlinno** [comment]
Triage 55. @kevincrepin these could be considered with UX/UI redesign project. 
Text highlight is supported by EP. 
Table of content is supported by EP.
Inserting tables is one of the features that we miss and is supported by EP.
Spell check is supported by EP (browser languages). 

There are quite a lot of plugins that are supported by EP but we should go with only what we need :)

**Comment by ilmartyrk** [comment]
List of plugins that should be the most safest to use as they are maintained by the Etherpads own organization https://github.com/orgs/ether/repositories

**Comment by ilmartyrk** [comment]
#Triage 84. Closing this issue as we are dropping Etherpad in our UX/UI re-design
