### ISSUE TITLE
ETHERPAD: Inline comments - UI freezes for a while trying to open an inline comment

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#207]
**Overview**

When cursor moves over an area with inline comment, the UI freezes - scroll does not work, clicking in the document does not work.

**TODO**

- [ ] Fix the lag of opening the inline comment. User should be able to click and edit any parts of the document while opening of the inline comment is in progress.
    - Example doc: https://app.citizenos.com/en/topics/ac8b66a4-ca56-4d02-8406-5e19da73d7ce - need edit mode to reproduce.
- [ ] Usability proposal - do not open inline comment on "hover", only on click on the area OR clicking on the comment indicator. 
    - The hover is very annoying when scrolling through a document and cursor accidentally hovers over a comment, thus opening it and covering the content I'm trying to read/scroll through.

**Comment by ilmartyrk** [comment]
Could not reproduce, also many changes have been added to the EP core and plugin. So closing this issue,
