### ISSUE TITLE
Topic should indicate if it's public or private, when opened

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#209]
When you click open the (yours or someone else's) topic, you won't know if it's public or private until you've figured out you can find this under Settings.

Ask: Please display an open/closed padlock prominently next to the topic name (or where appropriate), to indicate whether it's public or private.

**Comment by loorm** [comment]
Duplicate of issue #226

**Comment by kevincrepin** [comment]
Want to tackle a couple other visibility issues with this, namely favourited and (soon) reported (besides the initial overlay): https://projects.invisionapp.com/d/main#/console/17224475/362196834/preview

In case the topic is neither favourited nor reported and public: https://projects.invisionapp.com/d/main#/console/17224475/362199376/preview
