### ISSUE TITLE
ETHERPAD: Inline voting

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#212]
Add inline-voting (mini-voting) feature to etherpad.
TODO:
- [x] Vote setup, vote description text, selected text as vote option, up to 5 options, checkbox if vote result replaces selected text.
- [x] Close voting when topic status changes
- [x] Display current vote results
- [ ] Send users notifications about new mini-vote
- [x] ~~Determine if user is admin or editor, enable admins to create/close mini-vote~~
- [x] Get and add designs from @kevincrepin
- [x] Display voters count as how many people with permissions have voted and how many total voters there are
- [x] Fix popup placement
- [x] Add translation keys

**Comment by ilmartyrk** [comment]
@kevincrepin Could you have a look? If you need it, I can send user story in slack

**Comment by kevincrepin** [comment]
Added suggestions here: https://projects.invisionapp.com/d/main#/console/9829159/361927550/preview

I also updated the inline commenting designs to include the X to close which the inline voting module has as well...

**Comment by ilmartyrk** [comment]
There is a question on the table, how should plugin behave if topic status is changed. As topic doesn't have any statuses inside Etherpad, current solution is to send to request from API to Etherpad to change all inline vote statuses to closed. Now if vote is closed from API side there is a question if these results should be added to document or not? So I am adding some possible solutions here:

- Votes are closed and results are dropped - No changes to topic content, results are basically trashed
- Votes should be added to document automatically - Needs lot of work to add changes from server side. Also possible that some votes have only 1 or two voters and results would be too biased.
- Block changing topic status if there are inline votes open and make admin/editor close all open inline votes. This will add all vote results to topic content (if vote is set to replace content voted on). And adds chance to close/remove votes that don't have enough voters etc.

**Comment by loorm** [comment]
I'm thinking 3rd option ("Block changing topic status ...").

This most closely corresponds to what you would do in an offline discussion setting. You can't start voting on the final document, if there are still ongoing discussions about wording specific paragraphs.

Also, this avoids the downsides of both the other solutions (losing work already done or bringing biased results into a document).

**Comment by kevincrepin** [comment]
After talking to Ilmar, some updates to the designs: https://projects.invisionapp.com/d/main#/console/17224475/362147247/preview

**Comment by loorm** [comment]
Triage #4 - check, when and how mini-votes end. Keep consistency for not showing voting results while vote is ongoing.

**Comment by ilmartyrk** [comment]
@kevincrepin inline-voting is now in our test environment https://citizenos-citizenosfe-web-test.herokuapp.com/et/, I modified some styles to hide results while voting is still active, can you check if this is ok, or should be changed. Also need assets for bar background :)

**Comment by anettlinno** [comment]
My ideas and thoughts: 
- I think that currently is not clear that there are two options for voting (replacing the word inside the text or overall voting over some idea -- I know it because Ilmar told me). When the red box appeared, I thought I made something wrong and this is kind of "warning" box (everything will be deleted :)) Replacement text was unclear and after clicking "Yes, overwrite" I was confused about overwriting :)) 
- Red warning box is too much here! I think it should be softer and less confusing

**Comment by kevincrepin** [comment]
@anettlinno raised good points and using it now, I agree. I think a lot can be done with typography, how we word things and adding some additional text.

I've made some updates: https://projects.invisionapp.com/d/main#/console/17224475/362147247/preview

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
