### ISSUE TITLE
BUG: FE - when a link is opened in "editMode=true" by a read-only User, topic contents is blank

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#214]
**Overview**

If a Topic link with "editMode=true" flag is opened by a read-only User, the Topic contents is not shown.

**TODO**

- [x] Fall back to read-only view, when User has no permission to edit (not logged in, no permission)

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-fe/commit/85ae1c479a9e37e555da8915669fecd39d6e145f
