### ISSUE TITLE
BUG: FE - momentary error message on screen when opening topic view

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#216]
**Overview**

Sometimes there is a momentary error message on screen when entering topic view.
The error is caused by Topic view loading `/members/groups` and `/members/users` for some odd reason of which first fails with 403 and thus the error message.

![image](https://user-images.githubusercontent.com/7405383/54322850-801ef400-45ff-11e9-852a-01d5126d0240.png)

**TODO**

- [x] Do not load `/members/groups` and `/members/users` in Topic view.

**Comment by ilmartyrk** [comment]
Fixed as we are not loading these in topic view
