### ISSUE TITLE
(Etherpad) Can't add inline comment when too close to the end of body text

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#217]
When trying to add an inline comment closer towards the end of the [topic's](https://app.citizenos.com/en/topics/f7c4b873-9863-4eda-8ef5-0a26d818ccfd?editMode=true&commentId=514206b5-59b0-4d4b-8380-d2f2e109d34b&argumentsPage=1) body, the expanded inline comment pop-up window's Cancel/Submit buttons get hidden behind the "Arguments" section's header. So one can't submit or cancel posting of the comment, and one can't scroll so the buttons appear again, as the end of the topic body has been reached.

![Screenshot 2019-03-14 at 17 12 38](https://user-images.githubusercontent.com/34126353/54369258-46410280-467e-11e9-8029-b4e97f2fa28c.png)

**Comment by oksks** [comment]
Replicated in Chrome and Safari.

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/ep_resize/commit/3a3e15df75fb99c8058716aa504696aa36439d80

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
