### ISSUE TITLE
Sorting & filtering improvements

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#219]
**Current default frontpage sorting situation:**
Currently, the app's frontpage has all topics sorted by topic status, which looks confusing to the user, as there's visually no recognizable logic behind sorting - some 2016 topics (without any updates since then) are at the top of the page, while some fresh 2018-2019 topics fall way down.

![Screenshot 2019-03-18 at 12 20 35](https://user-images.githubusercontent.com/34126353/54523466-455aea00-4978-11e9-8e84-7ed433b92817.png)

**Current sorting options:**
The app currently offers two sorting dropdowns:
- Show me topics about <categories' list>
- Show <topic status list>

<img width="607" alt="Screenshot 2019-03-18 at 12 27 11" src="https://user-images.githubusercontent.com/34126353/54523886-30cb2180-4979-11e9-8d67-d2469d7152ef.png">

The common/expected sorting option for a frontpage of any user-generated content aggregator page would be to show freshest at the top, oldest at the bottom.
We don't have an option for the user to sort by the timeframe: by most recent activity, or topics with activity in <recent week/month/year>, etc.

If we were to add that, we'll need to rethink sorting layout, as 3 sorting dropdowns in one spot would be an overkill.

**Comment by loorm** [comment]
This has been implemented. Closing the issue.
