### ISSUE TITLE
Optimise screen use in Etherpad comments

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#220]
Currently, Citizen OS uses Etherpad standard comment formatting. However, this is very wasteful of screen real estate, as can be seen from attached screenshots. Need to solve this, because it is inconvenient even on a large screen.

![waste_of_screen_Capture](https://user-images.githubusercontent.com/22661743/54526797-88b95680-4980-11e9-8650-4a51836e3bee.JPG)

![waste_of_screen_Capture_2](https://user-images.githubusercontent.com/22661743/54526801-8bb44700-4980-11e9-8c56-0f9fcfcf78b2.JPG)

**Comment by kevincrepin** [comment]
Worked a bit on this. So we have the issue that nothing can fall "outside" of the etherpad area width, so considering the amount of things we need to include in this functionality, it will never be a "small thing". But I tried to cut some space here and there and make it cleaner. Explanations are also in the screenshot, seemed easiest to communicate the thoughts.

![inline comments](https://user-images.githubusercontent.com/26792281/55627852-d541c600-57b7-11e9-83bd-5a2851abfd59.png)

**Comment by loorm** [comment]
Triage 42. This has been solved, when implementing Etherpad 1.8. Closing issue.
