### ISSUE TITLE
BUG: unread updates label missing in activity feed

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#224]
**What is the problem?** 
There used to be a blue circular label on activity feed menu link, indicating number of unread activity feed entries. This is now missing.

**Why is this a problem?**
Users do not regularly check activity feed by themselves. The blue badge was there to direct user attention.

**Possible fix**
Bring the blue label back, please.

**Comment by ilmartyrk** [comment]
Closing as this is fixed
