### ISSUE TITLE
UX: make a clear visual distinction between public and private topics

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#226]
**What is the problem?**
When user is viewing/editing a topic, there is no way to tell public and private topics apart. In "My topics" view we use the padlock icon, but once you're in topic view, the only way is to check settings and even there the interpretation of on/off is a bit questionable.

**Why is this a problem?**
Accidentally entering content into a topic, which the user thinks is private, but has actually been made public by another admin, for example, may be a rather negative surprise for the user.

**Possible solution**
Make a clear visual distinction between private and public topics in all views of the topic.

**Comment by loorm** [comment]
@kevincrepin You had a linked view here https://github.com/citizenos/citizenos-fe/issues/209, but the link has expired. Can you post an updated link here, please.

**Comment by kevincrepin** [comment]
I think this was related to labels? https://projects.invisionapp.com/d/main#/console/9829159/404592997/preview

**Comment by loorm** [comment]
We can have certain "global labels", yes. Generally, labels would be private and user-generated. 

Thank you for the view. Assigning for Triage 23 on June 8.

**Comment by loorm** [comment]
Triage 23. @kevincrepin We discussed this. Because saving screen real estate in the topic header section is relevant for us; because we already have a nice, minimalist design for pinning and reporting (the round colourful icons) and because we will not be implementing user-generated labels right now, can we please ask you to create s round icon to indicate private/public topics? Something, that would match the current round pins and report icons.

**Comment by KatiVellak** [comment]
Legally reviewed, no additional comments, very needed improvement.

**Comment by loorm** [comment]
@kevincrepin Reminding you about this issue. See comment from June 8 2020.

**Comment by kevincrepin** [comment]
Added new icons: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=85%3A71

**Comment by loorm** [comment]
We have the designs. Moving to triage.

**Comment by anettlinno** [comment]
Triage #45 All good. Ready for development. Est. dev. time 2h.

**Comment by loorm** [comment]
Nice!!! This looks good in real life!
