### ISSUE TITLE
in different languages popup tab titles might get very long and break the design

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#228]
**What is the problem?**
Some popups are using tabs now to switch between content and in different languages they might get very long and break the design. 

**Why is this a problem?**
Not beautiful, when tab labels overlap and design is broken. In extreme cases might be unreadable and thus unusable.

**Possible solution**
So thought about it and came up with an alternative where we don't use popups where tabs are necessary and use the actual full width of the browser.

On desktop we can have the tabs as a submenu on the left and their respective content on the right.

On mobile we can make them into accordion type elements: tapping expands the element and reveals the content within.

![overlay_to_page_test_desktop](https://user-images.githubusercontent.com/22661743/55436729-be2b8a00-55a5-11e9-9b53-5fde3319162b.png)
![overlay_to_page_test_mobile](https://user-images.githubusercontent.com/22661743/55436730-be2b8a00-55a5-11e9-91a0-ccc682a5ceee.png)

**Comment by kevincrepin** [comment]
Added updated examples here: https://projects.invisionapp.com/d/main#/console/17224475/358860171/preview

- Tabs are divided along the entire width
- action button is in the bottom and the label changes according to the section. So for example in topic settings you save the changes, but in the invite section you send invites.
- Height behaviour (for the time being): Let's let the window expand in height until it would exceed the window's height. At that point the "header" and "footer" get fixed and the "content" becomes scrollable. Indicated these section also on the design for clarity.

----

A possible solution as long as we don't ditch these dialog windows within the context.

**Comment by loorm** [comment]
@kevincrepin Update the link, please.

**Comment by kevincrepin** [comment]
references:
https://projects.invisionapp.com/d/main#/console/9829159/404592935/preview
https://projects.invisionapp.com/d/main#/console/9829159/404592934/preview
https://projects.invisionapp.com/d/main#/console/9829159/404592933/preview

**Comment by loorm** [comment]
> references:
> https://projects.invisionapp.com/d/main#/console/9829159/404592935/preview
> https://projects.invisionapp.com/d/main#/console/9829159/404592934/preview
> https://projects.invisionapp.com/d/main#/console/9829159/404592933/preview

These still have horizontal tab headings and settings in pop-up dialogs. Does it mean we're not going to go with these vertically stacked "tabs" that you have in the attached image above?

**Comment by kevincrepin** [comment]
I thought that taking all of these settings out of dialogs was out of scope? Hence my "A possible solution as long as we don't ditch these dialog windows within the context." in my original reply.
If we can take tabs out of dialogs, then let's do it yes, but I have to review the existing dialogs then. Let me know if it's ok :)

**Comment by loorm** [comment]
Triage 42. Issue unreplicated. Margo was seeing ghosts where none exist. Couldn't find a language, where this would actually be a problem. Closing issue.
