### ISSUE TITLE
FEATURE: create status.citizenos.com

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#229]
**What is the problem?**
There is currently nowhere, where a user / partner can verify the status of Citizen OS service.

**Why is this a problem?**
For time critical decisions, if something is not responding, it is important to ascertain service status to track down the reason for non-responsiveness or alert Citizen OS team.

**Possible solution**
status.heroku.com is a good example to follow. Visually clear, comprehensive yet compact. Citizen OS should aim for smth similar. Link it to https://twitter.com/CitizenOSStatus Twitter account in some way.

**Comment by ilmartyrk** [comment]
This still seems relevant, but will need to be prioritized as it probably is more relevant when we have more users and possibly more instances running

**Comment by anettlinno** [comment]
Triage 55. Linking the status updates with Twitter but this needs more investigation. 

Investigate 2hours about if and how the log entry is doable in Twitter or web page.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/68
