### ISSUE TITLE
more ways to organise Topics in a Group

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#230]
What is the problem?
As an admin of a Group with lots of activity, I want to organise topics in my Group by topic status and star so that Topics view would focus on what's most relevant.

Why is this a problem?
Speed of use. Topics may "get lost" for user on Citizen OS. Most relevant content should be served up first.

Possible solution
Add filtering and sorting options to Topic list in Group view.

![Capture2](https://user-images.githubusercontent.com/22661743/55439474-655fef80-55ad-11e9-81ba-3878802b3344.JPG)

**Comment by loorm** [comment]
User story: as a user or a group admin, for groups with a larger number of topics, I want to be able to sort topics based on:
- status (in progress, in voting, in follow-up, closed);
- attention (pinned, non-pinned);
- last activity (latest, oldest).

This could be done either in the topic list on the left or the topic list on the right (which kind of duplicate each other). Where and how should we do this, @kevincrepin?

![sort_topics_in_group](https://user-images.githubusercontent.com/22661743/83010166-86d93180-a020-11ea-9bb2-eb6daf144020.jpg)

**Comment by kevincrepin** [comment]
Since we already show that info on the left side, it makes sense to tie the filtering to this view. Otherwise we need to include that data to the right side list.

Suggestion: https://projects.invisionapp.com/d/main#/console/9829159/419444197/preview
There might be a better way to word the ordering though?

**Comment by loorm** [comment]
@ilmartyrk How are the topics currently ordered in Groups view on the left hand.

**Comment by loorm** [comment]
Triage 42. Implement Kevin's proposal, however, use it both on the left and below topic information. Also, set default sorting to:
1) Pinned
2) Date / time created
Estimated dev time 8 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
@kevincrepin, can you please send the icons svg or png?

**Comment by kevincrepin** [comment]
@ilmartyrk here you go!
[icons.zip](https://github.com/citizenos/citizenos-fe/files/6917361/icons.zip)
