### ISSUE TITLE
UX: change creation date to update date on public topics

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#231]
**What is the problem?**
- In public topics view, it is unclear, what is the date in the topic box. Topics appear outdated, because update date is not displayed. 
- Also, the update date, which is actually used for sorting topics, is right now based on topic content only.

**Why is this a problem?**
The environment itself appears outdated, like there is nothing going on, when in fact there is.

**Possible solution**
- Change creation date to update date on public topics. Possibly also label it as such.
- Add arguments / replies into update date calculation, right now it's based on updates to topic content only. 

![Capture](https://user-images.githubusercontent.com/22661743/55440370-15365c80-55b0-11e9-8bcf-7396b559856c.JPG)

**Comment by tiblu** [comment]
@loorm Do I get it correct that ideally we would show "Last activity date" for the topic on the home page? By "Last activity" we mean any change - content edits, vote, comment etc.
What would the label for the date field be?

**Comment by loorm** [comment]
Correctamundo! 

If by "label" you mean something shown to the user visually, then I wouldn't have any label. I'd just leave it the way it is. Unless @kevincrepin can think of a tiny and universally understandable pictorgram to denote "date of latest update".

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-api/commit/f4985d119fccada56ac413647548e2b92175cd21

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
