### ISSUE TITLE
add a free text field to topic invite function

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#233]
**What is the problem?**
Author / admin cannot add a personalised message to users they are inviting to collaborate. Invite e-mail text is totally generic.

**Why is this a problem?**
Invited users not as motivated to join. May even consider the invite a spam and not respond at all.

**Possible solution**
Add a free text field to topic invite function, where inviting user can add a limited amount of free text, that will be sent out within the invite e-mail.

![Capture](https://user-images.githubusercontent.com/22661743/55440782-790d5500-55b1-11e9-9c54-6e60d28cea3f.JPG)

**Comment by kevincrepin** [comment]
Included this to the updated dialog window design: https://projects.invisionapp.com/d/main#/console/17224475/358860171/preview

**Comment by loorm** [comment]
@kevincrepin Can you update the link, please, so we can push this into development.

**Comment by kevincrepin** [comment]
Sorry: https://projects.invisionapp.com/d/main#/console/9829159/404592935/preview

**Comment by loorm** [comment]
Assigning for Triage 23 on June 8.

**Comment by loorm** [comment]
Triage 23. Ready for dev. Prioritizing. Estimated dev time 4 days. 

Limit the field to 512 chars.

**Comment by loorm** [comment]
Triage 26 - @liinaguiter Do you think this has marketing value? Would you like to be notified, when this feature will be going live?

**Comment by liinaguiter** [comment]
Yes, @loorm please notify me when this goes live.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
