### ISSUE TITLE
Make search more visible and only when it is relevant 

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#236]
**What is the problem?**
Search is omnipresent at the top of the window, even when it is not needed, like topic edit mode. Hoever, for some reason, it's visibility is low. Users end up browsing my topics view, rather than using the excellent search feature.

**Why is this a problem?**
Search is a much faster way of finding topics and groups, so by not being visible, users end up using the slower methods. Inconvenient. However, when it is not necessary, the search bar across the entire top of the right-hand screen is wasting a lot of screen real-estate.

**Possible solution**
Perhaps have a more visible search logo either in the menu on the left or somewhere on the top right, which slides out as the search bar, when you click on it or on a mouse over event. But there may be much more elegant solutions still. Needs a designer / UX approach to figure it out.

**Comment by loorm** [comment]
Perhaps this is a part of the larger dashboard rethink, but maybe there's smaller useful things we can do before that to improve visbility / saving screen resource.

**Comment by kevincrepin** [comment]
@tiblu for a quick fix (as discussed with Margo):

- show in homepage
- show in my topics and my groups
- hide in topic view
- hide in secondary pages (like about etc)

**Comment by kevincrepin** [comment]
Also making this part of the "bigger scope" UI changes, just FYI.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
