### ISSUE TITLE
make entering topic view mode from my topics easier

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#237]
**What is the problem?**
In My Topics view, in order to enter a topic view mode, user needs to click on the topic on the left, which opens the topic settings on the right. Then user needs a second click on the topic title on the right or clicking on view / edit under topic actions. This siims to be counter-intuitive and users do not understand, where they need to click to view topic contents.

**Why is this a problem?**
Confusion. Some users have thought, that My Topics view is the only view we have and they are surprised, when taken to topic view / edit mode etc. Some turn to CS to ask for help. Also, double click could be one click too many to enter a topic.

**Possible solution**
No idea. But My Topics view is good, we need to keep that. Just figure out how to make entering the topic view more intuitive.

**Comment by loorm** [comment]
@kevincrepin So **the goal is, both on desktop as in mobile, to get from topic list to edit mode in one click.** Right now it takes two (assuming logged in and in My Topics view: click on topic name on the left, click on "Edit" on the right) or three (topic name on the left, topic name on the right, "Edit topic" in Options on the right).

Any ideas?

The best that I can come up with is a paper and pencil icon or smth for every topic in the topic list. So I can scroll through the topic list and without opening up the infos of the topic, I could click that icon and go straight to edit mode. Tried to create a quick mockup. 

Or, alternatively, the icon would be for information on the topic, like I did with the governance topic in mockup. So clicking the i icon gives you info on the right, but clicking topic title takes you straight to topic.

WDYT?
![1-click-edit](https://user-images.githubusercontent.com/22661743/83013362-8ee7a000-a025-11ea-8519-2d7531da1f2b.jpg)

**Comment by kevincrepin** [comment]
If prefer having this edit because otherwise we break the current logic that people are used to
https://projects.invisionapp.com/d/main#/console/9829159/419454142/preview

**Comment by loorm** [comment]
Just out of curiosity, what's the logo doing at the topic "Kui palju pagulasi peaks Eesti..:"?

**Comment by loorm** [comment]
Assigning to Triage 23 on June 8.

**Comment by kevincrepin** [comment]
@loorm no doubt extreme legacy design to show that this belongs to a group

**Comment by loorm** [comment]
Triage 23. Ready for development. Prioritizing. Estimated dev time 1 hour.

**Comment by ilmartyrk** [comment]
@kevincrepin can you please add missing icons too (both white and dark)

**Comment by kevincrepin** [comment]
@ilmartyrk adding them here. Svg ok?


[icon_edit_topic.zip](https://github.com/citizenos/citizenos-fe/files/5274442/icon_edit_topic.zip)

**Comment by ilmartyrk** [comment]
@kevincrepin svg is ok, but there only seems to be pencil icon without paper part?

**Comment by kevincrepin** [comment]
Very weird, something always goes wrong when exporting as svg. had to go png. Also ok?
[icon_edit_topic_png.zip](https://github.com/citizenos/citizenos-fe/files/5276443/icon_edit_topic_png.zip)

**Comment by ilmartyrk** [comment]
@kevincrepin thanks, perfect!

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
