### ISSUE TITLE
hide / do not show disabled features

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#240]
**What is the problem?**
There are disabled features, that are shown to the user, but inactive. However, there's no explanation, why they are inactive.

**Why is this a problem?**
Confusing for the user to try to click on "Delegate" for example, but not be able to use it. It makes it look as if the product is not working. Also adds to visual clutter.

**Possible solution**
Hide / do not show disabled features.

**Comment by tiblu** [comment]
In case most of the places use our cos-disabled directive, it should be a change only in the cos-disabled directive code. OFC there may be few cases that don't. 

https://github.com/citizenos/citizenos-fe/blob/master/public/js/directives/cosDisabled.js

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by anettlinno** [comment]
In ID-card or Mobile-ID voting "Delegate your vote" inactive feature is shown and users are confused. Reminding to hide/ do not show this feature.

![Inactive Delegate your vote](https://user-images.githubusercontent.com/45175679/85981690-50ab1b00-b9ed-11ea-95dc-9d020538eceb.png)

**Comment by loorm** [comment]
Tested. Confirmed working.
