### ISSUE TITLE
Inlinecomment adding label hides selected text (Etherpad)

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#241]
**What is the problem?**
Towards the end of the row, comment adding label hides selected text. This is especially bothersome, if you never intended to enter a comment, but are simply doing text editing with copy-paste for example.

**Why is this a problem?**
Bothersome to edit text, when it occasionally gets hidden when selected.

**Possible solution**
Reconsider the placement of commenting label.

![Capture](https://user-images.githubusercontent.com/22661743/55458763-8bf64880-55f6-11e9-8e85-16cb6e3496af.JPG)

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
