### ISSUE TITLE
FEATURE: ensure compatibility with Estonian Business Register

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#244]
**What is the problem?**
Downloadable decision file needs to be amended to better fit Estonian Business Register. They auto-process files and our container has the .csv file that is incompatible.

Also, there should be an option to auto-send container to Business Register and to then link it back to implementation phase in our system.

**Why is this a problem?**
Apartment unions and other NGOs need this functionality to be able to make their legal decisions. Right now, it's possible, but they need to remove the .csv file manually, send it manually and follow up on it manually.

**Possible solution**
1.  Remove the .csv file from the container, when intended use is for Business Register.
2. Create auto-send possibility.
3. Create link to read status back to our implementation phase.

**Comment by tiblu** [comment]
@loorm I suggest splitting into 2:

* Remove the .csv file from the container, when intended use is for Business Register.
* Create auto-send possibility & create link to read status back to our implementation phase.

**Comment by ilmartyrk** [comment]
@loorm Container downloading has been added. We'll need a decision if and how to implement direct connection with Business Register. In my opinion this is too much of a nice to have.

**Comment by loorm** [comment]
I agree. It's a simple download-upload operation. Also, Business Register does not accept files only, anyway. You have to fill in an additional form in any case.

**Comment by anettlinno** [comment]
Triage 56. All previous arguments are valid and current solution is enough for now. Closing the topic.
