### ISSUE TITLE
BUG: vote container download opens a confusing extra tab in browser

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#245]
**What is the problem?**
When downloading container after social-ID voting is completed (in admin rights), an extra tab with an error message is opened up and not closed later on. The newly opened tab also receives focus, even though the main app remains open and functional in it's own previous browser tab. 

NB! The container download is successfully completed, this is not a part of the problem. 

**Why is this a problem?**
Since the used is left with the active tab containing the error message, it is confusing and leaves the impression, that the app malfunctioned.

**Possible solution**
No idea.

![Capture](https://user-images.githubusercontent.com/22661743/55552917-70b73600-56e7-11e9-9bf8-f7b0a3b7d7ca.JPG)

**Comment by tiblu** [comment]
Removed `target="_blank"` from links. Seems attribute `download` and `Content-Disposition: attachment` are good enough for IE, FF, Chrome and Chrome on Android.

**Comment by loorm** [comment]
Confirmed partially fixed. The extra tab no longer opens, but the confusing error message remains. It now opens in the same tab as Citizen OS web app.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Confirm fully fixed. No confusing error messages any more.
