### ISSUE TITLE
UX: Font future-proofing – Open Sans to Noto Sans

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe-old#246]
**What is the problem?**
Citizen OS has 2 font families: Open Sans for the general UI and Noto Serif for the topic texts. Noto Serif supports *all* languages and characters. However Open Sans supports only standard ISO Latin 1, Latin CE, Greek and Cyrillic character sets.

**Why is this a problem?**
Looking ahead we will eventually run into characters that are not supported by Open Sans.

**Possible solution**
I would even say "only" solution is to switch our sans font to Noto Sans: https://www.google.com/get/noto/
With  582 languages from 237 regions, we should be covered.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
