### ISSUE TITLE
FEATURE: include an open field to specify what the users are voting on

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#247]
Kevin (on Slack): Has there ever been some feedback on the voting concerning the clarity of what you’re actually voting on? You’re voting on “the topic” but a topic can contain a lot of info. It’s quite clear for example in the topic “logo change discussion” where the votes are YES/NO/NEUTRAL
yes, no, neutral to what?
I think we need to include an open field to specify what the users are actually voting on.

**Comment by loorm** [comment]
Oksana (on Slack): agree very much with the open field proposal! I was just recently confused with the "help me focus" topic's voting options. these things shouldn't be open to a person's interpretation of available options (and provide arguable results) but should specify exactly, what is the statement I'm voting for/against

**Comment by loorm** [comment]
I agree, there is possible confusion. In fact, a confusion is IMHO quite likely, if you take the literal topic heading and the literal voting option texts.

The risk here is, that a single person, who initiates the voting and therefore gets to set the voting question, can influence the outcome too much by wording the question / issue to be voted upon. For example, a group of people have been discussing logo change and have come up with a proposal, which is written in the topic. Now one of the group will move the topic to vote and will therefore set the voting question. Possible wordings:
a) Do we really want to change our logo?
b) Do you support to proposal we came up with?
c) We need a new logo, right?
d) Do you want us to agree on  deciding to start working on possibly changing the logo?

An alternative option would be to adjust wording of voting options. If you have a topic, then voting "yes" is confusing. Voting "in favor" is much less so, because you're clearly saying, that you're in favor of the latest revision of the document. 

Another, different source of confusion is, that arguments are not voted on. Votes only apply to topic titel and topic content. If good ideas come up in arguments, they must be included in the topic or else they will not be subject to voting and will not be part of the final decision. If you download the decision container, for example, arguments are not there. However, this is not immediately clear from the UI. There was some user feedback on this confusion, recently.

**Comment by ilmartyrk** [comment]
@loorm @kevincrepin  @anettlinno  From our UX/UI update meeting I understand that the whole vote functionality will have an overhaul and it should probably fix this issue too. Not sure if to close this or not.

**Comment by loorm** [comment]
> @loorm @kevincrepin @anettlinno From our UX/UI update meeting I understand that the whole vote functionality will have an overhaul and it should probably fix this issue too. Not sure if to close this or not.

I don't know the answer to your question. But as far as the content of this specific issue goes, I still think setting a separate voting question is unadvisable. Reason provided above.

**Comment by anettlinno** [comment]
We discussed this at our UX/UI meeting yes and agreed that the whole vote functionality will go through the UX/UI makeover :)  We also discussed this from the perspective if the whole topic content should be visually on the same page where the voting takes place and the decision was that YES, whole topic-related information has to be available (topic content, attachments, arguments). 

IMHO it would make voting more clear if the statement or summary of (long) topic would be added into the voting. I do understand that people can manipulate with how they phrase or raise the question or statement but I think that if someone wants to influence voting results then this is something s/he can do anyway. For example inside the topic or body text. 

OR here´s an idea. What if user would have an opportunity to highlight or choose inside the topic the phrase, question or the whole paragraph that is being voted and our system would display this short summary before the voting questions? And all the other information, of course, would still be available (full topic, attachments, arguments).

**Comment by kevincrepin** [comment]
These are interesting ideas which we will take with us when we're doing the redesign!

**Comment by anettlinno** [comment]
Triage 56. Sending back to In Preparation and looking forward to the new design.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/60
