### ISSUE TITLE
BUG: container download not available after voting deadline expires

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#248]
**What is the problem?** When social-ID voting deadline expires, the author / admin of the topic is unable to download a container with the voting results. In the voting tab, the text says: "Everyone has cast their votes. You can download the full document here.", but there's no link or button for actual downloading. The button only appears after the topic is sent to follow-up.

**Why is it a problem?** Confusing. The author / admin has no way of knowing, if or when the download becomes available.

**Possible solutions?** Either the text should say, that you can download the results once the topic is sent to follow-up. Or then the download button should become available, once voting deadline expires (preferable).

**Comment by loorm** [comment]
Triage #5 - Decision - text should say, that you can download the results once the topic is sent to follow-up. reason - API does not allow downloading before topic is in follow-up. TODO - need to update copy and visuals.

**Comment by tiblu** [comment]
@loorm This needs the updated copy and visuals. Moving to "In Preparation".

**Comment by loorm** [comment]
New text: "Votes have now been cast. Please send topic to follow-up, then return here to download voting results." If consistent with our design principles, the "send topic to follow-up" could even be a link, the effect of which would equal clicking the link in the menu. It would save user the trouble of having to go look for the relevant link in the menu.

**Comment by loorm** [comment]
Triage #13 - prep done, move to todo.

**Comment by tiblu** [comment]
**Why doesn't API enable container download before follow-up?**

The idea behind it is that from the container it's clearly visible who has voted and how. This information can be used to bug users or try to convince to change their vote. Not cool.

**Comment by tiblu** [comment]
@loorm 

Fixed. This is what the UX looks like

![image](https://user-images.githubusercontent.com/7405383/68673493-8d103080-055c-11ea-9ec8-f01289e62d2c.png)

Clicking the "Send to follow up" will just reload the page, thus showing the "download button".

**Comment by loorm** [comment]
Tested. Confirmed working.

@tiblu - does the added button play ball with our rights system? As in is the button disabled for users who do not have sufficient rights in the topic?

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by tiblu** [comment]
> Tested. Confirmed working.
> 
> @tiblu - does the added button play ball with our rights system? As in is the button disabled for users who do not have sufficient rights in the topic?

Yes. IF User does not have "admin" permissions, no download link with the token is returned from the API.

Source: https://github.com/citizenos/citizenos-api/blob/9f53b90a510ef42ead7b37c43783093663dd05c5/routes/api/topic.js#L5727
