### ISSUE TITLE
FE: Mobiil-ID/ID-card login - buttons are misaligned

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#250]
![image](https://user-images.githubusercontent.com/7405383/56695578-127fe080-66f2-11e9-82f9-d9668b97421c.png)

Thanks to @moll for reporting this.

**Comment by tiblu** [comment]
I think it's caused by `.single_secion` - https://github.com/citizenos/citizenos-fe/blob/3cf4531b47d99e7dcb107894a5d35301429af139/public/styles/lightbox.scss#L980

**Comment by ilmartyrk** [comment]
There was a typo in angular expression
