### ISSUE TITLE
BUG: Invite users - cannot modify permissions for existing users

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#253]
BLOCKER for Anetts demo.

![screen](https://user-images.githubusercontent.com/7405383/57222399-158ca200-700b-11e9-917c-c0bda9e33960.png)

**Comment by tiblu** [comment]
Reverted the changes in TopicSettingsCtrl - https://github.com/citizenos/citizenos-fe/commit/85ae1c479a9e37e555da8915669fecd39d6e145f#diff-10b9fb9e4ea8585e89d238c67b3b6e65.

There is no quick fix, the solution tried there cannot work.

Why?

* The implementation really does not consider removal for existing User, that is, server never gets a delete request.
* The implementation really does not consider update of existing Users, that is, all the Users are sent `POST /members/users` but that does not support update, only create.


IF we want the user experience to be so that the "Invite" tab also shows existing members, we need to put in an extra effort.

**Comment by tiblu** [comment]
Created a new task in case we want to implement the UX properly - https://github.com/citizenos/citizenos-fe/issues/254

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
