### ISSUE TITLE
Delete alignment in Safari

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe-old#257]
In Safari the delete is trying to escape!

![Screenshot 2019-05-08 at 15 47 03](https://user-images.githubusercontent.com/26792281/57377570-7226c300-71ab-11e9-8e6b-ce0c2c928921.png)

**Comment by loorm** [comment]
Triage #4 - 100% reproducible in Safari. Prioritized.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by tiblu** [comment]
Checked today, looks good in testing env and dev env, that is - issue has been fixed while fixing other stuff.

![image](https://user-images.githubusercontent.com/7405383/79349887-758c0800-7f3f-11ea-86f2-d8ef8b63a63c.png)

**TODO:**

* Verify in live once `master` is releasable.

**Comment by tiblu** [comment]
![image](https://user-images.githubusercontent.com/7405383/80374170-ea940180-889e-11ea-891e-9c545a3578be.png)

Fixed!
