### ISSUE TITLE
BUG: Dashboard - Topic member list - Group name empty in "through a group"

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#258]
![image](https://user-images.githubusercontent.com/7405383/57387261-aa83cc80-71be-11e9-8e19-6e806af511aa.png)

**Comment by loorm** [comment]
Triage #4 - this issue is a duplicate of #260 . Closing issue.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
