### ISSUE TITLE
Browser window title to match Topic title and other metadata

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#259]
**Overview**

Browser window title and meta tags decide how previews are generated in Slack and other applications.

**TODO**

- [x] Browser window title to match Topic title as a minimum, we may want to display other info in the title depending what content is shown in COS. **NOTE:** Be sure not to leak sensitive info. We need to think if we can do this for public topics only or also private.
- [x] Slack preview to display title and part/full content of the topic

Related to:

* https://github.com/citizenos/citizenos-fe/issues/166

**Comment by loorm** [comment]
Triage #4 - necessary enhancement. Will prioritize.

**Comment by KatiVellak** [comment]
Discussed with Mikk, no additional comments.

**Comment by tiblu** [comment]
Duplicate of https://github.com/citizenos/citizenos-fe/issues/420.
Fixed: https://github.com/citizenos/citizenos-fe/issues/420#issuecomment-633964786
