### ISSUE TITLE
BUG: App marks one option as winner regardless of a tie

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#261]
One topic's voting process has ended, which resulted in a tie - two options got an equal amount of votes. 
However, COS app clearly marked one of these options as a winner (coloured the "winning" option's name into green in two places), while it should've marked **both** options as such.

<img width="773" alt="Screenshot 2019-05-11 at 14 56 38" src="https://user-images.githubusercontent.com/34126353/57612011-b4218180-757c-11e9-931f-30b8b5ee719e.png">

It would've been good UX to also provide the user with some suggestions as to do what to do next, as users turn to our platform to GET to a decision, so having gone through the long process of setting up the topic and carrying through voting without arriving at a final decision to move on with is disappointing.

**Comment by loorm** [comment]
Queueing this for Triage #4

**Comment by loorm** [comment]
Triage #4 - linking this to vote distribution issue #262. Quick fix is to visually equalize all winning options and to suggest an offline coin-flip.

There's a larger dev task on Big Picture project relating to additional voting mechanisms. Equal votes situation requires a 2nd round of voting between the winning options only. This needs to be added with other new voting mechanisms. There's no quick fix, unfortunately.

issue by: @oksks

**Comment by oksks** [comment]
Proposing copy for the message per Ilmar's request (Margo, pls validate if it makes sense at all - I'm talking out of my a$$ (pardon my French) on this subject):

> **Looks like you've got multiple winners and your voting process resulted in a draw!**
Sometimes having several winning options is a good thing, but there are times, when you just really need one clear winner - we feel you.

>**Here's what you could do now:**
Depending on the size and location of your voting (committee?), it might be possible to talk things through offline - for example, a co-located team could flip a coin, or have a quick additional argumentation to arrive at a decision - people sometimes change their opinions when more (or more convincing) facts are presented.
However, if it's not possible, we suggest starting a new vote, and perhaps trying to bring all possible pros and cons together in the topic to make deciding easier and clearer for the users to decide.

**Comment by ilmartyrk** [comment]
@loorm could you please have a look

**Comment by ilmartyrk** [comment]
Adding an example with usage of standard info element
![vote](https://user-images.githubusercontent.com/19904307/58618143-894c6280-82ca-11e9-9aee-7bc321451c61.png)

**Comment by loorm** [comment]
Thank you, @oksks, for the copy. I have made some modifications.

Looks like your voting process resulted in a draw.
Sometimes having several winning options is a good thing, but there are times, when you just really need one clear winner.

Here's what you could do now:
It might be possible to solve this offline - for example, a co-located team could flip a coin between the two winning options.
Also, if you had votes going to non-winning options, we suggest you run another vote between the two previously winning options only. This time, you could pre-determine a tie-breaker in case you have another draw: a coin flip, a default winning option (usually status quo wins in a draw), a person whose vote is decisive etc.

**Comment by loorm** [comment]
Triage #5 - @kevincrepin is it ok, if the standard blue info box contains so much text or do we need some more elegant solution for larger blocks of text?

**Comment by kevincrepin** [comment]
@loorm Not ok :) 

I suggest rather like this: https://projects.invisionapp.com/d/main#/console/17224475/366873553/preview

@ilmartyrk I owe you a pattern
![ptrn_vote](https://user-images.githubusercontent.com/26792281/58877595-cc973e80-86d9-11e9-8b0d-c7f88695f873.png)

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
