### ISSUE TITLE
Check toolbar buttons and tooltip texts

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#265]
What is the problem?
![toolbar](https://user-images.githubusercontent.com/19904307/59585876-2e987080-90ea-11e9-95b0-f8b13fdf4d99.png)

Why is it a problem?
Some buttons have tool-tip texts describing what they do. At the same time some buttons don't have these texts. Also all icons are not too descriptive for their actions and probably need these tool-tips
What is the possible solution?
Check each button, find which plugin it comes from and if necessary update button html to display tool-tip texts. If translation keys are missing add them too

**Comment by loorm** [comment]
Triage #6. Assigned to Ilmar. He will add description of the bug.

**Comment by ilmartyrk** [comment]
Important notice for future.
To translate toolbar buttons without having the text rendered inside the button item the localizationId format should be:  _{plugin_name}.toolbar.{button_name}.title_

**Comment by ilmartyrk** [comment]
Updated all plugins to add translation keys to buttons. Added new translation keys to [etherpad_translations](https://github.com/citizenos/etherpad_translations)

**Comment by loorm** [comment]
Tested. There are still some issues w/ icons and tooltips. Please see video https://www.youtube.com/watch?v=VmzGeqXkQGg

**Comment by ilmartyrk** [comment]
@loorm, the missing footnote button icon is due to cache. If you clear browser cache or try it incognito, it should appear. I've also noted the missing tooltip text for drop-downs of font color and font size

**Comment by loorm** [comment]
> 
> 
> @loorm, the missing footnote button icon is due to cache. If you clear browser cache or try it incognito, it should appear. I've also noted the missing tooltip text for drop-downs of font color and font size

Confirmed. Footnote button icon is working. 

In addtiont to the drop-downs, the track changes icon does not have a tooltip either. The one with the eye icon. Can you fix?

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
@ilmartyrk The track changes button still has a generic tooltip text "Toolbar". Can you fix that as well, please?
