### ISSUE TITLE
BUG: ETHERPAD - Footnotes plugin results in broken UX

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#268]
**What is the problem?**

When I click the [FN] button in the toolbar, it results in weird broken UI as seen below.
There is no indication, what the feature actually does.

![image](https://user-images.githubusercontent.com/7405383/58871802-5be92580-86cb-11e9-8d50-5bbf83153e30.png)

**Why is this a problem?**
Broken, User has no idea what is happening or what the input is for.

**Possible solution.**
Fix it so that User has an idea, that it's a footnotes feature.

**Comment by loorm** [comment]
Triage #6. @kevincrepin - please have a look and suggest a more intuitive solution for adding footnotes in topic text.

**Comment by kevincrepin** [comment]
Putting this on my to-do list, but can take this on only next week at the earliest.

**Comment by kevincrepin** [comment]
@ilmartyrk @loorm I suggest adding a title and a paragraph on what footnotes are and how they're used. Text can (maybe should?) be rewritten?
https://projects.invisionapp.com/d/main#/console/17224475/370512916/preview

**Comment by loorm** [comment]
Confirm fixed.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
