### ISSUE TITLE
BUG: Unnecessary red stripe in Activity Feed

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#272]
**What is the problem?**

A tiny red stripe appeared on the dropdown icon, that shouldn't be there. Tested on Chrome and Safari - visible in both.
See below on the right:

<img width="729" alt="Screenshot 2019-06-21 at 12 31 07" src="https://user-images.githubusercontent.com/34126353/59913264-83a4f100-9420-11e9-9ece-38891c46302f.png">

**Why is this a problem?**
It shouldn't be there.

**Possible solution.**
Hide the red stripe.

**Comment by loorm** [comment]
Triage #7 - bug confirmed. Probably sprite cache reload error. High priority. Thank you for reporting, @oksks!

**Comment by oksks** [comment]
<img width="623" alt="Screenshot 2019-07-03 at 15 50 27" src="https://user-images.githubusercontent.com/34126353/60593269-0f1c6b80-9dab-11e9-946d-abf06136c055.png">
Np! Btw, found another occurrence of the Red Stripe - not sure if this had to be reported separately, please see above.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
