### ISSUE TITLE
BUG: (Topic report) unclear information on a pop-up

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#274]
**What is the problem?**
User's pre-selected reason for reporting should be labelled as such, not just say "hate". User-written text should also be labelled accordingly, otherwise this view is quite confusing.

<img width="627" alt="Screenshot 2019-07-03 at 15 14 34" src="https://user-images.githubusercontent.com/34126353/60590793-96ff7700-9da5-11e9-9ced-60d51a560d5a.png">

**Comment by loorm** [comment]
Triage #8: Ilmar will have a look. If quick fix is possible, he will fix. Looks like it's a simple fix. If not, this will await the return of Mikk.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
