### ISSUE TITLE
Invite link takes you to front page instead of topic after login

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#276]
**Problem:**
If you click on a topic invite link (Liina's topic https://app.citizenos.com/join/ZnbuTpMo, for example) and you aren't logged into your COS account, you land on the front page of COS app (https://app.citizenos.com/) instead of the topic after logging in, and you get absolutely no information about the topic while it happens.

**Background:**
I've mindlessly clicked on the invite link in a Slack chat and switched to another application. After logging in and looking at the front page, I was unable to backtrack, which topic should I look for (since the URL doesn't contain any topic information) and it took me a while to figure out which chat the link was posted to, to find and click the link again.

**Desired solution:**
If you click on an invite link, you should land in the topic after logging in.

**Comment by oksks** [comment]
UX issue #2:
Now that I've logged in and clicked the invite link, it took me to topic's settings, instead of topic itself - also not the most logical move. Did the creator copy the wrong link or it is so by design?

**Comment by loorm** [comment]
Triage No 9. Could not replicate issue 1. When not logged in, invite links take you to login page and after logging in, redirect to topic settings.

UX issue 2 replicated succesfully. Link needs to direct to topic view, not settings. Will backlog this for fixing.

Linked to issue #112

**Comment by tiblu** [comment]
Checklist:

- [x] The implementation redirected to dashboard (`my.topics.topicId`), redirect to topic view (`topic.view`).
- [x] The button "copy link" does not copy link to clipboard.
- [x] Expired link error messaging is not working. On expiry error, redirect to home page and show global error message at the top.

**Comment by loorm** [comment]
Tested. Confirmed working.

@ilmartyrk The "Varia" option used to be at the bottom of the drop-down. The new categories are now displayed below it. It's a little weird. Is there a quick fix for this?

**Comment by anettlinno** [comment]
I had the same issue yesterday, when going to the topic via link (Big Picture Board link).

**Comment by loorm** [comment]
Tested both issues #1 and #2. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
