### ISSUE TITLE
BUG: Code of conduct link is broken

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#278]
**What is the problem?**
A link to our Code of Conduct in the deleted comment notification box leads to the frontpage of the app, instead of the actual document.
<img width="821" alt="Screenshot 2019-08-08 at 13 36 26" src="https://user-images.githubusercontent.com/34126353/62696750-bbbcbf00-b9e1-11e9-809e-275c993ae844.png">

**Why is this a problem?**
It should lead to the proper document if it exists, or hidden if it doesn't.

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-fe/commit/50c1b55725ad5bd9572e1666d37a8d6f0c27d0c9
