### ISSUE TITLE
UX: Redirect from editMode when topic is not "inProgress" 

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#280]
**What is the problem?**
When topic is in voting and "editMode=true" then user is displayed a text "You do not have permission to access this pad"

**Why is this a problem?**
This is confusing to users.

**Possible solution.**
If topic is not "inProgress" then redirect from "editMode" so that the static topic text is always displayed to user

**Comment by loorm** [comment]
Triage #10 - when topic has moved on from from "inProgress", always load HTML view of topic content first, regardless of user permissions. Reason is, that by that time, topic content should have arrived at a point, where comments, edit history etc are no longer that relevant.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
