### ISSUE TITLE
BUG: Partner e-mail visuals broken

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#283]
**What is the problem?**
Some of the RAA.ee template content is somehow double. For example the header logo etc.

![image](https://user-images.githubusercontent.com/7405383/64625756-636c4900-d3f5-11e9-827f-555e4d051b00.png)

**Why is this a problem?**
Bad user experience.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
