### ISSUE TITLE
FE: Update Citizen OS logos

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#285]
Update Citizen OS logos.

![image](https://user-images.githubusercontent.com/7405383/65410985-58051e80-ddf4-11e9-9868-31cb8b18f710.png)

[cos_platform_logo.zip](https://github.com/citizenos/citizenos-fe/files/3641225/cos_platform_logo.zip)

**Comment by tiblu** [comment]
[sprites_new.zip](https://github.com/citizenos/citizenos-fe/files/3641550/sprites_new.zip)

**DONE**

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
