### ISSUE TITLE
Arguments (comments) section to support Markdown (MD)

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#286]
Please add Markdown (MD) support to the arguments (comments) section.
This would enable Users to do basic formatting of the arguments to improve readability.

Examples:

* GitHub issue descriptions/comments

Goal:

* Minimum: Basic text formatting - headings (h1-h6), bold, italic, strikethrough, code, quote, link, lists (ordered and unordered)
* Strech: images, mentions, tasklists

References:

* Markdown - https://en.wikipedia.org/wiki/Markdown

**Comment by loorm** [comment]
Triage 13 - instead of Markdown, we need to use a more down to earth text formatting option. Something simple - lists, bold. Can be markdown in the background, but has to be usable.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
@kevincrepin This needs your input, please. HTML formatting for comments. The toolbar views etc.

**Comment by kevincrepin** [comment]
I think the basic formatting – bold, italic, underline, strikethrough and lists – should be enough, but if there's some other specific thing let me know. 

Tried to make it look similar to Etherpad so we don't have some big break between these similar components: https://projects.invisionapp.com/d/main#/console/9829159/418248426/preview

**Comment by tiblu** [comment]
Idea looks good, but implementation MAY need to change - similar to Etherpad is a good idea, but in this case looks kinda out of context or different.

Note - I suggest that in the background we still implement it by supporting MD, like GH does.

**Comment by loorm** [comment]
Looks good to me. Assigning for Triage 23 on June 8.

**Comment by loorm** [comment]
Triage 23. This needs to be implemented for both argument and reply boxes. Ready for dev. Prioritizing. Estimated dev time 3 days. 

NB! Must make sure character counter stays correct.

**Comment by loorm** [comment]
This is linked to #301
