### ISSUE TITLE
BUG: Activity feed icons not showing properly

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe-old#288]
Check included screenshot. The location in the sprite is a bit offset.
<img width="99" alt="Screenshot 2019-10-08 at 13 55 30" src="https://user-images.githubusercontent.com/26792281/66390535-8cbbcd00-e9d3-11e9-827a-460a24d477b2.png">

**Comment by kevincrepin** [comment]
Not sure if using labels correctly...

**Comment by tiblu** [comment]
@kevincrepin Thanks for the report? What platform and browser?
Looking good on my screen (Win 10, Chrome 77.0.3865.90)

![image](https://user-images.githubusercontent.com/7405383/66392401-6f3d3200-e9d8-11e9-858b-cbb1e0782cbc.png)

**Comment by kevincrepin** [comment]
Chrome 77.0.3865.90
Mac os X 10.14.6 Mojave

**Comment by ilmartyrk** [comment]
It's probably to do with screen resolution, @tiblu try changing the screen width to 2000 in chrome developer tools

**Comment by kevincrepin** [comment]
@ilmartyrk @tiblu I confirm it's a resolution thing because on my external screen this isn't happening.

**Comment by tiblu** [comment]
Fixed!

**Comment by loorm** [comment]
Fix confirmed.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
