### ISSUE TITLE
Request access to a Topic

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#289]
As a User I MAY want to request access to a Topic:

* That is public and User wants to contribute
* User wants elevated permissions in a Topic that he/she is already a non-admin member.
* User has opened up an invitation to a private Topic and User wants the access to be given to some other account. Related to: https://github.com/citizenos/citizenos-fe/issues/112

**Comment by loorm** [comment]
Triage 13 - create user story (for example, should this task include requesting an elevated rights level in a topic that you are already a member of)

**Comment by loorm** [comment]
**User story:**
As a logged in user, I'm reading a topic, either public or private. I see, that there are things going on in the topic body, that I would like to participate in, however I have insufficient rights. Maybe I can participate in the discussion below the topic, but I would like to contribute more. I want to notify topic admin(s) somehow, that I would like to receive / elevate my rights to edit the topic.  Once I've clicked the button, I would like some feedback about the fact, that topic admins have been notified. If my request for edit rights has been either granted or denied, I would like information about this in my Activity feed. 

As a topic admin, I would like to see an a noticeable form, if someone (name and e-mail) has requested access to my topic (also, which topic, I may have multiple topics). Perhaps this is best done via e-mail. I would then like to be able to decide with as few clicks as possible, whether I grant this person access or not. I would prefer to have a reminder in the same e-mail, that the user will be informed of my decision, whichever way I decide. However, if I have made the decision once and have denied it, I would not like the same person to be able to spam me to death with additional access requests. If the topic has more than one admin, i would like all of us to receive the request for access. Whoever makes the decision first, has priority. Any subsequent decisions by other admins re the same request have no effect.

Handing this over to @kevincrepin for design.

**Comment by kevincrepin** [comment]
In the current UI we think the best way to do this is as an action which is visible in the dashboard and in the topic (on the right hand side in the actions panel). Once the admin has changed your rights you will receive a notification.
https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1043%3A29004

The admin would receive this in the notifications and also see it in the user list so they can take action.
https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1067%3A29883

**Comment by anettlinno** [comment]
Thanks for the designs, @kevincrepin I think what you proposed works well with private topics -- user can ask access to edit the topic in the dashboard. 

But what about public topics? I think it would make sense if "Ask to edit" would be under the "Options". As public topics are not under "My topics" list and they only come out with search (which is rather something that users have to know, it´s not intuitive), then it is hard to find topic´s General Information and "Ask to edit" permission from there. 

<img width="706" alt="Ask to edit" src="https://user-images.githubusercontent.com/45175679/138081484-9b7d8e38-3f56-497a-a927-4b4d4e97c4ad.png">

Regarding notifying admin. I´m afraid that if admin receives this notification only via User list, then they go unnoticed as User list is passive and Admin should go and check if there are any requests in User list. And again, if users don´t know about this, they won´t go to check the User list just in case. Email notification is more proactive as the Admin user(s) would receive prompt notification and could provide permission right away. There comes the questions that we shortly discussed with @tiblu last week (please add if I forgot something)  

- Where can Admin user change the access level? Inside the email ("Give access" or "Reject") or is she going to be re-directed on the platform (user list?); 
- If she rejects the access request then should she also explain why? If yes, then where can she leave the feedback?
- If there is more than one Admin user then should all receive the "access request? If yes then probably first Admin who sees that request either accepts of rejects the request and other Admins should be notified about this action;
- How to make sure that user who asked permission once and was rejected, is not going to spam Admins?

**Comment by kevincrepin** [comment]
We actually already have this in place that participant can ask to edit from the actions menu (as we call it now :D): https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1043%3A29532

But we reconsidered how the admin accepts/rejects the requests and added those designs to the flow as well.

- Request received and admin can accept/reject from the dashboard: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1067%3A29883
- And also from the notification feed: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1490%3A29834
- If rejecting then admin can give a reason: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1479%3A29746
- The participant will be notified about  the reason as well in the notification feed: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1490%3A29835

I agree all these things probably also need to be emails so that no one misses these things.

**Comment by anettlinno** [comment]
Thanks Kevin! I think we have now what we need and email notifications can be designed once we get to the Notification System creation https://github.com/orgs/citizenos/projects/1#card-14132538. 

Sending it to Triage.

**Comment by KatiVellak** [comment]
Technical improvement, no legal impact.

**Comment by anettlinno** [comment]
Triage 50. We have now everything we need for development. Thanks! Est. dev time 4 days. Sending to development.

**Comment by anettlinno** [comment]
Triage 61. @kevincrepin we would like to test it with some users and need prototype in Figma. Sending it back to In Prep until we have prototypes.

**Comment by anettlinno** [comment]
Sending the topic to UX/UI redesign.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/88
