### ISSUE TITLE
FEATURE: Switch account

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#290]
As a User I MAY want to switch account:

* When User receives an invite to a Topic/Group, that is originally sent to a different account to that User logged in right now.

**Comment by tiblu** [comment]
Triage 13 - I implemented a Log-out - Log-in for the #112. Talked to @loorm  that is good for now, no separate task needed.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
