### ISSUE TITLE
Invite not sent, when e-mail pasted to invite box and "Save topic" clicked

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#292]
**What is the problem?**
When inviting a single person to a topic, who is not a Citizen OS user, I clicked on "Invite users", pasted his e-mail in the box that says "name or e-mail", then clicked on "Save topic". The dialog window disappeared and there was no error message. But no invite was sent to the user, either.

I later checked, that when entering names or e-mails of existing users, a small pop-up appears below the entry box, instructing to click or press enter. But when entering a new e-mail, this pop-up does not appear.  

**Why is this a problem?**
It's very easy to "invite" people to topic like this, without anyone actually receiving an invitation. I only discovered this, because I then went to topic users list to check, who has which rights. 

**Possible solution.**
For unknown e-mail addresses, make the same pop-up (with instructions to click or press enter) appear below the entry field, which appears when entering known users / e-mails.

Possibly related to #254

**Comment by tiblu** [comment]
Triage 13:

* Show the "click to add User" dropdown for a non-existing e-mail address
* IF the input is filled with valid e-mail, but User was not added by pressing enter or selecting from dropdown, still add the User by the e-mail

**Comment by ilmartyrk** [comment]
@loorm click to add User is added, but: IF the input is filled with valid e-mail, but User was not added by pressing enter or selecting from dropdown, still add the User by the e-mail sounds confusing. It could make user expect the same thing to happen when searching other users or groups. Or should it work that way that if email returns a user as an result the user is automatically added too?

**Comment by loorm** [comment]
Yeah, 

> @loorm click to add User is added, but: IF the input is filled with valid e-mail, but User was not added by pressing enter or selecting from dropdown, still add the User by the e-mail sounds confusing. It could make user expect the same thing to happen when searching other users or groups. Or should it work that way that if email returns a user as an result the user is automatically added too?

We added the "automatically add user anyway" idea, when talking about this issue at Triage 13. Originally, the proposed solution was simply to make the pop-up appear.

I can see, how automatic adding breaks consistency. Let's not break it. Making the pop-up appear is enough. Now it is the user's responsibility to see, what has been written to them.

**Comment by ilmartyrk** [comment]
@loorm thank you for your reply, can close the issue now.

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
