### ISSUE TITLE
BUG: Window isn't scalable when text's length exceeds one row

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#295]
**What is the problem?**
Logo hides part of the text (see screenshot)

**Why is this a problem?**
Does not look good.

**Possible solution.**
Fix scalable positioning.

![Capture](https://user-images.githubusercontent.com/22661743/67202870-58ec9880-f412-11e9-9e7e-7a0ff258bbcc.JPG)

**Comment by loorm** [comment]
Triage 14 - dialog windows have scalability issues in other places as well, according to Mikk. No good idea for solution right now. Possibly pushing text down might work.

**Comment by ilmartyrk** [comment]
Could not reproduce, there have been changes to our dialog styles that seem to have fixed all these issues. Closing this issue
