### ISSUE TITLE
BUG: Badge and text overlap in top menu item

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#296]
**What is the problem?**
The concept of "activity feed" is difficult to translate into a short single word in many languages, so it would be great if the design allowed to use more than ~11 characters.
The second pic illustrates, that on hover the second word jumps to a next row, which isn't ideal, but should be the default way to display a translation, if it doesn't fit. The badge disappears on hover :)

_Switch to Russian or Indonesian to verify this._

**Why is this a problem?**
Does not look good.

**Possible solution.**
N/A
<img width="174" alt="Screen_Shot_2018-09-04_at_12 28 13" src="https://user-images.githubusercontent.com/22661743/67203511-f1cfe380-f413-11e9-8bf7-1aaf0db90043.png">

<img width="164" alt="Screen_Shot_2018-09-04_at_12 28 26" src="https://user-images.githubusercontent.com/22661743/67203517-f4cad400-f413-11e9-849b-5dce79d2bdc5.png">

**Comment by loorm** [comment]
Triage 14 - problem confirmed (see Finnish or Dutch, if Russian or Indonesian do not produce a problem on your screen). Input from Mikk - spaces are not a problem, long words are. @kevincrepin - please suggest a solution. Perhaps move the blue icon in front of the text, not in the end? @oksks - do translators see in CrowdIn, when they are translating menu items and should therefore prefer brevity over a very exact translation?

**Comment by kevincrepin** [comment]
@loorm 

What if it overlays the icon? If there are new notifications it's on top or rather in the place of the static icon. If there's nothing new/unread it's the regular icon?

![Screenshot 2019-11-04 at 12 27 22](https://user-images.githubusercontent.com/26792281/68114410-9c5d0180-fefe-11e9-88c9-a7dcf4329fe4.png)

**Comment by oksks** [comment]
>  @oksks - do translators see in CrowdIn, when they are translating menu items and should therefore prefer brevity over a very exact translation?

Well, the key does state "DEFAULT -> NAV -> LNK_ACTIVITY". 
I can try to make it clearer in Crowdin, but I'm afraid translators mostly don't read the context nor try to decipher the keys, if the context of the text is understandable on its own.
Even though we can restrict the amount of characters to a specific number in translation, characters weigh totally differently in different languages, and even within the same language (compare i, l and m, w, for instance). 
There's also not so many creative but correct ways to translate such menu items, usually one particular way to translate a word or combination of words is prevalent in the Interwebz (as is with Russian) and thus is expected by the users. 

Usually, the items that break the design in multiple languages should be resolved via design, as this issue will keep reappearing with any new languages.

**Comment by loorm** [comment]
I'm happy with what @oksks said and with the idea @kevincrepin proposed. Thank you, guys! Once Kevin has made a high-res version of the design idea available, I'm cool with moving this into production.

**Comment by kevincrepin** [comment]
@tiblu you can fetch the sizes etc from: https://projects.invisionapp.com/d/main#/console/17224475/395327399/inspect

**Comment by tiblu** [comment]
Fixed.

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
