### ISSUE TITLE
BUG: Topic view timeline text misalignment

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#297]
**What is the problem?**

Timline information text overlaps the graphics

![image](https://user-images.githubusercontent.com/7405383/67326402-267c9180-f51f-11e9-97a7-ba1f2d02a2df.png)

**Comment by tiblu** [comment]
Shallow investigation suggest that it's a rendering bug  in Chrome. It happens from time-to-time and if you pull up the Developer Tools, it will sometimes correct itself. If it does not, switching any CSS style out-in will correct it. 
Could not reproduce in IE or Firefox.

**Comment by loorm** [comment]
Triage 14 - nothing for us to do. Chrome needs to get itself fixed.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
