### ISSUE TITLE
Length of white strip behind text (appears on hover) is restricted to "Every category" text length

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#298]
In public topics view, choose a category with a longer title, then hover mouse over drop-down to replicate.

![Screen_Shot_2018-06-18_at_12 07 51](https://user-images.githubusercontent.com/22661743/67683293-cca21e80-f999-11e9-9be1-f7a02d373735.png)

**Comment by tiblu** [comment]
Fixed!

**Comment by loorm** [comment]
Tested. Fix verified.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
