### ISSUE TITLE
add a few new categories

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#300]
**What is the problem?**
We are lacking a public topic categories for "Youth", "Science and Technology",  "Democracy and civil society"

**Why is this a problem?**
There are many potential users in these categories. The "Youth" category has been requested on several occasions by users.

**Possible solution.**
Add the categories.

**Comment by loorm** [comment]
Triage 14:
1) dev goes first, adds relevant keys
2) keys go to @oksks for translations 

Time estimate - 1 day of work (because of dbase migra).

**Comment by ilmartyrk** [comment]
Added categories https://github.com/citizenos/citizenos-fe/commit/c8c201ecc5c7a5e0bfe84ea005692597d1251436

**Comment by loorm** [comment]
Tested. Confirmed working.

@ilmartyrk The "Varia" option used to be at the bottom of the drop-down. The new categories are now displayed below it. It's a little weird. Is there a quick fix for this?

**Comment by ilmartyrk** [comment]
@Margo, I can quickly change the order in code

**Comment by ilmartyrk** [comment]
@loorm  changed the order yesterday

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
