### ISSUE TITLE
Recreate character counter into argument / comment box

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#301]
**What is the problem?**
It used to be near argument / comment entry box, counting down from the max allowed characters, so our limit wouldn't come as a surprise to people. With the new UI, it was lost. Need to bring it back, we're getting questions from users - inside and outside of COS.

**Why is this a problem?**
Users are surprised, when they run out of room entering an argument. We don't want to make arguments longer, to prevent excessive posting. An argument should be clear and as brief as possible. However, users need to be able to plan for this.

**Possible solution.**
Bring it back.

**Comment by loorm** [comment]
Triage 14 - check, that FE char count matches server count. We had a bug with this, when server was counting bytes and rejected inputs, while FE accepted. This was an issue with non-ASCII chars.

Only display char counter, when user reaches last 20% of char limit.

@kevincrepin - please (re)create the visual for this.

**Comment by kevincrepin** [comment]
I don't seem to remember this being part of the design...Also this has not been redesigned so I don't know how it got there or then got lost :)

But anyways! Suggestion in attach.

![Screenshot 2019-11-04 at 12 59 50](https://user-images.githubusercontent.com/26792281/68116261-0c6d8680-ff03-11e9-993b-654e6fd01792.png)

**Comment by loorm** [comment]
Assigning for Triage 23 on June 8.

**Comment by loorm** [comment]
Triage 23. Ready for development. We do not allow user to type over 2048 char limit, but counter will be dsiplayed for last 20% of chars and will then count down in red. Prioritizing. Estimated dev time 4 hours.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by ilmartyrk** [comment]
Fixed together with https://github.com/citizenos/citizenos-fe/issues/286
