### ISSUE TITLE
Change tab name from "View" to "Edit" and back, based on what action user is performing

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#302]
**What is the problem?**
Tab name reads "View" regardless of whether user is viewing or editing the topic.

**Why is this a problem?**
It's a bit confusing to see two different action descriptions right below each other (see screenshot).

**Possible solution.**
Tab heading should change based on the action being performed below.

![image](https://user-images.githubusercontent.com/22661743/67685500-e04f8400-f99d-11e9-86ba-53117178264d.png)

**Comment by loorm** [comment]
Triage 14 - time estimate 1 hour. Translation key for "edit" already exists.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
