### ISSUE TITLE
No error message in mobile view for insufficient rights (to edit)

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#303]
If you click on the pencil icon in a topic, where you only have "view" rights, there's no error message for insufficient rights, the content of the topic disappears and the page stops loading, remains empty.

Perhaps the pencil icon shoule be hidden or inactive, if user has no edit rights. Or at least there needs to be an error message.

**Comment by tiblu** [comment]
@loorm Hiding the button. Also will fix the totally random placement of mobile icons and missing search.

**Comment by tiblu** [comment]
@loorm Actually, it's easier to disable the button as the code has been written into a corner so that other elements will not adapt to one being missing.

**Comment by tiblu** [comment]
Done!

**Comment by loorm** [comment]
Tested. Fix verified.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
