### ISSUE TITLE
In public topics view title is cut off at the line and the category has no bottom padding

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#304]
**What is the problem?**
How can we avoid situations like in the screenshot: title is cut off at the line and the category has no bottom padding. 

**Why is this a problem?**
Does not look good.

**Possible solution.**
Idea: a gradient to fade out to the line and just truncate the category line?

![topic_boxes](https://user-images.githubusercontent.com/22661743/67777763-dc3d6800-fa6a-11e9-86c3-1d1ddd4727c2.png)

**Comment by loorm** [comment]
Triage 14 - this is CSS linear gradient implementation. The three dots thing is a css cross-browser text overflow ellipsis bug, that needs javascript. Timebox to 1h. If not solvable in that time, split into a separate issue.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by tiblu** [comment]
TODO:

- [x] Ellipsis for category text overflow
- [x] Linear gradient for:
    - [x] Category boxes
        - [x] Desktop
        - [x] Mobile (has no `<div class="line"></div>`)  - @media >500px && max-width: 667px
![image](https://user-images.githubusercontent.com/7405383/79578284-b403fd00-80ce-11ea-8fb2-4d2c6afad14a.png) - removed the 500-667 px size exceptions. Felt like it was not adding much value.
    - [x] Special boxes (Eesti Jazzi Arengusuunad, 34 Island Project, Tutorial etc)

**Comment by loorm** [comment]
Tested. Confirmed working. Looks very much better.
