### ISSUE TITLE
Hover state of the topic blocks in public topics view is visually noisy

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#305]
**What is the problem?**
I'm also not liking the hover state of the topic blocks on the homepage. 

**Why is this a problem?**
Everything is underlined and this creates visual noise... 

**Possible solution.**
How about this idea - on hover the box expands a bit (for example with a 4px same color stroke on the outside) and casts a shadow. Image as reference.

![Screen_Shot_2017-10-20_at_15 24 29](https://user-images.githubusercontent.com/22661743/67778160-78676f00-fa6b-11e9-806a-871734984723.png)

**Comment by loorm** [comment]
Triage 14 - doable. Time estimate - 1 day.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by tiblu** [comment]
Done!

![image](https://user-images.githubusercontent.com/7405383/82329866-a356e780-99ea-11ea-88d8-362a259c7060.png)

**Comment by loorm** [comment]
Tested. Confirmed working. Looks great!
