### ISSUE TITLE
Facebook share of Citizen OS topic does not show topic content

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#306]
**What is the problem?**
If I share a Citizen OS public topic link on FB, the snippet that is auto-included below the post only has text about what Citizen OS is and nothing about the topic content.

**Why is this a problem?**
When I'm sharing as a user, I want primary focus for my content, not for the platform I'm using to discuss my content.

**Possible solution.**
Facebook has a quote plugin that enables to select and share part of a text from the page with a link to the page.

https://developers.facebook.com/docs/plugins/quote/#example

![FB_Capture](https://user-images.githubusercontent.com/22661743/67778740-4dc9e600-fa6c-11e9-8cc9-beabb2ff5962.JPG)

**Comment by loorm** [comment]
Triage 14 - this can be done for public topics only. This has to do with our pre-render. Linked to #259. Amount of topic text to display roughly equal to our public topic box on front page.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Linked to #420 and #166

**Comment by loorm** [comment]
This is a duplicate of #166. Closing.
