### ISSUE TITLE
Check group members against a pre-existing list

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#307]
Partners want to create a public topic, but limit participation to people on a certain list. For example, a local municpality will put up a public topic, but will only want people living in the municipality to participate. The same for a political party - the discussion can be public, but they only want their own people to join in on the final voting. Topic / group admin needs to be able to link the topic to a certain pre-existing list, such as an Excel sheet or an online dbase (e.g. X-road) and compare voters to that list prio to counting the vote.

**Comment by loorm** [comment]
Triage 14 - this needs more thought. Partial overlap with csv-based invites. Need a proper user story.

**Comment by loorm** [comment]
Possibly this is solved by (public) groups.

**Comment by loorm** [comment]
This problem was solved, when we created the enhanced user management functionality. You can copy-paste a large number of users into the invite, then assign rights invidually etc. This gives a lot of flexibility and granularity. Creating a link to live check topic or group membership against some other database or source is not justified at this point. I propose to close the issue, because the users' need has been addressed and solved.

**Comment by anettlinno** [comment]
Triage 47. Members list management will be improved with issues #239 and #670. Closing the issue.
