### ISSUE TITLE
Improve the ability to find the right users to add to topic / group

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#310]
**What is the problem?**
For users with common names like John Smith or Jaan Tamm, it is difficult to know, which one of the people on the list is the one you want to invite. 

**Why is this a problem?**
Wrong people might get invited to topics they have nothing to do with.

**Possible solution.**
1. Include a miniature profile picture in the drop-down list of users.
2. Allow invitations to "strangers" only based on e-mails. 
3. Populate the drop-down not from list of all users, but from the list of users that you are already "connected to" i. e. you share a private topic or a private group with.
4. When people enter profile info on signup, add explanation, why filling out company field makes them easier to identify.
5. Possibly add option for people to allow displaying their e-mail?

![find_a_name](https://user-images.githubusercontent.com/22661743/67850051-48be7280-fb10-11e9-9d02-b5e012f95449.JPG)

**Comment by loorm** [comment]
Triage 14 - An additional option is to sort your "friends" to the top of the list, but still display all users below. Needs investigation. Needs decision. Not yet ready for dev.

**Comment by loorm** [comment]
I propose this: we only populate the list with people you are connected to. For everyone else (i.e. people you're not connected to), you can only invite them by fully entering their correct e-mail. Connected to = you have at least one group or topic, where you both have edit rights or above.

Assigning this for triage, since no change in design or UX is needed. However, please discuss during Triage, whether the above suggestion makes response time too slow.

**Comment by anettlinno** [comment]
Triage 45. Ask user´s permission to show publicly her name and email in invite search results. Users who do not give their consent will not be displayed in search results.
1. **For excising users.** Add check-box to my account where we ask user consent to show her name and email in invite research results
2. **For new users.** Also add check-box to "register new account" form
Est. dev. time 6h. Sending to development.

**Comment by ilmartyrk** [comment]
Development tasks:
- [x] Update user Model
- [x] Update API endpoints
- [x] Update FE views

Administrative tasks:

- [x] Update CHANGELOG files
- [x] Inform marketing of new feature(s)
- [x] Inform localization on new translations

**Comment by KatiVellak** [comment]
Legally reviewed, suggestions were taken into account. No further suggestions.

**Comment by anettlinno** [comment]
"My account" view is broken and I think this is due to asking user´s consent for their name to appear in the search results. @tiblu could you help us to fix this, please?

<img width="431" alt="Preferences" src="https://user-images.githubusercontent.com/45175679/136744850-37b033a5-2eb1-45ca-9c2a-28735ffa6987.png">

**Comment by tiblu** [comment]
> "My account" view is broken and I think this is due to asking user´s consent for their name to appear in the search results. @tiblu could you help us to fix this, please?

Works on my screen both test and prod environments:
![image](https://user-images.githubusercontent.com/7405383/136751837-54e3c2e7-b4a5-43f5-9193-6d693397cdbd.png)

**Comment by anettlinno** [comment]
@tiblu works on my screen now too :) Tested both on desktop and phone 👍
