### ISSUE TITLE
Topic settings unsaved, when clicking away from the dialog.

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#312]
**What is the problem?**
When changing topic settings, changes are not save when clicking away from settings dialog window and no warning is provided. Settings only saved, when "Save" button is clicked.

**Why is this a problem?**
A user may think they made a topic private, for example, while the topic actually remains public.

**Possible solution.**
Provide some form of notification to the user, that there are unsaved changes.

![unsaved_changes](https://user-images.githubusercontent.com/22661743/67856113-7dd0c200-fb1c-11e9-8fdf-6e8978825257.JPG)

**Comment by loorm** [comment]
Triage 14 - @kevincrepin, need your input please.

**Comment by kevincrepin** [comment]
Hmmm, yeah... This needs entire rework because it's all a bit messy now anyway. We have different cta's according to the active tab in the new dialog design, so it makes it even more complex, with potentially 2 different notification types (you have unsaved changes and you have unsent invitations...)

I would very much like to break these apart entirely, but it's a bit "bigger picture" stuff.

**Comment by loorm** [comment]
@ilmartyrk Is there a way to prevent the user from closing the settings dialog, when they have unsaved changes? This would protect against unintentionally closing the dialog, too.

**Comment by loorm** [comment]
Ping @ilmartyrk.

**Comment by ilmartyrk** [comment]
@loorm we can possibly add the warning, also removing the close dialog when clicking away is a possibility. As it is quite old issue and the design has changed since then, I personally don't see the issue to be that relevant anymore.  But we can go over it during triage

**Comment by loorm** [comment]
> @loorm we can possibly add the warning, also removing the close dialog when clicking away is a possibility. As it is quite old issue and the design has changed since then, I personally don't see the issue to be that relevant anymore. But we can go over it during triage

I would not want to remove close dialog when clicking away. I agree, that the save button is now more visible and the problem is therefore smaller than it used to be. However, the expected behaviour, I think, is still for IT systems to warn, if user has unsaved changes and has started to navigate away.  IMHO, this would be the best solution in our case. However, with this I'm handing the reins over to you @anettlinno

**Comment by ilmartyrk** [comment]
I understand the point of warning users about unsaved changes. I propose on making a system-wide generic solution. I'll create a list of views that need this update and we can create a check if there were any changes that user made and only display the warning if there were.

**Comment by ilmartyrk** [comment]
Move to https://github.com/citizenos/citizenos-fe/issues/53
