### ISSUE TITLE
End voting of a private topic, when all participants have cast their votes

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#316]
In voting options dialog, for private topics, add more options. Right now, it visually seems as if you must set the deadline. Actually, there should be a choice there:
1) Set the deadline.
2) Voting ends, when I manually close it.
3) Voting ends, when all topic members have voted.

![end_vote_options](https://user-images.githubusercontent.com/22661743/67860325-38b18d80-fb26-11e9-9f94-194e0b9c8549.JPG)

**Comment by loorm** [comment]
Triage 14 - @kevincrepin, can you please create the visual for this.

**Comment by kevincrepin** [comment]
@loorm @tiblu 

This was actually already in design: https://projects.invisionapp.com/d/main?origin=v7#/console/9829159/210118123/preview

Although there we had max mount of votes instead of manual closing.

**Comment by tiblu** [comment]
> @loorm @tiblu
> 
> This was actually already in design: https://projects.invisionapp.com/d/main?origin=v7#/console/9829159/210118123/preview
> 
> Although there we had max mount of votes instead of manual closing.

Margo you ok with that?

**Comment by loorm** [comment]
> > @loorm @tiblu
> > This was actually already in design: https://projects.invisionapp.com/d/main?origin=v7#/console/9829159/210118123/preview
> > Although there we had max mount of votes instead of manual closing.
> 
> Margo you ok with that?

I'm ok with that. I initially thought, that admin would have to choose one or the other and in the design it's not immediately obvious, that they are alternative options. Then I got thinking, however, that admin might want to set up the ending on a "whichever-is-reached-first" principle. 

For example, you switch on both "deadline" and "everyone voted" and whichever criteria is hit first closes the voting. "Everyone has voted" and "x number have voted" seem to cancel each other out though, so they would need to be alternative options. So maybe somehow emphasize in design, that deadline is a separate end criteria, while vote count is another. They can be used either separately or together. And then within vote count, you have to choose either all votes in or "x number of votes in".

Manual closing always remains an option anyway, so no need to crowd the settings window wth it.

**Comment by kevincrepin** [comment]
@loorm @tiblu Would this be clearer? https://projects.invisionapp.com/d/main#/console/9829159/259485592/preview

**Comment by loorm** [comment]
Yes. Assigning for Triage 23 on June 8.

**Comment by loorm** [comment]
Triage 23. Might need a text copy update by Marvin. Need to think about clashes and edge cases.  Prioritizing. However, estimating dev time not possible at this stage.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by anettlinno** [comment]
We received new user request for the "All votes are in" end of voting system. User wants to get the results right after all members have casted their votes.

**Comment by loorm** [comment]
Triage 41. Prioritizing. Estimated dev. time 4 days.

**Comment by ilmartyrk** [comment]
Added with https://github.com/citizenos/citizenos-api/commit/9ff2ba91a061965f9c653812413987f63bfb5df3
