### ISSUE TITLE
Vote count illogical in public topics

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#319]
**What is the problem?**
While voting is active, the way that the number of votes is displayed is illogical. It makes sense for private topics, where only topic members can vote, but for public topics it's illogical.

**Why is this a problem?**
Confuses users unnecessarily.

**Possible solution.**
For public topics, simply display the vote count, without the slash and the eligible user count.

![image](https://user-images.githubusercontent.com/22661743/67864677-a8c41180-fb2e-11e9-9952-8ec64b24c793.png)

**Comment by loorm** [comment]
Triage 15: 30 minutes time estimate.

**Comment by tiblu** [comment]
Fixed.

**Comment by loorm** [comment]
Tested. Confirmed.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
