### ISSUE TITLE
Private topic icon is hidden, if topic name is longer

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#320]
**What is the problem?**
In "My topics" view, longer topic names push the private topic lock icon out of visible screen space.

**Why is this a problem?**
Lock icon no longer serves it's purpose, if for some topics you do not know, whether it's not there at all (black circle on screenshot) or whether it's just hidden away (red circle on screenshot).

**Possible solution.**
Cut the longer topic title a few chars earlier to fit the lock icon on visible screen.

![private_icon_hidden](https://user-images.githubusercontent.com/22661743/67865300-ba59e900-fb2f-11e9-8caa-788168a9bed3.jpg)

**Comment by ilmartyrk** [comment]
Issue has been fixed with new icons
