### ISSUE TITLE
Hide irrelevant information in "My topics" view

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#321]
**What is the problem?**
Information about topic belonging to a group is displayed even if the topic does not belong to any group.

**Why is this a problem?**
Quite a lot of unnecessary visual information. Makes the "My topic" view appear cluttered.

**Possible solution.**
If topic does not belong to a group, do not display that information.

![hide_irrelevant](https://user-images.githubusercontent.com/22661743/67865922-ceeab100-fb30-11e9-993e-1ad8b7938eff.jpg)

**Comment by loorm** [comment]
Triage 15: 30 minutes time estimate to live

**Comment by tiblu** [comment]
Fixed.

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
