### ISSUE TITLE
Can't share the topic, if my rights level is view or edit

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#322]
**What is the problem?**
User's with view and edit rights cannot share the topic. Share link on the right is active, but in the dialog that opens, everything is inactive. I should be able to share for other's to join in "view" rights.

**Why is this a problem?**
Confusing, when you see an active share button, but then cannot do anything in the dialog that opens up.

**Possible solution.**
Quick fix is to disable the Share button on the right. Long-term fix is to allow users to share with equla rights level to their own rights. Must take care, though, that users in "view" and "edit" rights cannot change the invite link.

![cant_share_in_view](https://user-images.githubusercontent.com/22661743/67950655-b347df00-fbf2-11e9-8885-63484e4a00c7.jpg)

**Comment by oksks** [comment]
Additionally, I can't invite other users from the "Invite" tab either, even when my user has "edit" mode defined for it - tried to invite Anett to [a topic](https://app.citizenos.com/en/topics/8112a6a1-5f42-4b44-8512-b6d3b37d13be) today, got a red error "You don't have permissions to complete the operation." several times. 
This seems like a major issue to be honest, as topic share and topic invite are one of our fundamental features.

**Comment by loorm** [comment]
Triage 15: We have several choices here:
a) disable share button
b) do not disable share button, show error message instead
c) add an option to request higher level of rights
d) allow "edit" rights users to invite new users + put a check box somewhere, where admin can remove this right

Best solution Mikk proposed - dialog opens up, if you don't have sufficient rights, everything is disabled, but there's an error msg in the dialog itself together (with an option of requesting additional rights.) The last part (request access part) is a separate task. 

@kevincrepin - can you please create the UX for this?

We also need copy texts for error message (generic for invite and share or separate).

**Comment by kevincrepin** [comment]
@loorm Another idea: Since the user can't do anything at all in this multi-tabbed dialog, why even bring them there? Can't we have a dialog saying you currently don't have the rights to share the topic, if you want to have those rights – request here. 

Keep the focus on one message/one action?

**Comment by loorm** [comment]
I think we fixed this, when we implemented the "hide inactive features" in https://github.com/citizenos/citizenos-fe/issues/240. You can try to replicate at Triage, just to be sure. I tried to replicate and when I had view/edit rights, I did not see the "Share" tab / option at all. The other part of this issue will be solved in #311 by adding rights level to join link.

So I would propose, that it's problem solved and this issue can be closed.

**Comment by anettlinno** [comment]
Triage 46. As this is solved in #311 then we are closing the issue. FYI @tiblu.
