### ISSUE TITLE
Make it possible to easily find topics I have voted for

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#323]
**What is the problem?**
If I vote for something, it can be difficult later on to find the topic again in order to follow up on implementation.

**Why is this a problem?**
Research indicates, that people are more likely to continue participating if they receive feedback about the implementation of the idea they voted for. But if you don't find the topic later on, you can't follow up on it and therefore do not find out about the implementation. 

**Possible solution.**
In "My topics" view, in the drop down menu under "Topics I created" there should be an additional option saying "Topics I voted". Clicking it would bring up all topics (public and private) that the user has voted on (soft and hard ID).

![topic_i_voted](https://user-images.githubusercontent.com/22661743/67957549-75e94e80-fbfe-11e9-93a5-6a58fa1fbb44.jpg)

**Comment by loorm** [comment]
Triage 15: 2 days.

**Comment by tiblu** [comment]
Done!

Added to extra filtering options:

- Topics I have voted on - Topics that you have voted on.
- Topics that need my vote - Topics that have a vote in progress and User has not voted.

![image](https://user-images.githubusercontent.com/7405383/77066002-ff9d8b00-69ea-11ea-9a5f-46bced00cfbf.png)

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
