### ISSUE TITLE
Search bar should provide feedback if user's input isn't suitable for search

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#324]
**What is the problem?**
Currently, if you input 2 characters into the search bar and hit enter, letters disappear and nothing happens. 
Also, if you type in 3 characters from the name of an existing topic (like "nõu", while there's a topic called "Nõuame 5g tehnoloogia...") and hit "Enter" too quickly, the letters disappear and there's no search result. 

**Why is this a problem?**
Can be confusing for the user or make it look like the search function does not work.

**Possible solution.**
Maybe provide feedback in a different color in the search box itself?

**Comment by loorm** [comment]
@kevincrepin - please have a look and suggest a fix.

**Comment by kevincrepin** [comment]
When I type in "nõu" the search doesn't find anything either...

A couple things here to note. I'm saying this a bit more for myself as a refresher so if I'm stating something false, please comment. @loorm @tiblu 

- we show autocomplete/suggestion only from 3 characters and the user doesn't have to hit enter, they show instantly.
- This means that for 1 or 2 characters, there is no suggestion and it seems like the search is broken
- This also means that pressing enter when there's only 1 or 2 characters, the system still does not make a search and it seems broken.

We can start solving this by
- allowing search from 1 character – but this will be heavy and with each additional character the system needs to send queries
- not doing an autocomplete/suggestion without the user's ENTER input. 
-- in case we still keep the 3 characters minimum rule, we need to then also have the "error message" to communicate this rule. For this we can reuse the same logic as we have when we communicate nothing was found.

- Combine both above and allow search from 1 character, but only after user hits ENTER. 
-- This actually seems the best way to go for me. We're not setting any vague rules the user doesn't know until they break said rule AND we only need to send queries once the user hits ENTER – less heavy I would presume.

**Comment by loorm** [comment]
Triage 15: @kevincrepin your comments are right. We tested and saw, that 3 chars are already enough for auto-complete to work. Decided that we want to have the ability to search with less characters + Enter. So "5G" + Enter would give you relevant search results, but just entering 5G will do nothing. No additional error messages. Nothing further for @kevincrepin to do here. Devs will solve.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
