### ISSUE TITLE
Containers with voting results cannot be downloaded

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#326]
**What is the problem?**
When you have non-signed vote and noone votes, attempting to download the container leads to an error message.

**Why is this a problem?**
Maybe this creates an avenue for attack?

**Possible solution.**
User should not crash out of the app, but should instead get an in-app error message or, better yet, the button should be disabled or not present.

![download_error](https://user-images.githubusercontent.com/22661743/67961562-8ac8e080-fc04-11e9-9e50-44a9e1018c0c.jpg)
![download_error_2](https://user-images.githubusercontent.com/22661743/67961578-8dc3d100-fc04-11e9-9e62-7229de223885.jpg)

**Comment by loorm** [comment]
UPDATE - seems to be the case for non-empty containers, too

**Comment by loorm** [comment]
UPDATE 2 - seems to be the case for signed votes, too. Elevating to "high priority", because app is not usable as it should be. Notifying developers.

**Comment by ilmartyrk** [comment]
Added the updated token logic from https://github.com/citizenos/citizenos-api/commit/9be336ca5467db2405982b5b813b7c9fee3e6136#diff-4b0bb1bf65417714c8f4cf5b79a648dc 
to zip download URL

**Comment by loorm** [comment]
Fix confirmed. Download works. **However** - issue #245 closed by @tiblu is partially back. New tab is not opened, but you still get the confusing error message. It now appears in the same tab, where Citizen OS was open. Browser's "Save as" dialog also opens and container download works. But the error message remains in the browser window. Is there a way to get rid of that?

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirm fully fixed. No confusing error messages any longer.
