### ISSUE TITLE
"Current vote results" tab not working in "My topics"

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#327]
**What is the problem?**
In "My topics" view, when I click on "Current vote results" for a topic that is "In voting", the tab does not open (even though some users have voted i.e. voting results do exist) and nothing else happens either.

**Why is this a problem?**
A feature is not working.

**Possible solution.**
Need a fix.

![Current_vote_results](https://user-images.githubusercontent.com/22661743/67962817-581fe780-fc06-11e9-9917-4f2db69e8ade.jpg)

**Comment by loorm** [comment]
Triage 14 - confirmed. Needs a fix.

**Comment by tiblu** [comment]
Fix was basically to revert https://github.com/citizenos/citizenos-fe/commit/0d90b2230f8430755ae1a0d1e4d3409ecf924daf and re-introduce bug #100. 
See  https://github.com/citizenos/citizenos-fe/issues/100#issuecomment-549327793

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
