### ISSUE TITLE
"View more results" crashes the search box

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#328]
**What is the problem?**
Write something into the search bar, that returns a lot of results, for example "worksh". Now click on "View more results" at the bottom of search results. If nothing happens immediately, click some more times and wait for about 10 seconds. The app returns to either public topics view or my topics view. No additional search results are displayed. The previous search text "worksh" remains in the search box and cannot be deleted or edited - it just returns to it's fixed state, if you try.

**Why is this a problem?**
I found it, when I was trying to bring up more search results for the particular string. So it's a problem, because more search results cannot be viewed.

**Possible solution.**
Needs a fix.

![view_more_results](https://user-images.githubusercontent.com/22661743/67963825-e9dc2480-fc07-11e9-9c68-4c1d0605ce35.JPG)

**Comment by loorm** [comment]
Triage 14 - confirmed by @tiblu. Must be fixed.

**Comment by tiblu** [comment]
Fixed.

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
