### ISSUE TITLE
BUG: Topic follow-up view - missing dates

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#334]
**What is the problem?**

The topics "follow-up" phase views are missing:

* "Document finalised on" date
* "Vote ended on" date

![image](https://user-images.githubusercontent.com/7405383/68673845-4ec74100-055d-11ea-8d63-5eed338ddd74.png)

**Why is this a problem?**

Information is incomplete.

**Possible solution.**

Implement as in designs:

![image](https://user-images.githubusercontent.com/7405383/68673892-6e5e6980-055d-11ea-8a3f-c3a1ae22167b.png)

**Comment by tiblu** [comment]
@loorm About those dates:

* "Document finalised on" date - is that the date the actual document text was modified in Etherpad?
* "Vote ended on" date - is that the date when voting expired OR was sent to follow-up?

**Comment by loorm** [comment]
> @loorm About those dates:
> 
> * "Document finalised on" date - is that the date the actual document text was modified in Etherpad?
> * "Vote ended on" date - is that the date when voting expired OR was sent to follow-up?

First, I wouldn't start calling it a "document", when we always talk about topics. I would suggest we say "Topic finalised". And I would use the date, when it was pushed into Voting.

Similarly, I would use the date it was pushed to follow up and phrase it as "Voting completed"

**Comment by loorm** [comment]
Triage 15: get rid of the whole Topic summary block. All of this information is available either from Topic activity feed or the "View" tab. This block was designed before activity feed. There is no more need for it. 30 minutes to live.

**Comment by tiblu** [comment]
Done! Topic summary block removed.

**Comment by loorm** [comment]
Tested. Confirmed.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
