### ISSUE TITLE
TECH: Git pre-push hook to validate language files

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#336]
**Why?**
We've pushed code to live (`prod`) several times without translations. That is not waiting for and merging Crowdin's pull request to create defaults to all languages.
Also validate that all language files are valid JSON.

**What?**
I suggest we:

* Create a `pre-push` hook that:
    * On push to `prod` branch checks if source (`en.json`) and other language files structures match. IF they don't, reject the push.
    * Validates all language files to be valid JSON
* Along the way upgrade the Husky (https://www.npmjs.com/package/husky) to the latest version.
* Start using `.huskyrc.js` as configuration file.
* Move existing hooks to the new configuration file.

**Where?**

Every Citizen OS app that has Husky in use.

That is:

- [ ] https://github.com/citizenos/citizenos-fe
- [ ] https://github.com/citizenos/citizenos-api
- [ ] ... ?

**Comment by tiblu** [comment]
Implemented in CI for FE.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
