### ISSUE TITLE
Multiple footnote issues

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#337]
**What is the problem?**
1. When pushing the footnote button on toolbar, the dialog appears, but control is not transferred to the text input field in the dialog. If I continue to enter text, it goes into the main topic body.
2. Blue button on the footnote text says "Submit", but "Insert" would make a lot more sense.
3. After I press submit and want to continue entering text into the main topic body, all text is superscript (like the footnote number). Since we have no superscript/subscript button on the toolbar, the only way to get out of this is to press Enter for new line, enter some text. press Home, then Backspace to erase newline.

**Why is this a problem?**
Because footnotes, while usable are uncomfortable in the current form.

**Possible solution.**
Fix the problems.

![footnote_err_capture](https://user-images.githubusercontent.com/22661743/68770016-0cba0000-062e-11ea-8f46-c587c81465f3.JPG)

**Comment by tiblu** [comment]
Related to:

* https://github.com/citizenos/citizenos-fe/issues/268

**Comment by loorm** [comment]
Triage #16. Ready to be prioritized.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working for all three.
