### ISSUE TITLE
Ability to remind Users to participate in a Topic

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#338]
**What?**

As a Topic creator I invite Users to join the Topic. When I open the members list, I instantly see all the invited Users, but have no idea, which of them have actually acknowledged the invite.

**Why?**

As a Topic creator I would like to know, if Users have seen and have not participated, because they have nothing to add OR they have missed the invite and I should send a reminder.
I would like to send the reminder to increase participation.

**Possible solutions?**

1. We could mark users in UI that have  opened the invite.
2. IF it's just a matter sending reminders, we MAY want to add "Remind Users to Participate" functionality, which would not expose Users that have not participated, but would still enable User to send reminders.
3. .....

Original idea: @anettlinno

**Comment by loorm** [comment]
Triage #16. @loorm will describe a detailed solution. Then pass onto Kevin.

**Comment by loorm** [comment]
This has been implemented, though slightly differently. User can now see "pending invites" in Topic user list.  Closing issue.
