### ISSUE TITLE
BUG: Activity feed - missing variables in activity texts

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#341]
**What is the problem?**
![image](https://user-images.githubusercontent.com/7405383/69166917-b6046880-0afc-11ea-8bd1-8f3c88c0a97a.png)

![image](https://user-images.githubusercontent.com/7405383/69253279-10fd9480-0bbd-11ea-8e3c-3acf454fd01c.png)

Related to:

* https://github.com/citizenos/citizenos-fe/issues/342

**Comment by loorm** [comment]
Triage #16.  ETA 3-6 dev hours. Ready for prioritization.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
