### ISSUE TITLE
BUG: Calendar should have a correct date/week format, based on browser settings

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#343]
**What is the problem?**
When setting a voting deadline, the calendar doesn't align with my locale - week starts with Sunday instead of Monday and the date format is incorrect (mm/dd/yyyy instead of dd/mm/yyyy). 
Date/week settings should align with user browser's locale settings.

<img width="569" alt="Screenshot 2019-11-20 at 10 38 16" src="https://user-images.githubusercontent.com/34126353/69222593-75e7c900-0b82-11ea-84c5-6b6e8e1220f3.png">

**Why is this a problem?**
It causes confusion and may cause choosing an incorrect date for the topic, as well as cause communication problems (it looks like Thursday is chosen, but it's actually Wednesday).

**Possible solution.**
Please make sure the calendar is synced with browser locale settings.

**Comment by ilmartyrk** [comment]
This view has been updated, but needs some investigation in the context of this issue

**Comment by anettlinno** [comment]
Calendar view still starts with Sunday. Date format is fixed.

**Comment by anettlinno** [comment]
Triage 56. Aligning calendar with browser´s local settings. Approx. dev. time 2h. Sending to development.

**Comment by anettlinno** [comment]
Triage 76. Should improve with Angular update. 
Sending to redesign.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/90
