### ISSUE TITLE
Delegation - no error messages

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#359]
**What is the problem?**

Delegation - no error messages when:

* Delegating to self
* Delegating to a person who has no access to the Topic

![image](https://user-images.githubusercontent.com/7405383/69951303-ac680100-14fd-11ea-95e9-f2e1bb1fba7c.png)

By design you can only delegate to a person who has at least `read` access to the Topic.

**Why is this a problem?**

User has no idea why delegation fails.

**Possible solution.**

* Make sure server sent error messages are shown. For example delegating to self.
* When entering an e-mail, name or whatever to the box and "Delegate" is pressed, send the input to server and make sure error is shown.

**Comment by loorm** [comment]
Triage 16. ETA 6 dev hours. Ready for prioritization.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by tiblu** [comment]
TODO:

- [x] Generic error messaging fix
- [x] Error message when delegating to self
- [x] Error message when delegating to a user who has no access

**Comment by oksks** [comment]
@tiblu may I please ask for screenshots for both new strings? I'm not sure how to reproduce the flow to get these :S

**Comment by tiblu** [comment]
Done!

![image](https://user-images.githubusercontent.com/7405383/82233029-0b98c100-9938-11ea-8cf3-06c05f8115cc.png)
![image](https://user-images.githubusercontent.com/7405383/82233105-253a0880-9938-11ea-958a-5084da43052a.png)

**Comment by oksks** [comment]
@tiblu Muchas gracias!!! <3

**Comment by loorm** [comment]
Tested. Confirmed.
