### ISSUE TITLE
Ability to copy  and direct link to an argument

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#361]
* Please add a possibility to copy a direct link to an argument.
* Please add a possibility to link to another argument in my argument.

**Comment by loorm** [comment]
Triage 16. Needs investigation. No idea right now how to solve. 

IF investigate_time>16hrs THEN describe_obstacles AND reTriage.

**Comment by tiblu** [comment]
**Development notes**

- [x] New argument should result in redirect to that argument.
- [x] Argument edit should redirect to that edit.
- [x] New reply should redirect to that reply.
- [x] Reply edit should redirect to that edit.
- [x] Delete argument should take back to that argument
- [x] Delete reply should take back to that reply
- [x] Link to an argument on the first page
- [x] Link to an argument reply on the first reply - this means replies have to be expanded to show
- [x] Link to an argument that is NOT on the first page
- [x] Link to an argument reply that is NOT on the first page
- [x] Link to a specific version of an argument (edited argument)
- [x] Link to a specific version of a reply (edited reply)
- [x] When an argument ref is clicked in UI, update URL WITHOUT reloading the page - that is if you 
click @Reply
- [x] When an argument or reply is posted, stay where it's posted, do not reload the whole page or if you do, take me back to where I was.
- [x] Link to another argument **DONE:** As a temporary solution added "Direct link" to the argument actions.

Testing notes:

- [x] Edit reply did not reload properly - after edit 0 arguments are shown.
- [x] Edit argument did not reload properly - after edit 0 arguments are shown.
- [x] "@ReplyReference" links not working (`goToParentComment`)
- [x] INFINITE LOOP - https://dev.citizenos.com:3001/en/topics/212b244b-7f76-4f4c-92b4-2b044fcbf9a7?commentId=604670eb-27b4-48d0-b19b-b6cf6bde33b2_v1&argumentsPage=3

**Comment by tiblu** [comment]
@kevincrepin We're trying to fix argument linking here. One of the things I guess would make sense is to Users to be able to easily copy a link to argument/reply. 

Any suggestions where to put it in the UI and what the UX would be like?

![image](https://user-images.githubusercontent.com/7405383/75773335-5dc53f80-5d56-11ea-892b-7fc59aebfb2e.png)

**Comment by tiblu** [comment]
@loorm Live. Right now implemented somewhat quirky "direct link" in the argument action block. 
Once @kevincrepin provides a better solution, we'll update to that.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working for the current solution.

**Comment by loorm** [comment]
@kevincrepin Please have a look. We need a better UX solution for copying a direct link to an argument. Like a "Share" button or smth.

Right now, clicking "direct link" creates the link in the browser address line, but it took even me 3-4 tries, before I understood this effect. Nothing is displayed, nothing is copied to the clipboard.

**Comment by loorm** [comment]
@ilmartyrk Can these direct links be incorporated into the activity feed? Right now, in a longer discussion, I see from the activity feed, that a reply has been posted, but clicking the link only takes me to the topic, not the argument or reply.

**Comment by kevincrepin** [comment]
Can we iterate a bit on this to reduce the amount of visible actions? Now it's a bit messy to differentiate between message and UI elements.

Maybe we can group the actions?

![Screenshot 2020-05-11 at 12 43 17](https://user-images.githubusercontent.com/26792281/81547924-2fcb2f80-9385-11ea-978d-1ef1d00647f9.png)

**Comment by kevincrepin** [comment]
We also need some positive feedback so the user knows the url has been copied. But we can also open a dialog to give the user some options as to how they could share, similar to how we can share a topic:
![Screenshot 2020-05-11 at 12 46 09](https://user-images.githubusercontent.com/26792281/81548105-6b65f980-9385-11ea-949f-6a4413d1665a.png)

**Comment by tiblu** [comment]
@loorm Does this look good to you? IF so, I think we can take it to triage.

**Comment by loorm** [comment]
"Actions" menu looks good.

@kevincrepin I think for an argument link, the dialog window with many options is too excessive. But we do need some feedback to the use. Perhaps a blue info ribbon at the top of the screen saying "argument link was copied to clipboard, use Paste" or something along these lines?

**Comment by loorm** [comment]
Moving this to Triage. A number of things are ready for dev.
- "Actions" menu for arguments looks good.
- Rights menu for link sharing looks good.
- Social sharing buttons look good.
- When user clicks "Direct link" for an argument, we need to give user some feedback. Currently, there is no feedback. Text is in previous comment. @kevincrepin can advise, which visual method to use for feedback (dialog window vs top of the screen ribbon vs smth else).

**Comment by kevincrepin** [comment]
I would like to propose the snackbar logic for this: A short notification that shows up on the bottom of the page and disappears again after a short while.

I have defined the types of notifications we have so far (not taking into account dialog windows): https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=710%3A23987

**Comment by loorm** [comment]
> I would like to propose the snackbar logic for this: A short notification that shows up on the bottom of the page and disappears again after a short while.

@kevincrepin Is the bottom-of-the-page snackbar in use somewhere, where I could have a look? It'd be good to have a look. "Bottom of the page" sound like it might go unnoticed, but maybe not.

**Comment by kevincrepin** [comment]
Though not at the bottom of the page in this example, it gives the idea. It's a Google Material Design pattern btw.

It needs to strike a fine balance between subtle, but noticeable, because it doesn't need to take up a lot of space all the time.


https://user-images.githubusercontent.com/26792281/132836799-4306a230-cda0-4a60-9dfe-90e88a7b32c5.mov

**Comment by loorm** [comment]
Yes, that was my concern, that bottom of the page may be off balance towards subtle. I've seen snackbars appear near the clicked button or filled field, something like the example above. We're on the same page now @kevincrepin. I'll leave the balancing act to you :) A well-balanced snackbar fits well in this case.

**Comment by kevincrepin** [comment]
Idea: On mobile it's a snackbar at the bottom of the page ( known pattern), but on desktop it's a small floating snackbar tied to your mouse cursor's location:

![Screenshot 2021-09-10 at 15 54 16](https://user-images.githubusercontent.com/26792281/132856418-26b88569-3b87-4f6e-a3b9-1c5d6d18c4d7.png)

**Comment by loorm** [comment]
I feel much more confident about users not missing it this way.

**Comment by anettlinno** [comment]
Triage 45. Separating social sharing link issue from the argument sharing. Est. dev. time 8h. Sending to development.

**Comment by ilmartyrk** [comment]
FIXED: 
https://github.com/citizenos/citizenos-fe/commit/ff8eb7c714663e089a6c08c88450b8703ff784c6
https://github.com/citizenos/citizenos-fe/commit/e12c30633e50ad1363bb58f0f525ccc76003d2b6

**Comment by anettlinno** [comment]
Tested and works nicely 👍
