### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#383]
Replace _Let´s Do It World Keep It Clean_ box with _Hacktivist Community_.

- [x] Remove _Let´s Do It World Keep It Clean_ box
- [x] Add _Hacktivist Community_ box, with description "Civic hacktivist community is meeting space for people who stand for the e-democracy and collaborative decision-making."
- [x] Add new design if proposed by @kevincrepin

**Comment by loorm** [comment]
Copy correction: ""Civic hacktivist community is a meeting space for people who stand for e-democracy and collaborative decision-making."

**Comment by loorm** [comment]
Having a coloured box (the same yellow we used for Keep It Clean looks nice) is fine by me, until @kevincrepin can have a look and propose a design solution.

**Comment by ilmartyrk** [comment]
About half an hour of work

**Comment by loorm** [comment]
Great. Let's make it happen!

**Comment by kevincrepin** [comment]
Added a new image on Invision, based on the visual used on the website: https://citizenos.com/community/

Available here: https://projects.invisionapp.com/d/main#/console/17224475/401979846/inspect

Also a while back @tiblu  said something about remaking all these visuals as circles, so they're also available from the same location.

**Comment by loorm** [comment]
@ilmartyrk Kevin created the design. Can we implement it, please?

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
