### ISSUE TITLE
Voting functionality with printable PDF as contact channel

### ISSUE THREAD

**Issue by jaakkokorhonen** [citizenos/citizenos-fe-old#392]
**What is the problem?**
Not everyone has a desktop, and initiatives might have too much text to read on a mobile.

**Why is this a problem?**
People who do not have laptops or desktops might need a mobile voting channel.
In some cases participation lacks representation if those who should participate are not reachable through digital channels.

**Possible solution.**
Voting functionality with description page as PDF and printable as paper, possibly including mobile 2D-barcode for direct voting.

**Comment by tiblu** [comment]
@jaakkokorhonen Thanks a lot! Added it to the list for prioritization meeting which we have every other week - https://github.com/orgs/citizenos/projects/4

**Comment by loorm** [comment]
Triage 17. Linked to topic printing in General, issue #330. Once we have topic printing, then we can go ahead and work on the current issue.

**Comment by tiblu** [comment]
@jaakkokorhonen With https://github.com/citizenos/citizenos-fe/issues/330 I implemented a solution that provides barcode to the print. Do you find sufficient or you have something else in mind?
Implementation details: https://github.com/citizenos/citizenos-fe/issues/330#issuecomment-600121409

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
@jaakkokorhonen What do you think? On the one hand, QR code is kinda high tec, I suppose. On the other, we need something that is printable and scannable, so QR code or barcode are not that different.
