### ISSUE TITLE
Admin tools could be visible even on a narrow responsive page

### ISSUE THREAD

**Issue by jaakkokorhonen** [citizenos/citizenos-fe-old#393]
**What is the problem?**
When on a narrow page, Done editing and Send to voting are not toggled visible. User is likely to bounce if they do not find the Admin functionalities to proceed.

![app citizenos com_en_topics_68f874f0-bbe7-4a2d-b7ad-5546eefd7259_editMode=true (2)](https://user-images.githubusercontent.com/3482497/73381081-d5263000-42cd-11ea-9d34-965a73cc0a00.png)
![app citizenos com_en_topics_68f874f0-bbe7-4a2d-b7ad-5546eefd7259_editMode=true (1)](https://user-images.githubusercontent.com/3482497/73381082-d5bec680-42cd-11ea-9b8d-2535c8690ef8.png)

**Why is this a problem?**
User gets easily lost if they are on a narrow responsive page, and Done editing and Send to voting are not toggled visible.

**Possible solution.**
Show a visual element for Admin funtionality even when on a narrow page. Or. Toggle Done editing and Send to voting funtionality visible even when on a narrow page.

**Comment by tiblu** [comment]
@jaakkokorhonen Thanks a lot for the report!

We have the "Settings" menu appearing in the header if the page gets narrow which brings up the rights side menu. Seems like that is not visible enough. 
If we fix the visibility/placement issue of the "Settings", would that be enough?
Any ideas where the "Settings" would appear?

**Comment by jaakkokorhonen** [comment]
![app citizenos com_en_topics_a406bf8d-8e03-426c-8e1f-8e6c7be6bfd5_editMode=true argumentsPage=1](https://user-images.githubusercontent.com/3482497/73638484-2b4ef680-4673-11ea-8d5d-2c54662e4743.png)
Just toggling the settings open would not do the rick because they take the whole page.

**Comment by tiblu** [comment]
@jaakkokorhonen What's the problem with covering the whole page? As in, what are the added benefits of seeing half of the topic and the "Settings" instead of "Settings" covering the whole page?

**Comment by jaakkokorhonen** [comment]
![app citizenos com_en_topics_a406bf8d-8e03-426c-8e1f-8e6c7be6bfd5_editMode=true argumentsPage=1 (1)](https://user-images.githubusercontent.com/3482497/73638595-62250c80-4673-11ea-9104-c41ff7b406fe.png)

I guess one option to work around it would be to change language texts so that "OPTIONS" in the right-hanging box would be called something like "Actions", and the "Settings" in the navigation bar would be called the same. 
![Screen Shot 2020-02-03 at 11 03 23](https://user-images.githubusercontent.com/3482497/73639448-15dacc00-4675-11ea-8887-ab42f88ea68e.png)
![Screen Shot 2020-02-03 at 11 02 48](https://user-images.githubusercontent.com/3482497/73639449-16736280-4675-11ea-94fe-e9176ca66f3f.png)

Then the instruction text could say something like:

"You are now in edit mode. You can add text or make changes to it. All changes are automatically saved. *Select 'Done editing' under 'Actions' to see final topic.*"

**Comment by jaakkokorhonen** [comment]
The original problem was that as the Topic author, when i'm done writing my Topic, i cannot *find* the OPTIONS what to do next if my browser window happens to be too narrow, and the article is likely to be left unpublished.

**Comment by tiblu** [comment]
@jaakkokorhonen OK, so I got it wrong from the start. 
The main problem is that on narrow screen you lose the flow actions eg "Whats next?".
@loorm @kevincrepin Do you have any how to improve visibility of flow actions on narrow screens?

**Comment by loorm** [comment]
Triage 17. Need to talk about this. Not ready for dev yet.

**Comment by loorm** [comment]
@kevincrepin What do you think if we did two (rather simple) things:

1. Change the menu name from "Settings" / "Options" (they are currently used interchangeably) to "Actions". It's a more accurate description + one of the sub-menu items is called "Settings" anyway. It's bad logic to nest Settings under Settings.

2. Change the gear icon in mobile view to something else. What that "else" might be requires a bit of creativity. Perhaps a hammer?

**Comment by kevincrepin** [comment]
Let's try it! https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=701%3A23875

**Comment by loorm** [comment]
Thank you, Kevin! Looks good to me. We have the design. Moving to Triage.

**Comment by anettlinno** [comment]
Triage 45. Successfully replicated. Est. dev. time 2h. Sending to development.

**Comment by KatiVellak** [comment]
No legal impact, good improvement.

**Comment by tiblu** [comment]
TODO:

- [x] Rename "Settings" to "Actions"
- [x] Change logo from gear to hammer.
- [x] Active tab logo and text should be black
- [x] Active tab background to match the rest of the page background. That is, it matches when "Actions" are open as the menu background is same gray as the menu, but when for example you are in "Edit" mode, the background should match the editor background.
- [x] Actions not to take full page height.
- [x] Click/touch outside the `.side_panel` closes the "Actions".

**Comment by tiblu** [comment]
**DONE!** 

@jaakkokorhonen Does the fix work for you? 

![image](https://user-images.githubusercontent.com/7405383/133440974-fed14195-853e-415e-bfb6-8efce61dd262.png)
