### ISSUE TITLE
BUG: No tooltip on hover over "Topic report" or "Add to favourites" in topic

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#394]
There are 2 icons visible in an open topic: 
<img width="836" alt="Screenshot 2020-02-03 at 16 03 05" src="https://user-images.githubusercontent.com/34126353/73659422-e771e680-469e-11ea-88fc-c06373a88f82.png">

Both of them should have a tooltip when hovering over the icons, but neither one does. 
It's not clear, what their purpose is, what actions will be taken and with which consequences, if a user clicks on either icon.

Please add tooltips to all icon-only buttons.

**Comment by loorm** [comment]
Triage 17. We have a tool tip directive that we can use for this. Estimated dev time 4 hours, because placement of icons is in top right corner. Placement might be an issue.

**Comment by loorm** [comment]
I don't even see the "report" icon for some of my topics. Picture attached of an example (I have edit rights, but I am not the topic creator). 
![missing_report_button_capture](https://user-images.githubusercontent.com/22661743/74648858-2025bb80-5187-11ea-9be4-5b5572a9f7d4.JPG)

**Comment by tiblu** [comment]
TODO:

- [x] Tooltips
- [x] Investigate why report button MAY be missing for @loorm  - https://github.com/citizenos/citizenos-fe/issues/394#issuecomment-586943547

**Comment by tiblu** [comment]
Done!

**Comment by tiblu** [comment]
@loorm Notes on the implementation:

* Dashboard topic list uses browser native tooltip cause the non-native makes page load very slow when the Topic list is very long.
* All other places use the non-native tooltip.

![image](https://user-images.githubusercontent.com/7405383/74963592-a9a0ec00-541a-11ea-809d-ad36e349bdba.png)


@loorm **Question: Would it make sense to use the native tooltip everywhere? Assuming there is no need to copy text from the tooltip? Native tooltip performs better and is supported by screen readers.**

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
> @loorm **Question: Would it make sense to use the native tooltip everywhere? Assuming there is no need to copy text from the tooltip? Native tooltip performs better and is supported by screen readers.**

@tiblu You said "cause the non-native makes page load very slow when the Topic list is very long". Is it possible to be more specific? What is a "very long" topic list? I have about 160 in my list, is that very long? And then what is "very slow" in ms?

Generally, a uniform application is better, but it's impossible to decide, if I don't know the numbers (even approx numbers will do).

**Comment by loorm** [comment]
Tested. Confirmed working. 

Esp. like the way report and pin topics are coloured from inside out on receiving focus. Nice little touch!

**Comment by tiblu** [comment]
> > @loorm **Question: Would it make sense to use the native tooltip everywhere? Assuming there is no need to copy text from the tooltip? Native tooltip performs better and is supported by screen readers.**
> 
> @tiblu You said "cause the non-native makes page load very slow when the Topic list is very long". Is it possible to be more specific? What is a "very long" topic list? I have about 160 in my list, is that very long? And then what is "very slow" in ms?
> 
> Generally, a uniform application is better, but it's impossible to decide, if I don't know the numbers (even approx numbers will do).

Not sure where the limit is and where the problems would start for the most of the users. IT does depend on the power of your machine.
Should I do some measurement and play around? IT's probably a good 4 hours of work to figure out how to reliably measure page performance and get numbers that are somewhat reliable. 
Still, these numbers would apply to the machine I have, not sure how they would change on lower spec hardware.

**Comment by loorm** [comment]
@tiblu So which takes more time - (A) trying to establish page load times for long topic lists with non-native tooltips or (B) changing to native tooltips everywhere? 
IF time(B) is < 4hrs THEN B 
ELSE A

**Comment by tiblu** [comment]
NOTE: By a mistake I have added wrong issue link and thus Group invite commits show up here. They actually belong to issue https://github.com/citizenos/citizenos-fe/issues/348
