### ISSUE TITLE
BUG: Etherpad -  Authors list is not visible when toolbar is on multiple lines

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#395]
**What is the problem?**

Authors list is not visible when toolbar is on multiple lines.

![image](https://user-images.githubusercontent.com/7405383/73836073-2d51ba80-4817-11ea-9ea0-1feb3985d48b.png)

See:

* https://github.com/tiblu/ep_authorship_toggle/issues/1

**Possible solution.**

Fix https://github.com/tiblu/ep_authorship_toggle/issues/1

**Comment by loorm** [comment]
Triage 17. Estimated dev time 1 day.

**Comment by tiblu** [comment]
Duplicate of:

* https://github.com/tiblu/ep_authorship_toggle/issues/1

**Comment by tiblu** [comment]
Done!

* Fixed menu multiline issues
* Added responsiveness
* Increased font size of the authors so that it's readable.

![image](https://user-images.githubusercontent.com/7405383/74963967-44012f80-541b-11ea-90fd-995fc474a6a6.png)

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
