### ISSUE TITLE
BUG:  Etherpad - inline comments - confusing user experience with "Include suggested change" functionality

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#396]
**What is the problem?**

When adding an inline comment, there is "Include suggested change" feature.
Problem is, when I add a new comment, there is a checkbox with "Include suggested change" but when I click it, nothing happens.
Works only for inline comment replies.

![image](https://user-images.githubusercontent.com/7405383/73836557-38f1b100-4818-11ea-8cc8-70c9b0a248ec.png)

**Why is this a problem?**

Cannot propose changes.

**Possible solution.**

- [ ] Inline comment "Include suggested change" functionality works the same way as for it's replies.

**Comment by tiblu** [comment]
Triage 17: Need to re-test this, I think it may have been out of scroll. I think I saw it working fine on Wed.

**Comment by tiblu** [comment]
Could not reproduce.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
