### ISSUE TITLE
Etherpad - ep_title_limit - title limit notification text styles are not consistent with the rest of the styles

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#397]
**What is the problem?**

Title limit notification text styles are not consistent with the rest of the styles

![image](https://user-images.githubusercontent.com/7405383/73837758-c930f580-481a-11ea-9aab-bde88bc8877d.png)

**Why is this a problem?**

Makes for an ugly visual.

**Possible solution.**

- [ ] Fix the styles, starting from font. Maybe even re-style the whole messsage?

**Comment by loorm** [comment]
Triage 17. Use blue info box style. Estimated dev time 3 hours.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by ilmartyrk** [comment]
This has been fixed by updating EP to new version and theme
