### ISSUE TITLE
BUG: "no permission" error message when creating topic into the group

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#410]
**What is the problem?**
I created new topic into the group and error message "You don´t have permission to complete the topic" occurred. When I went to "My topics", the topic was created and I was able to continue editing the text but the topic is not in the group where I opened it. 
 
<img width="956" alt="Error message" src="https://user-images.githubusercontent.com/45175679/74151637-42fb2180-4c15-11ea-8cbc-0a615d1ef14b.png">

**Why is this a problem?**
After creating the topic and seeing this error message, I was not able to continue creating the topic and I was not sure, if the topic was created or not. After checking under "My topics" and opening this, I understood that it is created, but I still could not find it from the group where I created it. 

**Possible solution.**
As I am member of this group, this error message should not occur

**Comment by loorm** [comment]
Attempted to replicate. Could not. Everything worked.

**Comment by tiblu** [comment]
Could not reproduce the issue but added some more logging to have more info when it actually fails.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
