### ISSUE TITLE
Mobiil-ID signing - 500 error when cancelling signing on the phone

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#411]
**Reproduce**

* Create Topic
* Set up voting with hard-auth.
* Start voting with Mobiil-ID
* When PIN is displayed on the phone, click "cancel"

**Result**

* 500 generic server error

![image](https://user-images.githubusercontent.com/7405383/74166311-0a684180-4c2f-11ea-83f5-f73e6d9994d7.png)

**Expected**

* User friendly error message saying that User has cancelled the vote process.

**Comment by loorm** [comment]
Triage 18: used to work, works no longer. Error message is generic, not specific, as it should be.  Classified as a bug. Dev time ETA - 2 hours.

**Comment by ilmartyrk** [comment]
@loorm @tiblu , cannot replicate, working fine

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working fine. Must have been a temporary problem or got fixed inadvertently with another fix.
