### ISSUE TITLE
BUG: Smart-ID icon not shown in appropriate places

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#414]
**What is the problem?**
When choosing eID vote signing, only logos for ID-card and mobile-ID are shown. Smart-ID logo does not show up.

![Capture](https://user-images.githubusercontent.com/22661743/74229626-713b3880-4ccb-11ea-8cb2-b7d10e3605ac.JPG)
![Capture2](https://user-images.githubusercontent.com/22661743/74229637-76988300-4ccb-11ea-915f-0d39ba435ec4.JPG)

**Why is this a problem?**
It provides incomplete information to user about secure voting options.

**Possible solution.**
Add Smart-ID icon.

**Comment by loorm** [comment]
Same as #412. Closing...

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
