### ISSUE TITLE
Change 'Show all' public topics sorted according to date 

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#415]
**What is the problem?**
In public topics view (show all view), topics appear outdated because they are not sorted by date.

**Why is this a problem?**
The environment itself appears outdated, like there is nothing going on, when in fact there is.

**Possible solution.**
Change to date for updating public topics (show all view).
![Screenshot 2020-02-12 at 12 34 23](https://user-images.githubusercontent.com/34899902/74326983-073a9600-4d94-11ea-8e2b-9c8b06e8df75.png)

Similar bug: https://github.com/citizenos/citizenos-fe/issues/231

**Comment by tiblu** [comment]
Related to:

* https://github.com/citizenos/citizenos-fe/issues/231 - more thorough fix

**Comment by loorm** [comment]
Triage 18: **let's move to state-independent sorting by most recent activity date in descending order.** Reason - in public view, users and guests want to see whatever is the most recent activity, regardless of state. You can filter for different states with a drop down.

Dev time ETA: 2 hours

**Comment by tiblu** [comment]
> Triage 18: **let's move to state-independent sorting by most recent activity date in descending order.** Reason - in public view, users and guests want to see whatever is the most recent activity, regardless of state. You can filter for different states with a drop down.

That is sort by `Topic.updatedAt DESC`, do not take `status` into account in default view. There are special filters for that.

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-api/commit/c734a5ddbab5fceb6fe8799e8c5500a850f9829e

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
