### ISSUE TITLE
Add "copy topic" functionality

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#416]
**What is the problem?**
If I want to create a copy of the topic, I have to copy-paste contents, add users again etc. 

**Why is this a problem?**
It takes more time compared to clicking "copy topic" somewhere, which would automatically copy everything over.

**Possible solution.**
Create "copy topic" functionality and UX.

**Comment by tiblu** [comment]
**Triage 18**

* All permissions have to be transfers
* Only Admin members can copy
* Do we need to transfer with status? That is if original is "in-voting", copy will also have "in-voting".
* NEW join links
* Attachments need to be copied over

I guess it needs open discussion.

**Comment by loorm** [comment]
Let's make it simple. Let's call it "Copy content":
- create a new private topic with "in progress" status
- copy topic content as is on the moment of copying (including images, footnotes, comments)
- copy attachments

Do not copy:
- settings (public / private, voting systems, hashtags etc)
- permissions (users, groups)
- history (Etherpad edit history, activity feed items, mini-votes)
- discussion (arguments, replies)
- related information (topic status, pinned status)
- votes
- follow-up posts

Anyone with at least edit rights can copy content of the topic.

**Comment by loorm** [comment]
@kevincrepin We need to put the "Copy content" link somewhere. Likely place is "Options" box.

**Comment by loorm** [comment]
Ping @kevincrepin

**Comment by kevincrepin** [comment]
I would call it "Duplicate Topic" and include a dialog window that shows what will and what won't be duplicated:

Duplicate in actions menu: https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?page-id=2%3A16032&node-id=675%3A23227&viewport=299%2C48%2C0.5&scaling=min-zoom

Dialog: https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?page-id=2%3A16032&node-id=675%3A23570&viewport=299%2C48%2C0.5&scaling=min-zoom

**Comment by loorm** [comment]
We have the designs. Ready for triage.

**Comment by anettlinno** [comment]
Triage #45 In dialog box, let´s write under the "Are you sure you want to duplicate this topic" -- "This will create **and open** new private topic with "in progress" status". Est. dev. time 5 days.

**Comment by KatiVellak** [comment]
Reviewed and discussed by legal. 

@kevincrepin one suggestion - replace the button "Yes, overwrite" with "Yes, duplicate" for the sake of clarity. otherwise it might confuse that the topic will be overwritten, not duplicated. 

Otherwise legally no other impacts.

**Comment by ilmartyrk** [comment]
Development tasks:
- [x] Update Etherpad API client
- [x] Update ep_inline_voting plugin
- [x] Add API endpoint
- [x] Add tests

Administrative tasks:
- [x] Update CHANGELOG files
- [x] Inform marketing of new feature(s)
- [x] Inform localization on new translations

**Comment by ilmartyrk** [comment]
@loorm if copy content as is, then why not include mini-votes. Currently Etherpad has really good support for copying pad contents, but adding extra feature for removing mini-votes from API side is quite a pain. Would it make more sense to add option for user to remove mini-votes from UI?

**Comment by anettlinno** [comment]
> @loorm if copy content as is, then why not include mini-votes. Currently Etherpad has really good support for copying pad contents, but adding extra feature for removing mini-votes from API side is quite a pain. Would it make more sense to add option for user to remove mini-votes from UI?

From the User´s perspective it sounds logical that mini-votes are being duplicated as all the other content-related co-creations are duplicated (comments, footnotes etc).

**Comment by loorm** [comment]
> > @loorm if copy content as is, then why not include mini-votes. Currently Etherpad has really good support for copying pad contents, but adding extra feature for removing mini-votes from API side is quite a pain. Would it make more sense to add option for user to remove mini-votes from UI?
> 
> From the User´s perspective it sounds logical that mini-votes are being duplicated as all the other content-related co-creations are duplicated (comments, footnotes etc).

I concur.
