### ISSUE TITLE
FEATURE: better Activity Feed icon for inviting users?

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#417]
**What is the problem?**
A red exclamation mark sreams at you. 
![Capture4](https://user-images.githubusercontent.com/22661743/74332161-d52e3180-4d9d-11ea-8534-90deee19e1d3.JPG)

**Why is this a problem?**
Maybe a tad bit extreme for user invite events?

**Possible solution.**
A more moderate icon, perhaps.

**Comment by loorm** [comment]
@kevincrepin For your consideration.

**Comment by kevincrepin** [comment]
Yep, that's extreme :) I placed an icon for any kind of invitation notification on https://projects.invisionapp.com/d/main#/console/9829159/241763981/inspect

<img width="55" alt="Screenshot 2020-02-14 at 14 32 07" src="https://user-images.githubusercontent.com/26792281/74532030-d9da1d80-4f36-11ea-8ac2-f932f8f3b65b.png">

**Comment by tiblu** [comment]
Forgot the Group invites.

**Comment by tiblu** [comment]
Added the icon for Group invites.

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
