### ISSUE TITLE
Social media and search engine metatags from articles

### ISSUE THREAD

**Issue by jaakkokorhonen** [citizenos/citizenos-fe-old#420]
As article writer, i want to share my article in a enticing way on social media and search engines.
![image](https://user-images.githubusercontent.com/3482497/74829595-0799da80-531a-11ea-8a99-4026d894a5bb.png)

Namely, title (~95 chars), description (~297 chars) and image:
`
<meta property="og:title" content="How to Become an SEO Expert (8 Steps)" />
<meta property="og:description" content="Get from SEO newbie to SEO pro in 8 simple steps." />
<meta property="og:image" content="https://ahrefs.com/blog/wp-content/uploads/2019/12/fb-how-to-become-an-seo-expert.png" />
`
https://ahrefs.com/blog/open-graph-meta-tags/

**Comment by loorm** [comment]
Triage 18: Pre-render issue. Dev time ETA: 8 hours.

**Comment by tiblu** [comment]
Related to:

* https://github.com/citizenos/citizenos-fe/issues/259

**Comment by tiblu** [comment]
**NOTE:** Can and MUST be only implemented for public Topics. CANNOT and is NOT OK to implement for private topics.

**Comment by KatiVellak** [comment]
Discussed with Mikk, can only be used for public topics.

**Comment by liinaguiter** [comment]
Highly important for #marketing!

**Comment by tiblu** [comment]
Done! @jaakkokorhonen does this solve the issue or you have more in mind?

The preview image is the first one found in the topic, BUT I've seen SOMETIMES Facebook override it and take some other image from topic.

* Facebook - 
![image](https://user-images.githubusercontent.com/7405383/82899645-005f1a00-9f64-11ea-821c-715733fe17b0.png)
* Skype - 
![image](https://user-images.githubusercontent.com/7405383/82899609-f3dac180-9f63-11ea-9660-9a9d4b8b32b7.png)
* Slack -
![image](https://user-images.githubusercontent.com/7405383/82899731-22f13300-9f64-11ea-83a2-8770330dacdc.png)

**Comment by tiblu** [comment]
Updated image previews as part of #166 - now taking first image from the topic, if there is none, it will show Citizen OS logo - https://github.com/citizenos/citizenos-fe/issues/166#issuecomment-633989073

**Comment by loorm** [comment]
Tested.

Facebook - not working (see image)
LinkedIn - OK
Skype - OK

![FB_Capture](https://user-images.githubusercontent.com/22661743/82900387-1de0b380-9f65-11ea-8ba7-4d80cf038146.JPG)

**Comment by tiblu** [comment]
@loorm I think it's an issue with the new FB redesign, if you switch back to classic mode, the previews look fine - 
![image](https://user-images.githubusercontent.com/7405383/82910250-145e4800-9f73-11ea-8476-8fccecbfbe6d.png)
Also their preview testing app looks fine - https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fapp.citizenos.com%2Fet%2Ftopics%2F6455dc68-ed64-4209-8b28-9b29a41728fb

So, I think there is nothing else to do but to wait and see if the compact preview is a design decision or full previews have not implemented jet.

**Comment by tiblu** [comment]
Also, FB docs say that images are processed async, thus image preview is delayed and usually does not show on first post of the link.
FB re-scrapes all previews every 24h.
Also, had an instandce today where FB new layout was showing OK for a link posted:
![image](https://user-images.githubusercontent.com/7405383/82987165-c8a5b000-9fff-11ea-841d-6d9bac656cf4.png)

Sources:

* https://developers.facebook.com/docs/sharing/best-practices
