### ISSUE TITLE
Topic filtering not working properly

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#427]
**What is the problem?**

When using the topic filter drop down menu to navigate to a certain group of topics, it isn't working smoothly. 

For example, if I choose '34 Islands Project', it takes me to screenshot 1, with all the 34 Islands topics - as expected. However, when I want to browse in and out of the topics it keeps taking me back to the home screen (screenshot 2) every time I use the 'back' button in my browser. 

For example, if I want to look into each of the topics in turn - first I go into the first topic (Sampah di Pesisir Pantai Aceh Barat), then click the back button, expecting to be taken back to screenshot 1, but instead I am taken all the way back to screenshot 2. This means that if I have to then select the '34 Islands Project' filter from the dropdown box every time I want to go into the next topic. 

![image](https://user-images.githubusercontent.com/61320526/75040919-deb14b00-54bb-11ea-9301-1d60ce83330d.png)

![image](https://user-images.githubusercontent.com/61320526/75040959-ef61c100-54bb-11ea-852d-2551d88e93fb.png)

**Why is this a problem?**
Not good UX - it is confusing and time-consuming, and seems to be a bug. 

**Possible solution.**
That when you click the back button while viewing a topic after navigating to it using the filter dropdown menu, you are taken back to the filtered topics to choose from (screenshot 1), not to the home screen (screenshot 2).

**Comment by loorm** [comment]
Triage 18: replicated. Dev time ETA: 8 hours.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
