### ISSUE TITLE
"Edit topic" button is not working properly in mobile view

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#434]
**What is the problem?**
I have admin rights to the topic. I go to my topics. Click on the topic. Then click on the title of the topic. I get the HTML view of topic content, but edit button at the top of the screen is greyed out and unclickable.

It is a problem of the button only. If I click the menu and then choose "Edit topic", then I can edit. Similarly, if I click "edit" right from the my topics view, I can edit. 

And once I start editing by other ways, the button turns especially weird (see screenshot).

**Why is this a problem?**
Regular users may not know of other ways to edit. They may also think, that they have insufficient rights etc.

**Possible solution.**
@tiblu already though of a solution during Triage 19. He gave dev time ETA as 15 mins.

![Screenshot_20200309_105144_com android chrome](https://user-images.githubusercontent.com/22661743/76201588-280fd300-61fc-11ea-93ee-8ce004273b30.jpg)

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
