### ISSUE TITLE
BUG: Public topics "boxes" categories do not work

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#436]
**What is the problem**: 
If you click on the "Hacktivist Community" or other boxes on the Public Topics page, all the categories are mixed. 

<img width="959" alt="Box" src="https://user-images.githubusercontent.com/45175679/76451946-f011b700-63d8-11ea-864f-d9dd7c5f3dc8.png">

**Why is this a problem:**
I want to see only topics that are created by this community, not all topics from all categories.

Possible solution: 
Please fix the categorization for each box.

**Comment by loorm** [comment]
Tested. Confirmed working.
