### ISSUE TITLE
Misleading generic error message

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#444]
**What is the problem?**
When I click "Show all my topics" => "Pinned topics":
<img width="407" alt="Screenshot 2020-03-24 at 19 14 54" src="https://user-images.githubusercontent.com/34126353/77456698-497bdc00-6e04-11ea-8c56-76cffa2b4397.png">

Then this is what I get:
<img width="1101" alt="Screenshot 2020-03-24 at 19 19 14" src="https://user-images.githubusercontent.com/34126353/77456761-5f899c80-6e04-11ea-8089-1e755c61e209.png">

The info we're serving is not true, as I just don't have any pinned topics at that moment - generic error message doesn't align with the action. The same applies for other options in the dropdown, too - we should have specific error messages for each option.

**Why is this a problem?**
It's confusing and outright misleading. Probably also scary to be told, that I haven't participated in any topics yet, while I may have contributed to loads of them.

**Possible solution.**
Create error messages for each dropdown option.

**Comment by loorm** [comment]
Triage 20 - replicated. Prioritizing.

**Comment by KatiVellak** [comment]
Legally reviewed, no comments.

**Comment by loorm** [comment]
@kevincrepin Can you please create a generic visual for "No topics found." that we could usr whenever someone chooses a category, where they have no topics? Right now, we are using the initial page that new users get and I agree, it's slightly misleading.

**Comment by kevincrepin** [comment]
In dashboard: https://projects.invisionapp.com/d/main#/console/9829159/419277028/preview
Let's also update the other empty states then, for example: 
https://projects.invisionapp.com/d/main#/console/9829159/419278099/preview

**Comment by tiblu** [comment]
@loorm  Looks good to me, can be taken to triage.

**Comment by loorm** [comment]
Scheduling for Triage 23 on June 8.

**Comment by loorm** [comment]
Triage 23. Ready for dev. Prioritizing. Estimated dev time 4 hours.

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-fe/commit/27aa06103d3dfae098043a710ca36edb15a97120
