### ISSUE TITLE
Analytics: Get rid of Google Analytics - analytics that do not share data with 3rd parties

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#457]
**What is the user story?**

While Google Analytics is a powerful tool, using it means that data in some shape or form is shared with 3rd party - Google. In respect to Users privacy, we do NOT want that.

**What is the requested feature?**

We have following options:

* Implement minimum viable analytics into Citizen OS app itself. All data collected would be kept in application database. This would be default analytics.
    * NOTE: We do not have to build system ourselves, search for OSS packages.
* Make analytics configurable. By default, GA should be off. IF possible, enable configuring whatever analytics maintainer wants, do not lock in to GA.

**CALL TO ACTION!**

* In order to implement any analytics, we need to know what we actually need to collect, what information do we need on User behavior to develop a better product?
* IF we do this task, please check with @KatiVellak IF we can remove cookie consent as ONLY required cookies would remain used on the site.

**Comment by tiblu** [comment]
Some alternatives to GA:

* https://plausible.io/ - OSS simple and lightweight analytics. Claims to be GDPR compliant.
* https://matomo.org/ - full blown OSS GA alternative. Can be installed on premise.

**Comment by tiblu** [comment]
What data do we want from new analytics:

* how long people spend time on each page,
* bounce rate - bounce rate is the percentage of visits that go to only one page before exiting a site
* how many ppl are visiting each page
* what country (and perhaps what region) are the visitors from
* how many ppl per region / country

**Comment by loorm** [comment]
Triage 20 - this needs further input from @KatiVellak. We're leaning towards plausible.io. Long term goal is to get rid of cookie notification altogether.

**Comment by loorm** [comment]
Triage 21: Our goal is to get rid of cookie notification and Google Analytics is the main reason we currently have to have it. We are wondering, if using an alternative service will enable us to get rid of our cookie notification.

@KatiVellak Can you verify that Plausible.IO can possibly be GDPR compliant **without showing a cookie notification to the end user**? https://plausible.io/data-policy

**Comment by KatiVellak** [comment]
@tiblu @loorm  From all the information I was able to retrieve, it does seem that Plausible does not use cookies nor collect any personal data, thus we are not required to display a cookie notice by using Plausible analytics.
The reason being that by not using cookies you do not need to obtain consent from the visitors to store and retrieve data from their devices. 
Hence, I can verify that to my knowledge using Plausible analytics doesn´t require cookie notice in case besides of Plausible we only use necessary cookies.

**Comment by loorm** [comment]
We have the legal opinion. Thank you, Kati! Moving issue back to Triage.

**Comment by tiblu** [comment]
Triage 22. If we want Plausible, we must:

* Verify that marketing gets the data they need, see comment https://github.com/citizenos/citizenos-fe/issues/457#issuecomment-617130795
* Are we OK to pay for it?

**Comment by loorm** [comment]
Asking Liina (marketing) to take a look at Q1 above. Once we info on this, move to Q2.

**Comment by liinaguiter** [comment]
Plausible fulfills our marketing needs. Thank you for this process!

**Comment by liinaguiter** [comment]
Let's go for Plausible and please remember to switch both the platform and the website! Thank you.

**Comment by tiblu** [comment]
We MAY WANT to run a test period, where we run Google Analytics and Plausible in parallel.
Plausible would be enabled ALWAYS (being GDPR compliant).
GA would be enabled IF allows it.

It would give us some info:

* How many of the Users actually enable analytics
* How the Plausible data compares to GA

**Comment by loorm** [comment]
Triage 35. Green light. @liinaguiter Please handle the registration for the service and ask them to send an invoice for the whole year (to use the 33% discount). **This needs to happen before we can do the technical implementation.**

2 months test period starting whenever Plausible starts tracking us.

Estimated developer time: 1 hour.

**Comment by tiblu** [comment]
@loorm @liinaguiter 

What do you think, is it worth running both GA and Plausible in parallel for a while or not?

**Comment by liinaguiter** [comment]
We have an account now on Plausible: Citizen OS Foundation. 30 days trial for free. @loorm, may I have the credit card please to pay for the whole year? 

@tiblu Login: alex@citizenos.com (see ongi loodud igasuguste loginide jaoks)
Password: Veesoda400

**Comment by tiblu** [comment]
@loorm @ilmartyrk @liinaguiter I will "fast track" this. I feel like this provides more value than other things in the priority list.

**Comment by tiblu** [comment]
@loorm @anettlinno @liinaguiter 
Decided not to run the 2 analytics in parallel:
* First of all, the sample size in this testing would be small, that is new user sample size.
* We can see the difference comparing GA stats from weeks back and Plausible.
* We can make a clean solution - get rid of all code related to the cookie policy and analytics.

**Comment by tiblu** [comment]
### Checklist

- [x] Custom DNS setup in Plausible - https://plausible.io/docs/custom-domain
- [x] Remove GA related code
- [x] CSP - remove GA domains, add `stats.citizenos.com`
- [x] Remove cookie policy related code
- [x] Insert Plausible snippet
- [x] Exclude `test` and `dev` from the traffic.

**Comment by tiblu** [comment]
**Done!**

* Removed all GA related code.
* Removed all cookie policy related code.
* Using Plausible.
* Analytics configurable from env `CITIZENOS_FEATURES_ANALYTICS` (JSON)
* Created a task for Citizen OS Web (landing page) to switch over to Plausible (https://github.com/citizenos/citizenos-web/issues/161)
