### ISSUE TITLE
Google picker script outdating

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#459]
**What is the problem?**
We are using google-api.js script for google picker to add files as topic attachments. Google sometimes updates this script and it breaks the picker as we have outdated code.
**Why is this a problem?**
Users might not be able to add attachment files from google drive without even getting an error.

**Possible solution.**
Load script from google URL or find some solution to automagically update it in our javascript lib directory

**Comment by tiblu** [comment]
Maybe we can add this script into CSP rules and load it from Google? It is a somewhat trusted source?

**Comment by tiblu** [comment]
We could:

* Update the script on build process - has no impact when app is not released.
* Try to make CSP exception

**Comment by loorm** [comment]
Triage 20 - est dev time 3 hrs. Prioritizing.

**Comment by tiblu** [comment]
To help prioritization - the Google Drive attachments are NOT very popular. Last 30 days only 4 requests:

![image](https://user-images.githubusercontent.com/7405383/80607256-f833bd80-8a3d-11ea-8de5-22838ce6fd93.png)

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
