### ISSUE TITLE
Weird user name in Etherpad user list

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#463]
**What is the problem?**
Weird user name displayed in Etherpad user list.

**Why is this a problem?**
I don't know who the real user is.

**Possible solution.**
N/A

![Capture](https://user-images.githubusercontent.com/22661743/80379186-6a719a00-88a6-11ea-9ac7-4bd5422d36f6.JPG)

**Comment by ilmartyrk** [comment]
Seems like translation function error, key exists but something is going wrong so it displays translation key instead of real value

**Comment by loorm** [comment]
Triage 20 - estimated dev time 3 hrs. Prioritizing.

**Comment by tiblu** [comment]
Done! 
MAY need browser cache to be cleared in order to work.

![image](https://user-images.githubusercontent.com/7405383/82322978-0a22d380-99e0-11ea-8ffd-2c198ee37043.png)

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
