### ISSUE TITLE
Report a Topic - hide/show moderated topics

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#464]
**What is the user story?**

As a User, I would like moderated Topics to be viewable, but not prominent in the UI.

Example:

* Anett reported public Topics that we're essentially a tests by User. Anett wanted them to be hidden from the Home page so that they do not clutter the view.
    * https://app.citizenos.com/en/topics/c984cd9b-baf3-4d4d-87b7-3c7d56aca307
    * https://app.citizenos.com/en/topics/72a8252d-1cb9-4962-a7e1-bd6f4b3629b1
* I moderated these Topics, marked them as "Test or unfinished topic without content".
* BUT, the Topics are still present on the Home page, cluttering the view.

Forgotten part of https://github.com/citizenos/citizenos-api/issues/5.

**What is the requested feature?**

Everywhere where we display Topic title or content, we  need a way to mask/mark/hide moderated topics it until there is user request to view it anyway. 
Among these are:
* Search results
* Home page
* Topics list view

![image](https://user-images.githubusercontent.com/7405383/58480400-f47b2500-8162-11e9-91fd-ce779f1c46b6.png)

![image](https://user-images.githubusercontent.com/7405383/58480558-402dce80-8163-11e9-8ff9-b2cbc3e0d76c.png)

![image](https://user-images.githubusercontent.com/7405383/58484975-d1a13e80-816b-11e9-9cf9-46959266d864.png)

**Additional information.**

Related to:

* https://github.com/citizenos/citizenos-api/issues/5

**Comment by loorm** [comment]
Triage 20 - decision as follows:
Search results - no change.
Home page - hide from default view. Add filter to home page for showing reported topics.
Topics list view - no change for now, @KatiVellak we need your input on this. Can we show reported topics in "My topics list"?

**Comment by loorm** [comment]
Related to https://github.com/citizenos/citizenos-api/issues/140

**Comment by loorm** [comment]
Also related to https://github.com/citizenos/citizenos-api/issues/5#issuecomment-500161340

**Comment by loorm** [comment]
@kativellak can you take a look at the question above, please?

**Comment by KatiVellak** [comment]
@tiblu @loorm can we have a short call on this, please?

**Comment by loorm** [comment]
> @tiblu @loorm can we have a short call on this, please?

Sent a calendar invite to both of you.

**Comment by loorm** [comment]
Had a meeting. Decision for topics, that have been reported AND where moderator has decided, that restricting access is justified.

Search results - do not show restricted topics.
Home page (public topics view) - hide from default view. Add filter to home page for showing restricted topics.
Topics list view (every users' own) - hide from default view. Add filter for showing restricted topics.

**Comment by loorm** [comment]
Triage 23. Ready for dev. Prioritizing. Estimated dev time up to 6 hours.
