### ISSUE TITLE
Activity feed direct link to comments

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#468]
@ilmartyrk Can these direct links be incorporated into the activity feed? Right now, in a longer discussion, I see from the activity feed, that a reply has been posted, but clicking the link only takes me to the topic, not the argument or reply.

_Originally posted by @loorm in https://github.com/citizenos/citizenos-fe/issues/361#issuecomment-621028817_

**Comment by loorm** [comment]
Triage 20 - est dev time 6 hrs. Prioritizing.

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
