### ISSUE TITLE
Unable to open topic from the invite email after the initial access

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#469]
**What is the problem?**
After I've accepted Margo's invite to a topic (via clicking the link in invite email), trying to access the topic via the same path takes me to COS app frontpage with an error message "Sorry, the invite to a topic has been deleted."

<img width="819" alt="Screenshot 2020-04-29 at 12 25 55" src="https://user-images.githubusercontent.com/34126353/80607813-9c1d6900-8a3e-11ea-993b-c27e140a1069.png">

Margo has confirmed he hasn't deleted my invite.
I do, however, see the topic and can access it from under "My topics".

**Why is this a problem?**
It leaves an impression, that my access to the topic has been revoked, while this isn't true.

**Possible solution.**
Topic invite link in the email should stay active as it's convenient to re-access the topic via email - if I click the link again, I should be taken to the topic.
IF we must notify the user, that he's already used up the invite for this topic, we should say "You've already accepted an invite to this topic". 
But imho this error message is absolutely unnecessary after the first access.

**Comment by loorm** [comment]
Right now, this works "as designed". We designed invites to be single-use. I agree, that this parts from what has emerged as "standard" in online tools, where e-mailed invites in most cases can be indefinitely perused. Will discuss at triage 21 if and how to change.

**Comment by loorm** [comment]
Triage 21. Est. dev hours 1 day. Prioritizing. Tentative idea for fix - check if user is already topic member when following invite link.

**Comment by tiblu** [comment]
Done, now all old links should work and take you to the Topic IF you still have access to the Topic.

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
