### ISSUE TITLE
Wrong terminology - "signing" is used instead of "voting"

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#471]
**What is the problem?**
We talk about signing deadline, when we should be talking about voting deadline.
![signing_deadline](https://user-images.githubusercontent.com/22661743/81055759-09634b00-8ed2-11ea-8531-9dd58ba1e1bf.jpg)

**Why is this a problem?**
Confusing for users, when mixing different terms.

**Possible solution.**
Use "voting deadline" instead, since that's the date when voting ends.

**Comment by loorm** [comment]
Triage 21. According to @tiblu, this is for @oksks to fix. Prioritizing.

**Comment by oksks** [comment]
I'll correct this in Github right away - seems to be present only in one place.

**Comment by oksks** [comment]
Fixed, though imho it should be fixed in the key as well, to avoid reappearing.
`"BAR_SIGNING_DEADLINE": "Voting deadline:",
`

**Comment by loorm** [comment]
Tested. Confirmed working for English and a few other languages that I speak.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
