### ISSUE TITLE
Activity Feed doesn't show new activities' badge upon login

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#472]
**What is the problem?**
If any new activities happen while I was **logged out**, upon login the Activity Feed button doesn't show the red circle with a number any longer - looks like there's been no new activities since my last visit. If I open AF, there can be plenty of new ones - they just haven't been marked as such.

BUT while I'm logged in to my account, everything works fine - activities trigger a notification almost immediately, as usual.

**Why is this a problem?**
User might miss all new activities in the topics, that happen while they're logged out of their account.

**Tech details**
MacOS Catalina, Chrome is up to date (Version 81.0.4044.129 (Official Build) (64-bit).

**Comment by loorm** [comment]
Triage 21. Confirmed. 
@ilmartyrk - can you please put estimated fix time?
Prioritizing.

**Comment by ilmartyrk** [comment]
Estimate MAX 1 hour, can be a lot less if done during some other task associated with activity feed

**Comment by oksks** [comment]
Tested, works. Thanks!

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
