### ISSUE TITLE
Activity Feed stays visible after log-out

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#473]
**What is the problem?**
After logging out of my account while having Activity Feed open, the post-log-out screen kept showing my AF. 
Tried to reproduce it - seems to happen, while any of the expandable/collapsible activities are expanded and in focus.

<img width="1438" alt="Screenshot 2020-05-05 at 14 14 43" src="https://user-images.githubusercontent.com/34126353/81061774-9e1f7600-8edd-11ea-9ec7-ebff02c55de2.png">

One more:

<img width="996" alt="Screenshot 2020-05-05 at 14 37 51" src="https://user-images.githubusercontent.com/34126353/81062099-14bc7380-8ede-11ea-81ec-d052d375d2d3.png">

**Why is this a problem?**
It's a security issue - all private user data should disappear as soon as I've logged out.

**Tech details**
MacOS Catalina, Chrome is up to date (Version 81.0.4044.129 (Official Build) (64-bit).

**Comment by loorm** [comment]
Triage 21. Bug is reproduced only when user is on "Public topics" view. According to @tiblu, the reason is, that logout redirects to public topics view. If user is already there, no page refresh happens and activity feed stays visible.
Est dev time - <1 hour
Prioritizing.

**Comment by loorm** [comment]
Tested. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no further comments.
