### ISSUE TITLE
Activity feed shows incorrect numbers in grouped activities

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#496]
**What is the problem?**
In some activities where it says "User **Random Name** and **X** others", when the activity is expanded, it shows a different (smaller) amount of users/activities.

<img width="766" alt="Screenshot 2020-05-14 at 01 02 08" src="https://user-images.githubusercontent.com/34126353/81870547-beef6780-957e-11ea-9a04-829ee24fa50d.png">

<img width="764" alt="Screenshot 2020-05-14 at 00 54 34" src="https://user-images.githubusercontent.com/34126353/81870552-c31b8500-957e-11ea-80b3-d82d1dc1a8b0.png">

<img width="771" alt="Screenshot 2020-05-14 at 01 06 00" src="https://user-images.githubusercontent.com/34126353/81870707-1e4d7780-957f-11ea-8993-87ac27c69d37.png">

<img width="761" alt="Screenshot 2020-05-14 at 01 05 42" src="https://user-images.githubusercontent.com/34126353/81870716-22799500-957f-11ea-9a56-aee5dc75c4ad.png">

**Why is this a problem?**
AF should display correct information. Especially since for some/most of these activities and various roles, it's not possible to find out the accurate data from within the topic.

**Comment by loorm** [comment]
Assigning for Triage.

**Comment by loorm** [comment]
Triage 22. Est dev time 2 hours. Prioritizing.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
