### ISSUE TITLE
No information about voting deadline passed

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#502]
**What is the problem?**
When voting deadline has passed, topic remains in "In voting" status.
It also show up in "In voting" topics under My Topics.
When you look at the "Vote" tab, you cannot vote, but there is no indication of the reason you cannot vote. (see screenshot) 

The invisible reason is, that voting deadline has passed. 
![Cannot_vote_in_voting](https://user-images.githubusercontent.com/22661743/82311143-fa9a8f00-99cd-11ea-8e66-173a8fddcb99.jpg)

**Why is this a problem?**
Very confusing even for an informed user.

**Possible solution.**
A clear and visible indication in the "Vote" tab on "Voting deadline expired"

**Comment by loorm** [comment]
@kevincrepin This needs your input first, please.

**Comment by kevincrepin** [comment]
Somewhat related to https://github.com/citizenos/citizenos-fe/issues/413

But basically the UI should say that voting has ended: https://projects.invisionapp.com/d/main#/console/9829159/418246142/preview

We've had this in older screens as well: https://projects.invisionapp.com/d/main#/console/9829159/404592814/preview

**Comment by loorm** [comment]
Assigning for Triage.

**Comment by loorm** [comment]
@kevincrepin Can you check the first link of the two above, please. It gives an error message.

Triage 22. Est dev hours 2. Prioritizing.

**Comment by kevincrepin** [comment]
New reference links:
https://projects.invisionapp.com/d/main#/console/9829159/418412299/preview
https://projects.invisionapp.com/d/main#/console/9829159/418412303/preview
https://projects.invisionapp.com/d/main#/console/9829159/418424724/preview

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
