### ISSUE TITLE
Bug: Inline reply feature shows cubes instead of something else

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#503]
**What is the problem?**

There are several issues:

- When you've selected a part of the text in the topic and leave a reply, it's posted with a cube, which purpose I'm not sure of
- Cube's tooltip shows a sequence of random numbers when I hover, instead of helpful text
- Clicking on the cube opens an "edit" button (then why it isn't an edit button on the first click?), but I'm also not sure why I should be able to edit someone else's reply
- My language is set to English, but the whole topic editing interface is in Russian. In order to get it to display English UI, I have to open language menu, select a random other language (as "English" is inactive) and then select English once again

<img width="939" alt="Screenshot 2020-05-19 at 13 09 29" src="https://user-images.githubusercontent.com/34126353/82314302-44857400-99d2-11ea-839a-d6e01937fde0.png">

**Why is this a problem?**
All of the above is confusing and not intuitive

**Comment by loorm** [comment]
This is a duplicate issue.
Original issue is #467. It has been triaged and prioritized for development.

Closing #503.
