### ISSUE TITLE
Etherpad language not always in sync with app UI language

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#504]
**What is the problem?**
Etherpad UI language sometimes goes out of sync with app UI language, esp. when switching languages. Could also include a window title language mismatch from both EP and UI language.

**Why is this a problem?**
Confusing for user.

**Possible solution.**
Ensure languages of the three elements always stay in sync.

However, having trouble pinpointing sequence of events leading to the mismatch.

**Comment by loorm** [comment]
This needs further investigation to describe exact conditions and make it replicable.

**Comment by loorm** [comment]
Unable to recreate issue and describe replicable conditions. Closing.

**Comment by loorm** [comment]
Got new content on this. Happened on Chrome. It seems to be happening, when there has been some pause in using. Like the session cookie "forgets" which language to use for which component. After language change and/or login-logout, it works normally.

Also, new thing is the window title language mismatch.

<img width="1439" alt="Screenshot 2020-05-27 at 14 53 48" src="https://user-images.githubusercontent.com/22661743/83020042-99f3fd80-a030-11ea-842e-5866f27843a5.png">

Screencast of some of the elements here https://www.dropbox.com/s/ssqgxpsa10jtdon/language.mp4?dl=0

**Comment by loorm** [comment]
Triage 23. Two separate issues. 
1) Window title does not refresh when creating a new topic. It stays on whatever was the title of the previously viewed topic. Replicated. Ready for dev. Estimated dev time 1 hour.
2) Etherpad and FE languages out of sync my happen, because user follows a link with a language parameter in it. This changes FE language. User then follows a link that does not contain a language parameter. This causes FE to swith back to user-preferred language. For the user, FE language switch happens without an apparent reason. EP language is currently set to user-preferred language in all cases. Need to think about a solution.

This needs to be split into two separate issues.

**Comment by ilmartyrk** [comment]
Update page title with every view change. Seems that if view doesn't change the global title parameter, the page title stays the same.

**Comment by loorm** [comment]
Triage 24. Proceed in this issue with the following description:
"Etherpad and FE languages out of sync my happen, because user follows a link with a language parameter in it. This changes FE language. User then follows a link that does not contain a language parameter. This causes FE to swith back to user-preferred language. For the user, FE language switch happens without an apparent reason. EP language is currently set to user-preferred language in all cases. Need to think about a solution."

Need to investigate.

**Comment by ilmartyrk** [comment]
I've found the cause to this issue, language parameter for the etherpad url is set from API side, so if user language in browser was set through URL (without changing the users prefered language) etherpad URL will contain users saved language thus possibly conflicting with current language in UI. 
Possible solution is to check for this param in FE and replace if UI language is not the same as in etherpad URL as it is a small and quick fix already applied a fix

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by loorm** [comment]
Tested. Confirmed working.
