### ISSUE TITLE
Syncing Etherpad author list with Citizen OS topic author list

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#505]
**What is the user story?**
User wants to add more authors on the topic.
![Screenshot 2020-05-19 at 14 22 30](https://user-images.githubusercontent.com/45175679/82346603-56314080-99ff-11ea-8576-247dad909e9e.png)

**What is the requested feature?**
There could be an opportunity to add more people as topic authors.

**Additional information.**
N/A

**Comment by loorm** [comment]
Assigning for Triage.

**Comment by tiblu** [comment]
Triage 22. 

We have 2 options:

1. We pull the author info using EP API from Etherpad on each Topic load. Etherpad API only returns author ID-s, not names, thus we need to implement that API and then use it.
2. We PUSH the author info to Citizen OS DB from Etherpad when new author adds content. Probably not feasible to do on "onEdit" event, but "leavePad" or similar, which does not run on every edit of the topic.

I personally feel like the 2 is a little better.

**Comment by loorm** [comment]
Est dev time 40 hours. Prioritizing.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
