### ISSUE TITLE
Change our date format

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#507]
**What is the user story?**
As a user, I want to clearly and quickly understand dates. Right now, dates are in the strange US mm/dd/yyyy format across the system.
![us_dates](https://user-images.githubusercontent.com/22661743/82597163-380b4200-9bb1-11ea-9314-ad6c9a266101.jpg)

**What is the requested feature?**
Either make the date format follow the geo-IP (or UI language?) or change it to international date format (https://www.w3.org/QA/Tips/iso-date).

**Additional information.**
Maybe @oksks has input on this.

**Comment by oksks** [comment]
Date and time format should always be taken from user's locale. Not sure why it's hardcoded in our case. I'd say it's a bug, not a feature.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/98
