### ISSUE TITLE
Activity feed shows incorrect activity - title update

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#508]
**What is the problem?**

- AF shows that I have updated a field "title" in a topic, while I certainly haven't done that. Seems like it happens to other users as well - I don't think each of us updated the title in the last 24h.
Maybe, just maybe, this activity is triggered by leaving an inline reply, as this activity didn't show up in AF separately.

<img width="766" alt="Screenshot 2020-05-21 at 22 27 45" src="https://user-images.githubusercontent.com/34126353/82598490-6a1da380-9bb3-11ea-9a83-3f173f4691a7.png">

- AF also added an extra word "title" at the end of the activity for some reason - I've checked "en.json" and there seems to be no such mistake in any of the source strings, so I'm not sure where it came from.

**Why is this a problem?**
It creates confusion, as I didn't perform this activity, nor I understand why others possibly did it - title isn't something you tweak a lot.

**Possible solution.**
Investigate what causes this activity and name it accordingly.

**Comment by loorm** [comment]
Replicated. Assigning for Triage.

**Comment by loorm** [comment]
Triage 22. Needs further investigation. Authors button and timeline view show different authors. Scrolling on timeline triggers title change event. 

Discovered, that timeline view and authors in EP have different authors lists. Timeline view authors show only authors of the most recent version. Authors view includes everyone, incl people who have minivoted but have not contributed any text.

This needs investigation. Est dev time 3 hours for investigation.
- Fix the double "title" entry in activity feed
- How likely is this bug to appear? We are only able to replicate in Style Guide topic for now.
- What is the estimated time to fix?

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
