### ISSUE TITLE
Allow voting with social ID without logging in

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#509]
**What is the user story?**
I want to enable users to vote using social ID, without having to log into the topic. With eID this is possible right now, with social ID it is not possible.

**What is the requested feature?**
Enable voting with social ID without logging in.

**Additional information.**
N/A

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/97
