### ISSUE TITLE
"Download signed file" when social media voting

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#510]
**What is the problem?**
when using social media log-in, in voting section the document download link says "Download **signed** files"
![Allkirjadega fail](https://user-images.githubusercontent.com/45175679/82820369-b36b3d00-9eaa-11ea-925d-6fdfa83ef88f.png)

**Why is this a problem?**
This is social media log-in and votes are not signed. It is misleading and incorrect to use the word "signed". 

**Possible solution.**
Change the wording into "Download file" or "Download voting results" or else.

**Comment by loorm** [comment]
Replicated. Assigned for Triage 23 on June 8.

**Comment by loorm** [comment]
Triage 23. Ready for dev. Prioritizing. Est dev time 30 mins.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
