### ISSUE TITLE
Separate Settings from Actions in Topic view

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#511]
**What is the user story?**
Menu items are scattered among "Options" menu on the right and "Settings" menu in modal. 

**What is the requested feature?**
Instead, the right-hand menu should be called "Actions" and shoudl contain actions. And modal should be for settings only.

**Additional information.**
N/A

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/96
