### ISSUE TITLE
Create a social media share button for public Citizen OS content

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#512]
**What is the user story?**
I want to share my topics, discussions and votes in social media (FB, Twitter, LinkedIn, Slack etc), because that's where the people are, that I want to join in. 

**What is the requested feature?**
The only way of sharing a topic on social media right now is to copy-paste the URL.  Perhaps use some standard social media share button tool or library (like https://www.sharethis.com/), that displays a single share button next to the topic, but then enables a choice between at least FB/LinkedIn/Twitter sharing. 

**Additional information.**
N/A

**Comment by loorm** [comment]
@kevincrepin This needs your input, please.

**Comment by loorm** [comment]
@KatiVellak "We had a talk with Kati, she said that share "widgets" are legally complicated. Don't remember exactly what, but I would take Katis input on this before we do it." This was by @tiblu

**Comment by kevincrepin** [comment]
@loorm A while back we made this: https://projects.invisionapp.com/d/main#/console/9829159/404592933/preview

Of course it's still hidden under the share menu item:
<img width="337" alt="Screenshot 2020-05-27 at 13 40 53" src="https://user-images.githubusercontent.com/26792281/83009671-c3585d80-a01f-11ea-82c1-054cb7cb2e93.png">

So question is whether it has enough visibility like this or should we bring out the social share buttons more?
We could add them to this top details for example:
![Screenshot 2020-05-27 at 14 14 14](https://user-images.githubusercontent.com/26792281/83012686-6ad78f00-a024-11ea-9420-b2bc8d603527.png)

**Comment by loorm** [comment]
From meeting with @kativellak:
Share buttons load scripts from social media pages. These scripts are out of our control and may access more confidential user data, than we would like them to have access to.  Therefore, not adivsable to use social media share buttons simply on the page.

@tiblu will think about better solutions, like popping up a separate window and showing share buttons there. Then, scripts loaded via buttons do not have access back into the parent window. Or smth like this.

**Comment by tiblu** [comment]
My 10 cents on this:

* IF we the widget loads a 3rd party script from their domain, we have no control over what info it gathers from the site in the future.
* We COULD make a local copy of the script, code review it to guarantee it never changes BUT as Google Picker script has shown, if Google changes their API, our functionality breaks. 
* I think to control the data the widgets have access we could:
    1. run them in isolation - pop-up window or iframe We would only provide the frame with data that is needed for the share.
    2. Implement sharing widgets ourselves and use 3rd party API (FB, Google...)
* Before we decide how we implement, we should check into the widgets code and see how they are implemented. MAYBE, just MAYBE there is some privacy built in.

**Comment by loorm** [comment]
@tiblu Check out ERR social share pop-up attached to #313. Possibly done as a pop-up for the same reasons. Perhaps we can learn from their implementation.

**Comment by loorm** [comment]
I want to bring this one back to life. @tiblu, @ilmartyrk  What if we only do this for public topics. Do our privacy-related problems then go away?

**Comment by loorm** [comment]
Triage 42. To avoid confusion between share and invite, move join link and QR code to invite tab. Add social media buttons to share tab. @kevincrepin, can you please work your magic?

**Comment by kevincrepin** [comment]
@loorm can you elaborate a bit on why it's confusing? I'm hesitant to just move link and qr to invite tab because we already have a lot of stuff going on there...

**Comment by loorm** [comment]
> @loorm can you elaborate a bit on why it's confusing? I'm hesitant to just move link and qr to invite tab because we already have a lot of stuff going on there...

It's confusing, because with the link / QR, I'm not actually sharing the topic out. I'm inviting people to participate in it, the only difference is, that whereas the invitations by e-mail are personal, invitations by link are general.

This is different from sharing, because sharing only directs you to the public topic. It gives you no rights at all (beyond read rights, which are global for public topics anyway). You cannot participate in the topic.

I understand the "lot of stuff going on in invite", too. @kevincrepin, maybe you can somehow solve the  confusion described above, while keeping them on the "Share" page? Maybe use some dividers, like we have in the "Settings" dialog...?

**Comment by tiblu** [comment]
From technical implementation POV the ERR.ee soluton is OK for us IF we do not use Twitters or Facebooks scripts but compile URL ourselves:

* Twitter - https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent
* FB - https://developers.facebook.com/docs/workplace/sharing/share-dialog/

**Comment by kevincrepin** [comment]
What I would suggest is like this: Instead of having 2 tabs Invite / Share, we have 3.

- Invite via e-mail: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=85%3A552
- Invite via link: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=744%3A25203
- share: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=744%3A24301

Then we don't need to include the link/QR with the e-mails because this can get very long. I would also rename the action (in the right bar) as "invite & share".

**Comment by loorm** [comment]
I like it. It makes things more clear. I'll push it into triage for tomorrow. If @anett and @ilmartyrk have changes they want to make, then the issue is in their hands from now on.

**Comment by anettlinno** [comment]
Triage 46. There are overlapping issues #311 #512. Share is already solved in #311 @tiblu are you also implementing via link and email too?

**Comment by anettlinno** [comment]
Closing issue as #311 is covering same share and invite topics.
