### ISSUE TITLE
When voting is active, open "Vote" tab by default

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#513]
**What is the user story?**
As a user, I want to get to voting with as few clicks as possible. Currently, when I go to topic that is "In voting" I land on "View" tab and have to find and click on "Vote" tab myself. This is unnecessary, because the "Vote" tab already contains an HTML version of the topic text, anyway.

**Which feature needs to be updated and how?**
Make the latest tab default, not the first. If topic is "In voting" status, open up "Vote" by default. If topic is "In follow-up" status, open up "Follow-up" by default.

**Additional information.**
N/A

**Comment by loorm** [comment]
Triage 23. Ready for dev. Prioritizing. Estimated dev time 2 hours.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by loorm** [comment]
Tested. Confirmed working.
