### ISSUE TITLE
A few tooltips are not translated

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#515]
**What is the problem?**
A few tooltips are not translated. I tried to switch from English to Estonian to Finnish. Two tooltips remaind in English for both languages. Finnish translation is at a 100% in CrowdIn.

1. "Pin topic" tooltip
2. "Font size" tooltip
![tooltips_no_translate](https://user-images.githubusercontent.com/22661743/83000562-34dddf00-a013-11ea-982c-f6f57d158c32.jpg)

**Why is this a problem?**
Language inconsistency.

**Possible solution.**
Insert translation keys.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/95
