### ISSUE TITLE
Optimize screen resource use in edit mode

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#516]
**What is the user story?**
On a normal laptop screen, when editing a topic, I should not have so much "extra" information on screen. Screenshot attached. The editable area is at the very bottom of the screen.

![Capture_screen_use](https://user-images.githubusercontent.com/22661743/83111643-9d899200-a0cd-11ea-9c5e-605a5271fcb8.JPG)

**Which feature needs to be updated and how?**
I'm not sure. We should look for ideas on conserving space in the topic view, so the actual topic content would take up at least 60% of the screen. Somehow make the top of the screen elements take less space.

NB! There is already a separate issue in dev pipeline, that will make the search bar go away when looking at topic content, so that will give some extra space. But we need more.

**Additional information.**
@kevincrepin Any ideas?

**Comment by loorm** [comment]
Just throwing some ideas out here:

- get rid of the middle sentence in the blue info box. It's kind of obvious, that in edit mode you can edit text. 
- hide the "Categories-authors-discussion" bit in edit mode (keep there in topic view, though)
- bring everything else closer together, it's all very vertically spaced out right now. However, don't want it to feel cramped, so need some deisgner magic here.
- perhaps also get rid of the "Current status: in progess" at the top? The visual progress line already indicates this quite clearly.

**Comment by kevincrepin** [comment]
This could/would look like this then: https://projects.invisionapp.com/d/main#/console/9829159/419473620/preview

**Comment by loorm** [comment]
@kevincrepin Functionally, this looks a lot better. But how does it look from a designer / UX expert POV? These were just some of my ideas. We don't have to implement them like that and we don't have to implement all of them. I want your perspective on this, too.

**Comment by loorm** [comment]
This became dormant a while ago, but it's ready for implementation. Let's make this happen.

**Comment by loorm** [comment]
Triage 38. Estimated dev time 2 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
FIXED https://github.com/citizenos/citizenos-fe/commit/a5d265d98079b772cd442945ccb096e9cd65ca66
