### ISSUE TITLE
Make comments visible in "View" mode

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#517]
**What is the user story?**
As a user with view rights, I still want to be able to see comments. Right now, comments are visible in "Edit" mode only. This also means, that once topic is "in voting", comments are no longer visible.

**Which feature needs to be updated and how?**
Make comments visible in "View" mode.

**Additional information.**
N/A

**Comment by loorm** [comment]
@ilmartyrk This needs some thinking from your side on if and how could this be done?

**Comment by loorm** [comment]
We don't need new UX for this. We just need to move the existing UX over to view mode. NB! Once a topic is moved to voting, it's cool, that comments and mini-votes are no longer visible. Everyting that is being voted on, needs to be in the document proper. But while topic is in progress, you should see comments without editing. A lot of discussion may actually happen in comments, but if you just take a look at the document, it seems that nothing is going on. Activity feed, also, does not reflect comments accurately, it just says that the field "Description" was updated.

Task is to investigate, if and how could comments (not mini-votes, just comments) be read from Etherpad database and be displayed in our view-only HTML topic mode. Propose a solution or two in the comments, then we will decide if and how to proceed.

**Comment by loorm** [comment]
Triage 38. Timebox investigation to 8 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
Found out that the ep_comments_page already has API endpoints to read comments and replies and it also returns HTML with data-comment tags that include comment id-s so it would be quite easy to link comments with parts of text that they are related to. I believe the time estimate for this task to be about 24h. That is to make proper API calls from our API and then link these with document

**Comment by loorm** [comment]
Triage 39. Change from investigate to develop. Let's use the same styles as in edit mode. Est. dev time 16 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
DONE 
https://github.com/citizenos/citizenos-fe/commit/e83e77f35e9bbe358d50d180649e4261b284d85e
https://github.com/citizenos/citizenos-fe/commit/4269be5772923b7e3f3613f2b307de70cab564f2
