### ISSUE TITLE
Create an option to include / exclude csv from final container

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#525]
**What is the user story?**
A clear and concise description of what the user needs to do.
+ add screenshot / screencast when applicable

**What is the requested feature?**
Describe the new feature, relative to the above user story.

**Additional information.**
Something you want to add, that didn't fit one of the boxes above.

**Comment by loorm** [comment]
Triage 24. This need input from @kevincrepin. What we need is some way for users to choose between some options, when downloading the container with votes. At this time, there will only be one option - container with CSV or without CSV. But in the future, more options may be necessary. Somewhere in the red circle, I suppose. 
![triage24_1](https://user-images.githubusercontent.com/22661743/92453441-efab7a80-f1c7-11ea-9029-6ace05ae40b6.JPG)

**Comment by kevincrepin** [comment]
Let's have the one button serve as a dropdown with more options: 
https://projects.invisionapp.com/d/main#/console/9829159/431950733/preview

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by anettlinno** [comment]
Many users I have worked with do not understand what is "CSV file". Would it be somehow possible to add explanation of what it is or make the difference more understandable for "ordinary people"? :))

**Comment by loorm** [comment]
Moving to triage. I propose to close the topic. This has been solved. 
<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/22661743/132206172-fee88d55-0786-4213-a7f4-5c2307540d26.PNG">

**Comment by anettlinno** [comment]
Triage 46. This issue is solved but Users do not understand what is the difference between "Machine-readable files" and "Human readable files". @seppviljar do you have any better idea how to make it more understandable for users? 
@kati provided: "Sending to Commercial Register" AND "Sending to Parliament, Local Government or internal use".
@ilmartyrk is suggesting that we could use the space for explanatory text under the "Voting is closed".

**Comment by loorm** [comment]
And then I want to send it to the Tax Board and I'm lost :)  You can't possibly list all use cases in the drop-down.

We're not using complicated technical language. Human-readable and machine-readable are plain and descriptive words. If you want to make it even more plain, you can say "download file for other humans" and "download file for computers". When you start describing what the file is for, you limit the use cases. When you say, what it is, that you get, there's no such limit. I know what I get, what I do with it is my business.

**Comment by seppviljar** [comment]
I'm stepping back a bit and.. what if, before that download button, there's a checkbox: "Include also votes as comma-separated file (CSV). You should do this when sending file to entities that have automated file processing workflow, like Äriregister or .."

Well, lengthy and sloppy text but you get my meaning, I hope :)

**Comment by ilmartyrk** [comment]
@loorm @seppviljar @anettlinno, there is the text before this download button, currently it says "Everyone has cast their votes. You can download the full document here.". We have enough screen space to alter this text to explain the options. So probably the easiest solution is to leave the dropdown options as they are and alter this description text. I don't have perfect wording, but this could say something like: "Human-readable container includes a table file (.csv) with voting results this file is excluded in the machine-readable container as it might cause errors when uploading to Äriregister or similar info-system"

**Comment by anettlinno** [comment]
@loorm I just went it through with users two days ago -- and people are really struggling to understand what the difference is (I believe that the reason is not about people being stupid, but rather how our brain catches this information in this current situation where the aim is to get the results as easily and quickly as possible). 

I support what @ilmartyrk proposed -- to use the text space to explain what is the difference and leave the drop-down as it is.

**Comment by anettlinno** [comment]
Triage 49. We alter the current description message above the download button. @seppviljar would need your magic (also with user friendly message) :) 

"Include also votes as comma-separated file (CSV). You should do this when sending file to entities that have automated file processing workflow, like Äriregister or .." This works well if we could find more user friendly term to "comma-separated file" and "human readable file" :)

**Comment by seppviljar** [comment]
"Everyone has cast their votes. You can download the full document here." ->

"To download voting results, select a suitable format below. Our "human-readable" container comes with an additional file (comma-separated table, .csv) containing data of each individual vote, as required by Riigikogu and local goverments. For systems that can't process such info (a la Äriregister) please select "machine-readable" file.

Horribly long but... ideas?

**Comment by loorm** [comment]
> "Everyone has cast their votes. You can download the full document here." ->
> 
> "To download voting results, select a suitable format below. Our "human-readable" container comes with an additional file (comma-separated table, .csv) containing data of each individual vote, as required by Riigikogu and local goverments. For systems that can't process such info (a la Äriregister) please select "machine-readable" file.
> 
> Horribly long but... ideas?

A: file for other humans
B: file for computers

**Comment by anettlinno** [comment]
@seppviljar I think this is very nice explanation and we could test it out with users.
@loorm comparing the "human-readable" to the "File for other humans" then IMHO the first one is better :)

**Comment by ilmartyrk** [comment]
@oksks can you confirm this text I can then change the current translation values for 
VIEWS.TOPICS_TOPICID.VOTE_HEADING_VOTE_CLOSED and
VIEWS.TOPICS_TOPICID.VOTE_TXT_VOTE_CLOSED

**Comment by oksks** [comment]
Fine with me to go with Sepp's proposal, @ilmartyrk :)
