### ISSUE TITLE
Bug: Translation issues when switching between languages.

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#534]
**What is the problem?**
Some of the texts sometimes shows in another language - in this case Indonesian. This has previously happened with Estonian showing too, while in English. It's only some parts though, as shown in the screenshots. Both are languages that I have at some point switched into previously to take screenshots for graphics, then switched back to English for normal usage. 

![image](https://user-images.githubusercontent.com/61320526/89039510-80c64080-d342-11ea-915a-3d3624165630.png)

![Capture](https://user-images.githubusercontent.com/61320526/89039551-8f145c80-d342-11ea-98a9-48e6cc4f2b92.JPG)

**Why is this a problem?**
Self-evident 

**Possible solution.**
Self-evident

**Comment by BeccaMelhuish** [comment]
And just to add a couple of further things to this, it seems all email notifications for topics are coming through in Indonesian (regardless of the language they've been created in), like this one from Ilmar:

![Capture 4](https://user-images.githubusercontent.com/61320526/89644570-1c5e3080-d8b0-11ea-9d35-41fc6bee5472.JPG)
 
And other notifications such as this one telling me the connection has broken - regardless of the topic I'm in it always comes up in Indonesian. So essentially, I'm having to use the platform half in English and half in Indonesian, on an on-going basis, rather than it being a one-off occurrence linked to just one or two topics.. 

![Capture 3](https://user-images.githubusercontent.com/61320526/89644652-44e62a80-d8b0-11ea-8390-989ddfb8d90b.JPG)

**Comment by ilmartyrk** [comment]
Triage 24 this is a duplicate of https://github.com/citizenos/citizenos-fe/issues/504

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
