### ISSUE TITLE
Account activation using e-mail is confusing

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#536]
**What is the problem?**
When new user is invited to join topic, or person who creates new account using e-mail, user has to activate e-mail using confirmation link sent in e-mail. This link redirects user to FE page without logging in or giving any notifications. If user was invited to join topic then the link redirects to topic URL and as user is not logged-in he/she is displayed 404 error for private topics. In other cases user is redirected to front page of app

**Why is this a problem?**
This is really confusing to users because they get no feedback if activation was success or not specially when 404 page is displayed.

**Possible solution.**

1. Display success notification asking users to log in
2. Display message and login form 
3. Display success message and log user in

**Comment by loorm** [comment]
Triage 24. We need to create a separate dialog window or page, which would say something like "E-mail confirmation successful. You are now welcome to log in and start your awesome collaborative discussions!" + the login button. @kevincrepin, can you come up with a visual solution for this, please.

**Comment by kevincrepin** [comment]
Let's use this kind of dialog which we should have already and adapt it a little bit:
https://projects.invisionapp.com/d/main#/console/9829159/431950537/preview

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by loorm** [comment]
Ready for development. Moving to Triage.

**Comment by ilmartyrk** [comment]
Seems that our changes to the initial login flow have solved the issue that was initially created, but we have discovered that we need to have a complete account registration flow for users that have been invited to a topic or group, but don't have an active account yet.

**Comment by anettlinno** [comment]
Triage 45. Initial issue is solved but new issue raised when tried to replicate. Ilmar will open new issue. Closing this issue.
