### ISSUE TITLE
BUG: Sharing private topics displays translations keys as title and description

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#543]
**What is the problem?**
When sharing a private topic robots cannot access topic content to fill out the topic title and description fields for visually complete post in Slack etc. 

**Why is this a problem?**
This makes the links shared to looks as if broken

**Possible solution.**
Replace fields with some placeholders for private topics etc.

**Comment by ilmartyrk** [comment]
Triage 24 Also solve "Update page title with every view change. Seems that if view doesn't change the global title parameter, the page title stays the same."

**Comment by loorm** [comment]
Needs copy from Marvin, prioritizing investigation for now.

**Comment by ilmartyrk** [comment]
One tool for debuging https://socialsharepreview.com/, also used sending messages to myself in facebook and slack. Couldn't reproduce with our test.app.citizenos links, for public topics got the topic title and description, but for private topic got default site title and description. Will check with live site URL-s too.

**Comment by ilmartyrk** [comment]
applied a fix to always set default title values if not in a topic view that can define a new meta title

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
