### ISSUE TITLE
Misaligned elements in dialog window

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#548]
**What is the problem?**
Alignment issue. See below.

**Why is this a problem?**
Ugly.

**Possible solution.**
Re-align the elements.
![triage24_2](https://user-images.githubusercontent.com/22661743/92454772-8fb5d380-f1c9-11ea-8cb0-496bdba7c41a.JPG)

**Comment by loorm** [comment]
Triage 24. Ready for development. Estimated time 1 hour.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
