### ISSUE TITLE
Make platform menu simpler by removing unnecessary parts.

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#549]
**Menu uses both text and icons, which duplicate each other**
Too much information confuses the user. In order to make navigation in the menu easier, remove unnecessary parts. Since text and icons duplicate each other, propose removing text. 

For example, in the 'Topics' menu: 
![image](https://user-images.githubusercontent.com/34899902/92471451-a4519600-f1e0-11ea-9137-f6a960e45033.png)
The exact same info can be conveyed by only having 3 buttons: 
'My topics' 
'Public topics'
Create new topic can be represented by a '+' button. 

Similarly for the 'Groups' menu part: 
![image](https://user-images.githubusercontent.com/34899902/92472192-d1eb0f00-f1e1-11ea-96fb-94c03e434263.png)
The exact same info can be conveyed by 1 button: 
'My groups'
Create groups can be represented by a '+' button.

**Comment by anettlinno** [comment]
IMHO icon and text combination works well. 
@kevincrepin what is the overall trend in this field? Probably this is something to think about in redesign project?

**Comment by anettlinno** [comment]
Triage 56. Icons and text makes it clearer for the user. If we remove text and leave only +, it would be more confusing for the users to understand what kind of action + consists. Closing the issue.
