### ISSUE TITLE
Improve language selector on platform

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#550]
**User needs to realise that the platform has been translated into 13 languages. We regularly get feedback, that user has not found the language selector button. Propose to make language selector button more clear that it is a language selector like we did on the website.**
Currently on the platform:
![image](https://user-images.githubusercontent.com/34899902/92472469-30b08880-f1e2-11ea-8bb0-cd25a7bcdd19.png)
For the website, we are changing the language selector to have the language code and an arrow (although a pop-up window appears instead of a drop-down menu): 
![image](https://user-images.githubusercontent.com/34899902/92472719-91d85c00-f1e2-11ea-8804-81260b13a6c2.png)
Propose the same solution for the platform. 

**'About' button has a confusing icon 'heart icon'. Propose to change it to 'info icon' or something similar.**

**Comment by anettlinno** [comment]
Issue 56. I personally haven´t received any feedback from the users regarding language change. @kevincrepin this could be something to think about during the redesign project,  but in current version we are not going to change that.
Closing the issue.
