### ISSUE TITLE
Activity feed displays translation keys

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#551]
**What is the problem?**
Activity feed displays translation keys.
![activity_feed_problem](https://user-images.githubusercontent.com/22661743/92690464-bb5fc780-f349-11ea-82c8-8c94b2a8f099.jpg)

**Why is this a problem?**
It's a bug :)

**Possible solution.**
N/A

**Comment by loorm** [comment]
Triage 25. Ready for dev. Estimated time 15 minutes. Prioritizing.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
