### ISSUE TITLE
Inline comments feature is not working

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#552]
**What is the problem?**
Inline comments feature is down.
![big_bug](https://user-images.githubusercontent.com/22661743/92727093-4a370900-f377-11ea-8c61-620dcfe76f3d.jpg)

**Why is this a problem?**
Part of core functionality not working.

**Possible solution.**
N/A

**Comment by ilmartyrk** [comment]
Plugin update that included some new translations was not released, merged new translations pull, but forgot to update plugin in heroku config. As some translations expected data values that weren't sent to them by old code the translation plugin broke thus resulting in a broken EP.

FIX: updated plugin
Needs fix in the future to get past translations possibly breaking EP https://github.com/citizenos/citizenos-fe/issues/553

**Comment by loorm** [comment]
Tested. Confirmed working.
