### ISSUE TITLE
Translations can break Etherpad

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#553]
**What is the problem?**
If a translation key expects a value, but this is not sent by code the html10n translator breaks and shows error message

**Why is this a problem?**
EP is unusable because a huge error message is displayed and features will not work

**Possible solution.**
Make html10n ignore missing params (replace with null etc.), remove errors from UI and send them to console etc.

**Comment by loorm** [comment]
Triage 25. #552 was an example, but we need a wider solution to avoid aggressive error messages when a translation entry is not found.

Estimated dev time 1 day. Prioritizing.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by ilmartyrk** [comment]
Added fix to etherpads original project, it is allready merged hopefully it will be in the 1.8.7 release and we can add it to our live, after that I will close this issue
