### ISSUE TITLE
Opinion festival box for front page

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#556]
@kevincrepin we need a design for an Opinion festival topics on our apps front page, similar to Hactivist Community,  34 Island Project and Eesti Jazzi arengusuunad.

**What is the requested feature?**
Design for the box, color and logo inside circle image. Added 3 different logo files and guide
![OF_white](https://user-images.githubusercontent.com/19904307/93305543-51db2f80-f807-11ea-8658-722934ea2faa.png)
[OPINION FESTIVAL LOGO GUIDE.pdf](https://github.com/citizenos/citizenos-fe/files/5230523/OPINION.FESTIVAL.LOGO.GUIDE.pdf)
![OF_black](https://user-images.githubusercontent.com/19904307/93305552-543d8980-f807-11ea-9c07-4dd575827493.png)
![OF_color](https://user-images.githubusercontent.com/19904307/93305554-54d62000-f807-11ea-9230-b1dd679525e1.png)

**Comment by anettlinno** [comment]
Here is introductory text: Indonesia Opinion Festival adalah even yang mempertemukan masyarakat untuk merayakan kebebasan berpendapat. Diskusi, debat, rekomendasi ide dan voting terhadap ide-ide terpilih dalam perjalanan menuju e-democracy bangsa.

**Comment by kevincrepin** [comment]
Not sure if you need the full circle visual or only what's inside the inner circle... 
The full circle is available from: https://projects.invisionapp.com/d/main#/console/9829159/404593274/preview
Let's make the box colour #D98B30

**Comment by ilmartyrk** [comment]
@kevincrepin thanks, exactly what was needed :)
