### ISSUE TITLE
Make more space for topic text by improving 'OPTIONS' menu location

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#558]
**When editing / viewing a topic in normal view, almost 1/3 of the page is reserved for the 'OPTIONS' menu
<img width="1427" alt="Screenshot 2020-09-16 at 15 28 18" src="https://user-images.githubusercontent.com/34899902/93337209-7e0ba600-f831-11ea-82fe-8c55eb2e31b5.png">
**

When the screen is made narrower, the page design changes to a much better UX: the 'Settings' (not 'OPTIONS' anymore) menu is now located at the top of the page, leaving more space for editing / viewing topic. Proposing that we use this version (or similar) always, not only with the narrow view, but also wider view. 
<img width="864" alt="Screenshot 2020-09-16 at 15 35 03" src="https://user-images.githubusercontent.com/34899902/93337737-35a0b800-f832-11ea-93c1-707ddafe5ae8.png">

**Comment by loorm** [comment]
Triage 25. We tried and tested on 13" laptop screens and 10" laptop screens and usability remains good. Even in the added screenshot, the text area appears wide enough. So we cannot identify the issue about the width. Is there any evidence, that this might be a problem to users?

It does, however, related to a wider UX issue, that our screen is too crowded with information perhaps. This is something that we need to deal with at some point, but it requires a wider UX rethink.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by loorm** [comment]
We tried and tested and did not see a problem. Liina reviewed our response, did not provide any additional evidence. I assign this to another Triage and propose to close the issue without further action.

**Comment by anettlinno** [comment]
Triage 46. Tested in different screens. Closing the issue without further action.

**Comment by anettlinno** [comment]
Triage 46. Tested in different screens. Closing the issue without further action.
