### ISSUE TITLE
Merge 'OPTIONS' menu with 'Settings' menu

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#559]
**'OPTIONS' menu doubles some options that are already included in the 'Settings' menu**
This makes both menus more confusing to the user. Also having only one settings menu is better UX. 

<img width="306" alt="Screenshot 2020-09-16 at 15 40 14" src="https://user-images.githubusercontent.com/34899902/93338424-fc1c7c80-f832-11ea-9166-e05f7fd0175e.png">
<img width="679" alt="Screenshot 2020-09-16 at 15 40 27" src="https://user-images.githubusercontent.com/34899902/93338438-00e13080-f833-11ea-88ad-fbf91e58ca79.png">

Propose to merge 'OPTIONS' menu with 'Settings' menu (and rename if necessary).

**Comment by loorm** [comment]
Triage 25. Problem acknowledged. Need to create specific distribution of links between Setting and Options. Perhaps rename Options to Actions. 

Moving to in preparation.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by loorm** [comment]
Moving to Triage. I propose to close this topic, because https://github.com/citizenos/citizenos-fe/issues/393 will have the exact same solution: renaming "Options" into "Actions".

**Comment by ilmartyrk** [comment]
Development tasks:
- [x] Remove Categories link from options
- [x] Rename Options into actions
- [x] Alter leave topic confirmation popup, needs the same info as in settings popup

Administrative tasks:

- [x] Update CHANGELOG files
- [x] Inform localization on new translations

**Comment by anettlinno** [comment]
Triage 47. Removing categories link under "Options" and leaving it only under the "Settings". Renaming "Options" into "Actions". Est. dev. time 30 min. Sending to development.

Menu (actions and settings) needs user testing @BeccaMelhuish.
