### ISSUE TITLE
Merge 'vote' and 'view' pages

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#560]
**Users have reported not finding the 'vote' tab (many times)**
Users find it difficult to find the 'vote' tab, because they are directed to 'view' mode, when they open an email invitation or link. 

Propose to merge 'vote' and 'view' pages. The voting section does not take up much space, it could be at the top of the page, if a topic has been sent to voting. Then all information about the topic would be on one page: voting, text itself and arguments. 

<img width="635" alt="Screenshot 2020-09-16 at 15 53 26" src="https://user-images.githubusercontent.com/34899902/93339882-c7112980-f834-11ea-9059-04501093fab5.png">

**Comment by ilmartyrk** [comment]
@liinaguiter this is already fixed by  https://github.com/citizenos/citizenos-fe/issues/513 vote tab is now automatically opened when topic is in voting. I am not closing this issue just to have a small discussion during next triage to see if this could possibly have some other solution.

**Comment by loorm** [comment]
Triage 25. #513 was a solution too the same problem. Has been implemented. Let's wait and see if the problem persists. If users are still not able to find where to vote, we need to come back to this.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
