### ISSUE TITLE
Missing translation in Etherpad on-screen menu

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#566]
**What is the problem?**
See orange circle.
![EP_translations](https://user-images.githubusercontent.com/22661743/93859830-d4139a00-fcc6-11ea-867a-5c44872d4c3c.png)

**Why is this a problem?**
User is unable to understand, what the menu item means.

**Possible solution.**
-

**Comment by loorm** [comment]
Triage 25. Discovered this. Prioritizing. Estimated dev time 1 day.

**Comment by ilmartyrk** [comment]
This translation key was not added to the plugin so by default it had no value before ep_translations plugin sync, fixed by adding this key to plugin locale files and also updated ep_tranlsations plugin dependencies

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
