### ISSUE TITLE
Centralized translation repo for plugins

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#571]
I've been contacted by a user of our ep_image_upload plugin if we are interested in using centralized repo for all ep plugins. Etherpads translations have always been an issue as all plugins have separate translations our current solution depends on a plugin I've created to be able to use Crowdin, but it still has some issues with sync-ing. If a native solution is developed by etherpad community it for sure will be more stable and future proof. But it seems that we would have to start using translatewiki for etherpad and move away from Crowdin.

**Comment by loorm** [comment]
Triage 26 - let's watch where this is going, but it would be costly in terms of time and effort to switch our translation system right now.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by loorm** [comment]
I propose to close this issue. Reason for closing is, that even if EP does come out with a native translation solution based on translatewiki, we should nevertheless maintain all our (product) translations in one place and there's no reason to move away from CrowdIn. Thus, there's also no reason to keep this issue open. I can't see a scenario, where we would bring this into dev. Scheduling for triage.

**Comment by anettlinno** [comment]
Triage 46. Closing the issue for the reason that Margo brought out.
