### ISSUE TITLE
Indian Youth Participation Network box on home page

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#575]
@kevincrepin We'll need to add a box for the Indian Youth Participation Network on the app-s home page. Sara will add all the info she has and then we will need the design (Logo in circle and color code).

**Comment by loorm** [comment]
Triage 26. Issue is waiting for input from Sara.

**Comment by ssin1901** [comment]
[logo] - link attached below

![pyln-cos-logo-black](https://user-images.githubusercontent.com/72747107/95753953-f8f49f00-0cbf-11eb-9cb0-34ccf204e159.png)

[title] - Participatory Youth Leadership Network
[short description] - PYLN is a community of practice for youth organisations to hack participatory leadership in India
[tags] Youth leadership, bottom-up innovation and civic engagement

**Comment by ilmartyrk** [comment]
@kevincrepin can you create the logo in circle image using the logo provided by @ssin1901

**Comment by kevincrepin** [comment]
Maybe the box itself can be #D080B4? We've had a lot of yellow / greenishes ones...

[img_partner_indiaYouthParticipationNetwork.zip](https://github.com/citizenos/citizenos-fe/files/5366487/img_partner_indiaYouthParticipationNetwork.zip)

**Comment by ssin1901** [comment]
@kevincrepin #00EAC4 is what we used for the web page but the pink is great too! Whichever colour you think works better.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
