### ISSUE TITLE
Issue with selecting options (buttons)

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#578]
**What is the problem?**
When you click in the circle or box in the buttons shown below (voting customisation, and multiple choice voting), the button doesn't work (nothing happens and it remains unselected). It only works if you click in the right hand section of the button, where the text is.

![Screenshot_20201007-200536](https://user-images.githubusercontent.com/61320526/95371227-30d39f00-08da-11eb-8104-3ae410b26069.png)
![Screenshot_20201007-200758](https://user-images.githubusercontent.com/61320526/95371231-316c3580-08da-11eb-8326-8690eda90916.png)

**Why is this a problem?**
It's a UX issue. 

**Possible solution.**
Make it so the button works regardless of where you press :)

**Comment by loorm** [comment]
Triage 27. Bug replicated. Prioritizing. Estimated dev time: 10 minutes.
