### ISSUE TITLE
A more communicative GitHub page

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#587]
**To have a more communicative GitHub page**
What can and should be added was discussed over a meeting. We agreed on the following: 
https://docs.google.com/document/d/1gTGNs3WCBfQK1knB4APt8UWTSZDCguTjZ6frnhX2Fzo/edit

Ilmar: "I believe it needs to be a separate GiHub issue to be prioritized. It will probably be a days work to get it looking as we discussed".

Thank you!
Liina

**Comment by loorm** [comment]
Triage 28. Reviewed. Agreed. Prioritized. Need to think about who the target group of this activity is.
