### ISSUE TITLE
Include recipient e-mail into invite text

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#589]
**What is the user story?**
User does not know, which email invite was sent to (forwarding etc)

**Which feature needs to be updated and how?**
Always include e-mail address in invite.

**Comment by loorm** [comment]
Triage 30. Needs a copy on how to include this in the current e-mail template ("You are invited to collaborate on ..."). Then, we can proceed to development. Estimated dev time - 30 mins. Prioritizing.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @helenkask what do you think, is it ok if we just add email after the users name to look like `Hi Ilmar Türk (ilmar@citizenos.com)!`

**Comment by BeccaMelhuish** [comment]
@ilmartyrk How about this? Would also help with the issue of them not knowing they need to use the same email address? (And also seem less odd to include it for everyone (most people) who can just see the email address by vieing the "to" field).  

"Please note: You must log in using the same email address (xxxx@xxxx.com) to access this topic." (Or "to access this group" for a group). 

![user-email-tip](https://user-images.githubusercontent.com/61320526/102251621-5cd85580-3f05-11eb-9198-3920002dc660.png)

**Comment by KatiVellak** [comment]
Legally reviewed, for what it's worth, I like Becca's proposal, helps to avoid the confusion :)

**Comment by helenkask** [comment]
Localizability wise both are good, personally voting for Becca's option too.

**Comment by ilmartyrk** [comment]
@KatiVellak @BeccaMelhuish @helenkask I really like Becca's option too and will go with that. Looks way more professional :)
