### ISSUE TITLE
How does the system handle time zones with regard to voting periods (start and end)

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#590]
**What is the user story?**
When voting organiser and voting participant are in different time zones, what is displayed as the deadline. When voter votes, where does the signature time stamp come from. What is displayed as the voting date in the container.

**Which feature needs to be updated and how?**
Describe the requested change, relative to the above user story.

**Additional information.**
Something you want to add, that didn't fit one of the boxes above.

**Comment by loorm** [comment]
Triage 30. Confirmed. Prioritizing.

Investigate current status - @ilmartyrk 
Investigate how it should work - @loorm @kativellak

**Comment by KatiVellak** [comment]
@loorm and @ilmartyrk we should organize a discussion for this topic.

**Comment by ilmartyrk** [comment]
Database time zone is set etc/UTC and all dates we use have +00 at the end that means all date comparisons are based on this that means all votes end at the same time for all users. By default all heroku servers also use UTC so our code and DB run in the same time zone. This also means that timestamp created by code is same as DB uses. Also tested how FE timezone parsing works and it also handles time zone as it should. API returns timestamp ending with Z that marks time zone as UTC +00. Now javascript uses browsers time zone and it gets it by default from system. Changing system time zone changes browser time zone and code can display everything to user from users time zone point of view.

**Comment by loorm** [comment]
Triage 36. Let's have the meeting before next triage.

**Comment by loorm** [comment]
Related to #667

**Comment by loorm** [comment]
We just had a meeting about this. Here are the results:

- Citizen OS system (DB, API) always operates in UTC;
- for user convenience, when displaying times, the UTC time held in DB is converted to user's local time when displaying deadlines etc;
- we always include time zone information, so that user is able to see, which time zone the given time is in;
- differences between browser time and server time cannot be abused to vote after the voting deadline.

This issue is thereby solved. Closing.
