### ISSUE TITLE
Voted user counter should show users count corretly

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#591]
**What is the problem?**
Vote counter currently is showing selected options count and for multiple-choice voting the counter will show n*x votes and vote creator cannot know how many users have voted.
**Why is this a problem?**
Vote count should show only users count else it is quite useless.

**Possible solution.**
replace with correct number

**Comment by loorm** [comment]
Triage 30. Confirmed. Est dev time - 1 day. Prioritizing.

**Comment by KatiVellak** [comment]
Legally reviewed, let´s get those voting numbers straight.

**Comment by ilmartyrk** [comment]
FIX By https://github.com/citizenos/citizenos-api/commit/076f7d2145c338edea233a0f7511d43995ea05f2 AND https://github.com/citizenos/citizenos-fe/commit/e4c0f2e875cf3cdf8c575a993027ee138ef39f69
