### ISSUE TITLE
Create a separate CSV with vote count otuside of container

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#592]
**What is the user story?**
Update CSV file creationg to reflect multiple choice voting.
Make it separately available as CSV file for download, outside of container.

**Which feature needs to be updated and how?**
Describe the requested change, relative to the above user story.

**Additional information.**
Something you want to add, that didn't fit one of the boxes above.

**Comment by loorm** [comment]
Triage 30. Confirmed. We need UX for this.

@kevincrepin Please have a look at this one. We need something (a button?) in the completed voting view in order to download additional files other than the main container.

**Comment by kevincrepin** [comment]
Seems like we've already had this :)
https://projects.invisionapp.com/d/main#/console/9829159/431950733/preview

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
