### ISSUE TITLE
UX issue with 'See who reacted' feature

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#593]
When you click to see who reacted to an argument, it takes you right back to the topic of the topic, which if it is a long topic or a discussion with many comments will mean you totally lose your place, and have to scroll back down through everything to find where you were again, possibly several times, if you want to see who reacted to several different comments.

![image](https://user-images.githubusercontent.com/61320526/99677559-216b7800-2a7a-11eb-951b-83eb82c61f99.png)

**Comment by anettlinno** [comment]
Triage 56. Successfully replicated. One opportunity is to show users who have liked the argument when scrolling over the number. The other opportunity is that number of likes will turn into button-like clickable button.
Current version needs investigation. There might be an opportunity that after clicking on the number of likes it will take you to the topic heading and after closing the window, user will be directed back to the same location where she started.
Investigation time 1h. Sending to development.

**Comment by anettlinno** [comment]
Triage 76. Should be improved with Angular update. 
Sending to redesign.

**Comment by ilmartyrk** [comment]
Fixed with angular update
