### ISSUE TITLE
Add "VOTE" button below voting box

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#594]
**What is the user story?**
In single selection voting (with social log-in) my vote is already counted when I click on the name (notification via the announcement bar), but it´s confusing because I don´t really understand (or trust) that my vote was counted. And if I click multiple times and different options, I don´t understand which vote was counted.

<img width="949" alt="Voting" src="https://user-images.githubusercontent.com/45175679/100330518-ba007b80-2fd7-11eb-9438-152032a7bc9e.png">

<img width="955" alt="Activity feed" src="https://user-images.githubusercontent.com/45175679/100330623-e0beb200-2fd7-11eb-9d7b-f9e7524bf963.png">

**Which feature needs to be updated and how?**
There could be an option for pre-selection(s) and big fat **VOTE** button below the voting box.

**Comment by loorm** [comment]
Triage 30. Confirmed. Solution exists, is implemented for multiple choice voting. Will harmonize. Est dev time - 30 minutes. Prioritizing.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
