### ISSUE TITLE
"Edit topic" blue box

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#595]
**What is the user story?**
"Edit topic" is not easy to find from the "Options" menu.

**Which feature needs to be updated and how?**
"Edit topic" blue box could be in the same place where "Done editing" blue box (in topic mode). 

<img width="806" alt="Edit topic2" src="https://user-images.githubusercontent.com/45175679/100442505-d45a5800-30b0-11eb-87d5-3d2da7bc7ad0.png">

**Additional information.**
"Edit topic" and "View topic" could be removed from the "Options" menu, as these duplicate the blue box commands. 
<img width="806" alt="Edit topic" src="https://user-images.githubusercontent.com/45175679/100442895-75491300-30b1-11eb-9cbd-8db9d8af1f75.png">

**Comment by loorm** [comment]
Triage 30. Confirmed. Est. dev. time - 20 mins. Prioritizing.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
