### ISSUE TITLE
Create a hovering Help Center bubble

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#597]
**What is the user story?**
As a user I need a quick way to get help, when unable to do what I wanted to do.

**What is the requested feature?**
Create a Proactive Window Support  system (a hovering bubble). Clicking the bubble opens up a menu, which has a few choices:

- link to Help Center
- e-mail a support request. It then gathers information about user's browser / OS versions, screen size etc to be able to accurately assist.  This information is then auto-emailed to designated support e-mail address.

**Additional information.**
- we will look for an open source library, which has hopefully created something similar
- the Proactive Window Support  will follow UX language, fallback to English will happen on Help Center website if needed

**Comment by loorm** [comment]
Triage 30. Confirmed. Prioritizing.

- [x] @ilmartyrk will look for open source library

- [x] @kevincrepin we need a design for this, please

- [x] @kativellak is browser / os info gathering in order to provide better support an ok thing to do legally?

**Comment by ilmartyrk** [comment]
Been looking for a simple lightweight solution, but there seems to be none that I can find. I believe that it is easier for us to create our own system. I can get the user browser and OS info from their browser data and add it to the end of the e-mail.

FE would have bubble in the corner when user clicks on it a popup is displayed. The popup should contain contacting field like user email so we can contact them back and a text field where they can describe their issue. This popups should also contain links to FAQ and Help page. 

Things to add to email:
`window.clientInformation.userAgent, window.clientInformation.platform, window.InnerHeight, window.innerWidth, window.location.url` if user is logged in on the server side will add `userId` too

**Comment by kevincrepin** [comment]
Closed: https://projects.invisionapp.com/d/main#/console/9829159/439830790/preview
Open: https://projects.invisionapp.com/d/main#/console/9829159/439830791/preview
Works pretty much same way as Intercom so when moving to that kind of solution, it shouldn't be too much of a different (for the user). Width is mobile proof.

Icons I'm attaching here, because Invision makes it hard :) 
[icons.zip](https://github.com/citizenos/citizenos-fe/files/5658192/icons.zip)

**Comment by ilmartyrk** [comment]
UI is ready, e-mail(s) need some tweaking

**Comment by loorm** [comment]
Triage 31. @KatiVellak, please have a look. We need to move on with deploying this.  Look at comments by Ilmar, he lists the data that we would be recording about the user who is using the Help Center bubble.

**Comment by KatiVellak** [comment]
The popup must include the information that by submitting the support request, COS will gather information about user's browser and OS versions, and screen size to be able to accurately assist. And that the information gathered is automatically attached to the support request the user will submit and only processed for assistance purposes. If there is more information we wish to gather and it seems unpractical to have so much information in that popup, we should supplement our privacy policy with this information and have short information and link to PP, e.g.: Please be aware that to be able to accurately assist you we will gather some of your information, for more information please visit {link to our PP].

**Comment by ilmartyrk** [comment]
@kevincrepin can you take a look at @KatiVellak comment? Is it possible to fit this info to current design or should we add confirmation popup that can display this data. Other solution that I can think of is a checkbox for user to allow us to gather extra data. What do you think @KatiVellak is that solution OK. If checked we gather the info I listed before and if not we only get the user inserted data.

**Comment by kevincrepin** [comment]
Yes, let's definitely not put all this info in there if we can avoid it. The checkbox seems like a reasonable solution for this. Updated the design to include this. Copy needs work.

**Comment by ilmartyrk** [comment]
@KatiVellak thanks for your review. Are you willing to add this data to PP. Basically everything you mentioned in your comment (OS, Browser version, screen size) and also current URL and `userId `if user is logged in is the data I would like to collect and that would probably be it as anything more would be asked case by case if needed.

**Comment by loorm** [comment]
@ilmartyrk I have removed the "blocked" status. Let's reactivate this task. This was waiting on the project plan and budget, we now have both. Let's finish this help center bubble.

**Comment by ilmartyrk** [comment]
First version is live, waiting on PP update for extra data from user and help page on web page to close the issue

**Comment by loorm** [comment]
Right now it doesn't seem to follow FE language. Maybe it's not supposed to, yet.
![Capture_1503](https://user-images.githubusercontent.com/22661743/111159463-cb2ec180-85a1-11eb-96e0-be7fa171b222.JPG)

**Comment by loorm** [comment]
Right now it doesn't seem to follow FE language. Maybe it's not supposed to, yet.
![Capture_1503](https://user-images.githubusercontent.com/22661743/111159634-fdd8ba00-85a1-11eb-8e74-8711c931e0ae.JPG)

**Comment by KatiVellak** [comment]
@ilmartyrk @loorm I have reviewed the current privacy policy and can confirm that it already has all needed information, thus from legal and data privacy perspective everything is covered to move on with the project.

**Comment by tiblu** [comment]
![image](https://user-images.githubusercontent.com/7405383/112174426-1464be00-8bff-11eb-9650-2e8e00d3d9a4.png)

@KatiVellak Do I understand it correct that we DO NOT NEED extra consent from User to collect following extra info along with the help request:

* Browser name and version (`window.clientInformation.userAgent` ex: `"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"`)
* Operating system name (`window.clientInformation.platform` ex: `Win32`)
* Browser window height (`window.innerHeight` ex: `688`)
* Browser window width (`window.innerWidth` ex: `1280`);
* The current URL from which the help request is sent (`window.location.href` ex: `https://app.citizenos.com/et/topics/87bd73c2-2250-43d4-b304-63c8f61023e6`)

?

**Comment by tiblu** [comment]
@tiblu  NOTE TO SELF: Add a shadow under the overlay so that on mobile it would not blend into other stuff too much.

**Comment by KatiVellak** [comment]
@tiblu Yes, you do understand it correct that we DO NOT NEED extra consent from User to collect the extra info along with the help request, because I have included all the needed information to our updated version of Privacy Policy.
