### ISSUE TITLE
Investigate eIDEasy suitability

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#599]
There is a service - https://eideasy.com/ - that might be useful for us. Need to look into it a bit.

**Comment by loorm** [comment]
Triage 31. Yes, let's look into it, but priority is lowish.

**Comment by ilmartyrk** [comment]
**Pros**: 
 - Supports multiple countries and authentication methods
 - Should be quite easy to setup, [API documentation](https://documenter.getpostman.com/view/3869493/Szf6WoG1)
 - we don't have to maintain our own authentication systems
**Cons:** 
 - Possibility that we would want to add authentication methods that they don't provide
 - If they have downtime users can't login/sign documents
 - Possibly cost, but this should be calculated https://eideasy.com/pricing/ seems that price is calculated per request
 - Seems that their own js library is not ready yet https://github.com/eideasy/eideasy-js-sdk

Overall, seems like a good alternative if we decide to alter our authentication/signing methods. It also should be easy to implement after reading some API documentation

**Comment by loorm** [comment]
Triage 35. Need to do some price calculation and risk analysis.

**Comment by loorm** [comment]
Financially, this would make sense. We currently pay around 133 euros to Sertifitseerimiskeskus for an average month of 279 signatures (mostly mobile ID). Using eIDEasy, the bill would be around 65 euros. 

In terms of risk, though, being dependant on someone for our core functionality does not rate well.

I propose this solution. We keep our own libraries and pay to SK for Estonian eIDs. However, we will remember eIDEasy and if we want to add aditional electronic signatures, we can decide whether to create our own native support or use their API.

WDYT @ilmartyrk?

**Comment by ilmartyrk** [comment]
Move to https://github.com/citizenos/citizenos-fe/issues/55
