### ISSUE TITLE
UX issue: attachments in topics

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#601]
When you open an attachment in a topic it opens in the same tab, so when you close it, you are no longer in COS, and have to reopen it and re-find the topic you were previously in. It should open in a new tab, for better UX. 

![image](https://user-images.githubusercontent.com/61320526/101749709-56457a80-3ace-11eb-9b18-36c3f5b67f39.png)

**Comment by loorm** [comment]
Triage 31. Confirmed. Estimated dev time 30 seconds. Fixed during Triage :)

Expected behaviour:
1) if downloadable attachment, do not open a new tab
2) if openable attachment (Drive etc), open in new tab
