### ISSUE TITLE
Posting topic on social media should show title + image in topic (if available)

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#609]
**What is the user story?**
Social media sharing is important for our users for sharing public topics. 
The channels are Facebook, LinkedIN and Twitter. 

**Which feature needs to be updated and how?**
Right now, none of the three social media channels show the topic title nor image when shared. On FB, shows up like this: 
![Screenshot 2020-12-21 at 22 46 47](https://user-images.githubusercontent.com/34899902/102821358-9b777f80-43df-11eb-85f6-7c473641cf54.png)

**Comment by liinaguiter** [comment]
NB! On FB, the title needs to be 60 characters or less (most likely).

**Comment by loorm** [comment]
Triage 32. @liinaguiter Are you trying to do this with a public topic or a private topic? A private topic will not and should not show title or content in FB. I tested it with a public topic in FB and LinkedIn and it worked for me. 
![FB_capture_working](https://user-images.githubusercontent.com/22661743/104295710-7ac7b480-54c9-11eb-9e5c-7f1214e991be.JPG)

**Comment by liinaguiter** [comment]
Weird that it worked for you.

It does not work for me. Trying to post a public topic, the exact same one
(PARE personalijuhi ametikirjeldus). See screenshot of how it looks for me.

**Comment by liinaguiter** [comment]
It worked now!

I logged out of COS, then posted the public topic. And then it showed the
title and description.
Then logged in to COS, posted the public topic. And also showed the title
and description.

**Comment by loorm** [comment]
Issue solved, then :) Closing topic.
