### ISSUE TITLE
In multiple choice, min/max voting plus button does not work

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#610]
**What is the problem?**
In multiple choice, min/max voting plus button does not work. Min button works. Please see video. 
https://user-images.githubusercontent.com/34899902/103351949-781e9580-4aad-11eb-8556-d8415e165565.mov

**Why is this a problem?**
Bug. 

**Possible solution.**
Please fix if possible.

**Comment by ilmartyrk** [comment]
Triage 32 .The "+" button only allows incrementing when inserted options count is more than current value in the max options field. Decided to visually separate max - min inserting as a next step after inserting options.
