### ISSUE TITLE
Social media previews are slow (9s)

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#628]
**What is the problem?**
Copying topic link to social media post times out.
![COS_error](https://user-images.githubusercontent.com/22661743/105973720-bfd91280-6095-11eb-8ef7-a26023e5a5e2.JPG)

**Why is this a problem?**
Topics get their audience from social media.

**Possible solution.**
N/A

**Comment by loorm** [comment]
Triage 34. Occasionally replicates, occasionally loads. Needs investigation, how social media loads a page to display a preview.  Need to test and find out, why does the time-out occur.

**Comment by ilmartyrk** [comment]
By looking at google page speed insights data, it is possible that background loading all views .html files is blocking the rendering/loading of social media views. Will confirm when removing this pre-loading part in our test environment

**Comment by ilmartyrk** [comment]
Removed template-cache.js and seems that it actually didn't make any difference in social media box loading timTe

Tested using: https://socialsharepreview.com/

**Comment by loorm** [comment]
Triage 35. Could be a Prerender service issue.  Need to investigate further.

**Comment by ilmartyrk** [comment]
After updating prerender code and removing template-cache from FE got speed up-to 6s. While doing the research tried own prerender system by using puppeteer, but it still was as fast/slow as prerender server, even without all the logic done by the prerender server (link checking etc.). Only thing that made any difference was removing template-cache.js from our FE code, as after going deeper in the code, found it was blocking the server response. As these files loaded by template-cache are quite small, there is no visible speed drop in page loading times. Will close this issue for now, but we can come back to it if it should re-appear

**Comment by ilmartyrk** [comment]
Important!!! to know, prerender production chrome crashed, but managed to get it working after https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache
