### ISSUE TITLE
"Disagree" counts one click multiple times 

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#631]
**What is the problem?**
Clicking "Disagree" once is displayed as a greater number. See video. It corrects, after you refresh the page.

https://drive.google.com/file/d/1UntbqRU1rc6mSJu9Hj7wxerP9ceKz8VH/view?usp=sharing

**Why is this a problem?**
It's just incorrect numbers and confusing

**Possible solution.**
N/A (it seems to use whatever number of "Agree" votes there are)

**Comment by loorm** [comment]
Triage 34. Replicated. Likely a small fix. Estimated dev time 10 minutes.

**Comment by ilmartyrk** [comment]
Issue was on the API side, fixed by https://github.com/citizenos/citizenos-api/commit/733ee11400f6137e4312a72eb1579f3e09c4f51c
