### ISSUE TITLE
"Edit" shortcut not working on mobiles

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#632]
**What is the problem?**
On mobiles in My Topics view, Edit shortcut does not work. You are still directed to viewing the topic, not editing the topic.  Touching the screen seems to register a touch for the whole block, not the individual shortcut link within. Android 7 & 9, Chrome.
![Screenshot_20210209-132018](https://user-images.githubusercontent.com/22661743/107356788-ea858b00-6ad9-11eb-8b4d-cea359f4b78c.jpg)

**Why is this a problem?**
It's a bug. It should work.

**Possible solution.**
N/A

**Comment by loorm** [comment]
Triage 34. Replicated. "Edit" shortcut malfunctions in desktop view as well. Redirects to another topic, presumably the one on the top of "My Topics" list. Does not do so every time. Estimated dev time 1 day.

Hypothesis: if you have a topic where voting is open, it always takes you to voting. As if to say: "Common, man, submit your vote!"

**Comment by ilmartyrk** [comment]
Created a separate issue from Triage 34  data https://github.com/citizenos/citizenos-fe/issues/643
