### ISSUE TITLE
UX issue: users click "leave topic" when they want to get back to the topic list or group

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#636]
**What is the user story?**

Users click on "Leave topic" option when they want to get back to the topic list or group list. 

<img width="819" alt="Leave topic" src="https://user-images.githubusercontent.com/45175679/108174275-e70c8800-7107-11eb-9a70-0f46374c8236.png">

**What is the requested feature?**

I would suggest to remove "leave topic" under the topic options, as this is confusing for users. 
"Leave topic" is more logical under the general topic information and it could be only under the topic actions:

<img width="824" alt="Leave topic2" src="https://user-images.githubusercontent.com/45175679/108174605-4cf90f80-7108-11eb-9645-89270285b6d9.png">

**Additional information**
N/A

**Comment by loorm** [comment]
Triage 34. Can see the confusion :) @kevincrepin Can you please suggest a solution?

**Comment by tiblu** [comment]
@kevincrepin Do you have time to comment on this?

**Comment by kevincrepin** [comment]
Hey, sorry. Very busy month. Earliest I can have a look at this is in April, I'm afraid :s

**Comment by tiblu** [comment]
@kevincrepin No problem!

@anettlinno I will do the quickfix:

* Remove "Leave" from Topic view
* "Leave" remains on the Dashboard.

**Comment by tiblu** [comment]
Removed "Leave topic" link from Topic view. Users can leave from Dashboard.
