### ISSUE TITLE
Google Picker API update 31.03.2021

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#637]
Hello Google Picker API developer,

We are writing to let you know about upcoming changes to the Google Picker API. We are contacting you because you use one or more apps connected to the Google Picker API.

What do I need to know?
Starting March 31, 2021, the Google Picker API will no longer support views and interactions with the following Google services:

Google Photos
Google Maps
YouTube
Google Image Search
Google Video Search
Webcam view (to record videos or take photos using a web camera).
The Google Picker API integration with Google Drive will remain unchanged and your application will continue to operate.

What Action do I need to take
If your applications use the Google Picker API integration for any of the services listed above, you will need to migrate your existing Picker integration to our modern APIs targeted for each specific application:

Photos API
Maps API
YouTube API
Custom Search API (supports Image & Video Search)
How do I know what Apps are affected?
Apps are affected if they use one or more of the following views: ImageSearchView, MapsView, PhotoAlbumsView, PhotosView, VideoSearchView, WebCamView.

Apps that currently have the Google Picker API enabled in the Google Cloud Platform console are listed below, up to ten. If you have more than ten apps, see the attached file. Please be sure to check for each one whether the app will be affected and migrate accordingly.

COSTest (costest-173306)
CitizenOS (citizenos-173522)

**Comment by loorm** [comment]
Triage 34. Needs investigation. Deadline is March 31.

**Comment by ilmartyrk** [comment]
As we are not using functionalities that are removed from picker, we are not affected.
