### ISSUE TITLE
Mobile responsiveness not working correctly in Estonian mode

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#638]
When trying to take a phone screenshot of the voting customisation options in Estonian, it seems that the mobile responsiveness isn't working properly (at least for this bit) when switched to Estonian. All the text, buttons etc. fit neatly within the width of phone screen when in English, but when switching to Estonian the content is slightly too wide for the screen. I tried it in both Chrome and Firefox (on Android) and the same thing happened. See screenshots in ENG and EST here: 

![Screenshot_20210218-203329](https://user-images.githubusercontent.com/61320526/108412796-86c23700-722a-11eb-9dbc-1bff3177a098.png)
![Screenshot_20210218-203916](https://user-images.githubusercontent.com/61320526/108412798-875acd80-722a-11eb-9ea0-4ae581ed508e.png)

**Comment by loorm** [comment]
Triage 34. Replicated on smaller screens. Buttons fit nicely when "TAVALINE" and "MUU VALIKVASTUS" are displayed, but once you make either choice, in Estonian the view becomes too wide to fit on screen. In English, this does not happen. Hypothesis: we saw a difference in e-ID on-off switch location and logos beneath it. Check this first. Estimated dev time: 2 hours.
