### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by battosai30** [citizenos/citizenos-fe-old#641]
Hi guys,

With a lot of effort I finally got my citizenos working :)

But I'm surprised to not found any admin panel to moderate the platform ? 

So if I did not missed something, it could be a great feature :) 

Regards

**Comment by tiblu** [comment]
@battosai30 Thanks for creating an issue!
Can you elaborate on the admin panel, that is, what functionality would you expect it to have?

**Comment by loorm** [comment]
Triage 35. @battosai30 There is no admin panel. We recognize the need, but have not got around to creating one.
**a) Topic moderation is handled via e-mails.** We use something called "community moderation", where no single moderator holds authoritarian censorship power. Instead, random community members are chosen to assess topics, which are highlighted for moderation. They receive e-mails, that request them to review and decide. A visual explanation is here:
![Topic Moderation Workflow_with info](https://user-images.githubusercontent.com/22661743/111446529-2df49a00-8715-11eb-8a53-7f89a97c7ede.jpg)

**b) Platform configuration is handled by editing the config file manually.**
Guide to changing configuration and adding Moderators etc. is found under our API [wiki ](https://github.com/citizenos/citizenos-api/wiki/Configuration)


- You said "with a lot of effort". Could you please elaborate, what required effort and how could we make it easier?

- If you would be willing to contribute code, creating a dedicated admin page, we would be most grateful.

**Comment by loorm** [comment]
@anettlinno This explanation about how we do moderation should go somewhere in our Help documentation.
