### ISSUE TITLE
UX: Dashboard (my/topics && my/groups) - when expanding multiple sections in /my/(topics|groups) switching between these views does not load the first item from the list

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#646]
**What is the problem?**

UX: Dashboard (my/topics && my/groups) - when expanding multiple sections in /my/(topics|groups) switching between these views does not load the first item from the list.

Reproduce:

* Go to /my/groups (or topics)
* Open up a detail view of a group (topic) that has multiple tabs to expand (user_list, group_list, topic_list). 
* Expand multiple tabs.
* Switch to /my/topics view from the menu.

Result:

* In the new /my/topics view, the first item in the list IS NOT EXPANDED.

![image](https://user-images.githubusercontent.com/7405383/111477641-ffd48180-8737-11eb-910c-0ec49cdbdcb6.png)

Expected:

* First topic in the list to be expanded, details shown on the right.

Extra info:

* If you reload the page with several `openTabs` parameters, it behaves correctly. IT ONLY acts up when changing state from menu.
* Looks like a race condition switching states, as if in "MyCtrl" timeout is added to the redirect to the expanded view, then it works just fine.
* Also works fine when `openTabs` is not defined on `my` route level, but on individual routes `/my/topics/` and `/my/groups`, but then navigating between the 2 views, parameters are not persisted.

**Why is this a problem?**

UX not consistent, UI looks broken.

**Comment by loorm** [comment]
Triage 36. Partially replicated. Probably race condition. Prioritizing to lowest. Fix only if nothing else to fix in the Universe.
