### ISSUE TITLE
BUG: Dashboard - inviting a User collapses the members sections on /my/groups.

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#647]
**What is the problem?**
When inviting Users to a Group, when the dialog closes, the "Users" section is collapsed.

**Why is this a problem?**
Inconvenient.

**Possible solution.**
Make the section reload it's content and stay open.

Related to:

* https://github.com/citizenos/citizenos-fe/issues/646
* https://github.com/citizenos/citizenos-fe/issues/348

**Comment by loorm** [comment]
Triage 36. Replicated. Estimated dev time 1 hour. Prioritizing.
