### ISSUE TITLE
Changing password when reactivating deleted account

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#658]
**What is the user story?**
After deleting user account, user wants to create new account with the same email address. She gets system message that "This email address is already in use" and do not understand that she needs to change the password for reactivating new account. 

**Which feature needs to be updated and how?**
System message should say that "For reactivating your account with this email, you need to change your password"

**Additional information.**
N/A

**Comment by ilmartyrk** [comment]
After doing some checks it seems that there is possible conflict with user accounts and e-mail aliases. User deleted account and while trying to create a new account, stumbled upon old un-activated or un-used account that was related to this email. We don't have any 2 different users with same e-mails and we always delete email when user deletes his/her account.

Only solution that comes to my mind is to go case by case when these conflicts happen.

**Comment by loorm** [comment]
Triage 36. When account is deleted, e-mail (and all other user related data) is deleted as well. In this case, the user must have done someting other than deleting an account. When an account has been deleted, this conflict is not possible.
