### ISSUE TITLE
Big fat notification for "Your vote has been registered"

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#660]
**What is the user story?**
"Your vote has been registered" notification should be bigger and better distinguishable as users do not "see" it in the current version. 

<img width="570" alt="Vote has been registered" src="https://user-images.githubusercontent.com/45175679/112019274-f1bba200-8b37-11eb-84fd-1f849d0ee48b.png">

**Which feature needs to be updated and how?**
"Your vote has been registered" pop-up window or bigger and more colorful (button-like) window that distinguishes from the background and other texts. 

**Additional information.**
N/A

**Comment by tiblu** [comment]
![image](https://user-images.githubusercontent.com/7405383/116399139-43d79d80-a831-11eb-8663-a231ba965a86.png)

**Comment by loorm** [comment]
Triage 36. Add border 5px solid green. Solved.

**Comment by loorm** [comment]
Linked to #696

**Comment by tiblu** [comment]
Did the following:

* Added big green border to "Your vote has been registered".
* Still needs investigation why top success message dissapears on signing - https://github.com/citizenos/citizenos-fe/issues/696

![](https://user-images.githubusercontent.com/7405383/116399139-43d79d80-a831-11eb-8663-a231ba965a86.png)
