### ISSUE TITLE
Increase the number of attachment

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#661]
**What is the user story?**
User needs to add more than 10 attachments. E.g. there are more than 10 board member candidates and they want to upload candidate introductions and presentations.

**Which feature needs to be updated and how?**
Increase the number of attachments from 10 to 15 or 20

**Additional information.**
Something you want to add, that didn't fit one of the boxes above.

**Comment by loorm** [comment]
Triage 36. We can do this, but this will become a paid feature. Every attachment is a direct cost to us, therefore additional attachments = additional cost.

**Comment by loorm** [comment]
Added to User Epic 7 - Paid Features.
