### ISSUE TITLE
Group and topic rights could be better distinguished and explained

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#662]
**What is the user story?**
User story 1: Group admin gave all group members "reading" rights and "admin" rights to the topic. User (group admin) did not understand which right is at a higher level - group or topic. In this case user thought that group rights are higher than the topic rights, and as a result, one of the group members deleted one topic.
User story 2: Group admin expects that when giving someone group "admin" rights, they automatically have topic "admin" rights. User didn´t find the solution, as he could not find the place where he could change the topic rights.

**Which feature needs to be updated and how?**
Group rights by default could be "reading" rights and we should not give the group admin the ability to set group rights during the group creation process. The possibility to change group rights could be available under group´s general information (admin page) where admin would be able to change the group rights either one by one or for all users at once.

**Additional information.**
How can we explain to the user that topic rights are above group rights? I don´t have the answer :)

**Comment by loorm** [comment]
Triage 36. Description is somewhat confusing. Need to clarify problem, before working on a solution. Postponed until Triage 37.

**Comment by anettlinno** [comment]
Triage 63. In redesign we should describe more precisely in a place where (admin) user determines user rights -- what are the differences between different rights.

**Comment by ilmartyrk** [comment]
Move to https://github.com/citizenos/citizenos-fe/issues/52
