### ISSUE TITLE
Update Environment variable config to support json values

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#669]
We currently need to make new commits when new language is added because there was not an option to add JSON from environment variables. But as there is now way to allow config to use JSON values we can update our config files to support it where possible. https://github.com/lorenwest/node-config/wiki/Environment-Variables

**Comment by tiblu** [comment]
https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables

```
// config/custom-environment-variables.json
{
  "Customer": {
    "dbConfig": {
      "host": "PROD_SERVER"
    },
    "credit": {
      "initialDays": "CR_ID"
    },
    // Environment variables containing multiple configs
    // New as of config@1.14.0
    "settings": {
      "adminAccounts": {
        "__name": "ADMIN_ACCS",
        "__format": "json"
      }
    }
  }
}
```

**Comment by loorm** [comment]
Triage 36. Estimated dev time 4 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
- [x] FE update 
    - [x] TEST
    - [x] LIVE 
- [ ] API update 
    - [x] TEST
    - [ ] LIVE
