### ISSUE TITLE
Bulleting & numbering does not work in arguments section

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#673]
**What is the problem?**
Bulleting and numbering does not work in arguments session. When I click either on the bulleting or numbering button, nothing happens.

<img width="576" alt="Bullets   numbers" src="https://user-images.githubusercontent.com/45175679/112473896-9aa41000-8d77-11eb-9e3a-57d9d645c82c.png">

**Why is this a problem?**
Bulletin & numbering is not working in arguments section.

**Possible solution.**
Fix it :)

**Comment by ilmartyrk** [comment]
Tracked it down to be a style issue, just needs bulleting and numbering visibility restored
