### ISSUE TITLE
ON/OFF toggle is truncated in French, Macedonian, Portuguese (Brazilian), Polish, Slovak and Ukrainian

### ISSUE THREAD

**Issue by helenkask** [citizenos/citizenos-fe-old#678]
ON/OFF toggle is truncated in all places it's used in the UI in French, Macedonian, Portuguese (Brazilian), Polish, Slovak and Ukrainian. 

The translation lengths for extra context:

ON

AAN | Dutch
JAH | Estonian
✔ | Finnish
Activé | French
AN | German
ON | Indonesian
IES | Latvian
ВКЛУЧЕНО | Macedonian
WŁĄCZONY | Polish
ATIVADO | Portuguese, Brazilian
ДА | Russian
ZAP | Slovak
Ac | Spanish
УВІМК | Ukrainian

UIT | Dutch
EI | Estonian
✘ | Finnish
Désactivé | French
AUS | German
OFF | Indonesian
IZS | Latvian
ИСКЛУЧЕНО | Macedonian
WYŁ. | Polish
DESATIVADO | Portuguese, Brazilian
НЕТ | Russian
VYPNÚŤ | Slovak
Des | Spanish
ВИМК | Ukrainian

![french - topic settings](https://user-images.githubusercontent.com/66247221/113200051-8b89fa00-9270-11eb-9612-70bb1225a78e.PNG)
![macedonian - topic settings](https://user-images.githubusercontent.com/66247221/113200056-8c229080-9270-11eb-8a61-ee1948d44183.PNG)
![polish - standard voting first options](https://user-images.githubusercontent.com/66247221/113200060-8cbb2700-9270-11eb-9371-354f64b8e674.PNG)
![vote type choosing3 pt-br](https://user-images.githubusercontent.com/66247221/113200062-8cbb2700-9270-11eb-80c9-dc98c8f879a1.PNG)

**Comment by loorm** [comment]
Triage 36. There must be a way to shorten things in Portugese. In Estonian you can say "Lülita sisse" or "Sisse" or "Jah". We can't expand the toggle buttons, because of mobile screens. Let's limit the number of characters in CrowdIn allowed to translators. Suggested max chars 4. Closing issue.
