### ISSUE TITLE
ETHERPAD: On MOBILE clicking Topic title scrolls page so that the cursor is out of screen

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#680]
**What is the problem?**
When I create a new Topic or edit an existing one on MOBILE, if I try to edit the title by clicking on it, it will scroll EP contents so that the actual cursor is out of vision and I cant see where and what I am typing.

Video:  https://user-images.githubusercontent.com/7405383/113566921-4837de80-9616-11eb-8a0d-bc712ecec410.mp4

Screenshot: 
![image](https://user-images.githubusercontent.com/7405383/113567069-93ea8800-9616-11eb-943c-2896ec407f0e.png)

**Why is this a problem?**
UX fail, creates confusion.

**Possible solution.**
?

**Comment by loorm** [comment]
Triage 36. Partially replicated. Seems to depend on mobile screen size. On larger screens, the bug does not appear. Estimated dev time 8 hours.

**Comment by ilmartyrk** [comment]
After going deep into etherpad code, creating a simple plugin, commenting out all scroll related functionalities, going through CSS etc.  and debugging with phone found that this is a browser functionality to focus on active input. This can be reproduced by trying to add an argument to a topic. Textarea is always scrolled to the view
