### ISSUE TITLE
TECH DEPT: All "ep_" packages published in NPM should have a release workflow

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#683]
Add publish workflow to all "ep_" packages published in NPM by CitizenOS.
Sample: https://github.com/citizenos/ep_image_upload/blob/master/.github/workflows/npmpublish.yml

**Comment by loorm** [comment]
Triage 36. Estimated dev time 8 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
Use this readme for guide in each package https://github.com/ether/eslint-config-etherpad ,
check for lint errors before push in each plugin
remove package-lock.json from .gitignore if exists

List of packages:
- [x] ep_foot_note
- [x] ep_resize 
- [x] ep_themes_ext
- [x] ep_embed_floating_toolbar
- [x] ep_authorship_toggle
- [x] ep_webhooks
- [x] ep_translations
- [x] ep_title_limit
- [x] ep_inline_voting

**Comment by ilmartyrk** [comment]
Updated all packages that we currently have listed under our organization
