### ISSUE TITLE
Uploading attachments not working

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#692]
Uploading attachments from my computer doesn't seem to work - it just goes back to this screen and nothing happens... 

![image](https://user-images.githubusercontent.com/61320526/116104174-8756ce00-a6b0-11eb-8e73-6cd2804a64a8.png)

**Comment by loorm** [comment]
Triage 36. This is a CSP policy issue. Short term, it's fixed. Upload is currently working. Long term - need to work out a CSP rule or exception. Estimated dev time - 8 hours.

**Comment by BeccaMelhuish** [comment]
OK great, yes works for me now! I also just noticed that it's only possible to upload one document at at a time, rather than being able to select several different documents and upload them at once, which would make it more user-friendly if possible. Currently it's quite slow and repetitive if you're uploading lots of documents.

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-fe/commit/cf9b3aefec5b2f192645e52a823ba8e0b76fc71a @BeccaMelhuish please confirm, also added support for multiple files to be uploaded
