### ISSUE TITLE
Suggested fixes for FAQ 1 (login/access issues)

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#693]
These are my suggested tweaks to try and reduce the number of people having trouble with accessing a group or topic due to logging in with the wrong email address. These link to FAQ 1: "Why can't I access the group or topic I've been invited to?"

These are the ideas I've come up with after testing the various login scenarios, and trying to replicate the journey the user has when they try to log in with the wrong email address. However, it would be good to put heads together to consider if there are any other scenarios I've missed! (I.e. which these tweaks wouldn't cover.) 

(1) Edit to invite email

I suggest adjusting the invitation email so that it is like it is below. Currently the information about which email address to log in with is very small and at the bottom of the email, out of sight so that people are unlikely to read it. Changing the hierarchy to the below should help ensure they actually read the "Please note" message, before clicking the button. 
Obviously wherever it says "Topic" in the mockup it should be changed to "Group" for a group invite. 

(Side note - currently the email address is hyperlinked, which doesn't make much sense, as when clicking on the email address they open up an email to themselves...). 

![image](https://user-images.githubusercontent.com/61320526/116227401-65168c00-a754-11eb-8e1a-61a7a27d2c92.png)

(2) Edit to pre-login pop-up

I suggest editing this pop-up to the below, to make it clearer. 

![image](https://user-images.githubusercontent.com/61320526/116228400-86c44300-a755-11eb-84cf-7c9c50b2ce6f.png)

My suggested text for the Help Button at the end of the "Heads up!" message, would be: 

"Topics and groups can only be accessed using a Citizen OS account which is registered with the same email address the invitation was sent to. 

Need more guidance? View Q1 in our FAQs (hyperlinked ‘FAQs’)."   
 
(3) Add a pre-login pop-up for Groups

Currently the above pre-login pop-up only appears when you click through from a topic invite. I would suggest it should be the same (but with the text adjusted accordingly) for group invitations too. 

(4) Edit to access permissions error message

This is my suggested edit to the edit message people receive when they have logged in with the wrong email address and therefore cannot access the topic / group. 

![image](https://user-images.githubusercontent.com/61320526/116228771-0225f480-a756-11eb-93b6-2b301cb4e4c5.png)

My suggested text for the Help Button at the end of the "Please note" line, would be the same as previously: 

"Topics and groups can only be accessed using a Citizen OS account which is registered with the same email address the invitation was sent to. 

Need more guidance? View Q1 in our FAQs (hyperlinked ‘FAQs’)."

**Comment by loorm** [comment]
Triage 36. @kevincrepin We need you input on this. Some of these suggestions seem necessary, but please tell us, your thoughts.

**Comment by kevincrepin** [comment]
Hey, I'll have a look at this tomorrow.

**Comment by kevincrepin** [comment]
Yes, makes sense to add those lines to make it clearer. I added the dialog here for dev: https://projects.invisionapp.com/d/main#/console/9829159/450875800/preview

**Comment by BeccaMelhuish** [comment]
We (@anettlinno @tiblu @ilmartyrk, in meeting on 06.05) discussed these solutions and agreed they were all useful additions to the UX to help reduce login confusion. And that once they have been developed we will test scenarios with users to make sure they no longer get confused. (Please let me know once they are live). 

@kevincrepin for the help buttons here, and in other FAQ related issues, @tiblu and @ilmartyrk need a design to be created for the pop ups (which appear when you click on the question mark), which could then be used for all future help button pop ups, as we are planning to include a few. 

Things which we discussed would need to be considered for the pop up design were: 
- How would links look
- how does the user close it
- what if it needed to include an image (or is it best to keep it text only?)
- should it include a “Was this helpful?” feedback feature so that we know if we are solving their problems?
- should it include links to the help email? Or is it better UX practice to keep it all very simple? 
- Also, it needs consideration of how it will look on mobile, especially when there is a lot of text.  

@kevincrepin your thoughts and input on the help buttons in general would be appreciated too. We have discussed included quite a few throughout the platform, to give the user easy access to relevant help/answers whenever they have issues/questions.

**Comment by loorm** [comment]
@kevincrepin Please see above for some more comments and requests to you. We would like to move on with this, but need your input first.

**Comment by kevincrepin** [comment]
This is all related to this task which is in progress: https://github.com/citizenos/citizenos-fe/issues/706

**Comment by BeccaMelhuish** [comment]
@kevincrepin @loorm @ilmartyrk Though I think "(1) Edit to invite email" could be moved forwards with already, if everyone's in agreement with the suggested changes, as there are no help icons involved in that one?

(And as mentioned in #706, I feel we could already go ahead with the Help icons now, before the rest of the Help panel (or whatever we will call it) - just using the designs Kevin made for Level 2 only to start with.)

**Comment by BeccaMelhuish** [comment]
And actually (2), (3) and (4) could all be moved forwards with too, again if everyone is happy with the suggestions. The changes could be made but with the Help icons left off for now, until we are ready to start using them.

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk would it be possible to go ahead with these four enhancements as @kevincrepin agreed that they would be sensible from a UX point of view, and I think there were no other objections? I believe they were in waiting due to the help button design not being ready (as this is part of the work in progress Help Centre panel) but they would all work fine without the Help Buttons too, in the meantime. 

And if so, for number 4, could a "access denied" heading be added to this screen as per below, as this will make it easier for clearly titling the relevant Help section in the Help Centre? 

![image](https://user-images.githubusercontent.com/61320526/133419564-7f5be14c-c9d3-4549-b740-82bf91267a6a.png)

My reason for wanting these done soon if possible, is that I would like to test some common/important possible user issues while testing the Help Centre design - e.g. giving them tasks to do that we think they might struggle with and therefore need to access the Help Centre for. So I can test that these solutions work at the same time, if they are done before the tests take place.

**Comment by loorm** [comment]
I've always felt, that "Access denied" is a rather sharp expression. Imagine going to a hotel or restaurant and have someone turn to you and say: "Access denied!". As a user, I'd like online environments to be respectful in their communication style, same as people. "Sorry, you don't have permission to access this." is much more courteous, something that I wouldn't mind hearing in the real world, when trying to go somewhere I'm not supposed to go. Perhaps remove the sad smiley, too. It's not sad, it's just the way it is.

**Comment by BeccaMelhuish** [comment]
OK sure yes that makes sense re the additional heading. It was mostly for ease of the user finding help in the Help Centre, but will see how else I can make it clear!

And I see that Ilmar has moved this to prioritisation now so will await updates on the other 4 suggestions once discussed :)

**Comment by anettlinno** [comment]
I cannot see why we couln´t go ahead with these enhancements. I will link here issue #785 as it relates with (4). 

Regarding the text for (4) I agree with Margo as we have agreed that our voice is friendly and polite :) I propose we remove the "Access denied" and leave only "Sorry, you don´t have permission to access this topic / group" and then the explanatory text. 

Also (2) Edit to pre-login pop-up: we shouln´t use the phrase "You must log in.." but rather "Please log in with..."

**Comment by anettlinno** [comment]
Triage 46. 
(1) Edit to invite email -- changing the texts and visuals as proposed by Becca. 
(2) Edit to pre-login pop-up -- changing the texts (Heads up! Please log in...) and visuals on pop-up as proposed by Becca
(3) Add a pre-login pop-up for Groups -- changing texts
(4) Edit to access permissions error message -- changing the texts
Sending to development.

**Comment by KatiVellak** [comment]
No legal impact.

**Comment by ilmartyrk** [comment]
- [x] Edit to invite email -- changed the texts and layout
- [x] Edit to pre-login pop-up -- changed the texts, but didn't add help icon as we have no proper design
- [x] Add a pre-login pop-up for Groups -- View already existed, changed texts
- [x] Edit to access permissions error message -- Removed smiley and fixed text order
