### ISSUE TITLE
Suggested fixes for FAQ 7 re attachments

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#695]
This is my suggestions for a tweak to reduce the number of people having trouble with FAQ 7: "What is the maximum attachment size that can be uploaded, and what file types are allowed?"

**Help button added where marked in yellow below**

This would be my suggested text for it: 

"The maximum size of a single attachment in a topic is 50 MB. 

A maximum of 10 files can be attached to one topic.

Acceptable file types are: 'txt', 'pdf', 'doc', 'docx', 'ddoc', 'bdoc', 'odf', 'odt', 'jpg', 'jpeg', 'img', 'png', 'rtf ',' xls', 'xlsx', 'ppt', 'pptx', 'pps',' xlt'. "

![image](https://user-images.githubusercontent.com/61320526/116253136-7ff6f980-a770-11eb-99d9-005f5e0f44a9.png)

**Comment by loorm** [comment]
Triage 36. Adding all this text would be UX clutter. Let's add this instead to the error message.  The size is already in error message. Will add file types, too. So if you try to upload something unacceptable once, then you get the info of what is acceptable. Estimated dev time 4 hours. Priritizing.

**Comment by ilmartyrk** [comment]
Fixed
