### ISSUE TITLE
"Start voting" button is hidden when adding voting options in mini-voting

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#703]
**What is the problem?**
When adding voting options in the mini-voting window, the "Start voting" button is hidden. Scrolling moves the topic window but not the mini-voting window. 

<img width="514" alt="Mini-Voting" src="https://user-images.githubusercontent.com/45175679/117311451-de1c8e80-ae8c-11eb-84d8-cf9f1c61ac72.png">

**Why is this a problem?**
User cannot start voting after s/he has defined many voting options because "Start voting" button is hidden.

**Possible solution.**
Mini-voting window could be scrollable.

**Comment by ilmartyrk** [comment]
Seems to be an issue with `ep_resize` plugin. Will take it as high-priority
