### ISSUE TITLE
Closing the Help Bubble

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#707]
When looking at the Help Bubble I had trouble working out how to close it, as I instinctively clicked off it to close, then looked for an "X" button next. 

So perhaps adding these two options rather than having to click on the question mark icon to close it would be more user friendly. 

Or perhaps have all three options, so that whatever a user tries, it works first time?

**Comment by loorm** [comment]
Triage 37. Replicated. Estimated dev time 15 minutes. Prioritizing.
