### ISSUE TITLE
Make activity feed icons more readable

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#714]
**What is the user story?**
I want to get a quick visual overview of what has happened by simply looking at the activity feed. 

**Which feature needs to be updated and how?**
- [x] Change user action icon (envelope) and group action icon (people) to a different color than topic action icon (document).  Currently, it is easy to miss at a quick glance, that there are three different types of icons. 
- [x] In Activity feed drop down, rename "User's activities" to "My activities". Currently, the two options at the bottom of the drop-down are too similar.
- [x] Remove pin actions from Activity feed. Since pinning has no effect on other users and is essentially only a topic sorting feature, it unnecessarily clutters the activity feed. 
- [x] Classify all argument actions as discussion (yellow chat bubble icon). Currently, only argument actions have a yellow icon, byut all reactions to arguments are blue.
- [x] Classify all voting related actions as voting (green pie chart icon). Currently, actions related to voting delegation are blue.

![delegation_wrong_icon_bug](https://user-images.githubusercontent.com/22661743/118106890-c8f0b400-b3e6-11eb-88a9-b517b6d70b81.jpg)
![reaction_wrong_icon_bug](https://user-images.githubusercontent.com/22661743/118106932-d443df80-b3e6-11eb-9584-ca00e47550fd.jpg)
![user_topic_icons_similar_bug](https://user-images.githubusercontent.com/22661743/118107454-6ea42300-b3e7-11eb-9e5e-9360ec763e0e.jpg)

**Additional information.**
@kevincrepin can suggest a new colors for user and group actions icons.

**Comment by loorm** [comment]
Triage 37. Estimated dev time 4 hours. @kevincrepin, please suggest 2 additional colors for icons. Prioritizing.

**Comment by kevincrepin** [comment]
@ilmartyrk you can find the new icons here: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=85%3A71
