### ISSUE TITLE
Closed topic is not really closed at all.

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#717]
**What is the problem?**
When you close a topic, it is only closed in the sense, that you cannot edit the content. Several other options remain available, but shouldn't.

Adding new users while viewing topic gives an error message, that inviting was unsuccessful. In reality, however, the user was invited and does receive access upon accepting the invite. From "My topics" view, there is no error message, either, you can simply add new groups and users to a closed topic. And remove them.

No idea, why changing voting deadling options shows up in settings for a closed topic, either :)

![closed_not_closed_bug](https://user-images.githubusercontent.com/22661743/118114952-f4789c00-b3f0-11eb-81a3-446bcc3820fa.jpg)

**Why is this a problem?**
The idea behind a closed topic is, that it is done and finished in all senses. However, for record keeping purposes, it is kept around, instead of deleting it. Being able to add categories, hashtags, invite new users and groups and especially adding new arguments and updates can substantially change the appearance and context of what the topic was about.

**Possible solution.**
A closed topic should be closed in all senses. Changing group and user access rights, categories, hashtags, updates should all be locked and inivisible.

**Comment by loorm** [comment]
Triage 37. Estimated dev time 3 days. Prioritizing.

**Comment by ilmartyrk** [comment]
Tasklist:
**API**
- [x] Update endpoints:
    - [x] PUT/PATCH /api/users/:userId/topics/:topicId
    - [x] PUT /api/users/:userId/topics/:topicId/tokenJoin
    - [x] POST /api/users/:userId/topics/:topicId/invites/user
    - [x] POST /api/users/:userId/topics/:topicId/events
    - [x] POST/PUT/DELETE /api/users/:userId/topics/:topicId/members/groups


**FE**
- [x] Hide all disabled features from settings
- [x] Hide all disabled features from topic view
- [x] Hide all disabled features from my topics

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-api/commit/1d57f5893ee16c77cd20a49dc940fd39d8429eec and https://github.com/citizenos/citizenos-fe/commit/ed6f9bd3360d7781751bd91859e4b926c1707a0a
