### ISSUE TITLE
Login/Registration potential confusion

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#725]
**What is the user story?**
When logging in, if I write my email address in wrong when logging in then I get taken straight to the Register screen. Once that happened previously and I almost accidentally registered a new account with the mispelled email as I didn't expect it to automatically switch to "register" (and when logging in quickly you don't always read the screen properly!), and this second time I started editing my email address in the register field, before realising I needed to go back to the previous field to try and log in (as I remembered it had happened before). Definitely some room for user confusion/frustration there I think. 

**Which feature needs to be updated and how?**
Perhaps separating out Login and Register into two buttons so the user can choose what they are trying to do (seems to be common practice from my experience?) and not just assuming the user wants to register just because they've entered an email address that the system doesn't recognise. 

**Additional information.**
Am just writing this quickly now but happy to think through further what a better solution could be if helpful!

**Comment by BeccaMelhuish** [comment]
Or just a show password tickbox like Google has would also work, maybe better: 

![image](https://user-images.githubusercontent.com/61320526/119819628-7c2dd280-bee8-11eb-8206-ebe152b581f0.png)

**Comment by loorm** [comment]
Triage 38. We discussed this. We are not fans of an additional button. We propose another solution. In the Register dialog window:

1. Change title from "Register" to "Register new account".
2. Add another line of text below the dialog window title "We didn't find an existing account with this e-mail. Do you wish to register a new account?". Possibly in an eye-catching color. 

@kevincrepin Your input needed once more.

![register_COS](https://user-images.githubusercontent.com/22661743/120283095-7e66a700-c2c3-11eb-95d8-40fc86b3991e.jpg)

**Comment by kevincrepin** [comment]
I'm with @BeccaMelhuish on this. It is unexpected and unusual behaviour. I understand the idea, but it gets a bit lost. People are used to a certain pattern by now so it might make sense to stick to it.

Log in: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=180%3A21066
We have a link for people who aren't registered yet (and don't want to use the social/identification methods. 

And if the user writes an e-mail we don't know we can still give an alert/notification with a prompt to register a new account:
https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=180%3A22500

Register: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=180%3A21910

**Comment by loorm** [comment]
Triage 42. Ready for dev. Estimated dev time 3 hours. Prioritizing.
