### ISSUE TITLE
View password when entered incorrectly 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#726]
**What is the user story?**
Currently if I put my password in incorrectly there's no way to see what I entered, to see whether it's because I simply misspelled it, or because I've misremembered by password and should therefore try to think what else it could be. 
![image](https://user-images.githubusercontent.com/61320526/119819165-fca00380-bee7-11eb-85b6-e587448a94fa.png)

**Which feature needs to be updated and how?**
Usually there's a little eye you can click on to see what you entered. That would solve it if possible.

**Comment by BeccaMelhuish** [comment]
Or just a show password tickbox like Google has would also work, maybe better:

![image](https://user-images.githubusercontent.com/61320526/119819768-a3849f80-bee8-11eb-846a-fed0d7c03258.png)

**Comment by loorm** [comment]
Triage 38. @kevincrepin We prefer the eye icon approach. It's become fairly standard and should be understandable for all. Devs need a design for the eye icon, please. Estimated dev time 1,5 hours. Once we have the design, can go straigth to TODO.

**Comment by kevincrepin** [comment]
@ilmartyrk You can find how it would look like here: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=177%3A1
And get the actual icon also from here: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=85%3A71

**Comment by loorm** [comment]
Triage 41. Estimated dev time 3 hours. Prioritizing.
