### ISSUE TITLE
Possibility to vote for several agenda points under one topic

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#729]
**What is the user story?**
User wants to vote for several agenda points under one topic. This is a asked when the "master topic" contains two or more discussion points where the group should make a decision. Currently some users have solved this situation with using inline voting option, but here is the feedback: 
- inline voting is complicated to implement with large group of people as people who are not that advanced users, do not find inline voting feature and those who find it, have accidentally deleted either mini-voting, some parts of the body text or done other strange things;
- inline voting results are not being seen when topic is not in editing view;
- inline voting results are not downloadable or presentable in any (official) way and that is why it is not applicable in this use case.

**Which feature needs to be updated and how?**
It is probably bigger enhancement and requires investigation, but one of the solutions is to allow to choose more than one voting under each topic. User should have an opportunity to create each voting separately and they would be shown under each other. 
Questions to think about are: 
- How to separate different voting from each other so that the user who is invited to voting wouldn´t get confused;
- Should there be separate body text or explanatory text above each voting option and if yes, how to merge this with the body text so that it wouldn´t go too long?
- Should user still have both voting types available (regular and custom voting) or only one of them?
- How to provide voting results for the users so that it would be clear and understandable.

**Additional information.**
If to improve the inline voting feature so that the voting would be seen and voteable also in non-editing mode and voting results would be presentable, it could solve this user need.

**Comment by loorm** [comment]
Triage 39. Problem well understood. Solution runs counter to our product logic, where voting = confirming topic content and all details are inline-voted before then. Technically, the code is there to support multiple votes per topic. UX needed. But first, must approach this from product use logic POV. Moving to "In preparation". For Margo to think about this.

**Comment by loorm** [comment]
There's no easy way to make this work. However we approach this, it would require a big twist of our product logic. The logic is, that there's content in the topic about an issue, then there's a pro-con argument-based discussion, then the vote and then follow-up. Iff you put multiple issues up for vote, how do you know, which issue the argument support or oppose? 

On the other hand, you can prepare a whole "decision document" and then the voting is for the document as a whole. 

Also, if user has multiple issues, that need to be voted on separately, then rational decision-making logic says, they also need to be discussed separately. After all, that's the reason, why the law requires a separate vote for each of these issues. And if they need to be discussed separately, then it means opening a separate topic for each. These topics can be joined into a group and the group can be called "Organisation X" or alternatively "Organisation X - General Meeting 2022" to make things visually easier for the user. Like this:
<img width="1260" alt="mutiple_votes" src="https://user-images.githubusercontent.com/22661743/132556435-10f0e1c0-328a-40f3-9112-80ee35947b0b.png">




But I would not change the product logic. I propose to close this issue. However, with this I hand the issue over to you @anettlinno.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/54
