### ISSUE TITLE
ETHERPAD: Timeslider/timeline view - for some screen widths, "return to Pad" button is not visible

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#730]
**What is the problem?**

ETHERPAD: Timeslider/timeline view - for some screen widths, "return to Pad" button is not visible.

![timeline_return_to_pad_not_visible](https://user-images.githubusercontent.com/7405383/120310757-6735b280-c2df-11eb-9eb2-39a36fe7700a.PNG)

**Why is this a problem?**

User has no way to return to the Pad editing view from the timeslider/timeline view.

**Possible solution.**

Show the "return to Pad" for all screen widths.

![timeline_return_to_pad_visible](https://user-images.githubusercontent.com/7405383/120310933-964c2400-c2df-11eb-8e8f-b4a54e3c92a2.PNG)

**Comment by loorm** [comment]
Triage 39. Replicated. Est. dev time 1 hour. Either fix with style sheets on our end or create a pull to EP project. Prioritizing.
