### ISSUE TITLE
Visualized voting results

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#731]
**What is the user story?**
Users love beautifully designed summarizing voting results that they get after casting their votes. Topic admins want to download visualized voting results for sharing the summarized results with organization members; or get visualized voting results in .zip or BDOC file after the voting is ended. 

<img width="512" alt="voting results" src="https://user-images.githubusercontent.com/45175679/120315108-a6b2cd80-c2e4-11eb-9964-dde5b3b289dc.png">

**Which feature needs to be updated and how?**
Allow downloading summarized voting results or add these into .zip and BDOC container.

**Additional information.**
N/A

**Comment by loorm** [comment]
Triage 39. Let's create a PDF with the vizualized voting results and add it to the container. Do not include in the machine-readable container version. Estimated dev time 24 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
Added with https://github.com/citizenos/citizenos-api/commit/5098c5abddc7a0cb0a966744f655e7f8d288e202
