### ISSUE TITLE
Add delegated votes on paper to the vote delegation option

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#733]
**What is the user story?**
User gets 10 delegated votes via COS platform and 5 delegated votes on paper (paper credentials). Currently those users have to vote two times -- once online and once offline. Both voting types are needed because some people still prefer offline voting and topic initiator wants to allow vote delegation. Topic admins have to add paper credentials manually to the voting results.

**Which feature needs to be updated and how?**
Delegated votes on paper should be included into the current voting system. Maybe topic admins should have an opportunity to attach all the paper delegations to the topic and manually accept delegated votes on paper. Topic admin could then have an opportunity to delegate votes manually and these could be included into the voting results. 

**Additional information.**
There are many "back doors" for the bad guys in this solutions so it definitely needs brainstorming and further investigation.

**Comment by loorm** [comment]
Triage 39. This needs to be a part of a larger online-offline development package. Whether we will support hybrid votes, needs to be discussed. Moving to "In preparation"

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/57
