### ISSUE TITLE
Inline voting is out of the editing window

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#739]
**What is the problem?**
When clicking on the inline voting, the table is out of the topic´s content editing window.

<img width="939" alt="Inline voting" src="https://user-images.githubusercontent.com/45175679/121050832-95c0fb00-c7c1-11eb-903d-458f2a863788.png">

**Why is this a problem?**
It is not possible to read the inline-voting options and vote.

**Possible solution.**
Inline voting window should fit into the topic´s content window.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/ep_inline_voting/issues/5
