### ISSUE TITLE
Allow voting system creator to pick a specific time to end voting (currently, one date is used)

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#750]
**What is the user story?**
Lately, users have asked about the option to set a time for voting. It is essential in two user cases:

1. NGO board have to publish general meeting agenda points with relevant documents at least 2 weeks before the general meeting. They want to allow people to read the documents and discuss over the agenda points, but they want to set shorter time period for voting;
2. For quick decisions. User wants to give opportunity for the NGO members to participate in important decision and wants to limit the time because the decision has to be done quickly and those who cast their arguments or votes later, are not being considered.

**Which feature needs to be updated and how?**
![COS_Capture](https://user-images.githubusercontent.com/22661743/125404005-d0204800-e3be-11eb-9125-99034d9996d2.JPG)

**Additional information.**
Split from issue #667

**Comment by loorm** [comment]
Triage 41. @kevincrepin We need a design for this, please. We are in the process of implementing the other two voting system end conditions, too, based on vote count (see #316). **NB!**  Please also create an option for voting system creator to choose time zone (drop down list or smth).

**Comment by kevincrepin** [comment]
Had to redo this a bit so it all fits. I think maybe it can also be useful to have a switcher between 24 hour clock and AM/PM?
https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?page-id=2%3A16033&node-id=0%3A10702&viewport=-2500%2C2956%2C0.5&scaling=min-zoom

**Comment by loorm** [comment]
Default time = midnight, 24:00 o'clock. Default time zone = user's time zone.

**Comment by anettlinno** [comment]
Triage 43. Estimated time 2 days. Needs layout change. Prioritizing.

**Comment by ilmartyrk** [comment]
Added with https://github.com/citizenos/citizenos-fe/commit/ca827fb24ce338e29ad88efcd6bd0bd603ad0652

**Comment by loorm** [comment]
Tested. Passed.

**Comment by ilmartyrk** [comment]
Forgot to fix edit deadline under topic settings. Fixed with https://github.com/citizenos/citizenos-fe/commit/86d553f049431164d713dc84bd5dfd9f048af06d
