### ISSUE TITLE
UX suggestions re footnotes feature

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#760]
I just tried out the footnotes feature as am planning to make a marketing graphic about it, and have a few UX suggestions:

It took me quite a while to work out how to insert one, and only found it on my second scan of the toolbar (after trying right clicking too), as I was focusing more on the text formatting section on the left, and also the little * is a bit subtle.  

![image](https://user-images.githubusercontent.com/61320526/127741188-6d596caf-b520-4a78-b6b3-da03b49caa27.png)

My suggestion would be to add it to the right of the lists bit, where I put the red dot. Hard to know what symbol could be better than the asterisk on its own, but perhaps a little 1 as well like this: 

![image](https://user-images.githubusercontent.com/61320526/127741225-360ec96c-497d-4597-973e-925b041db8c4.png)

Or one of these "dagger" symbols next to the asterisk too:

![image](https://user-images.githubusercontent.com/61320526/127741252-3f3bdbeb-8fb0-43a1-b8e7-9da6579dc0d5.png)

Also, when in edit mode, the footnote gets added right onto the very bottom of the existing text in the topic, like this below, so I would suggest there should be a gap:

![image](https://user-images.githubusercontent.com/61320526/127741295-46e53cd5-02cc-4c1e-9923-c9bd2d56811a.png)

In "view" mode. it's OK as there is a little gap, though perhaps also a "Footnotes" heading, or a subtle line to split them off from the rest of the topic would be better, like you get when you add one in Word:

![image](https://user-images.githubusercontent.com/61320526/127741344-6cd9503f-264c-4b1d-bb97-4b6f983c3a57.png)

And last thing: when in both edit mode and view mode, the little number should ideally be a hyperlink, so that when you click on it, it takes you down to the footnotes section, again like users are used to from using Word etc. (It could also be blue to show it is clickable).

![image](https://user-images.githubusercontent.com/61320526/127741389-afaaf19b-4861-4ef6-b85b-55d8760a087a.png)

**Comment by anettlinno** [comment]
Triage 43. Successfully replicated. We would divide this issue into three. 1: We don´t change footnote´s place and symbol as button has explanatory tool tip when sliding over. 2.  Add row(s) between text and footnote text. We will decrease text size (style change). Estimate dev time is 6 hours. 3. Ilmar will investigate how much time hyperlinking the text would take. Investigation time 1 hour.

**Comment by ilmartyrk** [comment]
Checklist
- [X] Add extra line
- [X] Add different style to footer lines
- [x] Update export to support new styling
- [x] Investigate linking

**Comment by ilmartyrk** [comment]
Backward compatibility needs fixing

**Comment by loorm** [comment]
Tested. Passed except for the style change. @ilmartyrk there seems to be no change of style.

<img width="440" alt="footnote" src="https://user-images.githubusercontent.com/22661743/132530729-4e2cfa88-6fb2-4705-8889-7d733215a252.png">

**Comment by ilmartyrk** [comment]
@loorm etherpad probably has style in cache I updated FE styles too so the difference should be visible in there
