### ISSUE TITLE
UX problems with the "reply" feature

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#762]
**A few (rather serious in my opinion! (1) and (3) in particular) UX issues with the "replies" threads:**

(1) The little "Show replies (X)" button is quite easy to miss. This means that a lot of important contributions to a discussion could easily be overlooked by someone browsing through the discussion and only reading the initial argument. 
(2) The little "replies" arrow seems to be the wrong way up. I tried clicking on it to close the replies, as it by pointing upwards it gives the impression that's what it should do. 
(3) The big "(at)Margo Loor" (in this case) makes it look like he is the one adding the comments. When reading the discussion I thought that Margo had added two further comments underneath his initial argument (and wondered why he seemed to be contradicting something he'd said elsewhere!). It's only when taking this screenshot that I noticed the little "Anett Linno" and "Sara" which shows that it's them who posted the replies.   

![image](https://user-images.githubusercontent.com/61320526/128868876-f18d138d-d9a7-4da1-bc54-3f3a07e70b57.png)

(4) After clicking "Reply" there seems to be no way to get rid of the reply box if you change your mind. (No X close button and clicking off it doesn't do anything). 

![image](https://user-images.githubusercontent.com/61320526/128869970-713e4b35-7dd7-44fd-9693-8d72d8457d17.png)

**Suggested solutions:**

(1) and (2): I'd suggest we follow Facebook's lead with both these. So for the replies, adding the name of the first person who replied (plus total number of replies), making the text nice and big and bold, and putting it underneath the like / reply buttons. And for the little arrow, just turning it around:  

![image](https://user-images.githubusercontent.com/61320526/128871048-bee4f0d7-1a4a-4a9a-ae4f-a49fa6a989d6.png)

(3) Perhaps making the "(at)Margo Loor" smaller and on the same line as the comment. E.g. "(at)Margo Loor. This is one reason I think etc..."   

Again, like Facebook does: 
![image](https://user-images.githubusercontent.com/61320526/128874580-3a320345-9b34-4427-9ac9-5a2318a80ec9.png)

(4) Add a close button and make it so you can also close it by clicking off it. 

Maybe Kevin will have some good ideas for these problems too, but will leave it for the product manager(s) to tag him :)

**Comment by BeccaMelhuish** [comment]
Another option for issue (1) might be to show the name and the first few words (fading out) of each of the replies to each argument (perhaps only up to a certain number though, obviously it can't get too long). This would make it very hard to miss, and also give a bit more "weight"/visibility to the replies (which should be valued as much as the original argument I feel, but are currently very much deprioritised).

**Comment by BeccaMelhuish** [comment]
Also, a related idea. The headings over the discussion could give more of a full picture of the conversations that are taking place, so that when glancing at the discussion it is clearer how many people are participating and how much dialogue between them is taking place.

As well as making the replies more obvious (which would help with this), where it currently says "X arguments" it could also list the total number of contributions (any post, be it argument or reply) as the biggest heading, the broken down in number of arguments and number of replies, plus number of participants. These could be listed in smaller text under the main heading, where I have highlighted below. 

For example, in this Biotoopia discussion it looks at first glance like four people have posted one thing each, and that's it. To me this looks a discussion that isn't really taking off/going anywhere. Whereas, when you look at the replies, you see that 6 people have participated in total, and 9 replies to arguments have been made, making 13 contributions in total. Which is quite a different picture. I've often found the same when looking at other topics, at first it looks disappointingly like no-one is engaging, but then once you notice and click into the replies, you realise that there is more going on than it looks like there is.  

So, if using my suggestions above, in this example the headings would be:

**13 contributions**
4 arguments | 9 replies
6 participants

And another argument for this - knowing how many people have actively participated in the discussion and also how many contributions have been made and how many active participants (rather than just topic members) could be useful for admins too, to get an quick easy overview of how successful or not the discussion is/was, and how representative it is in terms of the number of topic members in total (i.e. active versus passive participants). Maybe they can get this from elsewhere, but this would make it very easy to find. (I know once I manually counted all the comments on the 34 islands project topics to be able to say how many contributions there had been in an article about it, which was a bit of a pain to have to do..)  

![image](https://user-images.githubusercontent.com/61320526/129937397-28e34a68-f146-470c-8a1a-0a11170229b7.png)

**Comment by BeccaMelhuish** [comment]
P.S. the breakdown of the number of pros and cons arguments would need to be included too I've just realised. But if you're happy with the idea in principle then I can work out how it would all fit - just let me know :)

**Comment by anettlinno** [comment]
Triage 44. Problem with the "reply" feature needs more evidence. User testing planned with @BeccaMelhuish.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/58
