### ISSUE TITLE
In-product pop-up messaging 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#764]
@kevincrepin @anettlinno @loorm @ilmartyrk would be great to discuss the following with you! 

@liinaguiter and I were today discussing plans for our user research / UX testing recruitment campaign today, and would like to have a pop-up designed and developed in the platform, asking people to sign up and linking to the Google form I've created. 

You often see such pop-ups in products/websites, like this one I came across on the UK HMRC website the other day. And according to my research its a very common practice and effective way of recruiting actual current users to do testing/research :)  (Kevin I think you've recommended this yourself in one of our meetings?)   

![image](https://user-images.githubusercontent.com/61320526/129944144-878da804-b0c2-4e23-8802-e026ff50b2af.png)

We also discussed that while the user research testing recruitment is the current need and priority for these pop-ups, there are often other messages that are important for us to be able to communicate with users, and which such pop-ups would be very useful for (if used minimally so as not to annoy the user). So if @kevincrepin were to design a pop-up for this purpose, it would be great if it was done so that it could be flexible to other uses as well. Or if a few different formats were designed for different types of message (different lengths, with or without image, etc.).   

And on a similar note (this is a side note from me, not discussed yet with @liinaguiter), is there any reason why we don't / can't in future email our users directly, as we have their email addresses from their accounts? It would make a lot of sense to also be able to send the occasional well-timed, relevant etc email to them, for example when an important feature has been updated, we want to communicate something important (like about data security), or in cases like this when we want to recruit users for testing/feedback. Obviously they should have a chance to choose not to receive these emails, but the more of our users we have a direct means of communication with the better I feel - as is quite common practice with apps/platforms/services.. But perhaps there are some reasons why it was decided we wouldn't ever email them? 

Would love to hear all your thoughts on these points and whether it might be something we could get set up quite quickly (the pop-ups at least, if not the emailing), so that we can use it in the aforementioned recruitment campaign :)

**Comment by loorm** [comment]
Users have different preferences. Most websites currently serve multiple pop-ups on first visit - cookie policy, notification acceptance and newsletter subscription. This is already too much for me. If further pop-ups were to appear, this would be annoying. 

In Citizen OS terms, maintaining this on development side, would be quite resource heavy. More at Triage.

**Comment by anettlinno** [comment]
Triage 44. Discussed and decided not to use pop-ups for recruiting / marketing.  These should be done via marketing channels. Closing issue.
