### ISSUE TITLE
Weird issue with etherpad-lite-heroku kexec

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#765]
kexec functionality is used to build and launch etherpad in heroku. After upgrading etherpad to 1.8.14 and using node 14.17.3 (as in FE and API too) the launch will crash if package.json and package-lock.json don't have different packages (accidental commit that happened to work). 

1) Find package of kexec that works consistently
2) Update/create own implementation that works

**Comment by anettlinno** [comment]
Triage 44. Needs further investigation. As long as it works, it is low priority. Timebox 1 day.

**Comment by ilmartyrk** [comment]
Fixed the issue! replaced the deprecated "kexec": "3.0.0" with "@jcoreio/kexec"

Found out some things:
1) Heroku seems to prefer package.json to package-lock.json - not sure why, but the real working package was declared in package.json
2) Heroku loads submodules only on push events so that etherpad-lite folder was not included when etherpad-test synced with github
