### ISSUE TITLE
Highlight replies in argument section

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#772]
Split from https://github.com/citizenos/citizenos-fe/issues/762

In argument section we currently only show the number of pro and con arguments, but there is no number of replies showed, this underplays the importance of replies. Together with the number of main arguments we need to show the number of replies too.  
![image](https://user-images.githubusercontent.com/61320526/129937397-28e34a68-f146-470c-8a1a-0a11170229b7.png)

**Comment by anettlinno** [comment]
Triage 44. Leave only "13 contributions" from the example and find better copy for translation. @seppviljar. Estimated dev. time 15 min.

**Comment by loorm** [comment]
Becca proposed this:

13 contributions
4 arguments | 9 replies
6 participants

I propose this:

Contributions: 13 pro: 4 con: 0 replies: 9

**Comment by KatiVellak** [comment]
Important improvement, but technical one. No legal impact.

**Comment by anettlinno** [comment]
Triage 48. We will go with what Margo provided and leave the "Contribution: 13" font as "Arguments" font is in current version. Est. dev. time 1 hour. Sending to development.
