### ISSUE TITLE
Topics sorting

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#777]
I'm sure this will have been discussed before, but just in case! Would it be possible to make it so that you can choose how you filter topics? As currently it always shows up with all the "in voting" first (other than my starred ones), which are often very old and no longer active ones, and the ones I want to access are way down the list. I'd love to be able "Sort by" then Most Recent. Or preferably for it to show up like this as default, as I feel this must be the most useful for everyone - the most likely topics they want to access are the ones they most recently have? And then to have other ways of filtering (e.g. A-Z, stage of process, etc.) as secondary options. 

![image](https://user-images.githubusercontent.com/61320526/133414362-1b4295a2-4097-40f3-a16e-183d2c0adf30.png)

**Comment by loorm** [comment]
@BeccaMelhuish Try using the dropdown ("Show all my topics" in the attached pic).

**Comment by BeccaMelhuish** [comment]
Interesting! Thanks for pointing that out,

I guess I didn't click it because "Show all my topics" isn't an action that I wanted to take (as they were already all showing). Whereas if it said something like "Filter: all topics" and with the filter icon we're used to seeing next to it, that might be more intuitive :) (@kevincrepin may have better suggestions!)

Again though, if defaulting to being in order of the topics most recently active for the user (as in the ones they have taken any action in most recently, including having simply accepted the invite)) is technically possible then I feel it would be the most useful thing for users. Underneath any starred ones of course. Then they are very likely to be taken directly to what they were looking for, rather than having to take any action to search for it - trying to remember the name to search for, or trying to work out which of the filters is relevant, or just scrolling lots.

**Comment by loorm** [comment]
> Again though, if defaulting to being in order of the topics most recently active for the user (as in the ones they have taken any action in most recently, including having simply accepted the invite)) is technically possible then I feel it would be the most useful thing for users. Underneath any starred ones of course. Then they are very likely to be taken directly to what they were looking for, rather than having to take any action to search for it - trying to remember the name to search for, or trying to work out which of the filters is relevant, or just scrolling lots.

This is certainly a use case. Let's consider another. I have participated in a number of topics (if I have participated in only a few, the sorting and filtering issue is mute) and one of them comes up for voting. However, it has been some time since I personally was active in it. If topics where I have been active are sorted to the top by default, I might miss the vote. The current sorting order was not random. The thinking was, that for topics where I am constantly active, I pin them. These go to the very top. After that, come the ones in voting, so I will not miss any votes. Then come the ones that are in progress etc.

**Comment by anettlinno** [comment]
Triage 56. This is important topic and needs further discussion. Additionally it is part of our bigger redesign project. Sending this issue pack to In Preparation phase for finding good ideas how to solve this issue.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/61
