### ISSUE TITLE
Overview menu item overlaps other menu items in mobile view - /my/topics/:topicId

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#779]
**What is the problem?**
![image](https://user-images.githubusercontent.com/7405383/133438427-980cb080-92f9-4bb4-8dc1-d9339720815a.png)

**Why is this a problem?**

* Actions not properly usable due to the overlap.
* Visually not appealing.

**Possible solution.**

No overlap.

**Comment by loorm** [comment]
Replicated on my Android device, too.

**Comment by anettlinno** [comment]
Triage 46. Successfully replicated. Approx. dev. time 1h. Sending to development.

**Comment by KatiVellak** [comment]
Legally reviewed, technical issue, no impact legally.

**Comment by loorm** [comment]
@anettlinno Please test this. On my tablet screen, everything looks nice now. On my phone screen, it still overlaps. BUT my phone is very old, so it may not matter. Please test on newer phones.

**Comment by ilmartyrk** [comment]
@loorm @anettlinno there might be some cache issues, if you still see Overview text on your mobile it could be that the old style is still in browser cache. Can you please check incognito view?

**Comment by anettlinno** [comment]
@loorm @ilmartyrk I tested it and it works fine on my phone :)

**Comment by loorm** [comment]
> @loorm @anettlinno there might be some cache issues, if you still see Overview text on your mobile it could be that the old style is still in browser cache. Can you please check incognito view?

Issue persists on my phone in Incognito mode, too. See photo. But again, most people are on newer phones with newer Android and Chrome versions, so this doesn't really matter.

+ load time was **excrutiatingly** slow. Again, might be my phone issue.
![overlap issue](https://user-images.githubusercontent.com/22661743/136853007-b9624a8c-f08c-44ff-bb87-f5f510dca69c.jpg)

**Comment by anettlinno** [comment]
I tried to replicate this on narrow screen in Chrome and found that there are two mobile break points -- 338 pixels and 354 pixels. In 338 "Menu" text disappears and in 354 icons overlap. Maybe it´s helpful @ilmartyrk @loorm 

338 pixels where Menu disappears: 
<img width="308" alt="Narrow1" src="https://user-images.githubusercontent.com/45175679/137085749-06a44c83-c094-44ac-b5f6-3d0c2dc33c08.png">

And 354 where icons overlap:
<img width="348" alt="Narrow2" src="https://user-images.githubusercontent.com/45175679/137085972-e2abec87-c13a-498b-bfeb-7a1d1fbbdca0.png">
