### ISSUE TITLE
Inline comments - inconsistent behavior between read-only and edit mode

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#780]
**What is the problem?**

* Some inline comments exist in edit mode that do not exist in read-only mode.
* Some inline comments exist in read-only mode, that do not exist in edit-mode.
* In read-only mode, cannot view some comments that are marked as being available inline.

![image](https://user-images.githubusercontent.com/7405383/133454732-2ee05402-c5f4-411f-b926-5915595fa803.png)
![image (1)](https://user-images.githubusercontent.com/7405383/133454741-94101833-1c9a-4ba9-b781-e883aa8721e3.png)

**Why is this a problem?**

* Up-to-date info not available.
* Confusing user experience.

**Possible solution.**

* Same comments available in read-only and edit modes.
* All comments that are highlighted can be interacted.

**Comment by ilmartyrk** [comment]
Related to this issue, found that some comments get exported with data values "comment-deleted" so probably the proper solution would be not to export delete comments. Also made bad solution loading comments inside directive - this triggers API call for each inline-comment in topic

**Comment by ilmartyrk** [comment]
Created a partial fix on FE-side that removes deleted-comments. Etherpad plugin still needs check and fix 
Issue 
1. Delete comment button doesn't give any feedback.
2. Deleted comments should not get exported to html

**Comment by KatiVellak** [comment]
Technical issue, no legal impact.

**Comment by anettlinno** [comment]
Triage 48. Est. dev time 2 days. Sending to development.

**Comment by ilmartyrk** [comment]
Delete comment button fixed, didn't remote deleted comment export from plugin as it was too much effort. Filtering on API side works
