### ISSUE TITLE
BUG: Etherpad - topic member list out of position

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#783]
**What is the problem?**
![image](https://user-images.githubusercontent.com/7405383/133665014-3f8db910-2722-4275-abe9-8f8d371957f9.png)

**Why is this a problem?**

* When scrolled down, feels like the Topic member list does nothing.
* Looks broken.

**Possible solution.**

* The member list to open right above the icon.
* No gray background stretching on the screen.

**Comment by anettlinno** [comment]
Triage 48. Successfully replicated. Est. fix time 30 min. Sending to development.

**Comment by KatiVellak** [comment]
No legal impact, technical issue.

**Comment by tiblu** [comment]
## Release 08.03.2022 - ep_auth_citizenos@1.0.7

![image](https://user-images.githubusercontent.com/7405383/157233630-a0416f80-f61a-4141-86ed-8925f4fb2ade.png)

* Changes - https://github.com/citizenos/ep_auth_citizenos/commit/3e741690b35ab606f4394febcf9d16faedcd95fb

**Comment by anettlinno** [comment]
Tested. @tiblu if I remember correctly then topic members list should include all people who have edited the topic, right? 
I tested with Monthly meeting topic where we have 6 collaborators, but topic members list only shows one User.

Topic authors: 
<img width="323" alt="authors" src="https://user-images.githubusercontent.com/45175679/157670316-070c977a-9488-43df-bb97-61ffefd6ad4a.png">

Same topic in timeslider view: 
<img width="931" alt="Issue 783" src="https://user-images.githubusercontent.com/45175679/157669883-98046e5c-f53e-4e32-908f-10f207319e8e.png">

Same topic in topic members list view: 
<img width="695" alt="Issue 783_2" src="https://user-images.githubusercontent.com/45175679/157670058-bd18a7f4-36f5-4ac0-800f-46a56c1de58f.png">

**Comment by tiblu** [comment]
@anettlinno  

On the top bar, it MUST show all members who have collaborated on this Topic at any given time in history.
The lower pop-up shows ONLY people currently collaborating on the Topic that is - all people who have this Topic open in the edit mode.
