### ISSUE TITLE
BUG: Topic opens in editing mode by link share

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#784]
**What is the problem?**
When clicking on the topic link (link share) then topic opens by default in editing mode.  
<img width="929" alt="Editing" src="https://user-images.githubusercontent.com/45175679/133968029-f2f258b4-15bc-43e4-bd42-9123c6af1091.png">

**Why is this a problem?**
Topic should open in reading mode when clicking on the link as editing should be intentional activity. People might accidentally change the text. 

**Possible solution.**
Change topic from editing mode to reading mode when clicking on the link.

**Comment by loorm** [comment]
Just a quick comment, that this was an intentional design choice, because people were sometimes not finding the "Edit topic" button. So we made "Edit" the default mode. Your call, on how it should be from now on.

**Comment by anettlinno** [comment]
Thanks @loorm for the explanation. I think if people do not find the "Edit topic" button then we have serious UX problem :) 

In this situation where user gets invite via email to join the topic then I personally think that topic should be in reading mode, because user might accidentally change the topic.

**Comment by anettlinno** [comment]
Triage 48. It only happens when user copies topic URL in edit mode. As this is very specific user case, we close the issue without further action. Closing issue.
