### ISSUE TITLE
Error message is not helping to understand what went wrong after changing accounts

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#785]
**What is the problem?**
I opened topic in one window and was logged in with my COS account. Then I clicked on the topic invitation link which was sent to my Gmail account and I had to log in with other account. When I went back to the COS account topic, I continued writing the argument and when I wanted to post it, I received error message "You don´t have permission to complete the action". 

<img width="655" alt="Bug_1" src="https://user-images.githubusercontent.com/45175679/133969741-2f2db360-7e35-4748-92c4-24dce2db4dd4.png">

After refreshing the topic I received another error message "You haven´t go sufficient permission to access the resource".

<img width="948" alt="Bug_2" src="https://user-images.githubusercontent.com/45175679/133969898-1b4c1621-d36b-4819-8f41-19766ddf245c.png">

**Why is this a problem?**
If user wants to continue with the topic that was opened before she changed accounts and gets these error messages then she don´t understand that the problem appears because of changing the accounts. AND when user clicks on the link again (link share) then she will get the error message that "You don´t have permission" again but nowhere comes out the she is logged in with another account. 

**Possible solution.**
A clear and concise description of what you expected to happen (when applicable).

- Log out from all other windows after changing the account;
- When clicking on the link share link again then user should get notification that she is logged in with another account. Under the error message could be guide about what went wrong (e.g. "You don´t have permission to access the resource, here is what might went wrong: you are logged in with different account than the one you have permission to access this resource; etc). If this is only reason why user gets this error message then this could be the error message itself: "You are logged in with another account and you don´t have a permission to access the resource"

**Comment by anettlinno** [comment]
Triage 49. We will create web socket system and our system automatically log user out from every tab after user changes accounts. Adding error notification message "You are logged out". 

Log me out from all my devices option needs a little investigation (how server solves the issue that you have session in different devices). investigation time 2 hours.

Est. dev. time 5 days. Sending to development.

**Comment by KatiVellak** [comment]
Technical issue, no legal comment.

**Comment by ilmartyrk** [comment]
@anettlinno  Did some research about websocket and how to implement. At the time it seems too much effort and risk of breaking things to implement this just for authentication check purposes. I'll instead implement auth status check in our front end side with userId check. When this detects that the userId inside authentication data has changed it will automatically redirect to home page.

**Comment by anettlinno** [comment]
As talked to @ilmartyrk yesterday in Slack, that if user logs in with different account then all the open pages will be redirected on the platform´s landing page. System will let user know that she is now logged in with different account in all windows. 
Text could be something like "You are now logged in with anett@..... account" @oksks please do your magic here and propose better text that is also translatable :)

**Comment by ilmartyrk** [comment]
Discussed with @oksks. decided to use `"Page redirected due to account switch"`
