### ISSUE TITLE
Single user invitation to the topic or group: unclear error message

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#786]
**What is the problem?**
I was adding new User into a group who already existed in the group (single email entry). This bounced me back to the group´s General Information page and I received an error message on the red bar: _"No invites were created. Possibly because no valid userId-s (uuidv4s or emails) were provided"_ I don´t understand the error message and it doesn´t help me to understand what I did wrong.

![User ID](https://user-images.githubusercontent.com/45175679/135072667-3735be1c-4cfb-45ed-ba9d-a94756836766.png)

**Why is this a problem?**
Error message could explain me where I went wrong and say for example: "Invite was not sent to the user because this User is already a group member". "UserID-s" and "uuidv4s" and other similar words is not relevant information for a User to show. 

**Possible solution.**
Please change the error message on the red line.

**Comment by anettlinno** [comment]
Triage 48. We are not able to replicate this issue at the Triage meeting. Investigating the issue for 30 min. If still cannot replicate the issue, will go through the error message texts and make them human readable. Approx. error message review time 1 hour.

**Comment by KatiVellak** [comment]
Technical issue, no legal impact.

**Comment by ilmartyrk** [comment]
Replication:
Invite user(s) to topic and then repeat inviting the same user(s)
