### ISSUE TITLE
Changing the name of an attachment 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-old#789]
**What is the user story?**
The user would like to upload images and videos that provide guidance about the topic. The file names could be long and difficult (for example Screenshot 2021-09-29 at 3.50.10 PM) and the user needs to be able to change the attachment name before the topic is published.

![Screenshot 2021-09-29 at 4 45 56 PM](https://user-images.githubusercontent.com/72747107/135260089-c988fe22-df64-40a6-9c2e-86de4be4cea8.png)

However the button for confirming the updated text is not very intuitive. The button must be clicked to confirm the change.

![Screenshot 2021-09-29 at 4 46 15 PM](https://user-images.githubusercontent.com/72747107/135259961-0f1f6d08-f2b6-40f9-9beb-1a7bd6eed8be.png)

If the button is not clicked, the user sees the original attachment name and it seems as though there is no possibility to change the attachment name

![Screenshot 2021-09-29 at 4 46 23 PM](https://user-images.githubusercontent.com/72747107/135259907-a7753ea6-c2d3-412f-9607-241b9d6a71d0.png)

**Which feature needs to be updated and how?**
The attachment feature could include an attach or confirm button to avoid misleading the user into believing that attachment names cannot be changed. 

**Additional information.**

**Comment by anettlinno** [comment]
Triage 48. Successfully replicated. Change the "pen" icon to confirm icon (we should have the design) and add confirm by pressing enter. Est. dev. time 30 min. Sending to development.

**Comment by KatiVellak** [comment]
technical issue, no legal impact.

**Comment by tiblu** [comment]
## DONE!

![Attachment_edit_gh_789](https://user-images.githubusercontent.com/7405383/141483338-0c19a22f-10ef-4dd7-bf6e-3991f21469e2.PNG)

Implementation notes:

* Pressing ENTER now saves attachment name.
* Pressing confirm icon also saves the attachment.
* Added new confirm icon as there was none for this design.
* To cancel an edit, press ESC, this closes the modal and rejects all pending changes.
* Increased the width of the attachment name edit input to 100%

**Comment by anettlinno** [comment]
Tested and works beautifully!
