### ISSUE TITLE
"My Topics" view does not have scroll bars when content does not fit the screen

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#792]
**What is the problem?**

"My Topics" view does not have scroll bars when content does not fit the screen

![image](https://user-images.githubusercontent.com/7405383/135475811-7f620c84-8bc7-42af-aede-45ad150a3e49.png)

**Why is this a problem?**

A user MAY miss some content that is outside the scrollable content.

**Possible solution.**

Add scroll bars.

**Related to:**

* https://github.com/citizenos/citizenos-fe/issues/108

**Comment by anettlinno** [comment]
Triage 48. Could not replicate, we need more information. @tiblu what browser were you using?

**Comment by KatiVellak** [comment]
No legal impact, technical issue.

**Comment by anettlinno** [comment]
Friendly reminder to @tiblu that we couldn´t replicate the issue and need more info :)

**Comment by tiblu** [comment]
@anettlinno  Thanks for the friendly reminder!
Cannot replicate this any more. Closing.
