### ISSUE TITLE
Alter argument loading

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#796]
Current pagination solution only displays x amount of arguments, but to make arguments more visible we should add load more button and load arguments into same view.

**Comment by KatiVellak** [comment]
Good improvment, no legal impact.

**Comment by anettlinno** [comment]
Triage 49. Adding "Load more" button. Est. dev time 3 hours. Sending to development.

**Comment by tiblu** [comment]
### TODO

- [ ] Load arguments on scroll
- [ ] Make sure direct linking remains working

**Comment by tiblu** [comment]
@ilmartyrk @kevincrepin @anettlinno
I feel like the idea of loading more arguments on scrolling down on the page cannot be applied here as the last element of the UI is the "add argument" form.

If you try to scroll to the bottom to add an argument, more arguments would be loaded pushing the form to the bottom.
This ends up un an UX where you cannot add an argument before you have actually loaded all existing arguments.

My proposal - keep the pagination.
IF we want the scroll based argument loading, we MUST redesign the UI/UX.

**Comment by kevincrepin** [comment]
@tiblu I think what @ilmartyrk meant was to have a button "load more" which would trigger the loading in the place of where the pagination is now. It wouldn't happen automatically and so it wouldn't push the input away continuously either.

**Comment by ilmartyrk** [comment]
@kevincrepin @tiblu @anettlinno, we actually had a private discussion with Mikk about this feature. And my thought was to maybe use load more on scrolling, just like we do in our activity feed, as it would be more user friendly. But now getting the feedback. I do see the issues for adding the scroll solution. @tiblu I  still believe we should drop pagination as this was the initial idea for this issue, so that users could see all arguments on one page. It would make following the discussion a lot easier.

Issue with the load more button is that we didn't have any ideas or designs to use on where and how to add it. It should be quite visible for the user.

**Comment by anettlinno** [comment]
I agree with @ilmartyrk that if User chooses to press on "Load more" button after she has reached to the end of 10 arguments, she also sees the "Add argument" form. If she chooses to load more arguments (there could be said "Load 10 more arguments") then I think it´s OK, because there is also "Add argument" button on the right top of the Argumentary section.

If I remember correctly @kevincrepin, then this issue was solved in better way in our redesign project (add argument is always seen and clickable on the screen, even when scrolling up and down).

**Comment by ilmartyrk** [comment]
move to https://github.com/citizenos/citizenos-fe/issues/44
