### ISSUE TITLE
Topic search is not working

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#801]
**What is the problem?**
System gives error message when entering text in the search bar AND search is not working.

<img width="943" alt="Error_search" src="https://user-images.githubusercontent.com/45175679/136805529-7bfc75d4-8f50-4478-8edc-8867214ba0e1.png">

**Why is this a problem?**
Cannot use search bar

**Possible solution.**
Please fix the problem :)

**Comment by tiblu** [comment]
### Debugging

API call: `GET /api/search?include=my.topic&include=my.group&include=public.topic&limit=5&str=test`

**Comment by loorm** [comment]
Yup, broken. Bug replicated.

**Comment by tiblu** [comment]
**FIXED**

Caused by changes to the search code and missing test to perform an authenticated search.

Added test to replicate the issue and avoid same happening in the future.
