### ISSUE TITLE
Activity feed: share link stats incorrect

### ISSUE THREAD

**Issue by seppviljar** [citizenos/citizenos-fe-old#805]
Check the screenshot - shows 4 edits made to one topic (**Testtopic 2**)

In reality, **Testtopic 2** was created 20:17 and changed once
Other 3 changes belong to an older topic (**Uus pealkiri**)

Env: Test

<img width="776" alt="Screenshot 2021-10-14 at 20 19 04" src="https://user-images.githubusercontent.com/66470228/137450803-801b94fd-08be-4027-8324-effc43c67895.png">

**Comment by KatiVellak** [comment]
No legal impact, technical issue.

**Comment by anettlinno** [comment]
Triage 48. Investigating this issue, as it might only occur in test environment. Investigation time 1 hour.

**Comment by ilmartyrk** [comment]
Found the issue. It is because of how activity grouping is working. How to replicate:
Create topic 1, create topic 2 update 
Update topic 1 token join 2 times, Update topic 2 token join
Check activity feed, they are grouped under topic 1 updates
