### ISSUE TITLE
Grammar point - should be "create group" not "create groups" 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#821]
I noticed that the menu says "create topic" (singular) under Topics, but then "create groups" (plural) under Group. It should be singular for both I think (so changed to "create group"), as the action they are taking (and the pop-up that appears) is to create a single group, not to create more than one: 

![image](https://user-images.githubusercontent.com/61320526/138254987-049af557-91ef-413a-b120-b57328795a48.png)

**Comment by seppviljar** [comment]
Done, most languages translated accordingly
