### ISSUE TITLE
User vs participant

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#828]
Yeah, the good old "user" - in Skype we tried to avoid it too, where it made sense.

My few cents:

  *   I'm all in for changing it where it actually denotes a... well...  a participant - like discussion, voting etc
  *   I'd maybe keep "user" where the connection is vague or generic, a la activity feed "User Sepp created profile"
     *   ie small differences where you are platofrm user vs discussion participant
  *   There are approx 170 strings mentioning "user", 2/3 from Activity feed, roughly - so not exactly cheap to change everything
  *   The length is mostly fine - https://translated-into.com/participant 🙂

_Originally posted by @seppviljar in https://github.com/citizenos/citizenos-fe/issues/239#issuecomment-950925733_

**Comment by anettlinno** [comment]
User vs participate issue is separated from issue #239. 

@seppviljar it´s a good idea to keep the word "user" where we refer to people as "platform users". How much work do you think it would be to make the research about where we should keep "user" and where we should change it to "participant" + translations? Could you tell the approx. time please?

**Comment by seppviljar** [comment]
Probably an hour or two to extract copy that should/could be changed. 
Getting the copy actually changed adds more time since I'd like to get them before Becca's eyes and searh'n'replace is not a good options here

**Comment by anettlinno** [comment]
I´m thinking that let´s do the user/participant review with the UX/UI redesign as this seems to be the most logical time for that. 
@kevincrepin could you please consider this into the redesign project.

Closing this issue with the remark that user/participant will be reviewed in the UX/UI redesign.
