### ISSUE TITLE
FE: Topic AND Group invite QR code UX changes - save as PDF

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#832]
**What is the user story?**

![image](https://user-images.githubusercontent.com/7405383/139439795-9446e204-9782-4bf5-a1f0-09ff432fd8a3.png)

 One of the user cases is when people want to initiate topic in COS and invite people to the discussion by printing it on the poster (and putting the poster on the University wall for example). The other user case is when people are having public demonstration and want to print the topic on the poster. In these cases user needs only the QR code that is printable.
(src: https://github.com/citizenos/citizenos-fe/issues/311#issuecomment-944043275)

**Which feature needs to be updated and how?**

@kevincrepin  made a small change so that we don't show the QR code in the popup anymore and we have some explanation of how the QR code can be used. Then a generate QR code link will open it up in a separate page from which people can use the print as pdf functionality from the browser.

https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=744%3A25203

(SRC: https://github.com/citizenos/citizenos-fe/issues/311#issuecomment-949411815)

**TODO:**

- [ ] Implement UX as seen on the visuals - https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=744%3A25203

**Additional information.**

Depends on:

* https://github.com/citizenos/citizenos-fe/issues/311
* https://github.com/citizenos/citizenos-fe/issues/325

**Comment by anettlinno** [comment]
Triage 59. Let´s implement the QR code feature as proposed above -- replacing the QR icon with explanatory text and leave it to the "Share" tab as where it currently is. 
Approx. dev time 1 hours. Sending to development.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/72
