### ISSUE TITLE
Something is wrong with Acitivty Feed

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#856]
**What is the problem?**
Activity Feed shows variable names instead of values. Seems to be a double entry - the first one (circled in red) has variable names, the second one seems to be the same, but with values.

<img width="678" alt="activ_feed_problem" src="https://user-images.githubusercontent.com/22661743/141748184-53815c33-0639-403c-a5e1-c35e6f38a631.png">

**Why is this a problem?**
Useless and confusing for the user.

**Possible solution.**
N/A

**Comment by loorm** [comment]
@ilmartyrk Something else is now wrong with Activity feed, I think. It's supposed to load more entries as I scroll to the bottom, isn't it? Well, it's not doing that for me. All I get is the 20 or so pre-loaded entries.

**Comment by ilmartyrk** [comment]
@loorm could not replicate, but it could be some height related thing, that prevents the load action from triggering when u have X amount of issues on first page that fill the feed to Y height

**Comment by loorm** [comment]
@ilmartyrk Confirmed, it's a height related thing. It doesn't load additional entries on my laptop screen, but if I move the same Chrome window to an attached larger screen, then it loads. Considering, though, that my laptop is a native FullHD screen, which I guess is still the standard, I can't be alone in this issue.

**Comment by ilmartyrk** [comment]
I checked that currently by default we load 10 activities in one query and standard view displays ~9 - 10 activities depending on height, easiest solution is to increase the result count to 15 to be sure that the scrollbar will get displayed.

**Comment by anettlinno** [comment]
Triage 53. Apprx. dev. time 15 min.  Sending to development
