### ISSUE TITLE
Pictures are not opening in older topics

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#858]
**What is the problem?**
Pictures in existing (older) topics do not open (both on editing and viewing mode). User can only see the picture icon inside the text. 
User is unable to insert pictures to older topics. When clicking on the Picture icon, then nothing happens.

<img width="660" alt="1112" src="https://user-images.githubusercontent.com/45175679/141984763-4b1b3911-884b-4691-8336-8db840c03d0f.png">

**Why is this a problem?**
Participants do not see the pictures and important part of the discussion is missing. 

**Possible solution.**
Platform should show the pictures inside the text.

**Comment by ilmartyrk** [comment]
After updating ep_image_upload plugin, links to older images got broken, will need to create a migration that will fix the URLs in database in both API and etherpad.

**Comment by anettlinno** [comment]
Triage 53. Est. dev. time 1 day. Sending to development.

**Comment by ilmartyrk** [comment]
Decided to update the plugin to support older formats of images stored in etherpad. Reason is that updating database values is quite risky. https://github.com/citizenos/ep_image_upload/commit/0540987c66e54a623aafd59e60076b978f383adf

**Comment by ilmartyrk** [comment]
Found 3 topics that had broken images in our API DB. As I had access to all of theme (Were our team topics), I fixed them and now images are displayed correctly
