### ISSUE TITLE
Lodash not a dependency, yet used

### ISSUE THREAD

**Issue by moll** [citizenos/citizenos-fe-old#87]
`index.js` requires Lodash, yet it is not a dependency in `package.json`. Running `node index.js` therefore crashes immediately with `Error: Cannot find module 'lodash'`.

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-fe/commit/aac57c8c446aa3f037179f8b5de678927a75103b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
