### ISSUE TITLE
BUG: Topic vote creation - custom vote - no error displayed when trying to create a vote with 0 options

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#873]
**What is the problem?**

No error displayed when trying to create a vote with 0 options.

![image](https://user-images.githubusercontent.com/7405383/143444310-ec18629e-e0d0-41ac-8109-afad7ca3b536.png)

NOTES:

* API does return the correct error.

**Why is this a problem?**

Bad UX.

**Possible solution.**

Show field or generar error on vote options.

**Comment by anettlinno** [comment]
Triage 53. Successfully replicated. We have the API error message but currently it´s not displayed  to user. Need to check if we have the translations and if yes, then the text will be displayed. 
Est. dev. time 30 minutes. 
Sending to development.

**Comment by tiblu** [comment]
**DONE**

* Showing general error on top of the screen.
* Added context to Crowdin.

![image](https://user-images.githubusercontent.com/7405383/145570867-61db545c-b1b5-4cc1-914f-8e3e2453cdb5.png)

**Comment by anettlinno** [comment]
Tested. Works nicely!
