### ISSUE TITLE
Make it clearer that link sharing rights apply also to social media and QR sharing 

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#876]
**What is the user story?**
It´s not easily understandable for admin users that link sharing rights also apply to social media and QR sharing. Current design is confusing.
<img width="345" alt="11Linksharing" src="https://user-images.githubusercontent.com/45175679/144596970-90786a3d-a325-4a4a-a9b9-ec6aa7681d75.png">

**Which feature needs to be updated and how?**
@kevincrepin please propose design where it is clear and understandable that admin user can change social media and QR code sharing rights from the same place where she can change link sharing rights. 

**Additional information.**
Thought: We could add on the text field (or somewhere else) that if admin user regenerates link then it applies also to social media and QR sharings and once the new link is regenerated, all the old link(s) expire.

**Comment by anettlinno** [comment]
Triage 54. No need for new design. Suggestion to change the wording: "Share this link via social media" and "Share this link via QR code". @seppviljar please make the changes in texts. 
Sending to TO DO.

**Comment by ilmartyrk** [comment]
@oksks I've updated the source strings, you can check the changes from the commit reference above
