### ISSUE TITLE
Adding files to arguments & follow-up 

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#880]
**What is the user story?**
As a user, I would like to add files to visualize my follow-up messages and arguments. Currently there is no opportunity to add graphics or pictures into the discussion part, but in some cases it is really relevant to visualize your argument with infographics or pictures. 

**Which feature needs to be updated and how?**
Text description is not always that accurate as is infographic or picture. In Follow-up phase it would be great to add voting results and any further action (like how the community house building is going) in more visualized matter. In arguments, it´s sometimes needed to show same graphics, figures and numbers in table as a picture or infographic. 

**Additional information.**
N/A

**Comment by anettlinno** [comment]
Triage 59. Technically possible but we should think through how many pictures we allow to add, in what side. @kevincrepin have you thought about this solution in UX/UI redesign project?
Sending it to In prep for further ideation.

**Comment by loorm** [comment]
I would suggest one pic per message is fine. And just pics, no other files. Other files can always be linked. But visuals can be helpful in a discussion, I agree.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/45
