### ISSUE TITLE
Self branding - make it easy to add basic branding for self hosted instances

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#89]
**The need**
When I deploy a CitizenOS instance for my own organization, I would like to have possibility to have my own branding so that Users feel more at home as well as can distinct between different CitizenOS's they may be using

**Scope**

* Logos in the header in all views (desktop, mobile...)
* E-mails (just a reminder here, work needs to be done in https://github.com/citizenos/citizenos-api)

**Comment by ilmartyrk** [comment]
I believe I can close this as 
https://github.com/citizenos/citizenos-fe/commit/a184d9ff17467c43c523cd25894fa82166c9142e fixes the logo and style changes and https://github.com/citizenos/citizenos-api/commit/854f0425b440b05f7a00e504fccc3ecec217dc37 and https://github.com/citizenos/citizenos-api/commit/f186b3e2ca497118c8c6de7e49e1f872c3f765ae fix e-mails
