### ISSUE TITLE
Collecting donations

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#898]
**What is the user story?**
Some Users would like to (micro) donate money to support Citizen OS free open source platform development and maintenance. 
They want to find out about this opportunity from our web site and platform and make micro donations only with few clicks. 

**What is the requested feature?**
Let´s add donation information to our platform so that it would be: 
a) located somewhere where users can see and read the information but that is not annoying (actively jumping pop-up windows in every possible place)
b) Easy to donate -- user has to do only few clicks to donate
c) Many choices for donating money (via bank link (national and international transfers), credit card donation, paypal etc)
d) Understandable for user, where her donation goes. @loorm shared Wikipedia´s example which I think is really sweet and humble: https://donate.wikimedia.org/w/index.php?title=Special:LandingPage&country=EE&uselang=en&utm_medium=spontaneous&utm_source=fr-redir&utm_campaign=spontaneous 
c) @tiblu shared GitHub´s sponsorship (beta) opportunity that could also be included in our "donations" page.

@kevincrepin would you please help us to figure out, where in our platform donation information could be located and what information is needed for that. Thanks! Tagging also @ilmartyrk here.

**Additional information.**
Our bookkeeper researched donation information from her side a little bit and she said that it is our responsibility to know the source of donations (to avoid money laundry etc cases). She said that with micro donations it is not a problem, but if someone wants to donate 100 000 euros, this could become a problem :) Additionally, for organization there are certain regulations for income tax relief and we should then send the information about donators to Estonian Tax and Custom board. @kativellak would need your legal advise here :)

**Comment by kevincrepin** [comment]
I see two places, one more obvious than the other.

- The less obvious is in the sidemenu above "About" and this needs a small switch in icons: donate would get the heart and about would get a citizenos icon.
- The more obvious is to use some space of the search – which probably doesn't need that entire width anyway: on the top right we dedicate some space for a donate message.

https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?page-id=1034%3A25417&node-id=2256%3A38401&viewport=241%2C48%2C0.5&scaling=min-zoom 

The question is where the user gets redirected to. If it's only one place then I think it makes more sense on the website so that people can also donate from there and don't need to go through the platform.

**Comment by anettlinno** [comment]
Thanks @kevincrepin for the designs. 

IMHO "Donate" button near the search bar is better for the eye. "Want to contribute" is not quite right in this context as we use it for engaging volunteer contributors (for GitHub and translators community mainly). Maybe something like: "Help us to keep the platform for free" and "Donate". 

It could direct user to the website as recommended and would need the design for the "Donations" page as well. 
This page could be structured in following way: 

- Humble words about asking donations (why to help?). 
- Where your donation goes. 
- Predefined sums of donations. 2, 5, 10, 20, 50, 100
- Account number (with explanatory text), paypal information and GitHub donations (beta) platform.
There is also option to do it via bank links, but there are transfer fees (I think 4-5% of the amount on the average). Service providers, like Maksekeskus, are even more expensive, they take 2,5% of the amount + 0,3 EUR from each transaction. 
- Do we have any other information we need to add there resulting from the tax regulations, @kativellak? If you look at the Wikipedia´s example they have also brought out Tax deductibility information.

**Comment by KatiVellak** [comment]
We need to first decide whether to apply for https://www.emta.ee/ariklient/registreerimine-ettevotlus/tulumaksusoodustusega-uhingule/nimekirja-taotlemine . After that we know how and wht information to provide.

**Comment by anettlinno** [comment]
@kevincrepin would like to request design for the "Donations" webpage. 
Here is the content: https://app.citizenos.com/en/topics/c63e9b72-fda0-4688-8923-06b774b538c3

**Comment by kevincrepin** [comment]
Started design here: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=816%3A3177&viewport=363%2C48%2C0.5&scaling=min-zoom

Will add tax regulation info when it's defined. 

We also still need a place on the website that leads here. Link in the footer or the menu?

**Comment by anettlinno** [comment]
Thanks @kevincrepin! Design that was proposed has a lot of empty space (incl. pictures) and would actually prefer very simple design where User gets all the information from one place (no need to scroll down to get there). Maybe could do something similar as Wikipedia has: https://donate.wikimedia.org/w/index.php?title=Special:LandingPage&country=EE&uselang=en&utm_medium=spontaneous&utm_source=fr-redir&utm_campaign=spontaneous

**Comment by anettlinno** [comment]
> We also still need a place on the website that leads here. Link in the footer or the menu?

Yes, I´m thinking that in the Footer menu under the **Support** would be the most logical place for that

**Comment by anettlinno** [comment]
@tiblu made quick design for "Donations" page to the same layout -- this is quite nice too. What do you think @kevincrepin :) Could we do something similar? 

![citizenos_donations_sample](https://user-images.githubusercontent.com/45175679/151396345-9d57f60f-217e-497c-8615-4d132610d172.png)

**Comment by kevincrepin** [comment]
Sure, looks good, more concise!
https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=835%3A3128&viewport=368%2C48%2C0.25&scaling=min-zoom

**Comment by anettlinno** [comment]
PS! I have updated "COS Donations" topic with PayPal button code, link and QR file.

**Comment by oksks** [comment]
As agreed with @anettlinno, I've also asked Argo (can't tag him here but sent him the link to this issue) to add a floating "Donate" button to the frontpage as well, similar to one on https://www.toetusfond.ee/ - centered, and should be in one of our main colours, but not the same colour, as other buttons...COS yellow maybe, WDYT @kevincrepin? It should be prominent and very visible. 

Button would lead to the donate page, which would also be accessible from the footer ("Donate" link under Support).

![Screenshot 2022-02-21 at 11 27 48](https://user-images.githubusercontent.com/34126353/154947759-f63979cb-1c45-44f8-9571-13074d247873.png)

Offtopic: let's please add all future website requests to [the web project.](https://github.com/citizenos/citizenos-web)

**Comment by oksks** [comment]
Update: 
1. Agreed with Argo to have a webpage done by Tuesday, March 1
2. myself and @anettlinno to make sure everything looks as intended by Thursday, March 3
3. Argo to activate the Donate floating button and add a link to the page in the footer under Support category on March 4.

**Comment by oksks** [comment]
@anettlinno, page is delivered by Argo - https://citizenos.com/donate. I've asked to:
- replace the QR code with the real one (will be able to do it myself hopefully from next week)
- and to make sure the top button leads to the bottom section

May I please have a correct link for IOF?

PS. Waiting for the floating Donate button design from @kevincrepin, for it to be pushed live on Friday, along with the link in the footer.

**Comment by anettlinno** [comment]
> 
> May I please have a correct link for IOF?
> 
Here is the official IOF site: https://www.indorelawan.org/p/indonesiaopinionfestival @oksks

**Comment by kevincrepin** [comment]
If we go for a floating button then the bottom right corner is a logical place, especially because it's not occupied by the help centre on the website itself: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=967%3A4372&viewport=295%2C48%2C0.5&scaling=min-zoom

However, we do have the room in the main menu so why not...?
https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=967%3A4382&viewport=295%2C48%2C0.5&scaling=min-zoom

**Comment by anettlinno** [comment]
> If we go for a floating button then the bottom right corner is a logical place, especially because it's not occupied by the help centre on the website itself: https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=967%3A4372&viewport=295%2C48%2C0.5&scaling=min-zoom
> 
> However, we do have the room in the main menu so why not...? https://www.figma.com/proto/eHBSunqUv10fMcWmiEEXiv/Website?page-id=0%3A2160&node-id=967%3A4382&viewport=295%2C48%2C0.5&scaling=min-zoom

I personally even like it more in the main menu :)

**Comment by oksks** [comment]
Oh, looks awesome! I also like it in the main menu.

Maybe combine the two? Button in the main menu, and the floating button to appear in the bottom right corner, when you've scrolled away and the main menu is no longer visible.

**Comment by anettlinno** [comment]
IMHO as our main menu is static, then Donate button on the right top corner is just enough :) 

Please let´s keep the platform button on top right (change "Donate" button and "Use platform" button places in current design). Thanks!

**Comment by oksks** [comment]
https://citizenos.com/ done, tested. 
Thanks all! :)

**Comment by anettlinno** [comment]
Triage 61. Adding "Donate" button on the top of the page, next to search button BUT changing the button pink -- same color as on the web. @kevincrepin is this OK for you? :))
Est. dev. time 1 hour. Sending to development if Kevin says OK :)

**Comment by ilmartyrk** [comment]
Also @kevincrepin @anettlinno  how should it look like in mobile, currently I've hidden it away? Pushing initial version into live, we can finetune it on the go

**Comment by anettlinno** [comment]
@ilmartyrk @kevincrepin Do you think we could color "Donate" button to pink as it is on the webpage? Blue disappears into the platform colors. 

Heart is not symmetrical :( Is the font the same everywhere? It looks like typing machine style... 

![Donate](https://user-images.githubusercontent.com/45175679/159278613-7ef1e1fd-93aa-4fe8-9ca0-3c11732553e5.png)

**Comment by kevincrepin** [comment]
I made couple updates so it connects better to the webpage and also stands out of the platform more @ilmartyrk : https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?page-id=1034%3A25417&node-id=2256%3A38401&viewport=283%2C48%2C1&scaling=min-zoom

**Comment by anettlinno** [comment]
> I made couple updates so it connects better to the webpage and also stands out of the platform more @ilmartyrk : https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?page-id=1034%3A25417&node-id=2256%3A38401&viewport=283%2C48%2C1&scaling=min-zoom

Love it!
