### ISSUE TITLE
Product updates on the platform

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#900]
**What is the user story?**
As a user I would like to know what are the latest updates and improvements in Citizen OS platform, so I could get the most out of the platform. Users who have not used the platform for a long time might want to know what has been changed to keep themselves updated.   

**What is the requested feature?**
Latest updates should be on our platform somewhere where users could easily find it but that wouldn't be annoying for them. User who would like to get the latest updates should have an opportunity to make this decision by clicking on the "Latest updates" button. 
It would also be nice to know about upcoming updates (without time frame) so that users would know that the platform is being constantly developed and also, what to expect.  
@kevincrepin this is probably part of UX/UI redesign project, right?

**Additional information.**
As discussed with @liinaguiter and @BeccaMelhuish then latest updates will be also posted on our website and every once in a while we will do the (demo) videos about latest updates.

**Comment by anettlinno** [comment]
Triage 59. This is part of redesign project @kevincrepin, right? :)

**Comment by kevincrepin** [comment]
Yes, most definitely!

**Comment by loorm** [comment]
A long time ago, we thought the technical twitter account would be for this. So when a feature is released, we tweet about it and the tweet history becomes the release log. But, honestly, when was the last time any of you checked any SaaS product's feature release log? I think this user need is more of a hypothetical. I may be wrong, though...

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/46
