### ISSUE TITLE
Disable and update send button in invite views under topic and group views

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#916]
When user wants to invite new members to topic or group the invite modal has Blue  "Save topic" button, this is a left behind from previous view where we had multiple settings under one view. This button should now only have text "Send invites" and this button should be disabled if no users have been added to the invite list.

**Comment by anettlinno** [comment]
Triage 59. Let´s implement it as recommended above. IF there is no email added, the button is disabled. And please change the butoon text to "Send invites".
Approx. dev time 30 minutes. Sending to development.

**Comment by anettlinno** [comment]
Tested. Looks much better now BUT when clicking on the Share window then it shows "Send invites" button in the bottom right corner. I think it shouln´t be there @ilmartyrk?
<img width="577" alt="Send invites" src="https://user-images.githubusercontent.com/45175679/154518185-c39ff2e8-2abf-4d3f-ac13-ac134f77b8f4.png">

**Comment by anettlinno** [comment]
Tested. Now looks right. Thank you!
