### ISSUE TITLE
citizenos / citizenos-fe description update regarding new languages

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#923]
**Update Features list**
- Translated in 16 languages

**Update flags**
Add the latest language flag, Czech!

**Comment by seppviljar** [comment]
- web / funtiona has been updated
- do we have it somewhere else?
- do we have flags there, not recommended :)

**Comment by anettlinno** [comment]
Triage 61. Adding Czech flag: https://github.com/citizenos/citizenos-api
Est. time 15 minutes. Sending to To Do.
