### ISSUE TITLE
MOBILE (touch devices): Add "question" as a third category into the debate 

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#929]
**What is the user story?**

On touch devices you cannot read the descriptions of a statement type dropdown.
 
As touch devices have no "hover" and the UX of the https://github.com/citizenos/citizenos-fe/issues/329 UX relied on it, the touch device UX is not perfect.

At the time of implementing https://github.com/citizenos/citizenos-fe/issues/329 there was no touch device specific UX.

**Which feature needs to be updated and how?**

Implement UX as per design - https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?node-id=1034%3A25417

![image](https://user-images.githubusercontent.com/7405383/150786669-3bd2d73e-f82f-4bc7-8ae8-17aa3c2249f5.png)

NOTE: It's a "2-tab" design - you choose statement type, then the description is shown where the "select" button appears which actually selects the type.

**Comment by anettlinno** [comment]
Triage 59. It works when holding your finger on the chosen argument type but this is not intuitive and well known. Let´s do what Kevin proposed in Figma design. 
Approx. dev time 4 hours. Sending to development.

**Comment by anettlinno** [comment]
Works nicely in mobile view now. Found one translation thingy, @oksks :) 

![273866467_3003931943201651_802378139046416780_n](https://user-images.githubusercontent.com/45175679/154519474-b56da2c5-8e92-4e84-81a9-20c14fb23e02.jpg)

**Comment by ilmartyrk** [comment]
@anettlinno @oks this is mobile thing, outside of our system, we cannot change that
