### ISSUE TITLE
My Topics view is empty for a new User

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#933]
**What is the user story?**

When new User visits "My Topics", the page is empty:

![image](https://user-images.githubusercontent.com/7405383/151662963-0d4f5898-c4b8-4622-a81d-810c8f420625.png)

**Which feature needs to be updated and how?**

Don't show an empty page. Show information that a User can work with.
For example "Create a Topic" action or smth.

**Comment by anettlinno** [comment]
Triage 60. We decided not to change the current view in My topics, as the dashboard view is going to change with the redesign project anyway, right @kevincrepin? :)
Closing the topic.
