### ISSUE TITLE
Dashboard / My Topics - when scrolling to the end of all Topic activities a "Not found" error is displayed

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#934]
**What is the problem?**

Dashboard / My Topics - when scrolling to the end of all Topic activities a "Not found" error is displayed as no more results are to be loaded.

![image](https://user-images.githubusercontent.com/7405383/151705126-815e7b7e-29c5-4fa2-aa47-adc7bde33d1d.png)

**Why is this a problem?**

While actually nothing breaks, the error is misleading to the User.

**Possible solution.**

- [ ] Do not show an error when no more results is to be loaded.

**Related to:**

* Discovered while working with https://github.com/citizenos/citizenos-fe/issues/796

**Comment by anettlinno** [comment]
Triage 59. Approx. fix time 30 min. Sending to development.

**Comment by anettlinno** [comment]
Tested. Works nicely.
