### ISSUE TITLE
Add link behind keyword(s)

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#937]
**What is the user story?**
As a User I would like to keep my topic clean and neat because pasting long external links inside the topic makes it look messy and long. I would like to add external documents, websites, other COS topic etc link behind keywords that are marked with different color (usually dark blue). 

**What is the requested feature?**
I see two options how to solve this:
1. I would like to add the link by double-clicking on the keyword(s) and click on the "Add link" icon on menu bar. That will open the pop-up window where I could insert the link and change the keyword(s). 
2. OR I would like to add the link by double-clicking on the keyword(s), after what will open the window where currently I can insert comment or to create voting. By choosing "Add link", pop-up window will open and I can insert the link and change the keyword(s).
I want that linked keywords would be recognizable inside the text (different color is probably the best and most intuitive solution).
I also want to be able to remove links same way as I entered them. 

**Additional information.**
N/A

**Comment by anettlinno** [comment]
Triage 60. Duplicate issue #110. Closing the issue.

**Comment by BeccaMelhuish** [comment]
Neither are big problems, but for smoothness: I would suggest that "Remove" is greyed out when there is no link yet entered, and that the black comment/mini-vote box disappears once the user has clicked on the links button 

![image](https://user-images.githubusercontent.com/61320526/162579592-44625d8a-4858-46c0-9ea1-5b08ccec21cd.png)

**Comment by BeccaMelhuish** [comment]
For the removing link part, a smoother way might be to have a little delete "dustbin" icon that appears to the right of the URL when there is an URL entered into it. Instead of the "Remove link" button.

**Comment by anettlinno** [comment]
Sending it to back to Triage meeting

**Comment by BeccaMelhuish** [comment]
Might also be worth adding "Add hyperlink" as an option in the black box too, as this is the first thing people will see when they highlight the text, so where they would presumably initially expect to find it

**Comment by anettlinno** [comment]
Triage 64. Adding "add link" option in the black box. We´ll keep the "Remove" text button as it would take a lot of time to change it to dustbin but will change red color to grey. 
Est. dev. time 30 minutes.

**Comment by BeccaMelhuish** [comment]
@anettlinno @ilmartyrk I also noticed recently that when in edit mode, it's not possible to visit a link by clicking on it. As if you click on it then it assumes you want to edit it. So if you want to actually visit the link then you have to copy it, open a new tab and paste it in. Has happened to me a few times recently, and could be a cause of user frustration..

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @anettlinno I thought I had also added here that the links open in the same tab (so you lose access to the topic), but should instead open in a new tab. But I don't see it in the thread anymore so am adding it here now :) (It just happened to me again and is quite confusing/annoying..)

**Comment by anettlinno** [comment]
> @anettlinno @ilmartyrk I also noticed recently that when in edit mode, it's not possible to visit a link by clicking on it. As if you click on it then it assumes you want to edit it. So if you want to actually visit the link then you have to copy it, open a new tab and paste it in. Has happened to me a few times recently, and could be a cause of user frustration..

Good point! I think we could add third row as "Open the link" and then "hard" link where User can click. I agree that link should open in new window. 
@ilmartyrk I see that "Add link" in black box is already in test environment, but it doesn´t work yet :) Let´s please add these additions that Becca brought out. Thanks a million! (:

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/67
