### ISSUE TITLE
BUG: deleted users do not get access to the topic via email link after re-insertion

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#938]
**What is the problem?**
I invited myself to a topic and as I didn´t receive an invite, I went to check the "Manage participants" to see if the system has sent invitation out. My email was not in invited list and I entered my email address once again. Now, when I refreshed the page, I had two pending invites that were sent to the same email address. I deleted one and received this error message. 

<img width="951" alt="Delete user" src="https://user-images.githubusercontent.com/45175679/152130233-bfffe324-468a-4774-9fb3-4f9776205c76.png">

When finally invites received (after 5-7 minutes) on my email, I clicked on the link and received error message "Sorry, the invite to a topic has been deleted". 
<img width="944" alt="Error1" src="https://user-images.githubusercontent.com/45175679/152130516-15d459d2-b778-4ff2-a660-84077ce14700.png">

And clicking on the second invite link, I received another error message: 
<img width="940" alt="Error2" src="https://user-images.githubusercontent.com/45175679/152130731-b865c8d5-a7a0-4316-8af3-f7a048a70e73.png">

**Why is this a problem?**
The problem is that I cannot access to the topic via email link. 
AND I cannot add once deleted and re-inserted user into the group, where this topic is (I only added myself to the topic first and then wanted to add to group, but failed). I get following error message:
<img width="954" alt="Group error" src="https://user-images.githubusercontent.com/45175679/152131636-ca0a1427-ce66-4303-921c-4d71e2712372.png">

I have access to the topic when I go through "Activity feed" or "My topics" and I see my "pending" invite in "Manage participants" list (from the admin-user account), but I don´t have an access through invite email.

**Possible solution.**
User should have an access to the topic after her account is removed and later added into the topic (the last one sent by the system). Also admin-user should have an opportunity to add the same user into the group where this topic is.
Best solution would be to fix it (:

**Comment by tiblu** [comment]
I think there are 2 different issues:

* ```No invites were created. Possibly because no valid userId-s (uuidv4s or emails) were provided. *``` appears when:
    *  you try to invite a person who is already member of the Topic. Not sure what the right message should be? OR just say "OK" as if an invite was sent?
    * when no valid userId-s or email addresses are posted to API. From Citizen OS App it SHOULD NEVER HAPPEN. 
* ![image](https://user-images.githubusercontent.com/7405383/152140852-a620a0ad-9d7c-4641-8491-332f03683b00.png) I ASSUME this is related to this bug - https://github.com/citizenos/citizenos-api/issues/231

**Comment by anettlinno** [comment]
Triage 60. Needs replication to see where it goes wrong. Est. investigation time 1 hour. Sending to To Do.

**Comment by ilmartyrk** [comment]
I couldn't replicate the issue, but I found that when you invite user with read permissions and then send a new invite with admin permissions and then before user accepts invites you delete invite from under manage users. Then 1 invite is deleted, but the other remains and will be shown under manage users invites

**Comment by anettlinno** [comment]
I went the whole flow through again (sent an reading rights invite which I didn´t open, then sent admin rights invite, which I didn´t open and then as an Admin User I deleted invitation from the "Manage participants list") but this time there was only one pending invite (as it should be). When deleted pending invitation this is what I saw:

<img width="367" alt="Pending invite" src="https://user-images.githubusercontent.com/45175679/174553523-596e84e9-d2b3-40c9-976c-9ecbd7408506.png">

@ilmartyrk any idea where it goes wrong?

As a User who received two invitations and clicking on the links (both of them), I received an error message which said that invite to the topic has been deleted. So this is all good with that. 
Also I could invite the same email address that I previously deleted. So this part works nicely too. 

@ssin1901 could you test the flow as well please :)

**Comment by ssin1901** [comment]
@anettlinno @ilmartyrk the issue is prevalent across different devices (mobile and IPad) and different browsers (Chrome and Safari) and operating systems (iOS and Android). 

![Screenshot 2022-06-21 at 11 01 53](https://user-images.githubusercontent.com/72747107/174813165-f2757b11-e392-4100-8054-5d143b05cc92.png)

I was able to invite myself as a participant (using the same email) multiple times.

However, the issue disappears if the browser cache is flushed. At that point, the user is notified that they cannot create duplicate invitations, and duplicate invitations also disappear from the dashboard.

**Comment by anettlinno** [comment]
Triage 69. We need to change the behavior from the API side so that User can invite one participant (email) many times, but our system would handle all invites as one. From the participant´s side (User who receives the invitation), all invitations should be valid then. If Admin User will delete any email address from the users list, then all invitation links should be invalid and deleted user should not have access to the topic or group.  

Email error text needs further investigation. 

Approximate development and investigation time is 6 hours and sending it to development.

**Comment by ssin1901** [comment]
At the moment, you CAN invite the same user multiple times and the system treats it as one invitation so you don't see error messages [refer to screenshot]

<img width="1379" alt="Screenshot 2022-11-27 at 17 55 28" src="https://user-images.githubusercontent.com/72747107/204144691-a22b00f2-ec09-4dc7-bb8f-c8da94c91b2f.png">

HOWEVER, if you invite user x 3 times, then user x gets 3 separate invitations which is annoying! I am actually going to create a separate issue about this.

**Comment by ilmartyrk** [comment]
@ssin1901  thank you for noticing,  probably would be correct to send invite once and if new invite changes permissions only update them in database without sending a new invite

**Comment by anettlinno** [comment]
Triage 75. There is a bug in Manage Participants view (live version) where there is no "Delete" icon for removing participants: 

<img width="333" alt="Managae participants" src="https://user-images.githubusercontent.com/45175679/204478543-922020fb-b88c-49f3-b544-3c42e3d325c2.png">

We don´t change the current notification emails flow and leave it as it is (Users will receive an invitation email every time their email address is being inserted in topic or group).

Approximate fixing time 1 hour.

**Comment by ilmartyrk** [comment]
fixed the manage users bug

**Comment by ssin1901** [comment]
Just to confirm after testing that the overall user flow – you can invite participants multiple times and each invite will come as a separate email. @BeccaMelhuish @anettlinno @ilmartyrk 

Now testing 

a) what happens when a user tries to use the second, third of fourth email
b) what happens when user leaves the topic and tries to access the topic via an old email

**Comment by ssin1901** [comment]
User flow worked as expected! 
<img width="1306" alt="Screenshot 2023-01-24 at 11 02 45" src="https://user-images.githubusercontent.com/72747107/214250863-5fed2f3a-47f0-45e8-9338-8a41be30a8ea.png">

**Comment by ssin1901** [comment]
@ilmartyrk tested and all working now.
