### ISSUE TITLE
Do not show "connect your EID" modal for all users as this is Estonian specific

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#940]
**What is the user story?**

Every new user sees the "connect your EID" modal that is relevant only for Estonian citizen.

![image](https://user-images.githubusercontent.com/7405383/152336913-b5cb6ffe-ee01-48d9-b06e-fc3ac3cbf06d.png)

**Which feature needs to be updated and how?**

Do not show the modal. I propose checking the language list provided by the browser, IF that contains "ET" in any form, show the modal. IF not, do not show.

**Comment by anettlinno** [comment]
Triage 60. Important fix for non-Estonian Users. Est. dev. time 15. Sending to To Do.

**Comment by loorm** [comment]
For non-Estonian users, we should show "Get an EID" with a link to https://www.e-resident.gov.ee/become-an-e-resident/

**Comment by anettlinno** [comment]
> For non-Estonian users, we should show "Get an EID" with a link to https://www.e-resident.gov.ee/become-an-e-resident/

Good idea! :)) That would be really awesome! @ilmartyrk can we do that? :)

**Comment by tiblu** [comment]
I'm not sure about that. The UX for new users includes too many popups 
Indonesia with biggest user-base, it would be just confusing for them, I don't see how they would benefit from EID.
