### ISSUE TITLE
Emphasize the tutorial and explanation topic on main page

### ISSUE THREAD

**Issue by leonych** [citizenos/citizenos-fe-old#953]
**What is the user story?**
When I opened Citizen OS platform for the first time and arrived on the main page, I was confused with all the squares with same size but different colors and had no idea what to do at that moment. I didn't realize there's a tutorial and explanation topic at the first glace since it looked blend in with other topics.
![Capture1](https://user-images.githubusercontent.com/94454138/153858422-624e4130-1f09-4a8b-af2f-6c0f21e002ff.JPG)

**Which feature needs to be updated and how?**
Give different treatment (visually) on the tutorial and explanation topic so it can emphasize the topic that is important as an on boarding, especially for new users. Could be different size, shape, or placement.

**Comment by anettlinno** [comment]
Triage 61. With UX/UI redesign project the visuals will change and this problem will be solved. Closing this issue.
