### ISSUE TITLE
Topics in voting stage are missing "Log in to see options/vote" pop-up

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#954]
**What is the problem?**
When I open a topic, which is in a voting (multiple choice) phase, I don't see the multiple choice options, and am not notified, that only logged-in users see them and can interact with the topic. I also can't switch between "View" and "Vote" tabs

![Screenshot 2022-02-22 at 10 30 59](https://user-images.githubusercontent.com/34126353/155092951-41b6bd9c-a37b-496a-9ae9-bdec21cfff52.png)

**Why is this a problem?**
It looks like something is broken - user should probably see all proposed multiple choice options, but they should be partially hidden behind a pop-up saying something like "Voting is only for logged-in users. Sign up or log in", to motivate them to create an account or log in.

([Topic](https://app.citizenos.com/en/topics/fd66ecc5-8244-459c-9946-1955c7535a6c/votes/7f8c6207-c9b9-4cb1-bb3a-f83e7e3f4791?argumentsPage=1) in question)

**Comment by anettlinno** [comment]
Triage 61. Bug is successfully replicated. For eID votings participant can see the voting options: https://app.citizenos.com/en/topics/51f42747-4555-4f4e-9b63-7976f542ba49/votes/c1397a5f-1411-4b29-a996-e898141952bc?argumentsPage=1 
But for social voting participant cannot see voting options: https://app.citizenos.com/en/topics/2e447db4-399b-4913-b978-2b85278ae094/votes/0bf78a7f-4910-4897-a7a9-47722f5ac213?argumentsPage=1

Needs investigation and fixing. Est. investigation time 30 minutes. Sending to To Do.

**Comment by ilmartyrk** [comment]
Took suggestion from @oksks added overlay with "You have to login to participate" so it would be more clear for users that they cant vote without logging in

**Comment by anettlinno** [comment]
Thanks @ilmartyrk! I tested again and social voting and ID voting are still different. This applied only to social voting :) 
Please let´s add the same pop-up to the ID voting as well.

Social voting: 

<img width="934" alt="Social login" src="https://user-images.githubusercontent.com/45175679/157657628-80d5cc1d-111b-41a0-87f1-3ada9f5ee45c.png">

ID voting: 

<img width="937" alt="ID login" src="https://user-images.githubusercontent.com/45175679/157657952-318bae34-9af6-42d1-bbb3-bc9870f31c87.png">

**Comment by ilmartyrk** [comment]
@anettlinno Id card voting works without logging in, thats why they are different
