### ISSUE TITLE
Excessive tab separator + wrong tab colour

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#955]
**What is the problem?**
When I switch between "View" and "Vote" tabs in a [topic](https://app.citizenos.com/en/topics/fd66ecc5-8244-459c-9946-1955c7535a6c/votes/7f8c6207-c9b9-4cb1-bb3a-f83e7e3f4791?argumentsPage=1), which is in a voting stage, the active tab should lose a stripe underneath, to visually join it with the content the user is seeing, and normally the tab and content should become the same colour, too.
Currently, the "View" tab keeps the bottom separator stripe and stays a different colour from content background, which confuses the user as to which tab is active.

![Screenshot 2022-02-22 at 10 38 13](https://user-images.githubusercontent.com/34126353/155094783-82b2db49-8a93-4d08-b5b7-66fe2ce6627c.png)

**Why is this a problem?**
Users are accustomed to a certain tab behaviour. This flaw makes it hard to understand, which tab is active, especially if the topic content isn't changing between them (as in the link above).

**Possible solution.**
Remove the separator stripe from the active tab and make sure colour scheme is consistent.

**Comment by ilmartyrk** [comment]
Triage 61. This is expected behaviour as we redirect all topics in voting to always show voting view. Tabs work correctly when in follow-up.
