### ISSUE TITLE
Activity Feed message is missing an active topic URL

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#956]
**What is the problem?**
All topic names in **bold** should be clickable in all instances in Activity Feed, but this one isn't for some reason:

![Screenshot 2022-02-22 at 10 53 11](https://user-images.githubusercontent.com/34126353/155096766-65f99922-5d47-41b2-b34b-d472a804570c.png)

Please make it clickable :)

**Comment by anettlinno** [comment]
Triage 61. Bug that needs to be fixed. Est. fix time 30 minutes. Sending to development.

**Comment by anettlinno** [comment]
Tested. Works nicely.
