### ISSUE TITLE
Add video inside the topic

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#957]
**What is the user story?**
Sometimes, one short video can say more than long text and visualize the topic or problem the best.
As a user I would like to add video content to the topic field to visualize, explain or emphasize the importance of the topic. Or just show what is the situation in the real-world.

**What is the requested feature?**
Allow adding video content to the topic field.
Currently we can add video as attachment, but it gets lost and is not visually seen.

**Additional information.**
The size of the video should be limited to keep the page and content downloadable. Additionally I think we should also limit about how many videos per topic we allow to upload -- I think one per topic is reasonable. @ilmartyrk @tiblu what do you think?
Does different video sharing sites have sharing restrictions for "third" platforms @kati? 
If we are going to allow sharing video content, we probably take responsibility of the content moderation as well? If video is abusive or any other way harming, people should have an opportunity to report about it.

**Comment by anettlinno** [comment]
Triage 61. @kevincrepin, could we please consider this video adding functionality in our UX/UI redesign? 
Sending this issue to In Prep to decide how to add it into new version.

**Comment by kevincrepin** [comment]
I would definitely consider limiting to video embeds (youtube, vimeo,..) and not allowing users to upload locally. Compression to reduce video size and moderation come to mind as main challenges otherwise.

**Comment by anettlinno** [comment]
> I would definitely consider limiting to video embeds (youtube, vimeo,..) and not allowing users to upload locally. Compression to reduce video size and moderation come to mind as main challenges otherwise.

I was thinking that in our new design there is a separate field for header picture, do you think we could also have separate (optional) field for the video? Agree that video embedding should be via links as you said and not allowing upload locally.

**Comment by loorm** [comment]
"Agree that video embedding should be via links as you said and not allowing upload locally." +1

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/62
