### ISSUE TITLE
Formatted text in invitation email appears in one row

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#961]
**What is the problem?**
When writing customized and formatted text in invitation email, it will appear in one row. 

![274997203_698643944850301_7187080322655433386_n](https://user-images.githubusercontent.com/45175679/156355193-771e5cbc-f556-4d45-ae45-1ea0a1c50d4e.png)

**Why is this a problem?**
As a User, I´m thinking that my text appears in the same format as I entered it. If we allow formatting text in the "Invite users" text box, it should appear the same formatted way as User entered it. 

**Possible solution.**
- IF the text is being shown in one row in invitation email (as above), we should not allow formatting text in the "Invite users" text box 
- OR if we allow formatting then the same format should be displayed in the email.

**Comment by anettlinno** [comment]
Triage 61. We should support formatting the text. Est. Dev. time 2 hours. Sending to development.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/70
