### ISSUE TITLE
Can't view all topics in a group + sorting doesn't sort

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#962]
**What is the problem?**
I was trying to find our "Monthly Meetings 2022" topic. I opened our team group in the app and tried to find topic there, but as soon as I try to click open the "all topics view", I'm being displayed only 10 our of 89 topics (both in the group information and in the expanded topic view), and I don't know how to view all the rest.

Sorting also doesn't work - if I click on "Order group topics by: - Activity (latest)", which supposedly should surface the Monthly Meeting topic, I'm being shown ancient topics from 2018.

Please see the screencast to illustrate the above: https://drive.google.com/file/d/1cWYhBlupz4fkmtOOijnoexco5jCyEn0L/view?usp=sharing

**Why is this a problem?**
I'm unable to find the topic I need :(

**Comment by loorm** [comment]
<img width="950" alt="Capture" src="https://user-images.githubusercontent.com/22661743/157019852-6a1f007e-7c42-4bb2-a490-589d663c4e7e.PNG">

**Comment by anettlinno** [comment]
Triage 61. Agreed to loose "+" from the left side of the group list. Replacing Users list and Topic list on the right side, under the General information. AND when User clicks on the group name, topic list is open by default. 

Before we start developing this, we would like to test it with real users. @kevincrepin, we would like to have prototype in Figma to test it. We will test it with 2-3 Users and then make improvements according to the feedback. After that we are ready to develop this enhancement. 

Sending issue back to In Prep until we have prototype from DUX.

**Comment by anettlinno** [comment]
Triage 76. Groups dashboard will change with the redesign project and it is time consuming task in current Angular version. 
Closing the topic with no further action.
