### ISSUE TITLE
Login button inactive, when arriving at a pre-filled login window

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#987]
**What is the problem?**
I've clicked the topic [invite link](https://app.citizenos.com/topics/join/vLHRVfhAA50Y), which was shared by Anett in Slack. Upon arriving at the topic page, I got a login pop-up, which had my details pre-filled, but login button was inactive. It only becomes active, when I click on it once.

<img width="616" alt="Screenshot 2022-03-30 at 10 27 47" src="https://user-images.githubusercontent.com/34126353/160775979-8953f133-9f01-494f-b8ef-35ba8441d54f.png">

**Why is this a problem?**
It confuses the user, as to why can't they log in, while correct details are already in the form.

**Possible solution.**
When browser prefills user's login details, our platform should recognize details have been filled, and make the button active. Or maybe the pop-up is not in focus immediately, when moving from another platform.

**Comment by anettlinno** [comment]
Triage 65. Last wee one of our users had the same issue. We could not replicate it but will investigate the issue. 
Est. investigation time 30 min. Sending to TO DO.

**Comment by ilmartyrk** [comment]
@oksks Can you please add what browser and OS were you using when this thing happened. I tested on different browsers in Windows 10 (Chrome, Opera, Firefox, Edge). I could replicate this only in edge, button stayed inactive, but after clicking on input or the log in button. There might be some solutions to get this fixed https://stackoverflow.com/questions/14965968/angularjs-browser-autofill-workaround-by-using-a-directive

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/73
