### ISSUE TITLE
Changing language does not change language everywhere

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#991]
**What is the problem?**
I changed the language from English to Estonian. Some buttons in edit window changed accordingly, others did not (see screenshot).
<img width="939" alt="language_bug" src="https://user-images.githubusercontent.com/22661743/161795412-d78a3d4d-0ddb-4232-8d63-04014cbbd02d.png">

**Why is this a problem?**
A user may not be able to use the app properly, if it is not in desired language.

**Possible solution.**
Translate all buttons in edit window according to choice of language.

**Comment by ilmartyrk** [comment]
Triage 65. The issue comes from ep_translations plugin and loading translations from github. With updates to other code one library has stopped working and needs to be replaced or updated, Est dev time 6h
