### ISSUE TITLE
Problems with "suggested text" in comment feature

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#997]
My suggested (test) text was "target test" but it came out like this below. And it doesn't seem to be possible to delete or edit the suggested text once you have added it? 

![image](https://user-images.githubusercontent.com/61320526/168062672-08eeba3f-f115-41c2-b91d-8c04e7273a13.png)

And when I tried to accept the change it did this, but my connection seems to be fine. (Edit: OK connection seems to be a bit dodgy today actually).

![image](https://user-images.githubusercontent.com/61320526/168063192-1e7aa12e-848f-4ae1-bd47-5077265d1edb.png)

It then stopped doing that, and the change hadn't been made, and the comment had totally vanished - no comment or suggested change visible at all: 

![image](https://user-images.githubusercontent.com/61320526/168063475-537e994f-b032-4524-a296-02d8899000f7.png)

I tried again and it worked to some extent, but changed the formatting of the new text when it switched it: 

![image](https://user-images.githubusercontent.com/61320526/168063733-aad1d3b6-fd2a-4887-a5fd-19b36d4f07d3.png)

When deleting the comment, nothing happens when I clicked the dustbin, except the black pop-up popping up again. It's only when clicking off it that it disappears. 

![image](https://user-images.githubusercontent.com/61320526/168065637-ebec724e-99ac-4b87-a0a6-62279facaa2a.png)

**Comment by anettlinno** [comment]
Successfully replicated. I was also kicked out by the system because of bad internet connection but my connection is just fine.

**Comment by anettlinno** [comment]
Triage 66. Replicated again and found out that %20 will be added only when space is used. Icons layout should be fixed as well and deleting comment displays error message. Needs to fix all those things. 
Est. dev. time 6 hours. Sending to development.

**Comment by ssin1901** [comment]
Could not replicate the issue on Mac Safari and Chrome. In fact, I did not get any suggested text at all.

**Comment by anettlinno** [comment]
Triage 73. Working nicely. Closing the issue.
